// lib/fallback-words/countries/english/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "countries" category -- English.
 *
 * All 100 words are common, universally recognizable nations. Difficulty
 * controls ONLY how directly the hint points at the word:
 *   - easy (40):   states the most obvious landmark, shape, or cultural export.
 *   - medium (30): points to secondary details, neighboring context, or history.
 *   - hard (30):   oblique angles, indirect consequences, or geographic trivia.
 */
export const COUNTRIES_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-countries-en-1",
    word: "USA",
    hint: "The nation famous for Hollywood, baseball, and the Statue of Liberty.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-2",
    word: "Canada",
    hint: "A massive northern nation known for maple syrup, ice hockey, and polite citizens.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-3",
    word: "Mexico",
    hint: "The North American nation famous for tacos, mariachi bands, and ancient Mayan ruins.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-4",
    word: "Brazil",
    hint: "The South American giant famous for the Amazon rainforest and the vibrant Carnival festival.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-5",
    word: "UK",
    hint: "An island nation ruled by a monarchy, famous for Big Ben and drinking tea.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-6",
    word: "France",
    hint: "The European nation universally recognized by the Eiffel Tower and its romantic capital city.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-7",
    word: "Italy",
    hint: "A boot-shaped European nation famous for inventing pizza and pasta.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-8",
    word: "Germany",
    hint: "A central European powerhouse known for Oktoberfest, luxury cars, and the Berlin Wall.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-9",
    word: "Japan",
    hint: "An East Asian island nation famous for sushi, anime, and high-speed bullet trains.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-10",
    word: "China",
    hint: "The most populous Asian nation, famous for a massive Great Wall built centuries ago.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-11",
    word: "India",
    hint: "A massive South Asian nation famous for Bollywood and the magnificent Taj Mahal.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-12",
    word: "Australia",
    hint: "Both a massive island and a continent, famous for kangaroos and the Outback.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-13",
    word: "Egypt",
    hint: "An African nation historically defined by ancient pyramids, pharaohs, and the Nile River.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-14",
    word: "Russia",
    hint: "The absolute largest nation on Earth by total landmass, spanning two different continents.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-15",
    word: "Spain",
    hint: "A sunny European nation known for bullfighting, flamenco dancing, and delicious tapas.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-16",
    word: "Greece",
    hint: "The ancient Mediterranean nation where the original Olympic Games and democracy were born.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-17",
    word: "Switzerland",
    hint: "A neutral Alpine nation universally known for luxury watches, banking, and fine chocolate.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-18",
    word: "South Africa",
    hint: "The southernmost nation on the African continent, famous for safaris and Nelson Mandela.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-19",
    word: "Argentina",
    hint: "A South American nation famous for the tango dance and legendary soccer player Lionel Messi.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-20",
    word: "Saudi Arabia",
    hint: "A Middle Eastern kingdom containing Islam's two holiest cities, heavily reliant on oil exports.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-21",
    word: "UAE",
    hint: "A wealthy Gulf nation featuring the Burj Khalifa and massive luxury shopping malls.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-22",
    word: "South Korea",
    hint: "An East Asian tech hub famous for K-Pop music, skincare routines, and Samsung.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-23",
    word: "Thailand",
    hint: "A Southeast Asian tourist hotspot famous for beautiful beaches, ornate temples, and spicy curries.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-24",
    word: "Vietnam",
    hint: "A long, S-shaped Southeast Asian nation famous for pho noodle soup and motorbikes.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-25",
    word: "Indonesia",
    hint: "A massive archipelago in Southeast Asia containing popular tourist islands like Bali.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-26",
    word: "Philippines",
    hint: "A Southeast Asian archipelago nation where English is widely spoken alongside Tagalog.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-27",
    word: "New Zealand",
    hint: "A scenic island nation near Australia where the Lord of the Rings movies were filmed.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-28",
    word: "Sweden",
    hint: "A Scandinavian nation globally famous for producing IKEA furniture and pop group ABBA.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-29",
    word: "Norway",
    hint: "A cold Scandinavian nation famous for its stunning coastal fjords and Viking history.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-30",
    word: "Ireland",
    hint: "The Emerald Isle, famous for leprechaun folklore, Guinness beer, and lush green landscapes.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-31",
    word: "Portugal",
    hint: "A sunny Iberian nation famous for Port wine and producing soccer star Cristiano Ronaldo.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-32",
    word: "Netherlands",
    hint: "A flat European nation famous for windmills, tulip fields, and extensive bicycle paths.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-33",
    word: "Turkey",
    hint: "A transcontinental nation uniquely bridging Europe and Asia, famous for hot air balloons in Cappadocia.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-34",
    word: "Pakistan",
    hint: "A South Asian nation featuring K2, the world's second-highest mountain peak.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-35",
    word: "Israel",
    hint: "A Middle Eastern nation located on the Mediterranean, deeply significant to three major world religions.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-36",
    word: "Cuba",
    hint: "A Caribbean island nation famous for vintage 1950s cars, cigars, and salsa music.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-37",
    word: "Jamaica",
    hint: "A Caribbean island universally recognized for reggae music and legendary sprinter Usain Bolt.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-38",
    word: "Kenya",
    hint: "An East African nation globally dominant in long-distance marathon running.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-39",
    word: "Morocco",
    hint: "A North African nation known for the bustling markets of Marrakech and colorful tagines.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-en-40",
    word: "Peru",
    hint: "A South American nation primarily visited by tourists hiking up to Machu Picchu.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (30)
  {
    id: "fallback-countries-en-41",
    word: "Colombia",
    hint: "A South American nation that is one of the world's absolute largest producers of coffee beans.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-42",
    word: "Chile",
    hint: "An incredibly narrow and long South American nation that runs entirely along the Andes mountains.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-43",
    word: "Venezuela",
    hint: "A South American nation possessing some of the largest proven oil reserves in the entire world.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-44",
    word: "Poland",
    hint: "A Central European nation heavily impacted by WWII, known today for hearty pierogi dumplings.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-45",
    word: "Ukraine",
    hint: "A large Eastern European nation recognized globally as a massive producer of sunflower oil and grain.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-46",
    word: "Austria",
    hint: "A mountainous, landlocked European nation famous for classical music composers and the city of Vienna.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-47",
    word: "Denmark",
    hint: "A Scandinavian nation credited with inventing the hugely popular interlocking plastic Lego bricks.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-48",
    word: "Finland",
    hint: "A Nordic nation that consistently ranks as the happiest in the world, featuring thousands of saunas.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-49",
    word: "Iceland",
    hint: "A highly volcanic northern island nation completely powered by renewable geothermal energy.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-50",
    word: "Belgium",
    hint: "A small European nation serving as the de facto headquarters for the European Union.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-51",
    word: "Romania",
    hint: "An Eastern European nation heavily associated with the forested region of Transylvania and vampire folklore.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-52",
    word: "Hungary",
    hint: "A central European nation famously divided by the Danube river, known for spicy paprika dishes.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-53",
    word: "Iran",
    hint: "A Middle Eastern nation formerly known as Persia, famous for weaving incredibly intricate carpets.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-54",
    word: "Iraq",
    hint: "A Middle Eastern nation historically located in the cradle of civilization between two major ancient rivers.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-55",
    word: "Afghanistan",
    hint: "A highly mountainous, landlocked Central Asian nation known for its rugged terrain and complex geopolitical history.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-56",
    word: "Bangladesh",
    hint: "A densely populated South Asian nation heavily reliant on the textile and garment manufacturing industry.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-57",
    word: "Malaysia",
    hint: "A Southeast Asian nation heavily identified by the towering Petronas Twin Towers in its capital.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-58",
    word: "Singapore",
    hint: "A tiny, wealthy Southeast Asian city-state globally renowned for its impeccably clean public spaces.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-59",
    word: "Sri Lanka",
    hint: "A teardrop-shaped island nation located directly beneath the Indian subcontinent, famous for exporting tea.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-60",
    word: "Nepal",
    hint: "A landlocked Himalayan nation heavily reliant on tourism generated by Mount Everest climbing expeditions.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-61",
    word: "Taiwan",
    hint: "An East Asian island territory operating as a global powerhouse in producing advanced semiconductor microchips.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-62",
    word: "Nigeria",
    hint: "The absolute most populous nation on the African continent, featuring a booming film industry nicknamed Nollywood.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-63",
    word: "Ethiopia",
    hint: "An East African nation widely celebrated as the original historical birthplace of the coffee bean.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-64",
    word: "Ghana",
    hint: "A West African nation historically known as the Gold Coast, famous for exporting raw cocoa.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-65",
    word: "Algeria",
    hint: "The single largest nation in Africa by total land area, heavily dominated by the Sahara Desert.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-66",
    word: "Madagascar",
    hint: "A massive African island heavily recognized for its unique, highly specialized wildlife like lemurs.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-67",
    word: "Tanzania",
    hint: "An East African nation tourists visit specifically to climb Mount Kilimanjaro and witness the Serengeti migration.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-68",
    word: "Zimbabwe",
    hint: "A southern African landlocked nation that shares the spectacular Victoria Falls with its western neighbor.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-69",
    word: "North Korea",
    hint: "A highly isolated, secretive East Asian nation governed entirely by a single ruling family dynasty.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-en-70",
    word: "Costa Rica",
    hint: "A peaceful Central American nation that famously abolished its standing army to fund education and eco-tourism.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },

  // HARD (30)
  {
    id: "fallback-countries-en-71",
    word: "Uruguay",
    hint: "The small, highly progressive South American nation that historically won the absolute first World Cup tournament.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-72",
    word: "Paraguay",
    hint: "A completely landlocked South American nation bisected entirely by a massive river bearing the exact same name.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-73",
    word: "Ecuador",
    hint: "This South American nation literally derives its name directly from the imaginary line running through its center.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-74",
    word: "Bolivia",
    hint: "A high-altitude, landlocked Andean nation home to the massive, highly reflective Uyuni salt flats.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-75",
    word: "Panama",
    hint: "A narrow Central American nation globally vital because of a massive artificial waterway connecting two oceans.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-76",
    word: "Honduras",
    hint: "A Central American republic historically dubbed the original 'banana republic' due to early agricultural monopolies.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-77",
    word: "El Salvador",
    hint: "The absolute smallest and most densely populated nation in Central America, known as the Land of Volcanoes.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-78",
    word: "Guatemala",
    hint: "The northernmost Central American nation, recognized as the historical epicenter of the ancient Mayan civilization.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-79",
    word: "Dominican Republic",
    hint: "This Caribbean nation shares the island of Hispaniola and is a massive producer of professional baseball players.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-80",
    word: "Haiti",
    hint: "The first independent nation of Latin America and the Caribbean, uniquely established by a successful slave revolt.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-81",
    word: "Bahamas",
    hint: "An extensive archipelago nation located just slightly southeast of Florida, famous for swimming pigs.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-82",
    word: "Croatia",
    hint: "A European nation boasting a stunning Dalmatian coastline that heavily featured as a filming location for Game of Thrones.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-83",
    word: "Serbia",
    hint: "A landlocked Balkan nation centered entirely around its bustling capital city of Belgrade.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-84",
    word: "Bulgaria",
    hint: "A Balkan nation globally dominant in the agricultural production of specialized rose oil used in expensive perfumes.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-85",
    word: "Slovakia",
    hint: "A Central European nation born from a peaceful, velvet dissolution of its former united territory in the 90s.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-86",
    word: "Lithuania",
    hint: "The southernmost and largest of the three Baltic states bordering the sea of the same name.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-87",
    word: "Lebanon",
    hint: "A Middle Eastern nation historically recognized for the ancient Phoenician civilization and its majestic cedar trees.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-88",
    word: "Syria",
    hint: "A Middle Eastern nation containing Damascus, widely considered one of the oldest continuously inhabited cities on Earth.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-89",
    word: "Jordan",
    hint: "A Middle Eastern kingdom heavily reliant on tourism generated by the ancient rock-carved city of Petra.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-90",
    word: "Kuwait",
    hint: "A small, oil-rich Middle Eastern nation whose sudden invasion triggered a massive coalition response in 1990.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-91",
    word: "Qatar",
    hint: "A peninsular Gulf nation that heavily utilized its massive natural gas wealth to recently host the World Cup.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-92",
    word: "Bahrain",
    hint: "A tiny Middle Eastern island nation connected to its much larger western neighbor by a massive causeway bridge.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-93",
    word: "Oman",
    hint: "A peaceful Middle Eastern sultanate situated strategically at the mouth of the Persian Gulf.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-94",
    word: "Yemen",
    hint: "Located at the southern tip of the Arabian Peninsula, this nation is historically renowned for its ancient, towering mudbrick architecture.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-95",
    word: "Sudan",
    hint: "A North African nation containing significantly more ancient pyramids than its more famous northern neighbor.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-96",
    word: "Libya",
    hint: "A North African nation largely covered by the Sahara, formerly ruled by a highly eccentric dictator for decades.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-97",
    word: "Tunisia",
    hint: "The northernmost African nation, recognized historically as the powerful ancient empire of Carthage.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-98",
    word: "Senegal",
    hint: "The absolute westernmost nation on the African mainland, featuring a bustling coastal capital city.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-99",
    word: "Mali",
    hint: "A West African nation historically famous for the wealthy ancient trading hub of Timbuktu.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-en-100",
    word: "Fiji",
    hint: "A tropical South Pacific archipelago nation renowned heavily for its premium bottled spring water.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
];
