// lib/fallback-words/vehicles/urdu/index.ts
import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "vehicles" category -- Roman Urdu.
 *
 * 100 common vehicle and transportation terms used in daily Pakistani life.
 * Written in natural Roman Urdu (Latin letters only).
 *
 * Difficulty breakdown:
 *   - easy (40):   states the defining trait directly in conversational Roman Urdu.
 *   - medium (30): refers to contextual details, typical uses, or broad associations.
 *   - hard (30):   oblique angle, indirect effect, or subtle daily observation.
 */
export const VEHICLES_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // --- EASY (40 words) ---
  {
    id: "fallback-vehicles-ur-1",
    word: "Gari",
    hint: "Char paiyon wali aam sawari jo sadak par chalti hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-2",
    word: "Rikshaw",
    hint: "Teen paiyon wali sawari jo sheher mein aam safar ke liye istemal hoti hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-3",
    word: "Chingchi",
    hint: "Motorcycle ke peeche seating laga kar banai gayi teen paiyon wali sawari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-4",
    word: "Motorcycle",
    hint: "Do paiyon wali mehangi petrol se chalne wali aam sawari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-5",
    word: "Cycle",
    hint: "Do paiyon wali sawari jo pedal mar kar chalai jati hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-6",
    word: "Jahaz",
    hint: "Hawa mein udne wali bari sawari jo ek mulk se doosre mulk le jati hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-7",
    word: "Samundari Jahaz",
    hint: "Pani ke upar chalne wali bari float sawari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-8",
    word: "Train",
    hint: "Loki patri par chalne wali bohot sare dibbon wali lambi gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-9",
    word: "Bus",
    hint: "Bari awami sawari jisme bohot se musafir ek saath safar karte hain.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-10",
    word: "Metro",
    hint: "Sheher ke andar alag track par chalne wali tez tareen awami bus ya train.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-11",
    word: "Wagon",
    hint: "Local routes par chalne wali choti passenger van.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-12",
    word: "Coaster",
    hint: "Pahadi ilaakon aur safari groups ke liye istemal hone wali medium size bus.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-13",
    word: "Tractor",
    hint: "Khet hal chalane aur bhari samaan khinchne wali bari pehon wali gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-14",
    word: "Dumper",
    hint: "Reti aur bajri ko piche se utha kar gira dene wala bara truck.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-15",
    word: "Loader",
    hint: "Samaan ek jagah se doosri jagah le jaane wali choti ya bari truck gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-16",
    word: "Tanker",
    hint: "Paani ya petrol bhar kar laane wala bara gol dabba dhar truck.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-17",
    word: "Crane",
    hint: "Unchi imarton par bhari samaan uthane wali lambi arm wali machine gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-18",
    word: "Ambulance",
    hint: "Mareezon ko emergency mein hospital pahunchane wali siren wali gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-19",
    word: "Police Mobile",
    hint: "Ghasht karne aur kanoon banaye rakhne wali makhsoos police gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-20",
    word: "Fire Brigade",
    hint: "Kahin aag lag jaye toh usay buthane wali paani ki gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-21",
    word: "Tangha",
    hint: "Ghode ke saath jodi gayi lakdi ki traditional sawari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-22",
    word: "Rehrhi",
    hint: "Hath se dhakel kar phal ya sabzi bechne wali choti wheel gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-23",
    word: "Ghoda Gari",
    hint: "Janwar dwara khinchi jaane wali chaar paiyon wali samaan gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-24",
    word: "Gadha Gari",
    hint: "Sheher mein eent aur mitti uthane wali janwar ki sawari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-25",
    word: "Oont Gari",
    hint: "Sehra aur gaon mein camel ke peeche lagi samaan gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-26",
    word: "Scooter",
    hint: "Paanv rakhne ki jagah wali aasan do paiyon wali motor sawari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-27",
    word: "Helicopter",
    hint: "Upar ghumne wale pankhe ki madad se seedha upar udne wala jahaz.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-28",
    word: "Pan Doobi",
    hint: "Pani ke bilkul andar gahrai mein chalne wali makhsoos maritime gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-29",
    word: "Speedboat",
    hint: "Pani par bohot tezi se chalne wali choti motor kishti.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-30",
    word: "Kisti",
    hint: "Darya ya jheel mein chappu se chalai jane wali sawari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-31",
    word: "Rocket",
    hint: "Aasman se baahar khala mein jaane wala teez raftaar vehicle.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-32",
    word: "Fighter Jet",
    hint: "Fouj ka bohot teez udne wala jangi hawai jahaz.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-33",
    word: "Saji Hui Truck",
    hint: "Khoobsoorat phoolon aur rangon se sjaya gaya Pakistani cargo vehicle.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-34",
    word: "Heavy Bike",
    hint: "Bara engine aur teez raftaar wali sports motorcycle.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-35",
    word: "Battery Rikshaw",
    hint: "Bijli se charge hone wala silent chalne wala teen paiyon wala vehicle.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-36",
    word: "School Bus",
    hint: "Bachon ko subah ghar se school le jaane wali peeli ya bari bus.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-37",
    word: "School Van",
    hint: "Bachon ko mahana basis par lene aane wali choti van.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-38",
    word: "Kachra Gari",
    hint: "Galiyon se kachra uthane wali baldiya ki makhsoos gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-39",
    word: "Double Cabin",
    hint: "Aage sawari aur peeche khula dabba wali bari pickup gari.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-40",
    word: "Carry Dabba",
    hint: "Choti microvan jo har mohalle mein aam istemal hoti hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // --- MEDIUM (30 words) ---
  {
    id: "fallback-vehicles-ur-41",
    word: "Gari",
    hint: "Iss sawari ka tire puncture ho jaye toh jack laga kar badalna padta hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-42",
    word: "Rikshaw",
    hint: "Kraye par baat karte waqt conductor nahi hota bas driver se hi baat hoti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-43",
    word: "Chingchi",
    hint: "Peeche aamne samne do benches par chey log baith sakte hain.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-44",
    word: "Motorcycle",
    hint: "Subah kick mar kar start karna aur kickstand par khada karna iska tareeqa hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-45",
    word: "Cycle",
    hint: "Chain utar jaye toh haath kale ho jaate hain isay sahi karte waqt.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-46",
    word: "Jahaz",
    hint: "Boarding pass lene ke baad security check points se guzar kar ispar baithte hain.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-47",
    word: "Samundari Jahaz",
    hint: "Khangi container aur bhari maall ko behtareen tareeqay se doosre mulk bhejtay hain.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-48",
    word: "Train",
    hint: "Station par iske aane se pehle seeti aur patri ki aawaz sunai deti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-49",
    word: "Bus",
    hint: "Conductor chhat par samaan rakhta hai aur darwaze par khada hokar awaz lagata hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-50",
    word: "Metro",
    hint: "Token ya card scan kar ke turnstile barrier se guzar kar iski platform par jate hain.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-51",
    word: "Wagon",
    hint: "Tez raftaar driving aur khidkiyon se hawa aane ke liye mashhoor hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-52",
    word: "Coaster",
    hint: "Shadi ke mehmanon ko doosre sheher le jaane ke liye booking ki jaati hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-53",
    word: "Tractor",
    hint: "Gaon ki kachi sadkon par silencer se dhuan nikalte hue aahista chalti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-54",
    word: "Dumper",
    hint: "Constructing site par mitti gira kar wapas chal deta hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-55",
    word: "Loader",
    hint: "Ghar shift karte waqt samaan bharne ke liye sabse pehle bulaya jata hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-56",
    word: "Tanker",
    hint: "Garmiyon mein paani ki kami hone par line mein khada karke bulana padta hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-57",
    word: "Crane",
    hint: "Sadak par kharab gari ya accident ke baad rescue ke liye aati hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-58",
    word: "Ambulance",
    hint: "Traffic mein log isay pehle rasta dene ki poori koshish karte hain.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-59",
    word: "Police Mobile",
    hint: "Raat ko chowk par light chala kar checking ke liye khadi hoti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-60",
    word: "Fire Brigade",
    hint: "Lal rang aur paani ke pipe ke sath daudti aati hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-61",
    word: "Tangha",
    hint: "Purane zamane ki shahi ahsaas dene wali sair ke liye istemal hone wali gari.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-62",
    word: "Rehrhi",
    hint: "Galiyon mein sham ke waqt aazaan se pehle samaan bechne wale ise dhakelte hain.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-63",
    word: "Ghoda Gari",
    hint: "Bhari boriyan mandi se dukanon tak le jaane ke liye istemal hoti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-64",
    word: "Gadha Gari",
    hint: "Mitti aur kachra uthane ke liye mohallon mein aam dekhi jaati hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-65",
    word: "Oont Gari",
    hint: "Sehra ke meley aur maveshi mandi mein dekhi jane wali makhsoos sawari.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-66",
    word: "Scooter",
    hint: "Ghar ke kareebi market se rashan laane ke liye comfortable rehti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-67",
    word: "Helicopter",
    hint: "VIP hazraat ko sheher ke traffic se bacha kar direct building ke top par utarti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-68",
    word: "Pan Doobi",
    hint: "Gahrayi mein jaa kar dushman par khamoshi se nazar rakhti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-69",
    word: "Speedboat",
    hint: "Beach par picnic ke doran paise de kar chakkar lagane ka shauq hota hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-70",
    word: "Kisti",
    hint: "Machli pakadne wale subah savere isay le kar darya mein nikalte hain.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // --- HARD (30 words) ---
  {
    id: "fallback-vehicles-ur-71",
    word: "Gari",
    hint: "Peeche ke sheeshe par baby on board ka sticker laga hota hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-72",
    word: "Rikshaw",
    hint: "Peeche dilchasp aur mizahiya shayari likhi hoti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-73",
    word: "Chingchi",
    hint: "Choti galiyon mein sharp cut marte waqt jhukna padta hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-74",
    word: "Motorcycle",
    hint: "Achanak barish mein pul ke neeche log ise khada kar ke pnah lete hain.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-75",
    word: "Cycle",
    hint: "Pehli baar seekhte waqt ghutne chhilna lazmi hota hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-76",
    word: "Jahaz",
    hint: "Kaan mein hawa ke dabao se seeti bajna iske take off ke waqt hota hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-77",
    word: "Samundari Jahaz",
    hint: "Mahinon tak khule paani mein rehne ke baad port par langar daalta hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-78",
    word: "Train",
    hint: "Phatak band hote hi dono taraf gaariyon ki lambi line lag jaati hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-79",
    word: "Bus",
    hint: "Chath par sawariyan aur saman bhar kar tez speed mein chalti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-80",
    word: "Metro",
    hint: "Alag se bane huye laal ya sabz bridge ke upar se guzarti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-81",
    word: "Wagon",
    hint: "Seat poori hone ke baad bhi aik aur musafir ko zabardasti bithaya jata hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-82",
    word: "Coaster",
    hint: "Northern areas ke ghumaav-dar raste par sabse zyada nazarray karwati hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-83",
    word: "Tractor",
    hint: "Iski trolly mein saal ke makhsoos dinon par gannay lade hote hain.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-84",
    word: "Dumper",
    hint: "Raat ke waqt sheher mein dakhil ho kar tez raftaar se guzarta hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-85",
    word: "Loader",
    hint: "Mandi se dukan tak ka rasta daily basis par tay karta hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-86",
    word: "Tanker",
    hint: "Sadak par leaking hone ki wajah se peeche paani ka nishan rehta hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-87",
    word: "Crane",
    hint: "Ghalat jagah gari park karne par chalan ke sath ise utha le jati hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-88",
    word: "Ambulance",
    hint: "Isko peeche dekhte hi log gari side par kar ke raasta saaf kar dete hain.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-89",
    word: "Police Mobile",
    hint: "Makhsoos hooter ki aawaz sunte hi dukanain aahista aahista band hone lagti hain.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-90",
    word: "Fire Brigade",
    hint: "Isko dekhte hi samajh aa jata hai ke kareeb kahin emergency hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-91",
    word: "Tangha",
    hint: "Ghoongroo ki aawaz se mohalle mein iski aamad ka pata chalta hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-92",
    word: "Rehrhi",
    hint: "Aam tor par sham ke waqt bazaar ki patti par ek line mein khadi hoti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-93",
    word: "Ghoda Gari",
    hint: "Dhaat ke paiyon ki sadak par makhsoos aawaz paida karti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-94",
    word: "Gadha Gari",
    hint: "Kachi abadiyon mein taamirati samaan pahunchane ka sasta zariya hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-95",
    word: "Oont Gari",
    hint: "Peeche ret par lambi lakeerain chhodti hui chalti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-96",
    word: "Scooter",
    hint: "Purane zamane ke uncle subah akhbaar lene ispar jaate the.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-97",
    word: "Helicopter",
    hint: "Neeche zameen par tez hawa se mitti aur patte udne lagte hain.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-98",
    word: "Pan Doobi",
    hint: "Radar par choti dot ki surat mein hi pechani jaati hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-99",
    word: "Speedboat",
    hint: "Peeche paani ki uchi safed deewar banati hui aage nikalti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-100",
    word: "Kisti",
    hint: "Shaam ke waqt saahil par bandhi hui laharon ke sath hilti rehti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
