// lib/fallback-words/countries/urdu/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "countries" category -- Roman Urdu.
 *
 * 100 well-known countries instantly recognizable in everyday Pakistani
 * conversation. Uses standard Urdu names where applicable (e.g., Amreeka,
 * Cheen, Misr, Roos). Difficulty only changes the hint's directness.
 * Hints are written in natural conversational Roman Urdu using ONLY
 * Latin letters.
 */
export const COUNTRIES_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-countries-ur-1",
    word: "Pakistan",
    hint: "Hamara apna pyara watan jis ka dar-ul-hukumat Islamabad hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-2",
    word: "Hindustan",
    hint: "Hamara sab se bara hamsaya aur cricket mein sab se bara raqeeb.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-3",
    word: "Cheen",
    hint: "Hamara dushman ka dushman aur sab se gehra dost jis se CPEC ka muahida hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-4",
    word: "Amreeka",
    hint: "Dunya ki sab se bari taqat jahan sadar white house mein rehta hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-5",
    word: "Bartaniya",
    hint: "Goron ka wo mulk jis ne bar-e-sagheer par azaadi se pehle hukumat ki thi.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-6",
    word: "Saudia",
    hint: "Har saal lakhon musalman yahan makkah aur madina ki ziarat ke liye jate hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-7",
    word: "Afghanistan",
    hint: "Hamara shimal maghribi hamsaya jahan pathan rehte hain aur jang ka asar raha hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-8",
    word: "Iran",
    hint: "Farsi bolne walon ka hamara hamsaya jahan pichle daur mein badshah ki hukumat thi.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-9",
    word: "Turkiye",
    hint: "Khilafat-e-Usmania wala mulk jo ab apne dramon ki wajah se yahan bohat mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-10",
    word: "Canada",
    hint: "Baraf bari wala bara mulk jahan hamare bohut se log parhai aur job ke liye jate hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-11",
    word: "Australia",
    hint: "Kangaroo aur koala bear wala dunya ka sab se bara jazeera.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-12",
    word: "New Zealand",
    hint: "Kiwis ki zameen jo hamesha cricket world cup mein semi-final lazmi khelti hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-13",
    word: "Janubi Africa",
    hint: "Nelson Mandela ka azaad kardah mulk jo cricket mein hamesha choke kar jata hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-14",
    word: "Sri Lanka",
    hint: "Hindustan ke bilkul neechay chota sa jazeera jahan hathi aur chaye bohat aam hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-15",
    word: "Bangladesh",
    hint: "1971 se pehle isay mashriqi pakistan kaha jata tha aur in ki zuban bengali hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-16",
    word: "Misr",
    hint: "Firaon aur qadeem aharam (pyramids) ke liye poori dunya mein mashhoor.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-17",
    word: "Roos",
    hint: "Raqbay ke hisab se dunya ka sab se bara barafani mulk jis ka darul hukumat moscow hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-18",
    word: "France",
    hint: "Eiffel tower ki waja se mashhoor europe ka mulk jo perfumes banata hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-19",
    word: "Germany",
    hint: "Europe ki sab se bari maeeshat jo apni mazboot gariyon aur machinery ke liye jani jati hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-20",
    word: "Japan",
    hint: "Suraj nikalne ki zameen jahan technology bohat advance hai aur log mehnati hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-21",
    word: "Qatar",
    hint: "Chota sa arab mulk jis ne haal hi mein football ka sab se bara world cup karwaya.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-22",
    word: "Kuwait",
    hint: "Arab ka wo ameer tareen mulk jis ki currency dunya mein sab se mehengi mani jati hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-23",
    word: "Oman",
    hint: "Muscat is arab riyasat ka capital hai jahan hamare bohut se log kaam karte hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-24",
    word: "Iraq",
    hint: "Baghdad ka tareekhi mulk jahan saddam hussein ki hukumat thi.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-25",
    word: "Malaysia",
    hint: "Kuala Lumpur ke twin towers wala musalman mulk jahan jungle bohat hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-26",
    word: "Indonesia",
    hint: "Dunya ki sab se bari musalman abadi wala jazeeron ka mulk jahan bali hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-27",
    word: "Thailand",
    hint: "Bangkok ke khoobsoorat sahil aur bazaron ki waja se tourist yahan bohat jate hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-28",
    word: "Singapore",
    hint: "Asia ka sab se saaf aur mehnga tareen chota sa business mulk.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-29",
    word: "Switzerland",
    hint: "Barfili pahariyon aur chocolates wala europe ka mulk jahan bollywood ki shooting hoti thi.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-30",
    word: "Brazil",
    hint: "Football ka janun aur amazon ke jungle is janoobi amreeki mulk ki pehchan hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-31",
    word: "Argentina",
    hint: "Messi jaisa azeem khiladi is football jeetne wale south amreeki mulk se taluq rakhta hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-32",
    word: "Kenya",
    hint: "Africa ka safari mulk jis ke khiladi hamesha marathon race mein first aate hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-33",
    word: "Zimbabwe",
    hint: "Africa ka ye mulk puranay daur mein andy flower jese cricket khiladi paida karta tha.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-34",
    word: "Nepal",
    hint: "Dunya ki sab se oonchi choti mount everest is pahaari mulk mein waqia hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-35",
    word: "Maldives",
    hint: "Neele pani wale chhote jazeeron ka ye mulk honeymoons ke liye sab se mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-36",
    word: "Falasteen",
    hint: "Masjid-e-Aqsa wala wo mazloom mulk jis ki azaadi ke liye musalman duayen karte hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-37",
    word: "Sham",
    hint: "Dimashq ke tareekhi shehar wala arab mulk jahan pichle kai saalon se halat khrab hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-38",
    word: "Urdun",
    hint: "Petra jaisi qadeem imarat is chhote se arab badshahat wale mulk ki shaan hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-39",
    word: "Italy",
    hint: "Pizza aur pasta is jootay ki shakal wale mulk ki eejad hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-40",
    word: "Spain",
    hint: "Football clubs barcelona aur madrid is mulk ke sab se mashhoor shehar hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (30)
  {
    id: "fallback-countries-ur-41",
    word: "UAE",
    hint: "Burj Khalifa aur lambi chamakti garriyan is gulf ki riyasat ka mizaaj ban chuki hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-42",
    word: "Bahrain",
    hint: "Khaleej ka chota sa jazeera jo ek lambe pul ke zariye saudia se juda hua hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-43",
    word: "Yemen",
    hint: "Arab jazeere ke bilkul neechay waqia mulk jis ki tareekh qadeem tehzibon se bhari hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-44",
    word: "Lebanon",
    hint: "Mashriq e wusta ka wo haseen mulk jis ka capital beirut hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-45",
    word: "Holland",
    hint: "Tulip ke phool aur lakri ke jootay is naram zameen wale mulk ki alamat hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-46",
    word: "Belgium",
    hint: "Chocolate banane wala ye chota european mulk union ke headquarter ke tor par jana jata hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-47",
    word: "Sweden",
    hint: "Barafani mulk jis ki awam ne sab se pehle dunya ko ikea jesa furniture diya.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-48",
    word: "Norway",
    hint: "Samundari paharoun wala thanda mulk jahan musalman sab se lamba roza rakhte hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-49",
    word: "Denmark",
    hint: "Bachon ke khelne wale lego blocks ki ijad is scandinavian mulk mein hui thi.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-50",
    word: "Ireland",
    hint: "Haray bharay paharon ka jazeera jisay log green isle bhi kehte hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-51",
    word: "Scotland",
    hint: "Ye jagah wese tou england ke sath hai magar inke check wale skirt mashhoor hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-52",
    word: "Mexico",
    hint: "Spicy khanon aur lakri ki guitar wale mariachi bando ki wajah se amreeka ke neechay mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-53",
    word: "Cuba",
    hint: "Purani gariyan aur lamba cigar peene wale log is jazeere ki pehchan hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-54",
    word: "Nigeria",
    hint: "Africa ki sab se bari abadi jo apni oil ki pedawar aur filmi industry ke liye jani jati hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-55",
    word: "Marakash",
    hint: "Africa ka shimali hissa jis ki imarat bohat khubsurat hoti hain aur khane mazedar.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-56",
    word: "Libya",
    hint: "Sehra par mushtamil oil se bhara hua mulk jis ki kaman arse tak gaddafi ke pas rahi.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-57",
    word: "Sudan",
    hint: "Nile darya is baray mulk ko takseem karta hai jis mein kafi chote pyramids bhi hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-58",
    word: "Bosniya",
    hint: "Nawway ki dihai ki jang ke baad europe ka ye musalman khitta bohat masail se guzra.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-59",
    word: "Azerbaijan",
    hint: "Tail nikalne wala khoobsoorat mulk jo asia aur europe ke theek darmiyan me hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-60",
    word: "Uzbekistan",
    hint: "Samarqand aur bukhara jese azeem islami shehar isi madhya asia ki jagah aate hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-61",
    word: "Tajikistan",
    hint: "Central asia ki is riyasat ke log farsi se milti julti zuban bolte hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-62",
    word: "Kazakhstan",
    hint: "Raqbay ke lihaaz se musalmanon ka sab se bara mulk jahan pahari barf bari aam hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-63",
    word: "Ukraine",
    hint: "Roos se alag hone wala mulk jo pichle chand salon se ek barri jung ka shikar hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-64",
    word: "Poland",
    hint: "Dusri jang-e-azeem sab se pehle is ki sarhad par hamla hone se shuru hui thi.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-65",
    word: "Austria",
    hint: "Mozart jese musicians ki ye jagah apne haseen tareen shehar vienna ke liye jani jati hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-66",
    word: "Vietnam",
    hint: "Motorbikes aur noodles is asiayi mulk ki sadkon par sab se zyada nazr aatay hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-67",
    word: "Burma",
    hint: "Hamare mashriq mein waqia is jagah ko duniya myanmar ke naam se bhi pukarti hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-68",
    word: "Philippines",
    hint: "Manila is jazeeron wale mulk ka dar ul hukumat hai jahan english bohat aam boli jati hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-69",
    word: "Janubi Korea",
    hint: "Samsung aur chamakti hui pop music is asiayi technology hub ki mukammal pehchan hain.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-70",
    word: "Yunan",
    hint: "Purani tareekh wale is mulk ko angrezi mein greece kehte hain jahan olympics shuru huye.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (30)
  {
    id: "fallback-countries-ur-71",
    word: "Shumali Korea",
    hint: "Dunya ka sab se band aur pabandiyon wala mulk jahan awam ko bahr ki khabar nahi.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-72",
    word: "Taiwan",
    hint: "Computer aur mobile ke andar lagne wali chip banane wala sab se bara chota azaad khitta.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-73",
    word: "Chile",
    hint: "Naqshay par ye dunya ka sab se patla aur lamba mulk dikhai deta hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-74",
    word: "Peru",
    hint: "Machu Picchu ke qadeem pahaar dekhne ke liye log is dakshin amreeki mulk me aate hain.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-75",
    word: "Colombia",
    hint: "Khaalis coffee ki pedawar ke liye ye south amreeki jaga sab se mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-76",
    word: "Venezuela",
    hint: "Zameen ke neeche tail ke sab se baray zakhair hone ke bawajood inki economy girti rahi.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-77",
    word: "Panama",
    hint: "Ek bohat bari nehar ne is mulk ko mashhoor kiya jis se jahaz guzarte hain.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-78",
    word: "Portugal",
    hint: "Cristiano Ronaldo ka aabai watan jo europe ke kinare par samundar ke sath waqia hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-79",
    word: "Romania",
    hint: "Dracula ka qila isi mashriqi europe ke mulk ke ghane janglon mein tasawur kiya jata hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-80",
    word: "Hungary",
    hint: "Danube darya is european mulk ke dar ul hukumat ko do hisson mein takseem karta hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-81",
    word: "Bulgaria",
    hint: "Is balkan khitte mein log dunya ka behtareen gulab ka itar aur arq tayar karte hain.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-82",
    word: "Serbia",
    hint: "Tennis star djokovic is europe ki landlocked zameen se nikal kar dunya bhar mein mashhoor hua.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-83",
    word: "Malta",
    hint: "Samundar ke darmiyan aik chota sa qadeem island jis ki waja se yahan wazaif wale log chalte hain.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-84",
    word: "Habsha",
    hint: "Tareekh-e-islam mein pehli hijrat is africi zameen ki taraf hui jahan ka badshah najashi tha.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-85",
    word: "Somalia",
    hint: "Africa ke is greeb hisse ko dunya samundari luteron ki waja se zyada janti hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-86",
    word: "Uganda",
    hint: "Is african mulk par aik daur mein idi amin jese sakht shakhs ki purnazr hukumat thi.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-87",
    word: "Ghana",
    hint: "Puranay waqton mein isay gold coast kaha jata tha lekin ab ye cocoa beans deta hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-88",
    word: "Jamaica",
    hint: "Usain bolt ki tezi is carribean island ki alamat hai jahan log fast dorne wale hain.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-89",
    word: "Brunei",
    hint: "Borneo jazeere par waqia intehai ameer islami badshahat jahan sultan apni gariyon ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-90",
    word: "Belarus",
    hint: "Europe ka aakhri dictator is thandi jagah par hukumat karta hai aur ye russia ka dost hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-91",
    word: "Turkmenistan",
    hint: "Is chote aur ameer mulk mein darwaza of hell ke naam se mashhoor gas ka garha hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-92",
    word: "Kyrgyzstan",
    hint: "Bishkek ka ye pahari asiya mulk medicle parhne wale tulba ke liye aham muqam ban gaya hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-93",
    word: "Armenia",
    hint: "Kaukasus pahaaron ki ye eesai riyasat azerbaijan ke sath hamesha border ke masle par larti rahi hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-94",
    word: "Georgia",
    hint: "Roos aur turkey ke theek darmyan mojood ye sasta tareen khitta apne purane girja gharon se sajja hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-95",
    word: "Tunis",
    hint: "Arb bahaar ke inqalab ki shuruwaat shimali africa ke is haseen behri khitte se hui thi.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-96",
    word: "Jazair",
    hint: "Arabic mein is bare african hisse ka nam uske capital se milta julta hai jise angrezi me algeria kehte hain.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-97",
    word: "Albania",
    hint: "Europe ke andar balqan hisse ki wahid jaga jahan musalman isaiyon se zyada tadad mein rehte hain.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-98",
    word: "Ecuador",
    hint: "Is south amreeki jaga ka naam theek equator line ke uske upar se guzarne ki bina par rakha gaya.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-99",
    word: "Uruguay",
    hint: "Apne size mein bohat chota honay ke baad bhi inhone dunya ka pehla fifa cup apnay naam kiya tha.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-100",
    word: "Qibris",
    hint: "Mashriq e wusta aur europe ke darmiyan adha turk aur adha yunani control wala khoobsurat island.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
