import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "movies" category -- English.
 *
 * All 100 words are famous, globally recognized films an average person would
 * instantly recognize, regardless of difficulty. Difficulty here changes ONLY
 * how directly the hint points at the word -- never how obscure the word itself is:
 *   - easy (40):   the hint states the movie's main plot/premise directly.
 *   - medium (30): the hint points at a related detail/context instead
 *                  of the core plot, so it takes a moment of thought.
 *   - hard (30):   the hint is oblique -- an unusual angle, minor detail,
 *                  or consequence -- without ever naming the obvious premise.
 */
export const MOVIES_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-movies-en-1",
    word: "Titanic",
    hint: "A massive passenger ship hits an iceberg and sinks on its very first voyage.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-2",
    word: "Avatar",
    hint: "A marine uses an alien body to explore a blue planet inhabited by tall native people.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-3",
    word: "The Matrix",
    hint: "A computer hacker discovers that reality is a simulation controlled by machines.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-4",
    word: "Jurassic Park",
    hint: "Scientists clone dinosaurs for a theme park, but the prehistoric creatures escape their enclosures.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-5",
    word: "Star Wars",
    hint: "A young farm boy learns about the force and destroys a massive space station to save the galaxy.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-6",
    word: "Jaws",
    hint: "A giant man-eating great white shark attacks beachgoers in a summer resort town.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-7",
    word: "The Lion King",
    hint: "A young animated cub must reclaim his throne from his evil uncle after his father dies.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-8",
    word: "Forrest Gump",
    hint: "A slow-witted but kind-hearted man accidentally influences major historical events.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-9",
    word: "Home Alone",
    hint: "A young boy is left behind by his family and must defend his house from two burglars.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-10",
    word: "Harry Potter",
    hint: "An orphan discovers he is a wizard and goes to a magical boarding school.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-11",
    word: "Shrek",
    hint: "A grumpy green ogre sets out to rescue a princess to get his swamp back.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-12",
    word: "Frozen",
    hint: "A princess goes on a journey to find her sister whose icy powers trapped their kingdom in winter.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-13",
    word: "Spider Man",
    hint: "A teenager gets bitten by a radioactive insect and starts fighting crime in New York.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-14",
    word: "Batman",
    hint: "A wealthy vigilante dressed as a dark flying creature fights criminals in Gotham City.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-15",
    word: "Superman",
    hint: "An alien from Krypton hides his identity as a reporter and uses his powers to save the world.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-16",
    word: "The Avengers",
    hint: "Earth's mightiest heroes team up to stop a trickster god from conquering the planet.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-17",
    word: "The Terminator",
    hint: "A cyborg assassin is sent back in time to kill a woman before she gives birth to a resistance leader.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-18",
    word: "E.T.",
    hint: "A gentle alien becomes stranded on Earth and befriends a young boy to find a way home.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-19",
    word: "Finding Nemo",
    hint: "A clownfish crosses the ocean to rescue his captured son from a dentist's fish tank.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-20",
    word: "Toy Story",
    hint: "A cowboy doll feels threatened when a new space ranger action figure becomes the favorite.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-21",
    word: "Gladiator",
    hint: "A betrayed Roman general becomes a fighter in the arena to exact revenge against the emperor.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-22",
    word: "Inception",
    hint: "Thieves use special technology to enter people's dreams and steal their secrets.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-23",
    word: "The Godfather",
    hint: "The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-24",
    word: "The Wizard of Oz",
    hint: "A tornado sweeps a young girl and her dog to a magical land over the rainbow.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-25",
    word: "Rocky",
    hint: "An underdog boxer from Philadelphia gets a once-in-a-lifetime chance to fight the heavyweight champion.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-26",
    word: "Indiana Jones",
    hint: "An adventurous archaeologist travels the globe to find powerful ancient artifacts before the villains do.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-27",
    word: "Alice in Wonderland",
    hint: "A young girl falls down a rabbit hole into a bizarre fantasy world full of strange characters.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-28",
    word: "Beauty and the Beast",
    hint: "A smart village girl falls in love with a cursed prince living in an enchanted castle.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-29",
    word: "Aladdin",
    hint: "A street urchin finds a magic lamp containing a genie who grants him three wishes.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-30",
    word: "Cinderella",
    hint: "A poorly treated stepdaughter attends a royal ball with the help of a fairy godmother and a glass slipper.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-31",
    word: "Snow White",
    hint: "A princess hides in the forest with seven dwarfs to escape her wicked stepmother.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-32",
    word: "Mulan",
    hint: "A young woman disguises herself as a man to take her ailing father's place in the imperial army.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-33",
    word: "King Kong",
    hint: "A giant ape is captured from a remote island and brought to New York City.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-34",
    word: "Godzilla",
    hint: "A massive prehistoric monster awakened by nuclear radiation attacks a major city.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-35",
    word: "The Little Mermaid",
    hint: "A teenage sea creature trades her voice to a sea witch in order to become human.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-36",
    word: "The Lord of the Rings",
    hint: "A hobbit must journey across dangerous lands to destroy a powerful golden jewelry piece.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-37",
    word: "Back to the Future",
    hint: "A teenager is accidentally sent thirty years into the past in a time-traveling sports car.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-38",
    word: "Ghostbusters",
    hint: "Three eccentric scientists start a business catching supernatural spirits in New York City.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-39",
    word: "Men in Black",
    hint: "Two secret agents monitor and police extraterrestrial beings living secretly on Earth.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-en-40",
    word: "Independence Day",
    hint: "Humans must fight back when hostile aliens launch a massive invasion globally on July 4th.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-movies-en-41",
    word: "The Sixth Sense",
    hint: "A child psychologist tries to help a young boy who claims he can communicate with the dead.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-42",
    word: "Fight Club",
    hint: "An insomniac and a soap salesman start an underground society with strict rules about not talking about it.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-43",
    word: "Pulp Fiction",
    hint: "The lives of two mob hitmen, a boxer, and a gangster's wife intertwine in a non-linear storyline.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-44",
    word: "The Shining",
    hint: "A family heads to an isolated hotel for the winter where an evil presence drives the father into violence.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-45",
    word: "Psycho",
    hint: "A secretary on the run checks into a desolate motel run by a young man with a troubling mother fixation.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-46",
    word: "Casablanca",
    hint: "An expatriate cafe owner must choose between his former lover and helping her husband escape the Nazis.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-47",
    word: "The Sound of Music",
    hint: "A singing nun becomes a governess for seven children in Austria just before World War II.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-48",
    word: "Mary Poppins",
    hint: "A magical nanny arrives with her flying umbrella to bring joy to a strict London family.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-49",
    word: "Willy Wonka",
    hint: "A poor boy finds a golden ticket hidden in a chocolate bar and wins a tour of an eccentric factory.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-50",
    word: "The Truman Show",
    hint: "An insurance salesman discovers his entire life is actually a highly orchestrated television program.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-51",
    word: "Good Will Hunting",
    hint: "A brilliant but rebellious janitor at MIT is forced to see a therapist after solving an impossible math problem.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-52",
    word: "A Beautiful Mind",
    hint: "A brilliant mathematician struggles with severe schizophrenia while making groundbreaking economic theories.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-53",
    word: "Cast Away",
    hint: "A FedEx executive survives a plane crash and lives on a deserted island with only a volleyball for company.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-54",
    word: "Gravity",
    hint: "Two astronauts must fight to survive and find a way back home after their shuttle is destroyed in orbit.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-55",
    word: "The Martian",
    hint: "An astronaut is presumed dead and left behind on a red planet, forcing him to grow potatoes to survive.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-56",
    word: "Interstellar",
    hint: "A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-57",
    word: "Mad Max",
    hint: "In a post-apocalyptic wasteland, a drifter teams up with a tough rebel woman to outrun a warlord.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-58",
    word: "Blade Runner",
    hint: "A specialized cop is assigned to hunt down and retire advanced synthetic humans in a dystopian future.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-59",
    word: "Alien",
    hint: "The crew of a commercial spacecraft encounters a deadly extraterrestrial lifeform that uses them as hosts.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-60",
    word: "Predator",
    hint: "A team of commandos on a mission in a Central American jungle find themselves hunted by an extraterrestrial warrior.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-61",
    word: "Die Hard",
    hint: "An off-duty police officer tries to save his wife and others taken hostage by terrorists during a Christmas party.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-62",
    word: "Speed",
    hint: "A police officer must prevent a bomb from exploding aboard a city bus by keeping it above fifty miles per hour.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-63",
    word: "Lethal Weapon",
    hint: "A veteran detective is partnered with an unstable, suicidal cop to bust a massive drug smuggling ring.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-64",
    word: "Mission Impossible",
    hint: "An elite agent is framed for the murders of his entire team and must clear his name while hanging from wires.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-65",
    word: "James Bond",
    hint: "A British secret service agent with a license to kill constantly stops supervillains while wearing a tuxedo.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-66",
    word: "Jason Bourne",
    hint: "A man is pulled from the sea with two bullets in his back and must discover his true identity as a trained assassin.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-67",
    word: "Catch Me If You Can",
    hint: "An FBI agent tracks down a young con artist who successfully forged millions in checks as a pilot and doctor.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-68",
    word: "The Prestige",
    hint: "Two rival stage magicians in Victorian London engage in a bitter feud to create the ultimate illusion.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-69",
    word: "Memento",
    hint: "A man with short-term memory loss uses notes and tattoos to hunt for the person who killed his wife.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-en-70",
    word: "Shutter Island",
    hint: "A U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-movies-en-71",
    word: "Black Swan",
    hint: "A committed dancer struggles to maintain her sanity while preparing for the lead role in a major ballet production.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-72",
    word: "La La Land",
    hint: "A jazz pianist and an aspiring actress pursue their dreams in Los Angeles but find success tears them apart.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-73",
    word: "Whiplash",
    hint: "A promising young drummer enrolls at a cutthroat music conservatory where his instructor pushes him beyond his limits.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-74",
    word: "Parasite",
    hint: "A destitute family deceptively gets themselves hired one by one to work for a very wealthy household.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-75",
    word: "Spirited Away",
    hint: "A young girl gets trapped in a bathhouse for spirits and must work to free her parents who were turned into pigs.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-76",
    word: "Up",
    hint: "An elderly widower ties thousands of balloons to his house to fulfill his promise to visit South America.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-77",
    word: "Wall E",
    hint: "A lonely trash-compacting robot finds a plant on an abandoned Earth and follows a probe into deep space.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-78",
    word: "Ratatouille",
    hint: "A rodent with a highly developed sense of taste secretly controls a garbage boy to cook gourmet food.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-79",
    word: "Inside Out",
    hint: "Personified emotions struggle to keep a young girl happy when her family moves to a new city.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-80",
    word: "Coco",
    hint: "A young boy journeys to the Land of the Dead to uncover his great-grandfather's musical legacy.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-81",
    word: "Moana",
    hint: "A Polynesian teenager sets sail on a daring mission across the ocean to return the heart of a goddess.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-82",
    word: "Zootopia",
    hint: "A rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy among predators.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-83",
    word: "The Incredibles",
    hint: "A family of undercover superheroes is forced into action to save the world from a vengeful fanboy.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-84",
    word: "Monsters Inc",
    hint: "Two scaring professionals find their world turned upside down when a human toddler accidentally enters their factory.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-85",
    word: "Cars",
    hint: "A hot-shot race vehicle gets waylaid in a dusty, forgotten town and learns the true meaning of friendship.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-86",
    word: "Brave",
    hint: "A skilled archer defies an age-old custom in her kingdom, inadvertently unleashing chaos and a bear curse.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-87",
    word: "Tangled",
    hint: "A kidnapped princess with incredibly long, glowing hair escapes her tower with the help of a wanted thief.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-88",
    word: "Big Hero 6",
    hint: "A prodigy bonds with an inflatable healthcare robot to form a high-tech superhero team in San Fransokyo.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-89",
    word: "The Shawshank Redemption",
    hint: "An innocent banker spends decades in a grim prison but maintains his hope through small acts of kindness.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-90",
    word: "The Green Mile",
    hint: "Death row guards witness supernatural events when a gentle giant is brought into their custody.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-91",
    word: "12 Angry Men",
    hint: "A lone juror holds out against his peers in a stifling room, arguing for reasonable doubt in a murder trial.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-92",
    word: "Schindlers List",
    hint: "A German industrialist becomes concerned for his Jewish workforce and spends his fortune to save them from camps.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-93",
    word: "Slumdog Millionaire",
    hint: "An orphan from the streets reflects on his life experiences to answer questions on a high-stakes television game show.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-94",
    word: "Life of Pi",
    hint: "A young man survives a disaster at sea and forms an unexpected connection with a fearsome Bengal tiger on a lifeboat.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-95",
    word: "The Social Network",
    hint: "A Harvard student builds a massive digital platform that connects the world but severely damages his personal friendships.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-96",
    word: "Joker",
    hint: "A mentally troubled comedian in a decaying city starts a slow descent into madness and violence.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-97",
    word: "Oppenheimer",
    hint: "A brilliant physicist oversees the secret project that successfully detonates the first atomic weapon.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-98",
    word: "Barbie",
    hint: "A perfect plastic doll suffers an existential crisis and travels to the real world to find answers.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-99",
    word: "Dune",
    hint: "A noble family is thrust into a war for control over a desert planet producing a highly valuable spice.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-en-100",
    word: "John Wick",
    hint: "A retired hitman seeks vengeance against the mobsters who broke into his home and killed his puppy.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
];
