// game/game-types.ts
/**
 * Shared types for game configuration.
 *
 * These types describe *configuration only* -- how a round should be set
 * up. They intentionally know nothing about players, roles, words, or
 * scoring. Those concerns belong to the game engine / round provider that
 * consumes a `GameConfig` once the player list exists.
 */

export type GameMode = "classic" | "double" | "triple" | "random";

/**
 * The content language for a round's word/hint (and its fallback/cache
 * data). This is deliberately separate from any UI-localization concept
 * -- see lib/settings-store.ts for where the player's preference lives,
 * and game/game-engine.ts for how it gets fixed onto a RoundSession once
 * a round starts. Centralized here (rather than sprinkling raw string
 * literals across the codebase) so every layer -- settings, AI prompt,
 * Dexie schema, fallback data, round state -- shares one definition.
 */
export const ENGLISH = "english" as const;
export const ROMAN_URDU = "roman-urdu" as const;

export type GameLanguage = typeof ENGLISH | typeof ROMAN_URDU;

export const GAME_LANGUAGES: GameLanguage[] = [ENGLISH, ROMAN_URDU];

export function isGameLanguage(value: unknown): value is GameLanguage {
  return value === ENGLISH || value === ROMAN_URDU;
}

// Category is deliberately kept open-ended (`| string`) so that additional
// categories added later via the "More" sheet, or loaded from a local
// category catalog, don't require a type change here.
export type Category =
  | "random"
  | "food"
  | "animals"
  | "sports"
  | "movies"
  | "countries"
  | string;

export type Difficulty = "easy" | "medium" | "hard";

export type TimerSettings = {
  enabled: boolean;
  duration: number; // seconds
};

export type GameOptions = {
  discussionTimer: TimerSettings;
  votingTimer: TimerSettings;
};

export type GameConfig = {
  mode: GameMode;
  category: Category;
  difficulty: Difficulty;
  options: GameOptions;
};

/**
 * A player's public identity only. Screen 3 (Players) is the only place
 * this type is constructed -- it deliberately carries no secret game
 * state (no role, word, hint, or imposter flag). That information is
 * added later, per-round, by the Round Provider in Screen 4+.
 */
export type Player = {
  id: string;
  name: string;
};

/**
 * The handoff shape passed from Players (Screen 3) into Round Preparation
 * (Screen 4). Roles/word/hint are intentionally absent here -- Screen 4
 * is responsible for generating/loading them and assigning roles.
 */
export type GameSession = {
  config: GameConfig;
  players: Player[];
};

/* -------------------------------------------------------------------- */
/* Round Preparation (Screen 4)                                          */
/*                                                                       */
/* Types describing the *result* of preparing a round: the generated     */
/* word/hint, the resolved role assignment, and the full session that    */
/* Screen 5 (and beyond) will consume. Nothing in this section is ever   */
/* rendered on Screen 4 itself -- see game/game-engine.ts.                */
/* -------------------------------------------------------------------- */

/**
 * Which tier ultimately supplied a round's word/hint:
 *   "ai"       -- freshly generated by the AI just now (tier 1)
 *   "cache"    -- a previously AI-generated round, reused from the
 *                 IndexedDB cache (tier 2)
 *   "fallback" -- the static, in-bundle emergency word list (tier 3)
 * See game/game-engine.ts for the priority order between them.
 */
export type RoundContentSource = "ai" | "cache" | "fallback";

/**
 * The output of a word provider (AI or local), before it's attached to a
 * round. Both providers return this exact shape so the game engine stays
 * provider-agnostic (see providers/word-provider.ts).
 */
export type GeneratedRoundContent = {
  word: string;
  hint: string;
  source: RoundContentSource;
  /**
   * Which language this specific word/hint pair is in. Always set
   * explicitly by whichever provider produced the content (AI, cache, or
   * static fallback) -- never inferred later from the hint text itself,
   * since that would be unreliable (an English word like "Pizza" reads
   * the same regardless of which language its hint is in).
   */
  language: GameLanguage;
};

export type PlayerRole =
  | { playerId: string; role: "player" }
  | { playerId: string; role: "imposter" };

export type RoundData = {
  number: number;
  word: string;
  hint: string;
  imposterCount: number;
  roles: PlayerRole[];
  contentSource: RoundContentSource;
  /**
   * Fixed at round-creation time (see game/game-engine.ts) from the
   * player's Settings selection at that moment. Deliberately part of
   * `RoundData` (not re-read from Settings on every render) so that
   * changing the Settings language mid-round -- or refreshing the page
   * during Secret Reveal/Voting/Results -- never changes an
   * already-started round's language out from under the players.
   */
  language: GameLanguage;
};

export type RoundStatus = "preparing" | "ready" | "playing" | "finished";

/**
 * The fully-prepared round, ready to hand off to Screen 5. Distinct from
 * `GameSession` above (which is only the Setup -> Players handoff) --
 * this is what exists once word/hint/roles have actually been resolved.
 */
export type RoundSession = {
  id: string;
  config: GameConfig;
  players: Player[];
  round: RoundData;
  status: RoundStatus;
  currentPlayerIndex: number;
  /**
   * Screen 7's (Voting) persisted ballot box -- keyed by voter player ID,
   * valued by the player ID they voted for. Lives on `RoundSession` (not
   * `RoundData`) for the same reason `currentPlayerIndex` does: it's
   * mutable turn-taking state for one phase of the round, not part of
   * the round's static generated content. There is deliberately no
   * separate "current voter index" field -- game/vote-flow.ts derives
   * whose turn it is directly from this map plus `players` order, so a
   * refresh mid-voting can never desync from who has actually voted
   * (see spec sections 58-64).
   */
  votes?: Record<string, string>;
  /**
   * Screen 8's (Results) persisted outcome of every vote applied so far
   * this game -- player IDs who have been voted out. Optional/defensive
   * for the same reason `votes` is: sessions created before this field
   * existed won't have it. Lives here (not derived fresh from `votes`
   * on every render) because a tie eliminates no one, so "who's out"
   * is NOT simply "who got the most votes" -- it's the accumulated
   * result of every verdict, and must survive a refresh on the Results
   * screen itself (spec's "DATA / STATE REQUIREMENTS").
   */
  eliminatedPlayerIds?: string[];
};