/**
 * Shared types for game configuration.
 *
 * These types describe *configuration only* -- how a round should be set
 * up. They intentionally know nothing about players, roles, words, or
 * scoring. Those concerns belong to the game engine / round provider that
 * consumes a `GameConfig` once the player list exists.
 */

export type GameMode = "classic" | "double" | "triple" | "random";

// Category is deliberately kept open-ended (`| string`) so that additional
// categories added later via the "More" sheet, or loaded from a local
// category catalog, don't require a type change here.
export type Category =
  | "random"
  | "food"
  | "animals"
  | "sports"
  | "movies"
  | "countries"
  | string;

export type Difficulty = "easy" | "medium" | "hard";

export type TimerSettings = {
  enabled: boolean;
  duration: number; // seconds
};

export type GameOptions = {
  discussionTimer: TimerSettings;
  votingTimer: TimerSettings;
};

export type GameConfig = {
  mode: GameMode;
  category: Category;
  difficulty: Difficulty;
  options: GameOptions;
};

/**
 * A player's public identity only. Screen 3 (Players) is the only place
 * this type is constructed -- it deliberately carries no secret game
 * state (no role, word, hint, or imposter flag). That information is
 * added later, per-round, by the Round Provider in Screen 4+.
 */
export type Player = {
  id: string;
  name: string;
};

/**
 * The handoff shape passed from Players (Screen 3) into Round Preparation
 * (Screen 4). Roles/word/hint are intentionally absent here -- Screen 4
 * is responsible for generating/loading them and assigning roles.
 */
export type GameSession = {
  config: GameConfig;
  players: Player[];
};

/* -------------------------------------------------------------------- */
/* Round Preparation (Screen 4)                                          */
/*                                                                       */
/* Types describing the *result* of preparing a round: the generated     */
/* word/hint, the resolved role assignment, and the full session that    */
/* Screen 5 (and beyond) will consume. Nothing in this section is ever   */
/* rendered on Screen 4 itself -- see game/game-engine.ts.                */
/* -------------------------------------------------------------------- */

/**
 * Which tier ultimately supplied a round's word/hint:
 *   "ai"       -- freshly generated by the AI just now (tier 1)
 *   "cache"    -- a previously AI-generated round, reused from the
 *                 IndexedDB cache (tier 2)
 *   "fallback" -- the static, in-bundle emergency word list (tier 3)
 * See game/game-engine.ts for the priority order between them.
 */
export type RoundContentSource = "ai" | "cache" | "fallback";

/**
 * The output of a word provider (AI or local), before it's attached to a
 * round. Both providers return this exact shape so the game engine stays
 * provider-agnostic (see providers/word-provider.ts).
 */
export type GeneratedRoundContent = {
  word: string;
  hint: string;
  source: RoundContentSource;
};

export type PlayerRole =
  | { playerId: string; role: "player" }
  | { playerId: string; role: "imposter" };

export type RoundData = {
  number: number;
  word: string;
  hint: string;
  imposterCount: number;
  roles: PlayerRole[];
  contentSource: RoundContentSource;
};

export type RoundStatus = "preparing" | "ready" | "playing" | "finished";

/**
 * The fully-prepared round, ready to hand off to Screen 5. Distinct from
 * `GameSession` above (which is only the Setup -> Players handoff) --
 * this is what exists once word/hint/roles have actually been resolved.
 */
export type RoundSession = {
  id: string;
  config: GameConfig;
  players: Player[];
  round: RoundData;
  status: RoundStatus;
  currentPlayerIndex: number;
};