// lib/fallback-words/jobs/urdu/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "jobs" category -- Roman Urdu.
 *
 * 100 well-known professions instantly recognizable in everyday Pakistani
 * life. Difficulty changes ONLY how directly the hint points at the word.
 * Hints are written in natural, conversational Roman Urdu using ONLY
 * Latin letters.
 */
export const JOBS_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-jobs-ur-1",
    word: "Doctor",
    hint: "Beemari ke ilaj ke liye log sab se pehle is shakhs ke pas jate hain.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-2",
    word: "Ustad",
    hint: "School mein bachon ko parhane aur sikhane wala eham shakhs.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-3",
    word: "Police",
    hint: "Wardi pehan kar choron ko pakarne aur shehar mein aman kaim rakhne wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-4",
    word: "Fauji",
    hint: "Sarhad par khara ho kar mulk ka difa karne wala bahadur jawan.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-5",
    word: "Nurse",
    hint: "Haspataal mein mareezon ki dekh bhal aur injection lagane wali madadgar.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-6",
    word: "Darzi",
    hint: "Inchi tape se naap le kar machine par naye kapre seene wala peshawar.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-7",
    word: "Mochi",
    hint: "Sarak ke kinare baith kar phatay hue jootay ko sui dhage se theek karne wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-8",
    word: "Naai",
    hint: "Qainchi aur ustura istemal kar ke mardon ke baal katne aur daari banane wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-9",
    word: "Dhobi",
    hint: "Logon ke maile kapre dho kar un par aur theek se istri karne wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-10",
    word: "Driver",
    hint: "Gari ka steering pakar kar logon ko un ki manzil tak le jane wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-11",
    word: "Masi",
    hint: "Gharon mein jharoo poncha karne aur jhootay bartan dhone ke liye anay wali aurat.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-12",
    word: "Mali",
    hint: "Ghar ya park mein phool aur paudon ki hifazat aur kating karne wala shakhs.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-13",
    word: "Mistri",
    hint: "Eent aur cement mila kar paki deewarein khari karne wala taameeri karkun.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-14",
    word: "Mazdoor",
    hint: "Bhari wazan uthane aur imarat banane mein madad karne wala mehnati karkun.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-15",
    word: "Halwai",
    hint: "Baray se karhayi mein taaza jalebi, rasgullay aur dosri meethaiyan banane wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-16",
    word: "Kasai",
    hint: "Baray chaqu se gosht kaat kar dukaan par bechne wala shakhs.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-17",
    word: "Dukan dar",
    hint: "Mohalle mein cheezen bechne wala aur hisab kitab rakhne wala shakhs.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-18",
    word: "Chaprasi",
    hint: "Daftar mein boss ke liye chaye lane aur filen idhar udhar karne wala mulazim.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-19",
    word: "Vakeel",
    hint: "Adalat mein kaale coat mein apne client ka muqadma larne wala qanoondan.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-20",
    word: "Judge",
    hint: "Adalat mein sab se upar baith kar insaf aur faisla sunane wala bada afsar.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-21",
    word: "Kisaan",
    hint: "Kheton mein hal chala kar poore mulk ke liye gandum ugane wala gaon ka mehnati shakhs.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-22",
    word: "Khakroob",
    hint: "Subah savere sarak ke kinare lambi jharoo se kachra saaf karne wala karkun.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-23",
    word: "Pilot",
    hint: "Hawa mein hazaron foot unchai par bada sa hawai jahaz urane wala kaptaan.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-24",
    word: "Engineer",
    hint: "Imarat ke nakshay banane aur bari machines ki drawing theek karne wala mahir.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-25",
    word: "Chowkidar",
    hint: "Raat bhar jaag kar building ki hifazat karne wala aur seeti bajane wala pehredar.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-26",
    word: "Sabzi wala",
    hint: "Rehri par aloo pyaz aur taaza hari mirchein rakh kar awazain lagane wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-27",
    word: "Doodh wala",
    hint: "Subah subah bhains ka taaza khalis doodh dabbo mein daal kar ghar dene anay wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-28",
    word: "Nanbai",
    hint: "Bhatti ya tandoor par awam ke liye garam rotian lagane wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-29",
    word: "Phal wala",
    hint: "Dukaan ya rehri par kailay, saib aur mosam ke taaza fruit bechne wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-30",
    word: "Machli wala",
    hint: "Sardiyon mein khasa mutahrik rehne wala karkun jo kantay nikal kar zinda raho farokht karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-31",
    word: "Kabaari",
    hint: "Gharon se purana loha, raddi aur tooti hui plastic khareedne wala aur pheri lagane wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-32",
    word: "Qari Sahib",
    hint: "Sham ke waqt ghar aa kar masoom bachon ko deeni taleem dene wala shakhs.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-33",
    word: "Imam Masjid",
    hint: "Din mein paanch waqt ki namaz parhane wale mohtaram aalim.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-34",
    word: "Lohaar",
    hint: "Garam aag ki bhatti par loha pighla kar hathore se theek karne wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-35",
    word: "Tarkhaan",
    hint: "Aari chala kar lakri katne aur hamare darwaze kursi banane wala mahir.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-36",
    word: "Painter",
    hint: "Deewaron par brush aur roller se khubsurat rang o roghan karne wala.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-37",
    word: "Mechanic",
    hint: "Workshop mein gari ka engine aur tooti hui cheezen theek karne wala shakhs.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-38",
    word: "Plumber",
    hint: "Ghar mein jab pani ka pipe phat jaye ya toti theek karani ho to usay bulate hain.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-39",
    word: "Electrician",
    hint: "Khraab switch, jal gaya bulb ya bijli ka short circuit theek karne wala karigar.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-40",
    word: "Thekedar",
    hint: "Ghar ya imarat banwane ka poora contract apne sar lene wala boss.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (30)
  {
    id: "fallback-jobs-ur-41",
    word: "Munshi",
    hint: "Purane waqton se chalta araha hai jo seth ka kacha pakka hisab bahi khatay me likhta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-42",
    word: "Cashier",
    hint: "Bank ya bare store ki counter par baith kar dher saare note gin-ne wala shakhs.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-43",
    word: "Sahafi",
    hint: "Hath mein mic le kar jalson mein aur sadkon par taza khabar ikhathi karne wala.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-44",
    word: "Siyasat dan",
    hint: "Awam se vote maang kar parliament mein baithne wala asar o rasookh wala shakhs.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-45",
    word: "Wazir",
    hint: "Mulk ke qanoon aur idaron ka sarbarah jo prime minister ke neechay kaam karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-46",
    word: "Afsar",
    hint: "Government ke daftar mein AC wale kamre mein baith kar sign karne wala aala uhde daar.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-47",
    word: "Clerk",
    hint: "Daftar mein sarkari file bananay aur type writer ya computer chalanay wala mulazim.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-48",
    word: "Manager",
    hint: "Company ka wo ohde daar jis ki duty apne neechay sab ko control aur guide karna hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-49",
    word: "Chotu",
    hint: "Tea stall ya mechanic ke pas bhag bhag kar kaam aur safai karne wala chota mulazim.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-50",
    word: "Bawarchi",
    hint: "Shadi byah mein barray barray daig pakane ke liye makhsoos tor par bulaya gaya expert.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-51",
    word: "Waiter",
    hint: "Hotel mein uniform pehan kar table par khana lane aur order lene wala mulazim.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-52",
    word: "Daakiya",
    hint: "Khaki wardi pehan kar aap ki chithiyan aur parcel aap ke darwaze tak lene wala shakhs.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-53",
    word: "Hawaldar",
    hint: "Thanay mein sipahi se bada lekin afsar se chota muqam rakhne wala mahkuma numainda.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-54",
    word: "Thanedar",
    hint: "Kisi ilaqay ki mukammal hifazat aur qanoon ki zimedari uthane wala police station ka boss.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-55",
    word: "Jasoos",
    hint: "Chup kar logon ke raaz nikalne aur mujrim ko dhoondne mein police ki parda nasheen madad.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-56",
    word: "Jild saaz",
    hint: "Phatte hue Quran ya kitabon par pakhum cardboard laga kar unko mazboot aur naya banane wala.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-57",
    word: "Sunaar",
    hint: "Bari nazaqat se sonay aur chandi ke zewar banane wala bazari mahir.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-58",
    word: "Mimar",
    hint: "Banawat aur tarikh-saazi ki takhleeq karne wala bara aur azeem architect.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-59",
    word: "Kuli",
    hint: "Railway station par laal kameez pehan kar musafiron ka bhari saman apne sar par uthane wala.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-60",
    word: "Tanga wala",
    hint: "Ghore ko chabuk maar kar sawariyon ko lari adda tak le jane wala gariban.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-61",
    word: "Rickshaw wala",
    hint: "Teen pahiyon wali khuli gari chalanay aur paanch paanch logon ko adjust karne wala peshawar.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-62",
    word: "Bus Conductor",
    hint: "Sawariyon ke piche piche chal kar seeti marne aur sub se kiraya wasool karne wala.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-63",
    word: "Ticket Checker",
    hint: "Train ke andar ghoom kar dekhne wala ke kisi ke pas baghair paison ka ticket toh nahi.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-64",
    word: "Gwala",
    hint: "Gaon mein gai bhains rakhne wala jo shehar tak doodh poanchane ka kaam karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-65",
    word: "Maahi geer",
    hint: "Kashti mein baith kar samundar ya darya mein lamba jaal phenkne wala.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-66",
    word: "Kasht kaar",
    hint: "Zameen ko hamwar kar ke fasal ugane ka ilam jannay wala tehqeeqi kisan.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-67",
    word: "Zamindar",
    hint: "Gaon ka ameere tarren shakhs jis ki zameenon par sary gaon wale kaam karte hain.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-68",
    word: "Hakeem",
    hint: "Jari bootiyon ke zariye nubs pakar kar desi aur qudrati ilaj karne wala mahir tabib.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-69",
    word: "Pansari",
    hint: "Choti dukan par saunf, elaichi aur qadeem desi bootian wazan kar ke farokht karne wala.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-70",
    word: "Murgi wala",
    hint: "Gahak ke samne pinjre se zinda desi ya broiler nikal kar usay tayar karne wala karkun.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (30)
  {
    id: "fallback-jobs-ur-71",
    word: "Jallad",
    hint: "Qanooni hukam milne par mujrim ki saza-e-maut par khud amal daramad karwane wala parda nasheen shakhs.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-72",
    word: "Gor kan",
    hint: "Qabaristan mein murday ko supurd-e-khak karne ke liye zameen ke andar gehri jagah taiyar karne wala.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-73",
    word: "Pehelwan",
    hint: "Matti ke akhare mein dawat khaa kar apni taqat ka muzahira karne wala aur dangal jeetne wala.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-74",
    word: "Madari",
    hint: "Mela mein bandar ka tamasha dikha kar bachon ki tawayajo hasil karne wala awara karkun.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-75",
    word: "Sapera",
    hint: "Apni makhsoos been baja kar teh khanon mein chupe hue khatarnak zehreele janwar ko bahar nikalne wala.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-76",
    word: "Marasi",
    hint: "Shadi byah ki ronko mein dholak baja kar apni jugton aur mazaq se gaon walon ko hasane wala.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-77",
    word: "Qawwal",
    hint: "Mazar aur urs ke moke par mehfil mein haath baja kar sufiyaana kalaam paish karne wala maqbool fankaar.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-78",
    word: "Shayar",
    hint: "Mehfil-e-mushaira mein radif aur qafiya mila kar apne ahsaasat logon ko sunane wala fankaar.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-79",
    word: "Musawwir",
    hint: "Saday aur khali kaghaz par brush se behtareen khayalat aur manzarkashi utarne wala funkar.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-80",
    word: "Khattat",
    hint: "Quran ki ayaton ko mukhtalif tehreeron mein nihaayat khoobsurati se kaghaz par naqsh karne wala kalam-kaar.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-81",
    word: "Mulaah",
    hint: "Oonchi uthti hui mojon ke darmiyan chapu chala kar choti kashti ki simt theek rakhne wala kaptaan.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-82",
    word: "Ghota khor",
    hint: "Samundar ki satah se kahin foot neechay lambi saans le kar qeemti moti dhoondne wala karkun.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-83",
    word: "Shikari",
    hint: "Ghane jangal mein bandooq le kar jungli janwaron ke peeche apna waqt guzarnay wala fard.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-84",
    word: "Musiqaar",
    hint: "Gaanay mein harmonium aur tablaj baja kar ek nayi dhun aur beat peda karne wala ustad.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-85",
    word: "Adakaar",
    hint: "Camera ke aagay apne chehre ke tasiro se logon ko rulanay ya hasanay ki salahiyat rakhne wala ptv star.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-86",
    word: "Hidayat kar",
    hint: "Drama ya film ke set par tamam fankaron ko batane wala ke scene kahan se record hoga.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-87",
    word: "Safarat kaar",
    hint: "Gher mulk bheja gaya sarkari numainda jis ka kaam apne mulk ki numaindagi se taluqat theek rakhna hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-88",
    word: "Tajir",
    hint: "Cheezon ko darya paar se la kar bade paimane par khareed o farokht kar ke ahem munafa kamane wala set.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-89",
    word: "Dallal",
    hint: "Do anjaan farikon ke darmyan sode baazi aur khareedari par apna theek theek commission khane wala shakhs.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-90",
    word: "Neelaami wala",
    hint: "Kachehri ke bahar khara ho kar tezi se awazein laga kar saman par lagatar boli barhane wala.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-91",
    word: "Sarraaf",
    hint: "Currency market mein note check kar ke purane daur ka karobar karne wala paisay ki theek pehchan rakhne wala.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-92",
    word: "Qasid",
    hint: "Purane wqaton mein hukmarano ka nihayat zaroori pegham door daraz tak pohnchane wala wafadar ghulam.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-93",
    word: "Moharrir",
    hint: "Police station ki hadood mein tamam f.i.r aur dastawezat ko theek se darj karne wala bara afsar.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-94",
    word: "Patwari",
    hint: "Logon ki zameen aur malkiat ka theek aur mukammal kacha record apne pass rakhne wala mehkama-e-maal ka numainda.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-95",
    word: "Tehsildar",
    hint: "Ilaqay ke muqami zameen-daaron se theek theek saalana tax ki rakam aur wasooli ikathi karne wala eham ahde daar.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-96",
    word: "Nambardar",
    hint: "Gaon ki choti moti pinhchayat ya jhagday suljhane ke liye qaum ke buzurgo ka chuna gaya eham admi.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-97",
    word: "Guard",
    hint: "Bank ya atm ke theek samne subah se sham bandooq lay kar pahera dene wala mehfooz sipahi.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-98",
    word: "Khadima",
    hint: "Kisi ameer shakhs ki kothi mein poora din guzar kar tamam gharelu theek thaak aur intazamaat dekhne wali larki.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-99",
    word: "Dai",
    hint: "Purane zamanay mein gaon mein maon ki aur bacho ki paidaish aur deegar theek sehat mandi me eham kirdar ada karne wali.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-100",
    word: "Jarrah",
    hint: "Theek choti surgery ya zakhm ki murammat ko anjam dene wala muqami mahir karkun jisay amomi theek tareeqay aatay thay.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
