import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "food" category -- Roman Urdu.
 *
 * 100 words drawn from everyday Pakistani kitchen and food vocabulary
 * -- staples, home-cooked dishes, street food, and common spices --
 * every one of them something an average Roman Urdu-speaking player
 * would instantly recognize. As with the English list, difficulty only
 * changes how directly the hint points at the word, never how obscure
 * the word itself is (easy: 40, medium: 30, hard: 30). Hints are
 * written in natural Roman Urdu using only Latin letters, matching the
 * ROMAN_URDU_INSTRUCTIONS convention used for AI-generated hints in
 * app/api/round/generate/route.ts.
 */
export const FOOD_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  {
    id: "fallback-food-ur-1",
    word: "Roti",
    hint: "Har roz ke khane ka bunyadi hissa, gol aur chapti.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-2",
    word: "Naan",
    hint: "Tandoor mein paki hui narm roti.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-3",
    word: "Chawal",
    hint: "Sufaid daane, ubaal kar khaye jate hain.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-4",
    word: "Daal",
    hint: "Chhoti daanay, paani mein paka kar khaye jate hain.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-5",
    word: "Chai",
    hint: "Subah subah sab se zyada piya jane wala garam mashroob.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-6",
    word: "Doodh",
    hint: "Gaaye ya bhains se milta hai, sufaid rang ka.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-7",
    word: "Dahi",
    hint: "Doodh se banta hai, khatta aur gaara hota hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-8",
    word: "Makhan",
    hint: "Doodh se nikala gaya, roti par lagaya jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-9",
    word: "Ghee",
    hint: "Khana pakane ke liye istemal hone wali chikni cheez.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-10",
    word: "Cheeni",
    hint: "Meethay ka bunyadi jaz, chai mein dali jati hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-11",
    word: "Namak",
    hint: "Har khane mein zaroori, sufaid zaiqa dar cheez.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-12",
    word: "Mirch",
    hint: "Khane mein teekhapan lati hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-13",
    word: "Pyaz",
    hint: "Kaatne par aankhon mein paani laa deta hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-14",
    word: "Lehsan",
    hint: "Tez khushbu wali chhoti chhoti kaliyan.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-15",
    word: "Adrak",
    hint: "Chai mein dala jaye to zaiqa badal deta hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-16",
    word: "Aloo",
    hint: "Zameen ke neeche ugti hai, har sabzi mein daali jati hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-17",
    word: "Tamatar",
    hint: "Surkh rang ka, salad aur salan dono mein istemal.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-18",
    word: "Gajar",
    hint: "Lamba aur narangi rang ka, khargosh ki pasandeeda sabzi.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-19",
    word: "Kheera",
    hint: "Thanda aur pani se bhara hua, salad mein katta jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-20",
    word: "Palak",
    hint: "Sabz patton wali sabzi, sehat ke liye mufeed.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-21",
    word: "Gobi",
    hint: "Sufaid rang ki gol sabzi.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-22",
    word: "Bhindi",
    hint: "Lambi sabz sabzi, kaate par leslesi ho jati hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-23",
    word: "Baingan",
    hint: "Chamakdar jamni rang ki sabzi.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-24",
    word: "Matar",
    hint: "Chhote hare daane, ghar mein pulao mein daale jate hain.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-25",
    word: "Anda",
    hint: "Murghi deti hai, ubaal kar ya fry kar ke khaya jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-26",
    word: "Lassi",
    hint: "Dahi se banta hai, thanda aur gaara mashroob.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-27",
    word: "Halwa",
    hint: "Meetha aur garam, aksar naashte mein khaya jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-28",
    word: "Samosa",
    hint: "Tikone shape ka, tal kar banaya jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-29",
    word: "Biryani",
    hint: "Chawal aur gosht ke saath khushbudar masalon wala khana.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-30",
    word: "Pulao",
    hint: "Halka masaledar chawal ka khana, shaadiyon mein aam.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-31",
    word: "Paratha",
    hint: "Tawe par ghee laga kar sanka jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-32",
    word: "Chapati",
    hint: "Aata guundh kar bani hui patli roti.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-33",
    word: "Sabzi",
    hint: "Ghar mein rozana pakaya jane wala sadaharan khana.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-34",
    word: "Achar",
    hint: "Tez aur khatta, roti ke saath khaya jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-35",
    word: "Malai",
    hint: "Doodh ke upar jama hua moti tabaqa.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-36",
    word: "Kheer",
    hint: "Chawal aur doodh se bani meethi dish.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-37",
    word: "Gulab Jaman",
    hint: "Garam, chashni mein doobi hui gol meethi cheez.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-38",
    word: "Laddu",
    hint: "Gol shape ki meethi mithai, khushi ke moqe par batti hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-39",
    word: "Kulfi",
    hint: "Traditional thandi meethi cheez, garmi mein pasand ki jati hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-40",
    word: "Sharbat",
    hint: "Thanda aur meetha mashroob, aksar garmi mein banaya jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-41",
    word: "Karela",
    hint: "Zaiqa kadwa hota hai, lekin sehat ke liye acha mana jata hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-42",
    word: "Shimla Mirch",
    hint: "Teekhi nahi hoti, lekin salad ko rangeen bana deti hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-43",
    word: "Mooli",
    hint: "Zameen ke neeche ugti hai, kaatne par tez khushbu deti hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-44",
    word: "Saag",
    hint: "Sardiyon mein makai ki roti ke saath khaya jata hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-45",
    word: "Doodh Patti",
    hint: "Do cheezein aapas mein milakar garam ki jati hain.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-46",
    word: "Jalebi",
    hint: "Ghumavdar shape ki, chashni mein bhigoi jati hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-47",
    word: "Pakora",
    hint: "Baarish ke mausam mein banane ka rivaj hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-48",
    word: "Nihari",
    hint: "Raat bhar dheemi aanch par pakaya jane wala salan.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-49",
    word: "Haleem",
    hint: "Gosht aur daalon ko ghont ghont kar banaya jata hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-50",
    word: "Karahi",
    hint: "Bartan ke naam se pehchana jane wala mashhoor salan.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-51",
    word: "Qorma",
    hint: "Shaadiyon mein khaas taur par pakaya jane wala salan.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-52",
    word: "Tikka",
    hint: "Angeethi par seekh ke bagair bhi paka sakte hain.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-53",
    word: "Seekh Kebab",
    hint: "Kutte hue gosht ko lambi shape mein bana kar seka jata hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-54",
    word: "Puri",
    hint: "Tel mein phool kar ubhar aati hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-55",
    word: "Kulcha",
    hint: "Naan se milta julta, aksar cholon ke saath khaya jata hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-56",
    word: "Chutney",
    hint: "Khatti meethi, salan ke saath side mein rakhi jati hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-57",
    word: "Papad",
    hint: "Patla aur karara, khane se pehle seka ya talna padta hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-58",
    word: "Sevaiyan",
    hint: "Eid ke din khaas taur par banayi jati hain.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-59",
    word: "Barfi",
    hint: "Chowkor tukdon mein kaati jati hai, mithai ki dukan par milti hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-60",
    word: "Rasgulla",
    hint: "Sufaid rang ki, chashni mein tairti hui gol mithai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-61",
    word: "Falooda",
    hint: "Barf, doodh aur sewaiyan ek glass mein milti hain.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-62",
    word: "Nimbu Pani",
    hint: "Garmi mein tazgi ke liye piya jane wala khatta mashroob.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-63",
    word: "Aam Panna",
    hint: "Kachay phal se banaya jata hai, garmi mein thandak deta hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-64",
    word: "Pani Puri",
    hint: "Chhoti golian, andar bhara hua khatta pani foran khana padta hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-65",
    word: "Chaat",
    hint: "Sadak kinare ke stalls par mashhoor, khatti meethi dish.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-66",
    word: "Dahi Bhalla",
    hint: "Dahi ke neeche chhupi hui narm cheez hoti hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-67",
    word: "Bun Kebab",
    hint: "Do tukdon ke darmiyan gosht ka tikka rakha jata hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-68",
    word: "Chapli Kebab",
    hint: "Chapte shape ka, tawe par talna padta hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-69",
    word: "Gol Gappay",
    hint: "Shehar bhar mein har chowk par thele wale bechte hain.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-70",
    word: "Fruit Chaat",
    hint: "Kai phalon ko kaat kar ek saath mila diya jata hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-71",
    word: "Pan",
    hint: "Khane ke baad muh ka zaiqa taaza karne ke liye khaya jata hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-72",
    word: "Supari",
    hint: "Chhoti si cheez jo aksar ek aur cheez ke saath mili hoti hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-73",
    word: "Gur",
    hint: "Ganne se banta hai, cheeni ka purana desi mutabadil.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-74",
    word: "Shakkar",
    hint: "Dana dana, cheeni se thora mota mota hota hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-75",
    word: "Besan",
    hint: "Chane ki pissi hui cheez, pakoray isi se bante hain.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-76",
    word: "Maida",
    hint: "Bohot bareek pisa hua, cake aur naan dono mein istemal.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-77",
    word: "Suji",
    hint: "Halwa banane ke kaam aati hai, dane dane wali cheez.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-78",
    word: "Ajwain",
    hint: "Chhoti si beej, pet dard mein aksar istemal hoti hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-79",
    word: "Zeera",
    hint: "Salan mein sab se pehle tel mein dala jata hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-80",
    word: "Dhania",
    hint: "Sabz patte, garnish ke taur par upar chhirka jata hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-81",
    word: "Haldi",
    hint: "Peela rang deti hai, chot par bhi lagayi jati hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-82",
    word: "Garam Masala",
    hint: "Kai masalon ka aisa mixture jo har ghar ka apna hota hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-83",
    word: "Kali Mirch",
    hint: "Chhoti kaali gol dane, teekhapan ke liye pisi jati hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-84",
    word: "Tez Patta",
    hint: "Salan mein dala jata hai, lekin khaya nahi jata.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-85",
    word: "Elaichi",
    hint: "Chai mein dali jaye to khushbu bilkul badal jati hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-86",
    word: "Laung",
    hint: "Chhota sa masala, aksar daant dard mein dabaya jata hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-87",
    word: "Dalchini",
    hint: "Lakdi jaisi chhal, meethi dishon mein daali jati hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-88",
    word: "Til",
    hint: "Chhote chhote daane, laddu par chipkaye jate hain.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-89",
    word: "Khoya",
    hint: "Doodh ko ghanta kar sukhaya jata hai, mithai ki jaan hota hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-90",
    word: "Rabri",
    hint: "Doodh ki tehen dar mithai, kulfi ke saath parosi jati hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-91",
    word: "Custard",
    hint: "Naram aur gaara, phalon ke saath thanda parosa jata hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-92",
    word: "Jelly",
    hint: "Hilti hui, bachon ki pasandeeda meethi cheez.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-93",
    word: "Gola Ganda",
    hint: "Barf ko kaddu kas kar rang bharay jate hain.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-94",
    word: "Rooh Afza",
    hint: "Gulabi rang ka sharbat, Ramzan mein aam milta hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-95",
    word: "Sattu",
    hint: "Bhuni hui daal ka satu, garmi mein thandak ke liye ghola jata hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-96",
    word: "Channa Chaat",
    hint: "Ublay hue daane, pyaz tamatar ke saath mila diye jate hain.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-97",
    word: "Aloo Chaat",
    hint: "Talay hue tukdon par khatti meethi chutney dali jati hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-98",
    word: "Dahi Baray",
    hint: "Dahi mein doob kar naram ho jate hain.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-99",
    word: "Ganne ka Ras",
    hint: "Lambay danday se nichoda jata hai, sadak kinare milta hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-100",
    word: "Nariyal Pani",
    hint: "Upar se sakht, andar se thanda mashroob.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
