// lib/fallback-words/nature/english/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "nature" category -- English.
 *
 * All 100 words are common, universally recognizable elements of the natural
 * world (weather, geography, flora, celestial bodies). Difficulty controls
 * ONLY how directly the hint points at the word:
 *   - easy (40):   states the most obvious trait, color, or defining function.
 *   - medium (30): points to secondary details, associated natural cycles, or locations.
 *   - hard (30):   oblique angles, indirect consequences, or broader phenomena.
 */
export const NATURE_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-nature-en-1",
    word: "Sun",
    hint: "The massive, incredibly hot yellow star that lights up the sky during the daytime.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-2",
    word: "Moon",
    hint: "The glowing white orb that naturally illuminates the dark sky every night.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-3",
    word: "Star",
    hint: "A tiny, twinkling point of light visible entirely across the night sky.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-4",
    word: "Cloud",
    hint: "A fluffy white mass of condensed water floating high up in the blue sky.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-5",
    word: "Rain",
    hint: "Liquid water droplets that continuously fall from gray skies during a wet storm.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-6",
    word: "Snow",
    hint: "Soft, freezing white flakes that fall from the winter sky and cover the ground.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-7",
    word: "Wind",
    hint: "The invisible, moving outdoor air that blows fallen leaves across the street.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-8",
    word: "River",
    hint: "A large, continuously flowing stream of fresh water heading towards the sea.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-9",
    word: "Mountain",
    hint: "A massive, towering peak of rock and earth that stretches high into the clouds.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-10",
    word: "Ocean",
    hint: "The absolutely massive body of salty water that covers most of planet Earth.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-11",
    word: "Beach",
    hint: "The sandy shore located directly along the edge of the crashing sea.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-12",
    word: "Sand",
    hint: "The millions of tiny, gritty golden grains you walk on at the coastline.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-13",
    word: "Rock",
    hint: "A hard, solid piece of grayish stone found resting on the ground outdoors.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-14",
    word: "Grass",
    hint: "The short, green vegetation that completely covers a typical suburban front lawn.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-15",
    word: "Leaf",
    hint: "The flat, green part of a plant that changes color and falls off in autumn.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-16",
    word: "Flower",
    hint: "The beautifully colored, sweet-smelling bloom that grows gracefully in a garden.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-17",
    word: "Dirt",
    hint: "The brown, messy soil covering the ground where all plants and crops grow.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-18",
    word: "Sky",
    hint: "The massive blue expanse directly above us where birds and airplanes fly.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-19",
    word: "Fire",
    hint: "The hot, glowing orange flames you build at a campsite to stay warm.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-20",
    word: "Water",
    hint: "The clear, essential liquid that completely fills our lakes, streams, and oceans.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-21",
    word: "Ice",
    hint: "Solid, entirely frozen water that makes the winter sidewalks incredibly slippery.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-22",
    word: "Tree",
    hint: "A tall plant with a thick wooden trunk and branches covered in green foliage.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-23",
    word: "Wood",
    hint: "The hard, brown natural material you chop with an axe to burn in a fireplace.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-24",
    word: "Forest",
    hint: "A massive, dense woodland area completely covered by thousands of tall trees.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-25",
    word: "Island",
    hint: "A secluded piece of solid land completely surrounded on all sides by water.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-26",
    word: "Waterfall",
    hint: "A beautiful natural feature where a flowing river drops vertically over a steep cliff.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-27",
    word: "Cave",
    hint: "A deep, naturally dark hollow opening found carved directly into the side of a rocky hill.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-28",
    word: "Valley",
    hint: "The low, flat stretch of lush land situated directly between two high peaks.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-29",
    word: "Lightning",
    hint: "The sudden, blindingly bright jagged flash of electricity that strikes during a storm.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-30",
    word: "Thunder",
    hint: "The incredibly loud, booming sound that shakes the windows right after a bright electrical flash.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-31",
    word: "Storm",
    hint: "A severely violent weather event featuring dark clouds, heavy downpours, and harsh gales.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-32",
    word: "Tornado",
    hint: "A highly destructive, rapidly spinning funnel of dark air that violently tears across the plains.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-33",
    word: "Volcano",
    hint: "A massive, cone-shaped mountain that suddenly erupts by violently spewing out molten rock.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-34",
    word: "Earthquake",
    hint: "A terrifying natural disaster where the solid ground suddenly starts shaking violently.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-35",
    word: "Rainbow",
    hint: "A beautiful, multi-colored arc that appears in the sky right after a shower ends.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-36",
    word: "Desert",
    hint: "An incredibly dry, sandy wasteland where very little rain ever falls and cacti grow.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-37",
    word: "Lake",
    hint: "A large, mostly still body of fresh water completely surrounded by solid land.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-38",
    word: "Pond",
    hint: "A very small, quiet body of water where frogs and ducks usually swim.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-39",
    word: "Bush",
    hint: "A short, densely packed leafy shrub commonly planted as a decorative garden hedge.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-en-40",
    word: "Plant",
    hint: "Any living, green, growing organism that relies on soil, water, and sunlight to survive.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (30)
  {
    id: "fallback-nature-en-41",
    word: "Seed",
    hint: "The tiny, hard kernel you bury deep in the soil to slowly grow a brand new vegetable.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-42",
    word: "Root",
    hint: "The hidden, underground part of a crop that anchors it down and fiercely absorbs moisture.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-43",
    word: "Branch",
    hint: "The long, wooden arm extending outward from a trunk, where birds usually build their nests.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-44",
    word: "Bark",
    hint: "The tough, rough outer protective skin completely wrapping around the trunk of a tall pine.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-45",
    word: "Thorn",
    hint: "A sharp, painful, pointy spike growing defensively on the stem of a beautiful red rose.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-46",
    word: "Vine",
    hint: "A long, creeping green stem that aggressively climbs up brick walls or wraps around fences.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-47",
    word: "Moss",
    hint: "A soft, spongy green carpet that naturally grows on damp rocks heavily shaded by the canopy.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-48",
    word: "Mushroom",
    hint: "A fleshy, umbrella-shaped fungus that suddenly pops up in damp soil after a heavy shower.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-49",
    word: "Dust",
    hint: "Fine, dry particles of earth that easily blow around in the air during incredibly dry weather.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-50",
    word: "Mud",
    hint: "The wet, sticky, messy mixture created immediately when heavy downpours mix directly with topsoil.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-51",
    word: "Clay",
    hint: "A stiff, sticky natural soil used entirely for molding pottery and shaping building bricks.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-52",
    word: "Pebble",
    hint: "A very small, entirely smooth rounded stone commonly skipped effortlessly across the surface of a pond.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-53",
    word: "Cliff",
    hint: "A steep, high vertical wall of solid rock usually found dropping sharply right into the sea.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-54",
    word: "Hill",
    hint: "A naturally raised area of land, noticeably smaller and much easier to climb than a towering peak.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-55",
    word: "Canyon",
    hint: "A massive, deep gorge heavily carved through solid rock over millions of years by a flowing stream.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-56",
    word: "Stream",
    hint: "A narrow, continuously bubbling flow of fresh water that is significantly smaller than a full river.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-57",
    word: "Wave",
    hint: "The rolling swell of saltwater that rises up and violently crashes directly onto the shoreline.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-58",
    word: "Tide",
    hint: "The natural daily rising and falling of the sea level caused entirely by lunar gravity.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-59",
    word: "Breeze",
    hint: "A very gentle, highly refreshing puff of moving air on a suffocatingly hot summer afternoon.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-60",
    word: "Hurricane",
    hint: "A massive, severely destructive tropical cyclone characterized by furious gales and flooded coastal cities.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-61",
    word: "Fog",
    hint: "A thick, low-lying morning mist that makes driving on the highway incredibly difficult to see.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-62",
    word: "Dew",
    hint: "The tiny, delicate water droplets discovered sparkling gently on morning grass right at sunrise.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-63",
    word: "Frost",
    hint: "The thin, icy white coating that completely glazes your car windshield on a bitterly cold dawn.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-64",
    word: "Hail",
    hint: "Solid pellets of freezing ice that rapidly plummet from severe thunderstorms, heavily denting parked cars.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-65",
    word: "Meteor",
    hint: "A streak of burning space debris rapidly burning up as it instantly enters our upper atmosphere.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-66",
    word: "Comet",
    hint: "An icy, glowing celestial object with a distinct, long trailing tail sweeping across the cosmos.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-67",
    word: "Planet",
    hint: "A massive, spherical celestial body, like Mars or Jupiter, completely orbiting around our central solar system.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-68",
    word: "Galaxy",
    hint: "A massive, swirling cluster containing billions of glowing solar systems held together by immense gravity.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-69",
    word: "Sunrise",
    hint: "The glorious early morning phenomenon when daylight first breaks beautifully over the eastern horizon.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-en-70",
    word: "Sunset",
    hint: "The incredibly colorful evening hour when daylight inevitably disappears completely beyond the western edge.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },

  // HARD (30)
  {
    id: "fallback-nature-en-71",
    word: "Eclipse",
    hint: "An awe-inspiring astronomical alignment temporarily casting a massive dark shadow directly over a celestial body.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-72",
    word: "Equinox",
    hint: "The biannual celestial event ensuring daytime and nighttime are completely and perfectly equal in length.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-73",
    word: "Season",
    hint: "One of the four distinct quarters of the calendar year dictated by our axial tilt.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-74",
    word: "Spring",
    hint: "The rejuvenating quarter of the year where dormant buds awaken, thaw out, and begin blooming profusely.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-75",
    word: "Summer",
    hint: "The absolute hottest, most intensely sunny quarter of the year causing widespread vacations and sweltering temperatures.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-76",
    word: "Autumn",
    hint: "The transitional quarter of the calendar completely characterized by falling foliage and cooling twilight temperatures.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-77",
    word: "Winter",
    hint: "The bitter, intensely frigid quarter of the year dominated entirely by dormancy and icy conditions.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-78",
    word: "Drought",
    hint: "An incredibly prolonged, devastating atmospheric period completely lacking any precipitation, causing devastating agricultural failure.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-79",
    word: "Flood",
    hint: "An overwhelming, disastrous overflow of accumulated precipitation that rapidly submerges previously dry, habitable land.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-80",
    word: "Tsunami",
    hint: "An extraordinarily massive, destructive seismic swell traveling rapidly toward a vulnerable coastline after tectonic shifting.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-81",
    word: "Whirlpool",
    hint: "A rapidly rotating, incredibly dangerous downward spiraling current created entirely by conflicting, chaotic aquatic forces.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-82",
    word: "Reef",
    hint: "A bustling, shallow underwater ecosystem primarily constructed from the skeletal remains of tiny, colorful organisms.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-83",
    word: "Coral",
    hint: "The hard, brightly colored marine invertebrate that slowly builds sprawling, magnificent submerged architectural ecosystems.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-84",
    word: "Seaweed",
    hint: "A slippery, slimy green marine algae frequently discovered washed up and tangled completely on the shoreline.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-85",
    word: "Pearl",
    hint: "A smooth, highly valuable iridescent sphere organically formed completely inside the protective shell of a mollusk.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-86",
    word: "Shell",
    hint: "The discarded, hard calcium exterior originally utilized for protection by a small, crawling marine creature.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-87",
    word: "Fossil",
    hint: "The beautifully preserved, petrified remains of a prehistoric organism discovered deeply embedded in solid sediment.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-88",
    word: "Magma",
    hint: "The incredibly hot, pressurized semi-liquid subterranean material churning violently deep beneath the planetary crust.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-89",
    word: "Lava",
    hint: "The glowing, incredibly dangerous molten discharge actively flowing down the side of an erupting crater.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-90",
    word: "Ash",
    hint: "The powdery, gray particulate fallout continuously drifting downward in the immediate aftermath of heavy burning.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-91",
    word: "Smoke",
    hint: "The suffocating, hazy gray plume rapidly rising vertically from a newly ignited, smoldering campfire.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-92",
    word: "Shadow",
    hint: "The dark, completely unlit silhouette projected onto the ground whenever a solid object completely blocks illumination.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-93",
    word: "Light",
    hint: "The visible electromagnetic radiation absolutely essential for allowing human retinas to perceive their surroundings.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-94",
    word: "Darkness",
    hint: "The complete and total absence of any visible illumination, triggering primal fears of the unseen.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-95",
    word: "Heat",
    hint: "The intense thermal energy overwhelmingly felt radiating directly onto your skin during a sweltering afternoon.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-96",
    word: "Cold",
    hint: "The bitter, biting thermal absence that causes uncontrollable shivering when you accidentally step outside unprotected.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-97",
    word: "Humidity",
    hint: "The suffocating atmospheric moisture density making the air feel incredibly thick, sticky, and uncomfortably heavy.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-98",
    word: "Oxygen",
    hint: "The invisible, odorless atmospheric element actively inhaled by our lungs to keep our blood circulating.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-99",
    word: "Swamp",
    hint: "A severely waterlogged, incredibly humid wetland area heavily infested with mosquitoes and dangerous submerged reptiles.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-en-100",
    word: "Oasis",
    hint: "A lush, miraculously watered sanctuary utterly isolated completely by miles of surrounding, unforgiving arid wasteland.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
];
