import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // android/** contains the Capacitor web assets bundle -- compiled,
    // minified JS copied in by `npx cap sync`, never hand-written source.
    // Linting it produces thousands of meaningless warnings/errors on
    // minified variable names ('t', 'e', 'r', ...) and is pure noise.
    "android/**",
    // public/sw.js is generated by scripts/generate-sw.js, not
    // hand-written -- see that script's own header comment.
    "public/sw.js",
  ]),
  {
    // scripts/generate-sw.js is a standalone, zero-dependency Node CJS
    // script (see its own header comment) run directly via `node`, not
    // bundled by Next.js -- require() is the correct import style here,
    // not a mistake the TypeScript rule should flag.
    files: ["scripts/**/*.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
]);

export default eslintConfig;