import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "places" category -- Roman Urdu.
 *
 * 100 words drawn from everyday Pakistani locations and cultural hotspots
 * -- local shops, architectural spots, and community areas -- every one of
 * them something an average Roman Urdu-speaking player would instantly recognize.
 * As with the English list, difficulty only changes how directly the hint
 * points at the word, never how obscure the word itself is.
 * Hints are written in natural Roman Urdu using only Latin letters.
 */
export const PLACES_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-places-ur-1",
    word: "Masjid",
    hint: "Log yahan din mein panch waqt namaz parhne jama hote hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-2",
    word: "Bazaar",
    hint: "Wo jagah jahan se aap kapre, jootay aur zarurat ka saman khareedte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-3",
    word: "Tandoor",
    hint: "Yahan bhatti mein garm aur tazi rotiyan aur naan lagaye jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-4",
    word: "Shadi Hall",
    hint: "Wo bari building jahan dulha dulhan ki barat aur walima hota hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-5",
    word: "Haspataal",
    hint: "Jab koi bohat bemar ho ya accident ho jaye to usay yahan le jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-6",
    word: "Petrol Pump",
    hint: "Gari ya motorcycle mein eendhan dalwane ke liye log idhar jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-7",
    word: "Qabristan",
    hint: "Marne ke baad logon ko yahan mitti mein dafan kiya jata hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-8",
    word: "Bawarchi Khana",
    hint: "Ghar ka wo kamra jahan chulha hota hai aur khana pakta hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-9",
    word: "Ghusal Khana",
    hint: "Wo jagah jahan balti ya shower laga hota hai nahanay ke liye.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-10",
    word: "Baithak",
    hint: "Ghar ka wo aage wala kamra jahan mehmano ko bithaya jata hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-11",
    word: "Chhat",
    hint: "Ghar ka sab se oopar wala hissa jahan kapre sukhane daalte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-12",
    word: "Sehan",
    hint: "Ghar ke beecho beech khuli jagah jahan charpai daal kar baithte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-13",
    word: "Gali",
    hint: "Mohallay ki wo tang sarak jahan par gharon ke darwaze khulte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-14",
    word: "Chawk",
    hint: "Sarak ka wo hissa jahan chaar mukhtalif raste aapas mein milte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-15",
    word: "Bus Stand",
    hint: "Safar karne ke liye log yahan aakar dusre shehar ki gari pakarte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-16",
    word: "Medical Store",
    hint: "Bimari mein doctor ka nuskha dikha kar yahan se dawai milti hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-17",
    word: "Karyana Store",
    hint: "Mohallay ki dukan jahan se aanta, cheeni aur daal milti hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-18",
    word: "Naai Ki Dukan",
    hint: "Mard hazrat yahan ja kar apne baal katwate aur daari banwate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-19",
    word: "Darzi Ki Dukan",
    hint: "Eid se pehle yahan naye kapre silwane ka bohut rush hota hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-20",
    word: "Qasai Ki Dukan",
    hint: "Bara sa thaha aur chhuriyan hoti hain jahan se taza gosht milta hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-21",
    word: "Sabzi Mandi",
    hint: "Subah subah yahan truko mein aloo, tamatar aur deegar faslain utarti hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-22",
    word: "Lunda Bazaar",
    hint: "Wo market jahan se saste aur istemal shuda import kiye gaye kapre milte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-23",
    word: "Thana",
    hint: "Chori ya jurm hone ki surat mein police ki report likhwane idhar jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-24",
    word: "Kachehri",
    hint: "Yahan wakeel kale coat pehan kar logon ke muqadmat adalat mein larte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-25",
    word: "Daak Khana",
    hint: "Ek shehar se dusre shehar khatt bhejne ke liye ticket yahan se milta hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-26",
    word: "Bank",
    hint: "Log apni bachat ke paise jama karwane ya nikalwane is office ate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-27",
    word: "School",
    hint: "Bachay subah uniform pehan kar bag latkae idhar taleem hasil karne jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-28",
    word: "Tuition Center",
    hint: "Sham ke waqt talib ilm extra parhai ke liye is academy jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-29",
    word: "Khoka",
    hint: "Sarak kinare lakri ka chhota sa dabba jahan se biscuit aur juice milta hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-30",
    word: "Dhabba",
    hint: "Highway par truck driver yahan charpai par baith kar dal chawal khate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-31",
    word: "Mazar",
    hint: "Kisi wali Allah ki qabar jahan log dua aur fatiha ke liye aate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-32",
    word: "Khet",
    hint: "Kisan yahan hal chalata hai aur gandum ya chawal ki fasal ugata hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-33",
    word: "Karkhana",
    hint: "Bari bari machinon wali jagah jahan mazdoor din raat kaam karte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-34",
    word: "Toll Plaza",
    hint: "Motorway par inter hone ke liye yahan gari rok kar parchi katwani parti hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-35",
    word: "Railway Station",
    hint: "Phatak, platform aur lambi gariyon ka intezar karne ki jagah.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-36",
    word: "Chai Ka Hotel",
    hint: "Log doston ke sath aakar yahan dhoodh patti aur paratha enjoy karte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-37",
    word: "Nahar",
    hint: "Zameenon ko pani dene ke liye khodi gayi choti behti hui nadi.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-38",
    word: "Darya",
    hint: "Pani ka wo bara behata raasta jis mein log kashtiyan chalate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-39",
    word: "Pahar",
    hint: "Zameen ka kafi ooncha aur pathreela hissa jis par charhna mushkil hota hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-40",
    word: "Mela",
    hint: "Jashan ke moqay par lagne wala bazar jahan jhoolay aur khel tamashay hote hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-places-ur-41",
    word: "Mithai Ki Dukan",
    hint: "Khushi ke moqay par yahan se kaju katli aur gulab jamun latey hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-42",
    word: "Juta Market",
    hint: "Yahan ke har showroom mein qadam qadam par naye boot aur sandal saje hote hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-43",
    word: "Kapra Market",
    hint: "Aurten yahan ja kar suiton ke than khulwati hain aur mol bhao karti hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-44",
    word: "Sonaar Ki Dukan",
    hint: "Shadi ke zevarat aur angoothiyan khareedne ke liye is mehngi jagah jana parta hai.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-45",
    word: "Pan Shop",
    hint: "Log khana khane ke baad yahan se meetha ya saada patti banwate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-46",
    word: "Puncture Wali Dukan",
    hint: "Jab gari ya bike ka tyre flat ho jaye to yahan usay theek karwate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-47",
    word: "Workshop",
    hint: "Engine mein masla ho ya oil change karwana ho, mechanic yahan sab dekhta hai.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-48",
    word: "Service Station",
    hint: "Safar se wapsi par gari dho kar aur polish karwane yahan chor dete hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-49",
    word: "Marriage Bureau",
    hint: "Jin ke rishtay nahi ho rahe hote wo daftar wale inko madadd dete hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-50",
    word: "Nadra Office",
    hint: "Yahan log ghanton line mein lag kar apna shanakhti card banwate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-51",
    word: "Passport Office",
    hint: "Bahar ke mulk ka visa lagwane se pehle yahan ki kaghazi karwai zaroori hai.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-52",
    word: "Bijli Ka Daftar",
    hint: "Bill ziyada aa jaye ya transformer jal jaye to awam yahan aakar ehtejaj karti hai.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-53",
    word: "Chidiya Ghar",
    hint: "Itwar wale din familes yahan bhaloo aur bandar dekhne ki ticket leti hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-54",
    word: "Park",
    hint: "Shaam ke waqt log yahan ghaas par joging karne aur taazi hawa lene ate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-55",
    word: "Sahil",
    hint: "Log rati aur lahron ka maza lene aur oont ki sawari karne yahan jate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-56",
    word: "Barfani Ilaqa",
    hint: "Sardiyon mein log shehar se nikal kar pahaaron par thand aur snowfall dekhne jate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-57",
    word: "Jheel",
    hint: "Pahaaron ke darmiyan pani ka zakheera jahan kashti mein ghoomne ka apna maza hai.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-58",
    word: "Nala",
    hint: "Shehar ka ganda pani is khuli hui jagah se guzar kar bahar nikalta hai.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-59",
    word: "Qila",
    hint: "Badshahon ke zamane ki taameer karda majboot deewaron wali purani pathar ki building.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-60",
    word: "Jalsa Gah",
    hint: "Siyasi leader ground mein kursi par khare hokar awam ko yahan takreer sunate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-61",
    word: "Pind",
    hint: "Shehar ke shor se door jahan matti ke ghar aur kache raste hote hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-62",
    word: "Haveli",
    hint: "Zameendaron ka bohut bara aabaai ghar jis ke lakri ke baray darwaze hote hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-63",
    word: "Dairy Farm",
    hint: "Yahan kafi sari gaye aur bhensein bandhi hoti hain taza doodh nikalne ke liye.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-64",
    word: "Khali Plot",
    hint: "Bachay shaam ko cricket khailte hain kyun ke is jagah par abhi ghar nahi bana.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-65",
    word: "Godam",
    hint: "Tajir apna sara extra saman bechne se pehle is band aur andheri jagah rakhte hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-66",
    word: "Toll",
    hint: "Commercial gariyon ko shehar mein dakhil hone par yahan tax dena parta hai.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-67",
    word: "Bakery",
    hint: "Patties, cake aur biskut taze taze yahan se dabbay mein pack karwaye jate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-68",
    word: "Naka",
    hint: "Police wale sarak par barrier laga kar shanakhti card aur gari ke kaghaz check karte hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-69",
    word: "Tuition Center",
    hint: "Board ke imtehan se pehle talib ilm yahan crash course karne jate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-70",
    word: "Markaz",
    hint: "Kisi bhi sector ka wo hissa jahan sari commercial dukanay aur daftar mojood hote hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-places-ur-71",
    word: "Zanan Khana",
    hint: "Purane zamane ke gharon mein sirf aurton ke baithne aur milne julne ka makhsoos hissa.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-72",
    word: "Mardana",
    hint: "Wo baithak jahan sirf mard hazrat apne doston ke sath aakar gup shup lagate hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-73",
    word: "Balcony",
    hint: "Flats mein rehne wale bahar ki hawa khane ke liye is choti si jagah nikalte hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-74",
    word: "Chhajja",
    hint: "Barish se bachne ke liye deewar se bahar nikla hua lenter ka thora sa hissa.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-75",
    word: "Teh Khana",
    hint: "Ghar ka wo kamra jo zameen ke bilkul neechay khod kar banaya jata hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-76",
    word: "Store Room",
    hint: "Sardiyon ke kambal aur tootey phootey dabbe log is fuzool jagah par phaink dete hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-77",
    word: "Paani Ki Tanki",
    hint: "Jab motor chalti hai to sab se oopar rakhi ye cheez over flow ho jati hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-78",
    word: "Gutter",
    hint: "Jab barish bohut zyada hoti hai to sarak par iska dhakkan ubalne lagta hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-79",
    word: "Kabari Ki Dukan",
    hint: "Purane raddi akhbar aur tooti plastic yahan raddi ke bhao taul kar bechi jati hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-80",
    word: "Quetta Hotel",
    hint: "Yahan patti aur pathan ki roti khaas hoti hai aur subah paratha milta hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-81",
    word: "Biryani Center",
    hint: "Baray degh rakhe hote hain aur garam masalon ki mehak door se ati hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-82",
    word: "Shawarma Stall",
    hint: "Ek seekh par laga hua murghi ka gosht gol gol ghoom kar pakta rehta hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-83",
    word: "Ganne Ki Machine",
    hint: "Garmio ki dhoop mein yahan baraf daal kar thanda ras nikala jata hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-84",
    word: "Pushcart",
    hint: "Ek gari jis par dukaandar saman rakh kar pura din sarak par thelta hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-85",
    word: "Juma Bazar",
    hint: "Hafte mein ek din tambu laga kar yahan saste daamo har cheez milti hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-86",
    word: "Mochi Ki Dukan",
    hint: "Sandal ka tasma toot jaye to suwi dhaaga le kar isay yahan theek karate hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-87",
    word: "Lohar Ki Dukan",
    hint: "Aag ke bhambhar par garam lohe ko hathoray se koot kar naya roop dete hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-88",
    word: "Lakri Ka Karkhana",
    hint: "Aari chalne ka bohut shor hota hai aur har taraf burada hi burada urta hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-89",
    word: "Bakra Mandi",
    hint: "Eid ul Azha se chand din pehle yahan bohut keechar aur bhari rush hota hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-90",
    word: "Race Club",
    hint: "Log yahan aakar ghoron ki dor par apne hisab se shart lagate hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-91",
    word: "Snooker Club",
    hint: "Nojawan larke lambi stick le kar colored balls ko aik dosre se takrate hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-92",
    word: "Gaming Zone",
    hint: "Bachay andhere kamre mein screen ke samne controler pakar kar FIFA khailte hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-93",
    word: "Akhara",
    hint: "Mitti ke is maidan mein mard ek dusre ko dhoop mein zor azma kar patakhte hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-94",
    word: "Langar Khana",
    hint: "Ghareeb aur beghar logon ko yahan muft aur paka hua salan khilaya jata hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-95",
    word: "Yateem Khana",
    hint: "Aise bachay jin ke waldain is duniya mein nahi rahe, unki rehaish ki jagah.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-96",
    word: "Edhi Center",
    hint: "Lashon ko gusal dene se le kar lawaris logon ko panaah dene ka idara.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-97",
    word: "Pagal Khana",
    hint: "Wo jagah jahan zehni tawazun kho dene wale mareezon ka elaaj kiya jata hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-98",
    word: "Hawalat",
    hint: "Jurm sabit hone se pehle mulzim ko salaakhon ke peechay police yahin rakhti hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-99",
    word: "Phatak",
    hint: "Train ke guzarne se theek pehle traffic ko roknay ke liye isay gira diya jata hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-100",
    word: "Gol Chakkar",
    hint: "Traffic ko control karne ke liye sarak ke darmiyan banaya gaya aik bada daira.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
