// entities/round/model/round-types.ts
import type { Player } from "@/entities/player";
import type { GameConfig } from "@/entities/game-session";
import type { GameLanguage, VotingHistoryEntry } from "@/game/game-types";

/**
 * NOTE on the imports above: `GameLanguage` and `VotingHistoryEntry`
 * are still defined in the pre-FSD `game/game-types.ts` -- see
 * ../../README.md. `GameLanguage` hasn't been assigned a slice yet,
 * and `VotingHistoryEntry` belongs to the planned `entities/voting-history`
 * slice. This entity depends on both as a deliberate, temporary bridge;
 * update these imports once that slice moves. `GameConfig` no longer
 * needs a bridge -- it's imported directly from `entities/game-session`
 * now that that slice exists (a normal, sparing cross-slice import
 * within the entities layer, not a bridge).
 */

/**
 * Which tier ultimately supplied a round's word/hint:
 *   "ai"       -- freshly generated by the AI just now (tier 1)
 *   "cache"    -- a previously AI-generated round, reused from the
 *                 IndexedDB cache (tier 2)
 *   "fallback" -- the static, in-bundle emergency word list (tier 3)
 *   "custom"   -- a player-authored word from Settings -> Custom Words
 *                 (lib/db.ts's `customWords` table), selected instead of
 *                 the 3-tier chain above when the round's category is
 *                 the CUSTOM_CATEGORY pseudo-category (game/game-rules.ts)
 * See game/game-engine.ts for the priority order between them.
 */
export type RoundContentSource = "ai" | "cache" | "fallback" | "custom";

/**
 * The output of a word provider (AI or local), before it's attached to a
 * round. Both providers return this exact shape so the game engine stays
 * provider-agnostic (see providers/word-provider.ts).
 */
export type GeneratedRoundContent = {
  word: string;
  hint: string;
  source: RoundContentSource;
  /**
   * Which language this specific word/hint pair is in. Always set
   * explicitly by whichever provider produced the content (AI, cache, or
   * static fallback) -- never inferred later from the hint text itself,
   * since that would be unreliable (an English word like "Pizza" reads
   * the same regardless of which language its hint is in).
   */
  language: GameLanguage;
};

export type PlayerRole =
  | { playerId: string; role: "player" }
  | { playerId: string; role: "imposter" };

export type RoundData = {
  number: number;
  word: string;
  hint: string;
  imposterCount: number;
  roles: PlayerRole[];
  contentSource: RoundContentSource;
  /**
   * Fixed at round-creation time (see game/game-engine.ts) from the
   * player's Settings selection at that moment. Deliberately part of
   * `RoundData` (not re-read from Settings on every render) so that
   * changing the Settings language mid-round -- or refreshing the page
   * during Secret Reveal/Voting/Results -- never changes an
   * already-started round's language out from under the players.
   */
  language: GameLanguage;
};

export type RoundStatus = "preparing" | "ready" | "playing" | "finished";

/**
 * The fully-prepared round, ready to hand off to Screen 5. Distinct from
 * `GameSession` (game/game-types.ts's Setup -> Players handoff) -- this
 * is what exists once word/hint/roles have actually been resolved.
 */
export type RoundSession = {
  id: string;
  config: GameConfig;
  players: Player[];
  round: RoundData;
  status: RoundStatus;
  currentPlayerIndex: number;
  /**
   * Screen 7's (Voting) persisted ballot box -- keyed by voter player ID,
   * valued by the player ID they voted for. Lives on `RoundSession` (not
   * `RoundData`) for the same reason `currentPlayerIndex` does: it's
   * mutable turn-taking state for one phase of the round, not part of
   * the round's static generated content. There is deliberately no
   * separate "current voter index" field -- game/vote-flow.ts derives
   * whose turn it is directly from this map plus `players` order, so a
   * refresh mid-voting can never desync from who has actually voted
   * (see spec sections 58-64).
   */
  votes?: Record<string, string>;
  /**
   * Screen 8's (Results) persisted outcome of every vote applied so far
   * this game -- player IDs who have been voted out. Optional/defensive
   * for the same reason `votes` is: sessions created before this field
   * existed won't have it. Lives here (not derived fresh from `votes`
   * on every render) because a tie eliminates no one, so "who's out"
   * is NOT simply "who got the most votes" -- it's the accumulated
   * result of every verdict, and must survive a refresh on the Results
   * screen itself (spec's "DATA / STATE REQUIREMENTS").
   */
  eliminatedPlayerIds?: string[];
  /**
   * Every completed voting round's snapshot, oldest first -- captured by
   * game/results-flow.ts's `recordVotingHistoryEntry` at the same moment
   * a round's verdict is resolved on Screen 8, which is the last point
   * `votes` still holds that round's ballots before `continueRound`
   * resets it for the next round (see results-flow.ts). Optional/
   * defensive for the same reason `votes`/`eliminatedPlayerIds` are:
   * sessions persisted before this field existed won't have it.
   *
   * Deliberately a plain, storage-shaped snapshot (player id/name/vote
   * count pairs, not the full `Player` object) rather than reusing
   * results-flow.ts's `VoteTally`/`Verdict` types -- those live in a
   * module that already imports `RoundSession` from here, so importing
   * them back into this file would be circular. This is purely
   * additive read-only data for the Final Results screen's "Voting
   * History" option -- nothing in the live game (voting, elimination,
   * win checks) ever reads it back.
   */
  votingHistory?: VotingHistoryEntry[];
};
