// lib/fallback-words/everyday-things/english/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "everyday-things" category -- English.
 *
 * All 100 words are common, universally recognizable everyday objects. Difficulty
 * controls ONLY how directly the hint points at the word:
 *   - easy (40):   states the most obvious function, location, or appearance.
 *   - medium (30): points to secondary details, associated actions, or context.
 *   - hard (30):   oblique angles, specific components, or indirect consequences.
 */
export const EVERYDAY_THINGS_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-everyday-en-1",
    word: "Pen",
    hint: "An everyday writing tool filled with dark ink used for signing documents.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-2",
    word: "Key",
    hint: "A small carved metal object inserted into a lock to open a closed door.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-3",
    word: "Door",
    hint: "The large hinged wooden panel you open to enter a closed room.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-4",
    word: "Chair",
    hint: "A common piece of furniture with four legs and a backrest, designed for one person to sit on.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-5",
    word: "Bed",
    hint: "The large, soft piece of bedroom furniture where you sleep every single night.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-6",
    word: "Soap",
    hint: "A slippery, scented block you rub between your hands under water to get clean.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-7",
    word: "Toothbrush",
    hint: "A small, long-handled brush you use twice daily to keep your teeth completely clean.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-8",
    word: "Spoon",
    hint: "A curved piece of silverware shaped like a shallow bowl, used primarily for eating hot soup.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-9",
    word: "Fork",
    hint: "A common piece of dining silverware featuring several long metal prongs used for stabbing pieces of food.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-10",
    word: "Plate",
    hint: "A completely flat, circular ceramic dish that you serve your dinner on.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-11",
    word: "Cup",
    hint: "A small, deep drinking vessel, usually with a handle on the side, used for drinking hot coffee or tea.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-12",
    word: "Bottle",
    hint: "A tall glass or plastic container with a narrow neck, usually used to hold water or soda.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-13",
    word: "Mirror",
    hint: "A highly reflective glass surface hung on the wall that shows you exactly what you look like.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-14",
    word: "Comb",
    hint: "A flat piece of plastic with a row of narrow teeth, used to quickly part and style your hair.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-15",
    word: "Towel",
    hint: "A large, highly absorbent rectangular piece of thick fabric you use to dry off right after taking a shower.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-16",
    word: "Pillow",
    hint: "The soft, rectangular stuffed cushion you rest your head on when you lay down to sleep.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-17",
    word: "Blanket",
    hint: "A large, warm piece of thick fabric you pull completely over your body in bed during cold winter nights.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-18",
    word: "Window",
    hint: "A transparent square of glass built directly into the wall that lets natural sunlight enter the room.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-19",
    word: "Table",
    hint: "A completely flat wooden surface supported by four legs where families gather to sit down and eat dinner.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-20",
    word: "Phone",
    hint: "The handheld smart device you carry in your pocket all day to make calls and send text messages.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-21",
    word: "Clock",
    hint: "A round device hung high on the living room wall featuring numbers and moving hands to tell the time.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-22",
    word: "Watch",
    hint: "A small, strap-on timekeeping device securely worn directly on your left or right wrist.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-23",
    word: "Shoe",
    hint: "A protective outer covering worn tightly on your foot before stepping outside the house.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-24",
    word: "Sock",
    hint: "A soft, stretchy cotton garment slipped onto the foot right before putting on your sneakers.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-25",
    word: "Shirt",
    hint: "A common piece of clothing featuring a collar and buttons that covers the entire upper half of your body.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-26",
    word: "Pants",
    hint: "A piece of clothing covering the lower half of your body, featuring two separate legs.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-27",
    word: "Wallet",
    hint: "A small, folding leather pocketbook universally used for securely carrying cash and credit cards.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-28",
    word: "Bag",
    hint: "A flexible container with a handle or shoulder strap, used for carrying your personal belongings around.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-29",
    word: "Book",
    hint: "A thick stack of printed paper pages bound together inside a hard cover, meant for reading.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-30",
    word: "Pencil",
    hint: "A yellow wooden writing tool containing a grey lead core that can be easily erased.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-31",
    word: "Scissors",
    hint: "A cutting tool consisting of two sharp metal blades attached at the center, used to cut paper.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-32",
    word: "Knife",
    hint: "A single sharp metal blade attached to a handle, used specifically in the kitchen for chopping food.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-33",
    word: "Umbrella",
    hint: "A collapsible, dome-shaped waterproof canopy held over the head to stay dry during a heavy rainstorm.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-34",
    word: "Broom",
    hint: "A long-handled sweeping tool featuring a wide brush at the bottom, used to clean dusty floors.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-35",
    word: "Mop",
    hint: "A long stick with an incredibly wet, soapy sponge at the bottom, used to scrub hard floors clean.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-36",
    word: "Shampoo",
    hint: "A thick, liquid soap strictly formulated to lather into your hair while showering.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-37",
    word: "Trash can",
    hint: "The designated plastic bin in the corner of the room where you throw away all your garbage.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-38",
    word: "Lamp",
    hint: "A small, decorative tabletop light source topped with a wide fabric shade.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-39",
    word: "Remote",
    hint: "The handheld plastic device covered in buttons used to switch channels on your television from the couch.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-en-40",
    word: "Television",
    hint: "The large, flat electronic screen sitting in the living room that broadcasts movies and news programs.",
    category: "everyday-things",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (30)
  {
    id: "fallback-everyday-en-41",
    word: "Glass",
    hint: "A transparent, cylindrical vessel you pour cold drinking water into before a meal.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-42",
    word: "Bowl",
    hint: "A deep, round ceramic dish heavily relied upon when eating a liquid breakfast like cereal and milk.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-43",
    word: "Napkin",
    hint: "A small square of cloth or paper kept right next to your dinner plate to dab your messy mouth.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-44",
    word: "Toilet paper",
    hint: "A soft, white roll of easily flushable tissue found exclusively hanging on a dispenser in the restroom.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-45",
    word: "Iron",
    hint: "A heavy, heated metal appliance pressed forcefully over your formal shirts to eliminate wrinkles.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-46",
    word: "Vacuum",
    hint: "A noisy, motorized household machine that forcefully sucks dust and dirt directly out of the carpet.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-47",
    word: "Oven",
    hint: "The large, enclosed lower half of your kitchen stove used entirely for baking cakes or roasting meats.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-48",
    word: "Microwave",
    hint: "A rectangular kitchen appliance that rapidly reheats yesterday's cold leftovers in just a few seconds.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-49",
    word: "Refrigerator",
    hint: "The largest appliance in the kitchen, kept running constantly to keep milk and vegetables cold so they don't spoil.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-50",
    word: "Toaster",
    hint: "The small countertop appliance that violently pops up your sliced bread once it gets hot and crispy.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-51",
    word: "Blender",
    hint: "A tall glass pitcher with sharp, spinning metal blades at the bottom used to completely liquefy fruit for smoothies.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-52",
    word: "Sofa",
    hint: "The largest, most comfortable piece of padded furniture sitting directly in front of the living room television.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-53",
    word: "Rug",
    hint: "A thick, woven floor covering laid down in the center of the living room to make the hard floor much softer.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-54",
    word: "Curtains",
    hint: "Long strips of decorative fabric drawn firmly together at night to block the neighbors from seeing inside.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-55",
    word: "Fan",
    hint: "An electric machine featuring rapidly rotating plastic blades that successfully circulates a cooling breeze around a stuffy room.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-56",
    word: "Heater",
    hint: "A portable electronic device plugged in specifically to blow intensely warm air into a freezing cold room.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-57",
    word: "Laptop",
    hint: "A portable, folding personal computer you can easily balance on your knees while working from the couch.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-58",
    word: "Charger",
    hint: "The crucial white cable and plug block you desperately search for when your phone battery hits one percent.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-59",
    word: "Headphones",
    hint: "A pair of small audio speakers worn over the ears to listen to music privately without bothering others.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-60",
    word: "Spectacles",
    hint: "A pair of corrective glass lenses sitting comfortably on the bridge of your nose to cure blurry vision.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-61",
    word: "Sunglasses",
    hint: "Darkly tinted eyewear specifically put on before driving to prevent the bright afternoon glare from blinding you.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-62",
    word: "Hat",
    hint: "An accessory featuring a brim worn directly on top of the head to shield your face from intense sunlight.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-63",
    word: "Belt",
    hint: "A long strip of dark leather firmly buckled tightly around your waist to stop your trousers from sliding down.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-64",
    word: "Jacket",
    hint: "A heavy, zippered outer garment quickly thrown over your shoulders right before walking out into the freezing cold.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-65",
    word: "Gloves",
    hint: "Matching knitted accessories slipped over your hands in the winter to prevent your fingers from going completely numb.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-66",
    word: "Scarf",
    hint: "A long, woolen accessory tightly wrapped several times around your bare neck to protect it from the bitter wind.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-67",
    word: "Ring",
    hint: "A tiny, circular band of precious metal traditionally slipped onto a specific finger during a wedding ceremony.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-68",
    word: "Necklace",
    hint: "A delicate gold or silver chain, often featuring a dangling pendant, worn loosely around the throat for decoration.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-69",
    word: "Earring",
    hint: "A piece of sparkling jewelry pushed directly through a tiny pierced hole in the side of your head.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-en-70",
    word: "Bracelet",
    hint: "An ornamental metal band or chain clasped directly around the wrist alongside your favorite timepiece.",
    category: "everyday-things",
    difficulty: "medium",
    language: "english",
  },

  // HARD (30)
  {
    id: "fallback-everyday-en-71",
    word: "Toothpaste",
    hint: "You squeeze a tiny amount of this minty paste onto bristles twice a day to maintain your oral hygiene.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-72",
    word: "Dental floss",
    hint: "A thin, waxed string designed specifically to remove stubborn food stuck in extremely tight spaces between your molars.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-73",
    word: "Nail clipper",
    hint: "A small metal lever-action tool utilized purely to trim the hard keratin rapidly growing from your fingertips.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-74",
    word: "Tweezers",
    hint: "A tiny pincer tool commonly employed to painfully pluck out a single, incredibly stubborn stray eyebrow hair.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-75",
    word: "Razor",
    hint: "A sharp, hand-held grooming tool used with thick lather to carefully scrape away unwanted facial or body stubble.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-76",
    word: "Deodorant",
    hint: "An everyday cosmetic stick applied strictly to the underarms directly after showering to prevent highly unpleasant body odor.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-77",
    word: "Perfume",
    hint: "An expensive, highly scented liquid lightly sprayed on the wrists or neck to make someone smell incredibly elegant.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-78",
    word: "Lotion",
    hint: "A thick, creamy liquid rubbed directly onto severely dry, ashy skin to provide immediate moisturizing relief.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-79",
    word: "Hairbrush",
    hint: "A wooden tool covered in stiff bristles, repeatedly pulled forcefully through your scalp to remove messy morning tangles.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-80",
    word: "Hair tie",
    hint: "A tiny elastic band utilized to firmly pull long locks completely out of your face and into a tight ponytail.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-81",
    word: "Tissue",
    hint: "A soft, disposable square of incredibly thin paper you quickly grab from a cardboard box when you feel a sudden sneeze coming on.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-82",
    word: "Matchbox",
    hint: "A small cardboard container holding tiny wooden sticks that easily ignite when struck aggressively against the rough side.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-83",
    word: "Lighter",
    hint: "A small plastic device featuring a metal wheel you repeatedly flick with your thumb to instantly create a small flame.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-84",
    word: "Candle",
    hint: "A molded stick of scented wax containing a central wick that provides incredibly dim, romantic lighting when burned.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-85",
    word: "Flashlight",
    hint: "A handheld, battery-powered tubular device you desperately grab from the kitchen drawer whenever the house suddenly loses electricity.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-86",
    word: "Battery",
    hint: "A small, heavy cylindrical object that provides necessary portable power to your various household electronic remotes and toys.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-87",
    word: "Extension cord",
    hint: "A long, flexible electrical cable heavily utilized when the wall socket is just way too far away to reach.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-88",
    word: "Plunger",
    hint: "A rubber suction cup securely attached to a wooden stick, permanently kept behind the toilet for terrible unclogging emergencies.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-89",
    word: "Hanger",
    hint: "A triangular plastic or wire tool completely used to vertically suspend your nice dress shirts safely inside the closet.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-90",
    word: "Ironing board",
    hint: "A incredibly long, padded, foldable table specifically designed for pressing the stubborn wrinkles entirely out of clean laundry.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-91",
    word: "Laundry basket",
    hint: "The designated large plastic container in the corner of the bedroom where you aimlessly toss all your dirty, worn-out clothes.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-92",
    word: "Clothespin",
    hint: "A small, spring-loaded wooden clip heavily used to firmly secure wet, freshly washed garments directly to an outdoor drying line.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-93",
    word: "Tape",
    hint: "A sticky, transparent roll of thin film used to quickly mend ripped paper documents or beautifully wrap a birthday gift.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-94",
    word: "Glue",
    hint: "A thick, sticky white liquid squeezed directly from a plastic bottle to permanently bind two completely separate crafts together.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-95",
    word: "Stapler",
    hint: "A heavy, metal office device you forcefully press down on to permanently bind multiple thick sheets of paper using wire.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-96",
    word: "Paperclip",
    hint: "A simple, bent piece of steel wire easily slipped over a small stack of important documents to hold them temporarily.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-97",
    word: "Envelope",
    hint: "A folded paper container featuring a lickable sealable flap, used entirely for keeping an outgoing letter completely private.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-98",
    word: "Stamp",
    hint: "A tiny, expensive adhesive square specifically purchased from the post office to legally mail a physical letter.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-99",
    word: "Calendar",
    hint: "A printed grid chart prominently hung on the wall to help you successfully keep track of upcoming months and daily appointments.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-en-100",
    word: "Calculator",
    hint: "A small electronic keypad device rapidly used to instantly solve complex math problems without forcing you to do mental arithmetic.",
    category: "everyday-things",
    difficulty: "hard",
    language: "english",
  },
];
