// lib/fallback-words/everyday-things/urdu/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "everyday-things" category -- Roman Urdu.
 *
 * 100 well-known everyday objects instantly recognizable in a Pakistani
 * household (e.g., Lota, Balti, Charpai, Jharoo). Difficulty only changes
 * the hint's directness. Hints are written in natural conversational
 * Roman Urdu using ONLY Latin letters.
 */
export const EVERYDAY_THINGS_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-everyday-ur-1",
    word: "Sabun",
    hint: "Nahanay aur hath dhone ke liye istemal hone wali jhaag dar cheez.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-2",
    word: "Toliya",
    hint: "Gusl ke baad geele jism aur balon ko khushk karne wala mota kapra.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-3",
    word: "Kangi",
    hint: "Uljhe hue balon ko theek karne aur sanwarne ke liye istemal hone wali cheez.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-4",
    word: "Sheesha",
    hint: "Deewar par laga hua aaina jis mein insan apni shakal dekhta hai.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-5",
    word: "Joota",
    hint: "Ghar se bahr nikalte waqt pairo mein pehne jane wali chamre ya kapre ki cheez.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-6",
    word: "Chappal",
    hint: "Ghar ke andar ya aam tor par pairo mein pehni jane wali khuli jooti.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-7",
    word: "Moza",
    hint: "Sardiyo mein ya jogger pehnne se pehle pairo par charhaya jane wala kapra.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-8",
    word: "Bistar",
    hint: "Raat ko aaram aur neend poori karne ke liye kamre mein mojood jagah.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-9",
    word: "Takiya",
    hint: "Sote waqt sar ke neechay rakha jane wala naram aur gudedar gadila.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-10",
    word: "Kambal",
    hint: "Sardiyo ki thand se bachne ke liye raat ko orha jane wala mota kapra.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-11",
    word: "Darwaza",
    hint: "Kamre ya ghar ke andar dakhil hone ke liye kholi jane wali lakri ki patti.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-12",
    word: "Khirki",
    hint: "Kamre mein tazi hawa aur dhoop aane ke liye deewar mein chora gaya rasta.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-13",
    word: "Kursi",
    hint: "Mez ke sath rakhi gayi char tangon wali jagah jis par akele baitha jata hai.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-14",
    word: "Mez",
    hint: "Char tangon wala lamba ya gol takhta jis par khana ya kitabein rakhi jati hain.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-15",
    word: "Pankha",
    hint: "Garmi mein hawa dene ke liye chat par latakne wali ghoomti hui machine.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-16",
    word: "Ghari",
    hint: "Waqt dekhne ke liye kalai par bandhi jane wali ya deewar par lagi cheez.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-17",
    word: "Chammach",
    hint: "Chawal ya soup khane ke liye istemal hone wala steel ka gol bartan.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-18",
    word: "Kanta",
    hint: "Chowmein ya boti uthane ke liye istemal hone wala nook-dar steel ka bartan.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-19",
    word: "Churri",
    hint: "Bawarchi khane mein phal aur sabziyan katne ke liye istemal hone wala teez aala.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-20",
    word: "Gilaas",
    hint: "Thanda pani ya sharbat peene ke liye shishey ya steel ka lamba bartan.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-21",
    word: "Botal",
    hint: "Pani ko fridge mein thanda karne ke liye istemal hone wala dakkhan dar bartan.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-22",
    word: "Jug",
    hint: "Mehmaan aane par sab ke liye ikatha pani ya sharbat dalne wala bara bartan.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-23",
    word: "Pyali",
    hint: "Garam chaye ya coffee peene ke liye istemal hone wala chota kundi dar bartan.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-24",
    word: "Thali",
    hint: "Chawal aur salan nikal kar khane ke liye bilkul chapti aur gol plate.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-25",
    word: "Tawa",
    hint: "Chulhe par gol aur garam roti pakanay ke liye istemal hone wala chapta loha.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-26",
    word: "Belan",
    hint: "Atey ki pairi ko gol aur patli roti mein badalne ke liye lakri ka danda.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-27",
    word: "Chimta",
    hint: "Garam taway se paki hui roti ko ulatne aur pakarne wala lohe ka auzar.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-28",
    word: "Jharoo",
    hint: "Farsh aur qaleen se mitti aur kachra saaf karne ke liye istemal hone wali seenkhon ki gucchi.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-29",
    word: "Balti",
    hint: "Nahanay ke liye ya farsh dhone ke liye pani se bhari jane wali plastic ki container.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-30",
    word: "Lota",
    hint: "Bathroom mein wazu karne ya safai ke liye pani dalne wala choti tonti wala bartan.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-31",
    word: "Istri",
    hint: "Dhule hue kapron se silwatein nikalne ke liye un par pheri jane wali garam machine.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-32",
    word: "Kapre",
    hint: "Jism ko dhampne aur hifazat ke liye pehne jane wale silay hue libas.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-33",
    word: "Qalam",
    hint: "Kaghaz par siyahi se likhne ke liye istemal hone wala rozmarra ka auzar.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-34",
    word: "Kitaab",
    hint: "Nisab parhne ya ilm hasil karne ke liye safhon se bandhi hui cheez.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-35",
    word: "Tala",
    hint: "Ghar ko chori se bachane ke liye main gate par lagaya jane wala bhari loha.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-36",
    word: "Chabi",
    hint: "Band darwaze ya tale ko kholne ke liye istemal hone wala chota sa lohe ka tukra.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-37",
    word: "Chata",
    hint: "Tez barish ya dhoop se bachne ke liye sar par khola jane wala kapre ka gumbad.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-38",
    word: "Dhaaga",
    hint: "Phate hue kapron ko dobara jorne ya silai karne ke liye istemal hone wali patli doori.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-39",
    word: "Sui",
    hint: "Kapray seene ke liye dhagay ko is chote aur barik lohe ki nukili cheez mein dala jata hai.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-40",
    word: "Qainchi",
    hint: "Kapre ya kaghaz ko asani se katne ke liye do dhar wali lohe ki cheez.",
    category: "everyday-things",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (30)
  {
    id: "fallback-everyday-ur-41",
    word: "Poncha",
    hint: "Farsh ke daagh dhabe saaf karne ke liye geele kapre ya sponge ko ragarna.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-42",
    word: "Dastarkhwan",
    hint: "Zameen par bichaya jane wala wo lamba kapra jis par khane ke bartan rakhe jate hain.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-43",
    word: "Tasbeeh",
    hint: "Namaz ke baad wazeefa aur zikr parhne ke liye dagon mein piroye hue dane.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-44",
    word: "Jai Namaz",
    hint: "Pak aur saaf ho kar ibadat karne ke liye zameen par bichayi jane wali khubsurat chadar.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-45",
    word: "Topi",
    hint: "Masjid mein jate waqt ahtaram ke tor par mardon ke sar par pehne jane wali cheez.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-46",
    word: "Shalwar",
    hint: "Pakistan ki qomi poshak ka nichla hissa jis mein nala dala jata hai.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-47",
    word: "Kameez",
    hint: "Jism ke upari hisse ko dhampne wala libas jis mein collar aur batan hote hain.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-48",
    word: "Dupatta",
    hint: "Aurat ke libas ka eham hissa jo sar ya kandhon ko dhampne ke liye istemal hota hai.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-49",
    word: "Bulb",
    hint: "Kamre mein andhera door karne ke liye chhat se latkai jane wali roshan sheeshe ki cheez.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-50",
    word: "Switch",
    hint: "Pankhe ya roshni ko on aur off karne ke liye deewar par daba jane wala plastic ka batan.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-51",
    word: "Toti",
    hint: "Washbasin mein hath dhone ke liye jise ghumane se taaza pani aata hai.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-52",
    word: "Pipe",
    hint: "Pani ko aik jagah se dosri jagah le jane wala lamba aur lachakdar rubber ka rasta.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-53",
    word: "Matka",
    hint: "Garmiyon mein baghair fridge ke pani ko intehai thanda rakhne wala kumhaar ka bana mitti ka bartan.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-54",
    word: "Palang",
    hint: "Kamre mein sone ke liye rakha gaya lakri ya lohe ka bara frame jis par matress bichaya jata hai.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-55",
    word: "Gadda",
    hint: "Bistar ko naram karne ke liye charpai ya palang par bichaya jane wala mota rui dar chakor.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-56",
    word: "Rajai",
    hint: "Shadeed sardi mein bachanay ke liye istamal hone wala bhari aur rui se bhara hua naram lihhaf.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-57",
    word: "Rassi",
    hint: "Bhari saman bandhne ya geele kapre latkane ke liye chat par bandhi hui buni hui door.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-58",
    word: "Thela",
    hint: "Bazar se rashan ya sabziyan khareed kar ghar lane ke liye kapre ya plastic ka banna bag.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-59",
    word: "Chashma",
    hint: "Kamzor nazar ko theek karne ya dhoop se ankhon ko bachanay wali ainak.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-60",
    word: "Rumaal",
    hint: "Pasina saaf karne ya cheenk aate waqt mu par rakhne ke liye chota sutti kapra.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-61",
    word: "Degchi",
    hint: "Chulhe par salan pakane ya chawal ubalne ke liye dhakkan wala bara steel ka bartan.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-62",
    word: "Channi",
    hint: "Garam chaye ko pyali mein dalne se pehle patti ko alag karne wali bari jaali.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-63",
    word: "Katora",
    hint: "Shorba ya salan dalne ke liye gilaas se chota aur pyali se bara gol bartan.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-64",
    word: "Dhakkan",
    hint: "Khorak ko makhiyon se mehfooz rakhne ke liye bartan ke upar rakhi jane wali gol cheez.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-65",
    word: "Dabba",
    hint: "Rashan, chini ya chai ki patti ko mehfooz rakhne ke liye plastic ya lohe ka container.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-66",
    word: "Machis",
    hint: "Bawarchi khane mein gas ka chulha jalanay ke liye teeli se bhari hui choti si dabiya.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-67",
    word: "Mombatti",
    hint: "Light chale jane par roshni ke liye jalai jane wali wax se bani hui lumbi silai.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-68",
    word: "Bori",
    hint: "Aata ya chawal rakhne ke liye istemal hone wala bara aur sakht patsan ka thaila.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-69",
    word: "Feeta",
    hint: "Joggers ko paon par tight karne ke liye bandha jane wala lamba dhaga.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-70",
    word: "Kooda Daan",
    hint: "Ghar ka tamam fuzla aur kachra phenkne ke liye rkhi gayi makhsoos plastic ki balti.",
    category: "everyday-things",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (30)
  {
    id: "fallback-everyday-ur-71",
    word: "Chimti",
    hint: "Gili qameez ko taar par latkane ke baad hawa se uurne se rokne wali cheez.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-72",
    word: "Hanger",
    hint: "Almaari mein iron kiye hue kapron ko silwat se bachanay ke liye latkane wala frame.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-73",
    word: "Zanjeer",
    hint: "Lohe ki kadiyoun se bani mazboot dori jo aam tor par bhari tala lagane ke kaam aati hai.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-74",
    word: "Hathora",
    hint: "Deewar mein keel thokne ya kisi sakht lohe ki cheez ko torne wala bhari auzar.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-75",
    word: "Keel",
    hint: "Lohe ka wo chota sa nukila tukra jisay deewar mein thonk kar tasveer latkai jati hai.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-76",
    word: "Pechkass",
    hint: "Screw ko gol ghuma kar theek se kasanay ya kholne ke liye lamba nokdar auzar.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-77",
    word: "Plass",
    hint: "Bijli ki taar ko asani se kaatne ya kisi sakht cheez ko mazbooti se pakarne wala auzar.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-78",
    word: "Tape",
    hint: "Phatti hui kitab ka safha jorne ya kisi gift box ko pack karne wali chipku patti.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-79",
    word: "Gond",
    hint: "Kaghaz ke do tukron ko hamesha ke liye sakhti se aapas mein chipkane wala lais-dar mawad.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-80",
    word: "Rubber",
    hint: "Pencil se likhi hui ghalti ko kaghaz se jaldi se mitane ke liye naram cheez.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-81",
    word: "Phutta",
    hint: "Kaghaz par bilkul seedhi line lagane ya lambai napne ke liye lakri ya plastic ka paimana.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-82",
    word: "Gamla",
    hint: "Mitti aur khaad se bhara hua wo bartan jis mein ghar ki sajawat ke phool ugaye jate hain.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-83",
    word: "Chatai",
    hint: "Zameen par bicha kar baithne wali khajoor ke patton ya patli plastic se bani chadar.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-84",
    word: "Charpai",
    hint: "Sone ke liye lakri aur baan se buna hua aam sa desi bistar jo sehat ke liye behtar hai.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-85",
    word: "Moora",
    hint: "Baan ya sirkande se bani hui gol aur choti si kursi jis par baghair taik ke baithte hain.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-86",
    word: "Surma",
    hint: "Ankhon ki thandak aur khubsurati ke liye salai se lagaya jane wala kaale rang ka bareek powder.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-87",
    word: "Lifafa",
    hint: "Khat bhejte waqt ya shadi mein doston ko salami dene ke liye kaghaz ka band cover.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-88",
    word: "Pin",
    hint: "Kapre ka koi hissa udhar jaye to isay earzi tor par bandhne wali barik aur tez sui.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-89",
    word: "Wiper",
    hint: "Farsh dhone ke baad wahan jama hone wale pani ko tezi se baha kar bahar nikalne wala danda.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-90",
    word: "Kundi",
    hint: "Raat ko sote waqt darwaze ko andar se theek tarah band aur lock karne wali lohe ki patti.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-91",
    word: "Tijori",
    hint: "Ghar mein qeemti sonay ke zewarat aur nakad paise ko mehfooz rakhne wala bhari lohe ka dabba.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-92",
    word: "Parda",
    hint: "Taiz dhoop ko andar aane se rokne ya parde ke liye khirki par latkaya jane wala lamba kapra.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-93",
    word: "Chulha",
    hint: "Bawarchi khane mein aag jalanay wali wo makhsoos jagah jis ke upar bartan rakh kar salan pakaya jata hai.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-94",
    word: "Silbatta",
    hint: "Masala peesne ke liye bawarchi khane mein istemal hone wala qadeem zamane ka chora aur bhari pathar.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-95",
    word: "Chakla",
    hint: "Gondi hui atey ki pairi ko golai mein bilkul saaf belne ke liye lakri ya pathar ka takhta.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-96",
    word: "Batan",
    hint: "Qameez ko samne ya gale se band karne ke liye dhage se tanka gaya chota sa gol plastic.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-97",
    word: "Chhalla",
    hint: "Bohat sari chabiyon ko ek hi jagah gum hone se mehfooz rakhne wala lohe ka chota sa ring.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-98",
    word: "Danda",
    hint: "Chori ke darr se awara kutton ko bhagane ya hifazat ke liye rakhi gayi lumbi aur sakht lakri.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-99",
    word: "Tokri",
    hint: "Bazar se taaza sabzi ya gila phal khareed kar ghar lane ke liye istemal hone wali buni dabba.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-100",
    word: "Bartan",
    hint: "Khana khane, serving aur pakane ke liye bawarchi khane mein mojood tamam cheezon ka poora majmua.",
    category: "everyday-things",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
