import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "animals" category (see
 * ./index.ts for the combined TIER 3 pipeline this feeds into).
 *
 * English and Roman Urdu use the EXACT SAME animal word.
 * Only the hint is localized.
 *
 * This keeps English/Roman Urdu parity so Roman Urdu never silently
 * falls back to English.
 *
 * 50 unique animal concepts:
 * - 20 easy
 * - 15 medium
 * - 15 hard
 *
 * Total: 100 entries
 * - 50 English
 * - 50 Roman Urdu
 */
export const ANIMALS_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------
  {
    id: "fallback-animals-1",
    word: "Dog",
    hint: "A common pet known for being loyal to people.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-2",
    word: "Cat",
    hint: "A popular pet that likes to climb and sleep.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-3",
    word: "Cow",
    hint: "A farm animal that gives milk.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-4",
    word: "Goat",
    hint: "A farm animal that likes to eat grass and leaves.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-5",
    word: "Horse",
    hint: "An animal that people can ride.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-6",
    word: "Sheep",
    hint: "A farm animal covered in wool.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-7",
    word: "Chicken",
    hint: "A common farm bird that lays eggs.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-8",
    word: "Duck",
    hint: "A bird that can swim and is often found near water.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-9",
    word: "Rabbit",
    hint: "A small animal with long ears that can hop.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-10",
    word: "Monkey",
    hint: "An intelligent animal that is good at climbing trees.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-11",
    word: "Lion",
    hint: "A large wild cat often called the king of the jungle.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-12",
    word: "Tiger",
    hint: "A large wild cat with orange fur and black stripes.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-13",
    word: "Elephant",
    hint: "A huge animal with large ears and a long trunk.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-14",
    word: "Bear",
    hint: "A large furry animal that lives in many forests.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-15",
    word: "Fox",
    hint: "A wild animal known for its bushy tail.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-16",
    word: "Wolf",
    hint: "A wild animal that often hunts in a pack.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-17",
    word: "Deer",
    hint: "A fast animal commonly found in forests.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-18",
    word: "Camel",
    hint: "A desert animal known for carrying people and goods.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-19",
    word: "Zebra",
    hint: "A horse-like animal famous for its black and white stripes.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-20",
    word: "Giraffe",
    hint: "A very tall animal with a long neck.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },

  {
    id: "fallback-animals-21",
    word: "Dolphin",
    hint: "A smart sea animal known for jumping out of the water.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-22",
    word: "Whale",
    hint: "A huge animal that lives in the ocean.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-23",
    word: "Shark",
    hint: "A large sea animal with sharp teeth.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-24",
    word: "Crocodile",
    hint: "A large reptile with a long body and powerful jaws.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-25",
    word: "Snake",
    hint: "A long animal with no legs that moves by sliding.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-26",
    word: "Turtle",
    hint: "An animal protected by a hard shell.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-27",
    word: "Frog",
    hint: "A small animal that can jump and often lives near water.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-28",
    word: "Eagle",
    hint: "A large bird known for powerful wings and sharp eyesight.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-29",
    word: "Parrot",
    hint: "A colorful bird that can sometimes copy human speech.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-30",
    word: "Peacock",
    hint: "A colorful bird famous for its beautiful tail feathers.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-31",
    word: "Owl",
    hint: "A bird that is usually active at night.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-32",
    word: "Penguin",
    hint: "A bird that cannot fly but is an excellent swimmer.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-33",
    word: "Gorilla",
    hint: "A large and powerful ape that lives in forests.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-34",
    word: "Leopard",
    hint: "A fast wild cat with a spotted coat.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-35",
    word: "Cheetah",
    hint: "The fastest land animal in the world.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },

  {
    id: "fallback-animals-36",
    word: "Kangaroo",
    hint: "An Australian animal that moves by jumping and carries babies in a pouch.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-37",
    word: "Koala",
    hint: "An Australian animal that spends much of its time in trees.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-38",
    word: "Panda",
    hint: "A black and white animal famous for eating bamboo.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-39",
    word: "Jaguar",
    hint: "A powerful spotted wild cat found mainly in the Americas.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-40",
    word: "Hyena",
    hint: "A wild animal known for its unusual laugh-like call.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-41",
    word: "Flamingo",
    hint: "A tall pink bird that often stands on one leg.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-42",
    word: "Squirrel",
    hint: "A small animal with a bushy tail that climbs trees.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-43",
    word: "Butterfly",
    hint: "A flying insect with colorful wings.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-44",
    word: "Spider",
    hint: "An eight-legged creature that can make webs.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-45",
    word: "Scorpion",
    hint: "A creature with claws and a tail with a stinger.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-46",
    word: "Octopus",
    hint: "A sea animal with eight arms.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-47",
    word: "Buffalo",
    hint: "A large farm animal that is common in many parts of Asia.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-48",
    word: "Donkey",
    hint: "A strong farm animal often used to carry heavy loads.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-49",
    word: "Fish",
    hint: "An animal that lives in water and uses fins to swim.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-50",
    word: "Mouse",
    hint: "A small animal with a long tail that can live near people.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------
  {
    id: "fallback-animals-ur-1",
    word: "Dog",
    hint: "Ek aam paaltu janwar jo apni wafadari ke liye mashhoor hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-2",
    word: "Cat",
    hint: "Ek mashhoor paaltu janwar jo aksar charhta aur sota rehta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-3",
    word: "Cow",
    hint: "Ek farm ka janwar jo doodh deta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-4",
    word: "Goat",
    hint: "Ek farm ka janwar jo ghaas aur pattay khata hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-5",
    word: "Horse",
    hint: "Aisa janwar jis par log sawari kar sakte hain.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-6",
    word: "Sheep",
    hint: "Ek farm ka janwar jis ke jism par oon hoti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-7",
    word: "Chicken",
    hint: "Ek aam farm ka parinda jo anday deta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-8",
    word: "Duck",
    hint: "Ek parinda jo pani mein tair sakta hai aur aksar pani ke paas milta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-9",
    word: "Rabbit",
    hint: "Ek chhota janwar jis ke kaan lambe hote hain aur jo uchhalta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-10",
    word: "Monkey",
    hint: "Ek hoshiyaar janwar jo darakhton par charhne mein mahir hota hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-11",
    word: "Lion",
    hint: "Ek bara jangli janwar jise aksar jungle ka badshah kaha jata hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-12",
    word: "Tiger",
    hint: "Ek bari jangli billi jis ke jism par kaali dhariyan hoti hain.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-13",
    word: "Elephant",
    hint: "Ek bohat bara janwar jis ke kaan bare aur sund lambi hoti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-14",
    word: "Bear",
    hint: "Ek bara aur roaydar janwar jo kai jangalon mein paya jata hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-15",
    word: "Fox",
    hint: "Ek jangli janwar jis ki dum ghani hoti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-16",
    word: "Wolf",
    hint: "Ek jangli janwar jo aksar jhund mein shikar karta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-17",
    word: "Deer",
    hint: "Ek tez janwar jo aksar jangalon mein paya jata hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-18",
    word: "Camel",
    hint: "Registan ka mashhoor janwar jo logon aur samaan ko utha sakta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-19",
    word: "Zebra",
    hint: "Ghoray jaisa janwar jis ke jism par kaali aur safed dhariyan hoti hain.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-20",
    word: "Giraffe",
    hint: "Ek bohat lamba janwar jis ki gardan bohat lambi hoti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },

  {
    id: "fallback-animals-ur-21",
    word: "Dolphin",
    hint: "Samandar ka samajhdar janwar jo pani se uchhalne ke liye mashhoor hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-22",
    word: "Whale",
    hint: "Samandar mein rehne wala bohat bara janwar.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-23",
    word: "Shark",
    hint: "Samandar ka bara janwar jis ke daant bohat tez hote hain.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-24",
    word: "Crocodile",
    hint: "Ek bara reengne wala janwar jis ke jabre bohat mazboot hote hain.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-25",
    word: "Snake",
    hint: "Ek lamba janwar jis ke pair nahi hote aur jo rengta hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-26",
    word: "Turtle",
    hint: "Ek janwar jis ke jism ko sakht khol mehfooz rakhta hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-27",
    word: "Frog",
    hint: "Ek chhota janwar jo uchhal sakta hai aur pani ke paas rehta hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-28",
    word: "Eagle",
    hint: "Ek bara parinda jis ke par mazboot aur nazar bohat tez hoti hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-29",
    word: "Parrot",
    hint: "Ek rang biranga parinda jo kabhi kabhi insan ki awaaz ki naqal karta hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-30",
    word: "Peacock",
    hint: "Ek rang biranga parinda jo apni khoobsurat dum ke liye mashhoor hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-31",
    word: "Owl",
    hint: "Ek parinda jo aam tor par raat ko zyada active hota hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-32",
    word: "Penguin",
    hint: "Ek parinda jo urr nahi sakta lekin bohat acha tairta hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-33",
    word: "Gorilla",
    hint: "Ek bara aur taqatwar bandar jaisa janwar jo jangal mein rehta hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-34",
    word: "Leopard",
    hint: "Ek tez jangli billi jis ke jism par dhabbay hote hain.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-35",
    word: "Cheetah",
    hint: "Duniya ka sab se tez zameeni janwar.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },

  {
    id: "fallback-animals-ur-36",
    word: "Kangaroo",
    hint: "Australia ka janwar jo uchhal kar chalta hai aur apne bachay ko pouch mein rakhta hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-37",
    word: "Koala",
    hint: "Australia ka chhota janwar jo zyada waqt darakhton par guzarta hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-38",
    word: "Panda",
    hint: "Kaale aur safed rang ka janwar jo bamboo khane ke liye mashhoor hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-39",
    word: "Jaguar",
    hint: "America mein payi jane wali taqatwar dhabbay daar jangli billi.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-40",
    word: "Hyena",
    hint: "Ek jangli janwar jo apni hansne jaisi awaaz ke liye mashhoor hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-41",
    word: "Flamingo",
    hint: "Ek lamba gulabi parinda jo aksar ek taang par khara hota hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-42",
    word: "Squirrel",
    hint: "Ek chhota janwar jis ki dum ghani hoti hai aur jo darakhton par charhta hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-43",
    word: "Butterfly",
    hint: "Ek urta hua keera jis ke par rang birangay hote hain.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-44",
    word: "Spider",
    hint: "Aath tangon wali makhlooq jo jaala bana sakti hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-45",
    word: "Scorpion",
    hint: "Ek makhlooq jis ke panjay aur dunk wala dum hota hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-46",
    word: "Octopus",
    hint: "Samandar mein rehne wala janwar jis ki aath bazu hoti hain.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-47",
    word: "Buffalo",
    hint: "Ek bara farm ka janwar jo Asia ke kai ilaqon mein aam hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-48",
    word: "Donkey",
    hint: "Ek mazboot farm ka janwar jo aksar bhaari samaan uthata hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-49",
    word: "Fish",
    hint: "Ek janwar jo pani mein rehta hai aur fins ki madad se tairta hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-50",
    word: "Mouse",
    hint: "Ek chhota janwar jis ki dum lambi hoti hai aur jo logon ke aas paas bhi reh sakta hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
