import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "countries" category (see
 * ./index.ts for the combined TIER 3 pipeline this feeds into).
 *
 * English and Roman Urdu cover the exact same 20/15/15
 * easy/medium/hard grid.
 *
 * The Roman Urdu `word` deliberately stays EXACTLY the same
 * as the English country name. Only the hint is localized into
 * natural Roman Urdu.
 *
 * Total:
 * - 50 English
 * - 50 Roman Urdu
 * - 100 entries
 * - 50 unique countries
 */
export const COUNTRIES_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-countries-1",
    word: "Pakistan",
    hint: "A South Asian country known for its mountains, rivers, and rich culture.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-2",
    word: "India",
    hint: "A large South Asian country known for its diverse culture and history.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-3",
    word: "China",
    hint: "A large East Asian country known for the Great Wall.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-4",
    word: "Japan",
    hint: "An island country known for sushi, technology, and bullet trains.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-5",
    word: "America",
    hint: "A country known for cities such as New York and Los Angeles.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-6",
    word: "Canada",
    hint: "A large country north of the United States, famous for its cold winters.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-7",
    word: "Australia",
    hint: "A country and continent famous for kangaroos and the Great Barrier Reef.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-8",
    word: "England",
    hint: "A country in the United Kingdom known for London and football.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-9",
    word: "France",
    hint: "A European country famous for Paris and the Eiffel Tower.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-10",
    word: "Germany",
    hint: "A European country known for cars, football, and its history.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-11",
    word: "Italy",
    hint: "A European country famous for pizza, pasta, and Rome.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-12",
    word: "Spain",
    hint: "A European country known for football, beaches, and Madrid.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-13",
    word: "Brazil",
    hint: "The largest country in South America, famous for football and the Amazon.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-14",
    word: "Egypt",
    hint: "A country famous for the pyramids and the Nile River.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-15",
    word: "Turkey",
    hint: "A country located between Europe and Asia, famous for Istanbul.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-16",
    word: "Saudi Arabia",
    hint: "A Middle Eastern country home to the cities of Makkah and Madinah.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-17",
    word: "UAE",
    hint: "A Gulf country known for Dubai and Abu Dhabi.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-18",
    word: "Russia",
    hint: "The world's largest country by land area.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-19",
    word: "Mexico",
    hint: "A North American country famous for tacos and its colorful culture.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-countries-20",
    word: "Afghanistan",
    hint: "A mountainous country located in South-Central Asia.",
    category: "countries",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-countries-21",
    word: "South Korea",
    hint: "An Asian country known for K-pop, technology, and Seoul.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-22",
    word: "Indonesia",
    hint: "A large island country in Southeast Asia.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-23",
    word: "Malaysia",
    hint: "A Southeast Asian country known for Kuala Lumpur and the Petronas Towers.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-24",
    word: "Thailand",
    hint: "A Southeast Asian country famous for beaches, temples, and Bangkok.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-25",
    word: "Singapore",
    hint: "A small island country known for its modern city and cleanliness.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-26",
    word: "Bangladesh",
    hint: "A densely populated South Asian country near India.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-27",
    word: "Iran",
    hint: "A country in the Middle East with a long and ancient history.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-28",
    word: "Iraq",
    hint: "A Middle Eastern country with an ancient history connected to Mesopotamia.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-29",
    word: "Qatar",
    hint: "A small Gulf country known for Doha and hosting the 2022 World Cup.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-30",
    word: "Italy",
    hint: "A European country shaped like a boot and famous for its food and art.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-31",
    word: "Greece",
    hint: "A European country famous for ancient ruins and many islands.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-32",
    word: "Switzerland",
    hint: "A European country famous for mountains, watches, and chocolate.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-33",
    word: "Netherlands",
    hint: "A European country famous for windmills, canals, and tulips.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-34",
    word: "New Zealand",
    hint: "An island country known for beautiful mountains and nature.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-countries-35",
    word: "South Africa",
    hint: "A country at the southern end of the African continent.",
    category: "countries",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-countries-36",
    word: "Portugal",
    hint: "A European country on the Atlantic coast, next to Spain.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-37",
    word: "Argentina",
    hint: "A South American country famous for football, tango, and beef.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-38",
    word: "Colombia",
    hint: "A South American country famous for coffee and colorful cities.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-39",
    word: "Chile",
    hint: "A long, narrow country along the western edge of South America.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-40",
    word: "Peru",
    hint: "A South American country home to the famous Machu Picchu.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-41",
    word: "Morocco",
    hint: "A North African country known for colorful markets and Marrakech.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-42",
    word: "Nigeria",
    hint: "A large West African country with a very large population.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-43",
    word: "Kenya",
    hint: "An East African country famous for safaris and wildlife.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-44",
    word: "Norway",
    hint: "A northern European country famous for fjords and the northern lights.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-45",
    word: "Sweden",
    hint: "A Scandinavian country known for its forests and modern cities.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-46",
    word: "Denmark",
    hint: "A Scandinavian country known for Copenhagen and its islands.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-47",
    word: "Ireland",
    hint: "An island country in Europe known for its green landscapes.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-48",
    word: "Austria",
    hint: "A European country known for the Alps and classical music.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-49",
    word: "Belgium",
    hint: "A European country famous for chocolate, waffles, and Brussels.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-countries-50",
    word: "Iceland",
    hint: "A northern island country known for volcanoes, geysers, and glaciers.",
    category: "countries",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-countries-ur-1",
    word: "Pakistan",
    hint: "South Asia ka mulk jo apne paharon, daryaaon aur rang birangi saqafat ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-2",
    word: "India",
    hint: "South Asia ka bara mulk jo apni mukhtalif saqafat aur tareekh ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-3",
    word: "China",
    hint: "Mashriqi Asia ka bara mulk jo Great Wall ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-4",
    word: "Japan",
    hint: "Ek island mulk jo sushi, technology aur bullet trains ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-5",
    word: "America",
    hint: "Ek mulk jo New York aur Los Angeles jaise shehron ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-6",
    word: "Canada",
    hint: "United States ke shumal mein waqay bara mulk jo apni sardiyon ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-7",
    word: "Australia",
    hint: "Ek mulk aur continent jo kangaroo aur Great Barrier Reef ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-8",
    word: "England",
    hint: "United Kingdom ka ek mulk jo London aur football ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-9",
    word: "France",
    hint: "Europe ka mulk jo Paris aur Eiffel Tower ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-10",
    word: "Germany",
    hint: "Europe ka mulk jo cars, football aur apni tareekh ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-11",
    word: "Italy",
    hint: "Europe ka mulk jo pizza, pasta aur Rome ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-12",
    word: "Spain",
    hint: "Europe ka mulk jo football, beaches aur Madrid ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-13",
    word: "Brazil",
    hint: "South America ka sab se bara mulk jo football aur Amazon ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-14",
    word: "Egypt",
    hint: "Ek mulk jo pyramids aur Nile River ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-15",
    word: "Turkey",
    hint: "Europe aur Asia ke darmiyan waqay mulk jo Istanbul ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-16",
    word: "Saudi Arabia",
    hint: "Middle East ka mulk jahan Makkah aur Madinah waqay hain.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-17",
    word: "UAE",
    hint: "Gulf ka mulk jo Dubai aur Abu Dhabi ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-18",
    word: "Russia",
    hint: "Raqbe ke lihaz se duniya ka sab se bara mulk.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-19",
    word: "Mexico",
    hint: "North America ka mulk jo tacos aur apni rang birangi saqafat ke liye mashhoor hai.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-20",
    word: "Afghanistan",
    hint: "South-Central Asia ka pahari mulk.",
    category: "countries",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-countries-ur-21",
    word: "South Korea",
    hint: "Asia ka mulk jo K-pop, technology aur Seoul ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-22",
    word: "Indonesia",
    hint: "Southeast Asia ka bara island mulk.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-23",
    word: "Malaysia",
    hint: "Southeast Asia ka mulk jo Kuala Lumpur aur Petronas Towers ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-24",
    word: "Thailand",
    hint: "Southeast Asia ka mulk jo beaches, temples aur Bangkok ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-25",
    word: "Singapore",
    hint: "Ek chhota island mulk jo apne modern shehar aur safai ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-26",
    word: "Bangladesh",
    hint: "South Asia ka ghani abadi wala mulk jo India ke qareeb hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-27",
    word: "Iran",
    hint: "Middle East ka mulk jis ki tareekh bohat purani hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-28",
    word: "Iraq",
    hint: "Middle East ka mulk jo purani Mesopotamian tareekh se jura hua hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-29",
    word: "Qatar",
    hint: "Gulf ka chhota mulk jo Doha aur 2022 World Cup ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-30",
    word: "Greece",
    hint: "Europe ka mulk jo purane ruins aur bohat se islands ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-31",
    word: "Switzerland",
    hint: "Europe ka mulk jo paharon, watches aur chocolate ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-32",
    word: "Netherlands",
    hint: "Europe ka mulk jo windmills, canals aur tulips ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-33",
    word: "New Zealand",
    hint: "Ek island mulk jo khoobsurat paharon aur qudrati manazir ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-34",
    word: "South Africa",
    hint: "Africa ke janub mein waqay mulk.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-35",
    word: "Italy",
    hint: "Europe ka mulk jo apni art, food aur boot jaisi shape ke liye mashhoor hai.",
    category: "countries",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-countries-ur-36",
    word: "Portugal",
    hint: "Europe ka Atlantic coast par waqay mulk jo Spain ke saath hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-37",
    word: "Argentina",
    hint: "South America ka mulk jo football, tango aur beef ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-38",
    word: "Colombia",
    hint: "South America ka mulk jo coffee aur rang birange shehron ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-39",
    word: "Chile",
    hint: "South America ke maghribi kinare par waqay lamba aur patla mulk.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-40",
    word: "Peru",
    hint: "South America ka mulk jahan mashhoor Machu Picchu waqay hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-41",
    word: "Morocco",
    hint: "North Africa ka mulk jo rang birangi markets aur Marrakech ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-42",
    word: "Nigeria",
    hint: "West Africa ka bara mulk jis ki abadi bohat zyada hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-43",
    word: "Kenya",
    hint: "East Africa ka mulk jo safaris aur wildlife ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-44",
    word: "Norway",
    hint: "Northern Europe ka mulk jo fjords aur Northern Lights ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-45",
    word: "Sweden",
    hint: "Scandinavia ka mulk jo apne jangalon aur modern shehron ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-46",
    word: "Denmark",
    hint: "Scandinavia ka mulk jo Copenhagen aur apne islands ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-47",
    word: "Ireland",
    hint: "Europe ka island mulk jo apne sabz qudrati manazir ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-48",
    word: "Austria",
    hint: "Europe ka mulk jo Alps aur classical music ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-49",
    word: "Belgium",
    hint: "Europe ka mulk jo chocolate, waffles aur Brussels ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-countries-ur-50",
    word: "Iceland",
    hint: "Northern Europe ka island mulk jo volcanoes, geysers aur glaciers ke liye mashhoor hai.",
    category: "countries",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
