import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "everyday" category.
 *
 * English and Roman Urdu cover the exact same 20/15/15
 * easy/medium/hard grid.
 *
 * The Roman Urdu `word` deliberately stays EXACTLY the same
 * as the English everyday object. Only the hint is localized
 * into natural Roman Urdu.
 *
 * Total:
 * - 50 English
 * - 50 Roman Urdu
 * - 100 entries
 * - 50 unique everyday things
 */
export const EVERYDAY_THINGS_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-everyday-1",
    word: "Chair",
    hint: "You sit on it when you need to rest or work at a table.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-2",
    word: "Table",
    hint: "You put food, books, or other things on top of it.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-3",
    word: "Phone",
    hint: "You use it to call people, send messages, and browse the internet.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-4",
    word: "Cup",
    hint: "You drink tea, coffee, or water from it.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-5",
    word: "Spoon",
    hint: "You use it to scoop up food or stir a drink.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-6",
    word: "Plate",
    hint: "Your food is usually served on it.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-7",
    word: "Bottle",
    hint: "You can fill it with water or another drink and carry it around.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-8",
    word: "Key",
    hint: "You use it to unlock a door or a lock.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-9",
    word: "Book",
    hint: "You open it to read stories, information, or lessons.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-10",
    word: "Pen",
    hint: "You use it to write with ink.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-11",
    word: "Mirror",
    hint: "You look into it when you want to see yourself.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-12",
    word: "Towel",
    hint: "You use it to dry yourself after washing.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-13",
    word: "Pillow",
    hint: "You rest your head on it while sleeping.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-14",
    word: "Blanket",
    hint: "You cover yourself with it to stay warm in bed.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-15",
    word: "Shoes",
    hint: "You wear them on your feet when going outside.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-16",
    word: "Wallet",
    hint: "You usually keep your money and cards inside it.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-17",
    word: "Comb",
    hint: "You run it through your hair to keep it neat.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-18",
    word: "Bucket",
    hint: "You can fill it with water and carry it using its handle.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-19",
    word: "Broom",
    hint: "You use it to sweep dust and dirt from the floor.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-everyday-20",
    word: "Lamp",
    hint: "It gives you light when a room is dark.",
    category: "everyday",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-everyday-21",
    word: "Backpack",
    hint: "You carry books, clothes, or other things in it on your back.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-22",
    word: "Toothbrush",
    hint: "You use it with toothpaste to clean your teeth.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-23",
    word: "Umbrella",
    hint: "You hold it above your head when it rains.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-24",
    word: "Remote Control",
    hint: "You use it from a distance to change or control an electronic device.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-25",
    word: "Refrigerator",
    hint: "It keeps food and drinks cold so they last longer.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-26",
    word: "Kettle",
    hint: "You use it to heat water for tea or other hot drinks.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-27",
    word: "Backpack",
    hint: "Students often carry their books and supplies in it.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-28",
    word: "Hanger",
    hint: "You use it to keep clothes hanging neatly in a wardrobe.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-29",
    word: "Drawer",
    hint: "It slides in and out of a desk or cabinet for storing things.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-30",
    word: "Doormat",
    hint: "You wipe your shoes on it before entering a home.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-31",
    word: "Scissors",
    hint: "You squeeze its handles together to cut paper, cloth, or other materials.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-32",
    word: "Notebook",
    hint: "You write notes, ideas, or homework in it.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-33",
    word: "Charger",
    hint: "You connect it to a device when its battery needs power.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-34",
    word: "Flashlight",
    hint: "You carry it when you need a small portable source of light.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-everyday-35",
    word: "Mop",
    hint: "You use it with water to clean a hard floor.",
    category: "everyday",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-everyday-36",
    word: "Thermostat",
    hint: "A device that helps control the temperature of a room.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-37",
    word: "Stapler",
    hint: "A small desk tool that fastens several sheets of paper together.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-38",
    word: "Colander",
    hint: "A bowl with holes that lets water drain away from food.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-39",
    word: "Canister",
    hint: "A container often used to store dry food or kitchen ingredients.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-40",
    word: "Dustpan",
    hint: "You hold it near the floor to collect dirt swept up with a broom.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-41",
    word: "Ladle",
    hint: "A deep spoon used for serving soup, curry, or other liquids.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-42",
    word: "Whisk",
    hint: "A kitchen tool used to mix ingredients and add air to them.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-43",
    word: "Measuring Cup",
    hint: "You use it to measure a specific amount of a liquid or dry ingredient.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-44",
    word: "Extension Cord",
    hint: "It lets you power an electrical device from a socket farther away.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-45",
    word: "Doorbell",
    hint: "Visitors press it to let people inside know they have arrived.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-46",
    word: "Ironing Board",
    hint: "You place clothes on it while removing wrinkles with an iron.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-47",
    word: "Laundry Basket",
    hint: "You put dirty clothes in it before washing them.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-48",
    word: "Screwdriver",
    hint: "You use it to tighten or loosen screws.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-49",
    word: "Thermometer",
    hint: "You use it to find out how hot or cold something is.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-everyday-50",
    word: "Picture Frame",
    hint: "It holds and displays a photograph or piece of artwork.",
    category: "everyday",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-everyday-ur-1",
    word: "Chair",
    hint: "Is par baith kar aaram karte hain ya table par kaam karte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-2",
    word: "Table",
    hint: "Is ke upar khana, kitaabein ya doosri cheezen rakhte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-3",
    word: "Phone",
    hint: "Is se logon ko call, message aur internet istemal karte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-4",
    word: "Cup",
    hint: "Is mein chai, coffee ya pani peete hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-5",
    word: "Spoon",
    hint: "Is se khana khate ya kisi drink ko hilate hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-6",
    word: "Plate",
    hint: "Aksar khana is par parosa jata hai.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-7",
    word: "Bottle",
    hint: "Is mein pani ya koi drink bhar kar saath le ja sakte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-8",
    word: "Key",
    hint: "Darwaza ya tala kholne ke liye is ka istemal hota hai.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-9",
    word: "Book",
    hint: "Isay khol kar kahaniyan, maloomat ya sabaq parhte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-10",
    word: "Pen",
    hint: "Is se siyahi ke saath likhte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-11",
    word: "Mirror",
    hint: "Is mein dekh kar apna chehra nazar aata hai.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-12",
    word: "Towel",
    hint: "Nahaane ya haath dhone ke baad khud ko sukhaane ke liye istemal hota hai.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-13",
    word: "Pillow",
    hint: "Sote waqt sar is par rakhte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-14",
    word: "Blanket",
    hint: "Sote waqt thand se bachne ke liye isay opar lete hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-15",
    word: "Shoes",
    hint: "Bahar jaate waqt inhein pairon mein pehente hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-16",
    word: "Wallet",
    hint: "Is mein aam tor par paise aur cards rakhte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-17",
    word: "Comb",
    hint: "Baalon ko seedha aur theek rakhne ke liye isay istemal karte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-18",
    word: "Bucket",
    hint: "Is mein pani bhar kar handle se utha sakte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-19",
    word: "Broom",
    hint: "Farsh se mitti aur kachra saaf karne ke liye isay istemal karte hain.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-20",
    word: "Lamp",
    hint: "Andhera hone par yeh roshni deta hai.",
    category: "everyday",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-everyday-ur-21",
    word: "Backpack",
    hint: "Kitaabein, kapre ya doosri cheezen kandhon par le jane ke liye istemal hota hai.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-22",
    word: "Toothbrush",
    hint: "Toothpaste ke saath daant saaf karne ke liye istemal hota hai.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-23",
    word: "Umbrella",
    hint: "Barish mein isay sar ke upar rakhte hain.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-24",
    word: "Remote Control",
    hint: "Door se TV ya kisi doosre electronic device ko control karne ke liye istemal hota hai.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-25",
    word: "Refrigerator",
    hint: "Yeh khane aur drinks ko thanda rakhne mein madad karta hai.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-26",
    word: "Kettle",
    hint: "Chai ya doosri garam drinks ke liye pani garam karne mein istemal hota hai.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-27",
    word: "Backpack",
    hint: "Students aksar apni kitaabein aur zaroori saman is mein rakhte hain.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-28",
    word: "Hanger",
    hint: "Kapron ko wardrobe mein seedha latkane ke liye istemal hota hai.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-29",
    word: "Drawer",
    hint: "Yeh desk ya cabinet mein andar bahar hota hai aur cheezen rakhne ke kaam aata hai.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-30",
    word: "Doormat",
    hint: "Ghar mein dakhil hone se pehle jootay is par saaf karte hain.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-31",
    word: "Scissors",
    hint: "Is ke handles dabane se kagaz, kapra ya doosri cheezen kaat sakte hain.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-32",
    word: "Notebook",
    hint: "Notes, ideas ya homework likhne ke liye is mein likhte hain.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-33",
    word: "Charger",
    hint: "Jab device ki battery khatam ho rahi ho to is se charge karte hain.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-34",
    word: "Flashlight",
    hint: "Andhere mein portable roshni ke liye isay saath le ja sakte hain.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-35",
    word: "Mop",
    hint: "Pani ke saath farsh saaf karne ke liye isay istemal karte hain.",
    category: "everyday",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-everyday-ur-36",
    word: "Thermostat",
    hint: "Yeh device kamre ka temperature control karne mein madad karta hai.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-37",
    word: "Stapler",
    hint: "Yeh chhota desk tool kagaz ke kai pages ko aapas mein jorne ke kaam aata hai.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-38",
    word: "Colander",
    hint: "Is mein chhed hote hain jin se pani nikal jata hai aur khana reh jata hai.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-39",
    word: "Canister",
    hint: "Kitchen mein dry food ya doosri cheezen mehfooz rakhne ke liye container hota hai.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-40",
    word: "Dustpan",
    hint: "Jhaaru se jama ki hui mitti ko is mein ikatha karte hain.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-41",
    word: "Ladle",
    hint: "Soup, curry ya doosri liquid cheezen nikalne ke liye gehra chamach hota hai.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-42",
    word: "Whisk",
    hint: "Kitchen mein ingredients ko mix karne aur hawa milane ke liye istemal hota hai.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-43",
    word: "Measuring Cup",
    hint: "Liquid ya dry ingredient ki khaas miqdaar naapne ke liye istemal hota hai.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-44",
    word: "Extension Cord",
    hint: "Yeh door maujood socket se electrical device ko power dene mein madad karta hai.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-45",
    word: "Doorbell",
    hint: "Mehmaan ghar ke bahar se isay daba kar apni aamad ka pata dete hain.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-46",
    word: "Ironing Board",
    hint: "Kapre press karte waqt unhein is ke upar rakhte hain.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-47",
    word: "Laundry Basket",
    hint: "Dhule na hue kapre dhone se pehle is mein rakhte hain.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-48",
    word: "Screwdriver",
    hint: "Screw ko kasne ya kholne ke liye is tool ka istemal hota hai.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-49",
    word: "Thermometer",
    hint: "Kisi cheez ka temperature maloom karne ke liye isay istemal karte hain.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-everyday-ur-50",
    word: "Picture Frame",
    hint: "Tasveer ya artwork ko display karne ke liye is mein lagate hain.",
    category: "everyday",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
