import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "food" category.
 *
 * English and Roman Urdu cover the exact same 20/15/15
 * easy/medium/hard grid.
 *
 * The Roman Urdu `word` deliberately stays EXACTLY the same
 * as the English food name. Only the hint is localized into
 * natural Roman Urdu.
 *
 * Total:
 * - 50 English
 * - 50 Roman Urdu
 * - 100 entries
 * - 50 unique foods
 */
export const FOOD_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-food-1",
    word: "Apple",
    hint: "A common fruit that can be red, green, or yellow.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-2",
    word: "Banana",
    hint: "A soft yellow fruit that is easy to peel.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-3",
    word: "Mango",
    hint: "A sweet, juicy fruit that is especially popular in summer.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-4",
    word: "Orange",
    hint: "A round citrus fruit with a bright orange peel.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-5",
    word: "Bread",
    hint: "A baked food often eaten with breakfast or used for sandwiches.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-6",
    word: "Rice",
    hint: "Small grains that are commonly boiled or steamed as a meal.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-7",
    word: "Egg",
    hint: "A common food that can be boiled, fried, or scrambled.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-8",
    word: "Milk",
    hint: "A white drink that comes from animals such as cows.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-9",
    word: "Cheese",
    hint: "A dairy food often added to sandwiches, pizza, and burgers.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-10",
    word: "Chicken",
    hint: "A popular type of meat that can be fried, grilled, or cooked in curry.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-11",
    word: "Potato",
    hint: "A vegetable that can be boiled, fried, mashed, or baked.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-12",
    word: "Tomato",
    hint: "A red food often used in salads, sauces, and curries.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-13",
    word: "Carrot",
    hint: "A crunchy orange vegetable that can be eaten raw or cooked.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-14",
    word: "Onion",
    hint: "A layered vegetable that adds a strong flavor to many dishes.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-15",
    word: "Pizza",
    hint: "A flat baked dish usually covered with sauce, cheese, and toppings.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-16",
    word: "Burger",
    hint: "A round bun usually filled with a patty and other toppings.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-17",
    word: "Ice Cream",
    hint: "A cold, sweet dessert that comes in many flavors.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-18",
    word: "Chocolate",
    hint: "A sweet food made from cocoa and often used in desserts.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-19",
    word: "Biscuit",
    hint: "A small baked snack that is often sweet and crunchy.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-20",
    word: "Watermelon",
    hint: "A large fruit with green skin and juicy red flesh.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-food-21",
    word: "Biryani",
    hint: "A spiced rice dish commonly cooked with meat, vegetables, or both.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-22",
    word: "Samosa",
    hint: "A crispy triangular snack usually filled with potatoes, vegetables, or meat.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-23",
    word: "Naan",
    hint: "A soft flatbread commonly cooked in a tandoor.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-24",
    word: "Kebab",
    hint: "Seasoned meat that is usually grilled on a skewer or cooked over heat.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-25",
    word: "Pasta",
    hint: "An Italian food made from dough and shaped into many different forms.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-26",
    word: "Noodles",
    hint: "Long thin strips of dough that are boiled or stir-fried.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-27",
    word: "Sandwich",
    hint: "Food made by placing fillings such as meat, cheese, or vegetables between bread.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-28",
    word: "Pancake",
    hint: "A flat, soft breakfast food usually cooked in a pan.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-29",
    word: "Popcorn",
    hint: "Corn kernels that puff up when heated and are often eaten as a snack.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-30",
    word: "Yogurt",
    hint: "A creamy dairy food made by fermenting milk.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-31",
    word: "Strawberry",
    hint: "A small red fruit with tiny seeds on its surface.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-32",
    word: "Pomegranate",
    hint: "A round fruit filled with many small juicy red seeds.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-33",
    word: "Pineapple",
    hint: "A tropical fruit with a rough skin and sweet yellow flesh.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-34",
    word: "Spinach",
    hint: "A leafy green vegetable often used in curries, soups, and salads.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-35",
    word: "Cauliflower",
    hint: "A white vegetable made up of many tightly packed florets.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-food-36",
    word: "Nihari",
    hint: "A slow-cooked spicy meat stew commonly eaten with naan.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-37",
    word: "Haleem",
    hint: "A thick dish made by slowly cooking grains, lentils, and meat together.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-38",
    word: "Chapli Kebab",
    hint: "A flat, spiced meat kebab strongly associated with Pakistani cuisine.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-39",
    word: "Gulab Jamun",
    hint: "A soft, round South Asian sweet soaked in sugary syrup.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-40",
    word: "Jalebi",
    hint: "A bright orange spiral-shaped sweet soaked in sugar syrup.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-41",
    word: "Kheer",
    hint: "A creamy South Asian dessert traditionally made with milk and rice.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-42",
    word: "Pakora",
    hint: "A crispy fried snack made by coating vegetables or other ingredients in batter.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-43",
    word: "Falafel",
    hint: "Small fried balls made mainly from ground chickpeas or fava beans.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-44",
    word: "Lasagna",
    hint: "An Italian baked dish made with layers of pasta, sauce, cheese, and filling.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-45",
    word: "Tiramisu",
    hint: "An Italian dessert made with coffee-soaked biscuits, cream, and cocoa.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-46",
    word: "Croissant",
    hint: "A flaky, crescent-shaped pastry commonly eaten for breakfast.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-47",
    word: "Guacamole",
    hint: "A creamy dip made mainly from mashed avocado.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-48",
    word: "Ratatouille",
    hint: "A French vegetable dish made by cooking ingredients such as tomato, eggplant, and zucchini.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-49",
    word: "Sushi",
    hint: "A Japanese dish commonly made with seasoned rice and fillings such as seafood or vegetables.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-50",
    word: "Kimchi",
    hint: "A Korean side dish made from fermented and seasoned vegetables.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-food-ur-1",
    word: "Apple",
    hint: "Ek aam phal jo laal, sabz ya peela ho sakta hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-2",
    word: "Banana",
    hint: "Ek naram peela phal jis ka chilka asani se utar jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-3",
    word: "Mango",
    hint: "Ek meetha aur ras bhara phal jo khaas taur par garmiyon mein pasand kiya jata hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-4",
    word: "Orange",
    hint: "Ek gol citrus phal jis ka chilka chamakdar narangi rang ka hota hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-5",
    word: "Bread",
    hint: "Aate se bani hui baked cheez jo nashtay ya sandwich mein khayi jati hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-6",
    word: "Rice",
    hint: "Chhotay chhotay danay jo aam tor par ubaal kar ya steam karke khaye jate hain.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-7",
    word: "Egg",
    hint: "Ek aam ghiza jo ubaal kar, fry karke ya scramble karke khayi ja sakti hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-8",
    word: "Milk",
    hint: "Ek safed mashroob jo gai jaise janwaron se milta hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-9",
    word: "Cheese",
    hint: "Doodh se bani ghiza jo sandwich, pizza aur burger mein bhi dali jati hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-10",
    word: "Chicken",
    hint: "Ek mashhoor gosht jo fry, grill ya salan mein pakaya ja sakta hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-11",
    word: "Potato",
    hint: "Ek sabzi jo ubaal, fry, mash ya bake karke khayi ja sakti hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-12",
    word: "Tomato",
    hint: "Ek surkh ghiza jo salad, sauces aur salan mein aksar istemal hoti hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-13",
    word: "Carrot",
    hint: "Ek narangi rang ki kurkuri sabzi jo kachi ya paki hui khayi ja sakti hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-14",
    word: "Onion",
    hint: "Ek parat dar sabzi jo bohat se khanon mein tez zaiqa deti hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-15",
    word: "Pizza",
    hint: "Ek gol baked dish jis par aam tor par sauce, cheese aur toppings hoti hain.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-16",
    word: "Burger",
    hint: "Ek bun jis ke darmiyan aam tor par patty aur doosri toppings hoti hain.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-17",
    word: "Ice Cream",
    hint: "Ek thandi aur meethi dessert jo mukhtalif flavors mein milti hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-18",
    word: "Chocolate",
    hint: "Cocoa se banne wali meethi ghiza jo desserts mein bhi istemal hoti hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-19",
    word: "Biscuit",
    hint: "Ek chhoti baked snack jo aksar meethi aur kurkuri hoti hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-20",
    word: "Watermelon",
    hint: "Ek bara phal jis ka chilka sabz aur andar ka hissa ras bhara surkh hota hai.",
    category: "food",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-food-ur-21",
    word: "Biryani",
    hint: "Masalay daar chawal ki dish jo gosht, sabzi ya dono ke saath pakayi jati hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-22",
    word: "Samosa",
    hint: "Ek kurkura tikona snack jis mein aloo, sabzi ya gosht bhara hota hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-23",
    word: "Naan",
    hint: "Ek naram roti jo aam tor par tandoor mein pakayi jati hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-24",
    word: "Kebab",
    hint: "Masalay daar gosht jo aam tor par seekh par ya aanch par grill kiya jata hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-25",
    word: "Pasta",
    hint: "Italy ki mashhoor ghiza jo aate ke dough se mukhtalif shapes mein banti hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-26",
    word: "Noodles",
    hint: "Aate ya chawal se bani lambi patli strips jo ubaal ya fry ki jati hain.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-27",
    word: "Sandwich",
    hint: "Do bread slices ke darmiyan gosht, cheese ya sabzi jaisi filling hoti hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-28",
    word: "Pancake",
    hint: "Ek naram aur chapti nashtay ki dish jo pan mein pakayi jati hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-29",
    word: "Popcorn",
    hint: "Makki ke danay garam hone par phool kar yeh mashhoor snack ban jate hain.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-30",
    word: "Yogurt",
    hint: "Doodh se banne wali ek creamy ghiza jo fermentation se tayar hoti hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-31",
    word: "Strawberry",
    hint: "Ek chhota surkh phal jis ki satah par chhotay chhotay beej hote hain.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-32",
    word: "Pomegranate",
    hint: "Ek gol phal jis ke andar bohat se chhotay ras bhare surkh danay hote hain.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-33",
    word: "Pineapple",
    hint: "Ek tropical phal jis ka chilka sakht aur andar ka hissa meetha peela hota hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-34",
    word: "Spinach",
    hint: "Ek sabz patton wali sabzi jo saag, soup aur salad mein istemal hoti hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-35",
    word: "Cauliflower",
    hint: "Ek safed sabzi jo bohat se chhotay phool jaisay tukron se mil kar banti hai.",
    category: "food",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-food-ur-36",
    word: "Nihari",
    hint: "Ek masalay daar gosht ka dheemi aanch par pakaya hua salan jo naan ke saath khaya jata hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-37",
    word: "Haleem",
    hint: "Ek gaari dish jo daalon, gandum ya doosre grains aur gosht ko dheemi aanch par paka kar banti hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-38",
    word: "Chapli Kebab",
    hint: "Ek chapta aur masalay daar gosht ka kebab jo Pakistani khanon mein mashhoor hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-39",
    word: "Gulab Jamun",
    hint: "Ek naram gol mithai jo meethay sheere mein bhigo kar pesh ki jati hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-40",
    word: "Jalebi",
    hint: "Ek narangi rang ki gol gol bani hui mithai jo cheeni ke sheere mein duboyi jati hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-41",
    word: "Kheer",
    hint: "Doodh aur chawal se banne wali ek mashhoor South Asian meethi dish.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-42",
    word: "Pakora",
    hint: "Ek kurkura fried snack jo sabzi ya doosri cheezon ko batter mein lapet kar banta hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-43",
    word: "Falafel",
    hint: "Cholay ya doosri daalon se banne wale chhotay gol fried balls.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-44",
    word: "Lasagna",
    hint: "Italy ki baked dish jo pasta, sauce, cheese aur filling ki layers se banti hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-45",
    word: "Tiramisu",
    hint: "Italy ki dessert jo coffee mein bhigoye biscuits, cream aur cocoa se banti hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-46",
    word: "Croissant",
    hint: "Ek halki aur flaky crescent shape pastry jo aksar nashtay mein khayi jati hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-47",
    word: "Guacamole",
    hint: "Avocado ko mash karke banayi jane wali ek creamy dip.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-48",
    word: "Ratatouille",
    hint: "France ki vegetable dish jo tomato, baingan aur zucchini jaisi sabziyon se banti hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-49",
    word: "Sushi",
    hint: "Japan ki mashhoor dish jo aam tor par seasoned rice aur seafood ya vegetables se banti hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-food-ur-50",
    word: "Kimchi",
    hint: "Korea ki mashhoor side dish jo fermented aur masalay daar sabziyon se banti hai.",
    category: "food",
    difficulty: "hard",
    language: "roman-urdu",
  },
];