import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "jobs" category.
 *
 * English and Roman Urdu cover the exact same 20/15/15
 * easy/medium/hard grid.
 *
 * The Roman Urdu `word` deliberately stays EXACTLY the same
 * as the English job name. Only the hint is localized into
 * natural Roman Urdu.
 *
 * Total:
 * - 50 English
 * - 50 Roman Urdu
 * - 100 entries
 * - 50 unique jobs
 */
export const JOBS_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-jobs-1",
    word: "Doctor",
    hint: "You visit this person when you are sick or injured.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-2",
    word: "Teacher",
    hint: "This person helps students learn new things at school.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-3",
    word: "Nurse",
    hint: "This person cares for patients in a hospital or clinic.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-4",
    word: "Dentist",
    hint: "You visit this person for checkups on your teeth.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-5",
    word: "Chef",
    hint: "This person prepares food in a kitchen.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-6",
    word: "Police Officer",
    hint: "This person helps keep people safe and enforces the law.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-7",
    word: "Firefighter",
    hint: "This person helps put out fires and rescue people.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-8",
    word: "Farmer",
    hint: "This person grows crops or raises animals on a farm.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-9",
    word: "Driver",
    hint: "This person operates a car, bus, truck, or other vehicle.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-10",
    word: "Pilot",
    hint: "This person flies an airplane.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-11",
    word: "Engineer",
    hint: "This person uses science and math to design and build things.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-12",
    word: "Mechanic",
    hint: "This person repairs cars and other machines.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-13",
    word: "Carpenter",
    hint: "This person builds or repairs things made from wood.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-14",
    word: "Electrician",
    hint: "This person installs and repairs electrical systems.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-15",
    word: "Plumber",
    hint: "This person repairs pipes and water systems.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-16",
    word: "Farmer",
    hint: "This person works with crops, fields, and farm animals.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-17",
    word: "Barber",
    hint: "You visit this person to get your hair cut.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-18",
    word: "Waiter",
    hint: "This person serves food and drinks in a restaurant.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-19",
    word: "Cashier",
    hint: "This person takes payments in a shop or supermarket.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-20",
    word: "Photographer",
    hint: "This person takes pictures professionally.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-jobs-21",
    word: "Journalist",
    hint: "This person researches and reports news stories.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-22",
    word: "Architect",
    hint: "This person designs buildings and other structures.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-23",
    word: "Lawyer",
    hint: "This person gives legal advice and represents clients.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-24",
    word: "Pharmacist",
    hint: "This person prepares and provides medicines.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-25",
    word: "Librarian",
    hint: "This person helps people find and organize books.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-26",
    word: "Electrician",
    hint: "This person works with wiring, electricity, and electrical equipment.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-27",
    word: "Designer",
    hint: "This person creates the look and appearance of products or visuals.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-28",
    word: "Accountant",
    hint: "This person manages financial records and calculations.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-29",
    word: "Architect",
    hint: "This professional plans how buildings should look and function.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-30",
    word: "Scientist",
    hint: "This person studies the world through research and experiments.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-31",
    word: "Programmer",
    hint: "This person writes code to create computer programs.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-32",
    word: "Journalist",
    hint: "This person gathers information and writes about current events.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-33",
    word: "Veterinarian",
    hint: "This person treats sick or injured animals.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-34",
    word: "Electrician",
    hint: "This worker installs and fixes electrical wiring and equipment.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-35",
    word: "Translator",
    hint: "This person changes written or spoken words from one language to another.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-jobs-36",
    word: "Astronaut",
    hint: "This highly trained professional travels into space.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-37",
    word: "Cartographer",
    hint: "This person creates and studies maps.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-38",
    word: "Blacksmith",
    hint: "This skilled worker shapes metal using heat and a hammer.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-39",
    word: "Archaeologist",
    hint: "This person studies ancient people through objects and remains.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-40",
    word: "Entomologist",
    hint: "This scientist studies insects.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-41",
    word: "Geologist",
    hint: "This scientist studies rocks, minerals, and the Earth.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-42",
    word: "Ornithologist",
    hint: "This scientist specializes in studying birds.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-43",
    word: "Meteorologist",
    hint: "This scientist studies weather and the atmosphere.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-44",
    word: "Paleontologist",
    hint: "This scientist studies fossils and ancient life.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-45",
    word: "Cryptographer",
    hint: "This specialist works with codes and methods for securing information.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-46",
    word: "Geographer",
    hint: "This person studies places, people, and features of Earth.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-47",
    word: "Anthropologist",
    hint: "This person studies humans, cultures, and societies.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-48",
    word: "Meteorologist",
    hint: "This professional uses scientific data to understand weather conditions.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-49",
    word: "Taxidermist",
    hint: "This specialist prepares and preserves animal specimens.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-50",
    word: "Gemcutter",
    hint: "This skilled worker cuts and shapes precious stones.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-jobs-ur-1",
    word: "Doctor",
    hint: "Jab aap bemar ya zakhmi hon to is shakhs ke paas jate hain.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-2",
    word: "Teacher",
    hint: "Yeh shakhs school mein students ko nai cheezen seekhne mein madad karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-3",
    word: "Nurse",
    hint: "Yeh shakhs hospital ya clinic mein mareezon ki dekh bhaal karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-4",
    word: "Dentist",
    hint: "Daanton ka checkup karwane ke liye is shakhs ke paas jate hain.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-5",
    word: "Chef",
    hint: "Yeh shakhs kitchen mein khana tayar karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-6",
    word: "Police Officer",
    hint: "Yeh shakhs logon ki hifazat karta aur qanoon par amal karwata hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-7",
    word: "Firefighter",
    hint: "Yeh shakhs aag bujhane aur logon ko bachane ka kaam karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-8",
    word: "Farmer",
    hint: "Yeh shakhs khet mein faslein ugata ya janwar palta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-9",
    word: "Driver",
    hint: "Yeh shakhs car, bus, truck ya koi doosri sawari chalata hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-10",
    word: "Pilot",
    hint: "Yeh shakhs airplane urata hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-11",
    word: "Engineer",
    hint: "Yeh shakhs science aur maths ki madad se cheezen design aur build karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-12",
    word: "Mechanic",
    hint: "Yeh shakhs cars aur doosri machines ki marammat karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-13",
    word: "Carpenter",
    hint: "Yeh shakhs lakri se bani cheezen banata ya repair karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-14",
    word: "Electrician",
    hint: "Yeh shakhs bijli ke system aur wiring ko install aur repair karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-15",
    word: "Plumber",
    hint: "Yeh shakhs pipes aur pani ke system ki marammat karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-16",
    word: "Farmer",
    hint: "Yeh shakhs faslon, kheton aur janwaron ke saath kaam karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-17",
    word: "Barber",
    hint: "Baal katwane ke liye aap is shakhs ke paas jate hain.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-18",
    word: "Waiter",
    hint: "Yeh shakhs restaurant mein khana aur drinks serve karta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-19",
    word: "Cashier",
    hint: "Yeh shakhs shop ya supermarket mein payments leta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-20",
    word: "Photographer",
    hint: "Yeh shakhs professionally tasveeren kheenchta hai.",
    category: "jobs",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-jobs-ur-21",
    word: "Journalist",
    hint: "Yeh shakhs news stories ke liye maloomat jama karke report karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-22",
    word: "Architect",
    hint: "Yeh shakhs buildings aur doosri structures ka design banata hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-23",
    word: "Lawyer",
    hint: "Yeh shakhs qanooni mashwara deta aur clients ki numaindagi karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-24",
    word: "Pharmacist",
    hint: "Yeh shakhs medicines tayar karta aur logon ko deta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-25",
    word: "Librarian",
    hint: "Yeh shakhs logon ko kitaben dhoondne aur arrange karne mein madad karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-26",
    word: "Electrician",
    hint: "Yeh shakhs wiring, bijli aur electrical equipment ke saath kaam karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-27",
    word: "Designer",
    hint: "Yeh shakhs products ya visuals ka look aur appearance banata hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-28",
    word: "Accountant",
    hint: "Yeh shakhs paison ke records aur calculations manage karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-29",
    word: "Architect",
    hint: "Yeh professional plan karta hai ke building kaisi dikhegi aur kaise kaam karegi.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-30",
    word: "Scientist",
    hint: "Yeh shakhs research aur experiments ke zariye duniya ka mutalea karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-31",
    word: "Programmer",
    hint: "Yeh shakhs computer programs banane ke liye code likhta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-32",
    word: "Journalist",
    hint: "Yeh shakhs current events ke bare mein maloomat jama karke likhta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-33",
    word: "Veterinarian",
    hint: "Yeh shakhs bemar ya zakhmi janwaron ka ilaaj karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-34",
    word: "Electrician",
    hint: "Yeh worker electrical wiring aur equipment ko install aur theek karta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-35",
    word: "Translator",
    hint: "Yeh shakhs alfaaz ko ek zaban se doosri zaban mein badalta hai.",
    category: "jobs",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-jobs-ur-36",
    word: "Astronaut",
    hint: "Yeh bohat trained professional space mein safar karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-37",
    word: "Cartographer",
    hint: "Yeh shakhs maps banata aur unka mutalea karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-38",
    word: "Blacksmith",
    hint: "Yeh maahir worker garam metal ko hathoray se shape deta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-39",
    word: "Archaeologist",
    hint: "Yeh shakhs purane logon aur unki zindagi ka objects aur remains ke zariye mutalea karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-40",
    word: "Entomologist",
    hint: "Yeh scientist insects yani keeron makoron ka mutalea karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-41",
    word: "Geologist",
    hint: "Yeh scientist patharon, minerals aur zameen ka mutalea karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-42",
    word: "Ornithologist",
    hint: "Yeh scientist parindon ke mutalea mein mahir hota hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-43",
    word: "Meteorologist",
    hint: "Yeh scientist mausam aur hawa ke atmosphere ka mutalea karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-44",
    word: "Paleontologist",
    hint: "Yeh scientist fossils aur purani zindagi ka mutalea karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-45",
    word: "Cryptographer",
    hint: "Yeh specialist codes aur information ko secure karne ke tareeqon par kaam karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-46",
    word: "Geographer",
    hint: "Yeh shakhs duniya ke ilaqon, logon aur zameeni features ka mutalea karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-47",
    word: "Anthropologist",
    hint: "Yeh shakhs insano, cultures aur societies ka mutalea karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-48",
    word: "Meteorologist",
    hint: "Yeh professional scientific data se mausam ko samajhne ki koshish karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-49",
    word: "Taxidermist",
    hint: "Yeh specialist janwaron ke specimens ko preserve karne ka kaam karta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-jobs-ur-50",
    word: "Gemcutter",
    hint: "Yeh maahir worker qeemti patharon ko kaat kar shape deta hai.",
    category: "jobs",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
