import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "movies" category (see
 * ./index.ts for the combined TIER 3 pipeline this feeds into).
 *
 * English and Roman Urdu cover the exact same easy/medium/hard grid --
 * see index.ts's doc comment for why that parity matters (Roman Urdu
 * must never silently fall back to English). The Roman Urdu *word*
 * deliberately stays the same movie title as its English counterpart
 * -- only the hint is written in natural Roman Urdu.
 */
export const MOVIES_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-movies-1",
    word: "Spider-Man",
    hint: "A teenager gains superpowers after being bitten by a spider.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-2",
    word: "Titanic",
    hint: "A young couple falls in love aboard a famous ship.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-3",
    word: "Avatar",
    hint: "A former soldier becomes part of an alien world called Pandora.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-4",
    word: "Avengers: Endgame",
    hint: "The Avengers try to reverse the destruction caused by Thanos.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-5",
    word: "The Dark Knight",
    hint: "Batman faces the dangerous Joker in Gotham City.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-6",
    word: "Harry Potter",
    hint: "A young wizard studies magic and fights dark forces.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-7",
    word: "Jurassic Park",
    hint: "A theme park filled with cloned dinosaurs becomes a disaster.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-8",
    word: "The Lion King",
    hint: "A young lion must take his rightful place as king.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-9",
    word: "Frozen",
    hint: "Two sisters are caught up in a magical kingdom covered in ice.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-10",
    word: "Iron Man",
    hint: "A billionaire builds a powerful armored suit and becomes a hero.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-11",
    word: "Superman",
    hint: "A powerful hero from another planet protects Earth.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-12",
    word: "Batman",
    hint: "A billionaire uses his wealth and skills to fight crime in Gotham.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-13",
    word: "Home Alone",
    hint: "A young boy is accidentally left home while his family goes on vacation.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-14",
    word: "The Avengers",
    hint: "A team of Marvel heroes joins forces to save the world.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-15",
    word: "Toy Story",
    hint: "Toys secretly come to life when humans are not around.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-16",
    word: "Mission: Impossible",
    hint: "A secret agent takes on dangerous missions around the world.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-17",
    word: "Fast & Furious",
    hint: "A group of drivers becomes involved in fast cars and dangerous missions.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-18",
    word: "Star Wars",
    hint: "Heroes and villains battle across a galaxy using the Force.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-19",
    word: "Baahubali",
    hint: "A legendary warrior becomes involved in a battle for a kingdom.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-movies-20",
    word: "3 Idiots",
    hint: "Three college friends face friendship, education, and pressure to succeed.",
    category: "movies",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-movies-21",
    word: "Interstellar",
    hint: "Astronauts travel through space searching for a new home for humanity.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-22",
    word: "Inception",
    hint: "A team enters dreams to plant an idea inside someone's mind.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-23",
    word: "Joker",
    hint: "A troubled man in Gotham slowly transforms into a dangerous villain.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-24",
    word: "Black Panther",
    hint: "A superhero king protects the hidden African nation of Wakanda.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-25",
    word: "Deadpool",
    hint: "A sarcastic antihero with healing powers seeks revenge after an experiment.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-26",
    word: "Guardians of the Galaxy",
    hint: "A group of unusual heroes joins together to protect the galaxy.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-27",
    word: "Pirates of the Caribbean",
    hint: "Captain Jack Sparrow gets caught up in adventures on the high seas.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-28",
    word: "The Hunger Games",
    hint: "Young contestants are forced to fight for survival in an annual competition.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-29",
    word: "Transformers",
    hint: "Giant robots from another planet battle each other on Earth.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-30",
    word: "John Wick",
    hint: "A legendary hitman returns to action after criminals attack his peaceful life.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-31",
    word: "Oppenheimer",
    hint: "A scientist leads a secret project to develop the atomic bomb.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-32",
    word: "Dangal",
    hint: "A father trains his daughters to become successful wrestlers.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-33",
    word: "RRR",
    hint: "Two revolutionaries form a powerful friendship while fighting British rule.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-34",
    word: "KGF",
    hint: "A determined man rises from poverty and seeks power in dangerous gold mines.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-movies-35",
    word: "Koi... Mil Gaya",
    hint: "A young man becomes friends with an alien who arrives on Earth.",
    category: "movies",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-movies-36",
    word: "The Prestige",
    hint: "Two rival magicians become obsessed with creating the ultimate illusion.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-37",
    word: "The Departed",
    hint: "An undercover police officer and a criminal informant secretly work for opposite sides.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-38",
    word: "Gladiator",
    hint: "A betrayed Roman general becomes a gladiator and seeks revenge.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-39",
    word: "The Shawshank Redemption",
    hint: "A wrongly imprisoned man holds onto hope through many years in prison.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-40",
    word: "Pulp Fiction",
    hint: "Several connected crime stories unfold through an unusual timeline.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-41",
    word: "Forrest Gump",
    hint: "A kind-hearted man becomes part of many major moments in American history.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-42",
    word: "Parasite",
    hint: "A struggling family becomes deeply involved with a wealthy household.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-43",
    word: "The Godfather",
    hint: "A powerful crime family deals with loyalty, power, and succession.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-44",
    word: "Memento",
    hint: "A man with severe memory problems tries to discover who attacked him.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-45",
    word: "Everything Everywhere All at Once",
    hint: "A woman discovers that different versions of her life exist across multiple universes.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-46",
    word: "Tumbbad",
    hint: "A man searches for mysterious treasure connected to an ancient curse.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-47",
    word: "Andhadhun",
    hint: "A pianist becomes involved in a complicated murder mystery.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-48",
    word: "Drishyam",
    hint: "A family creates an elaborate plan to protect itself after a terrible incident.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-49",
    word: "Bhairava",
    hint: "A futuristic warrior becomes involved in a battle surrounding a special child.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-movies-50",
    word: "Dilwale Dulhania Le Jayenge",
    hint: "Raj and Simran fall in love while facing their traditional families.",
    category: "movies",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-movies-ur-1",
    word: "Spider-Man",
    hint: "Ek teenager ko spider ke kaatne ke baad superpowers mil jati hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-2",
    word: "Titanic",
    hint: "Ek jawan couple ek mashhoor ship par mohabbat mein par jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-3",
    word: "Avatar",
    hint: "Ek former soldier Pandora naam ki alien duniya ka hissa ban jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-4",
    word: "Avengers: Endgame",
    hint: "Avengers Thanos ki ki hui tabahi ko reverse karne ki koshish karte hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-5",
    word: "The Dark Knight",
    hint: "Batman Gotham City mein khatarnak Joker ka samna karta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-6",
    word: "Harry Potter",
    hint: "Ek jawan jadugar magic seekhta hai aur buri quwwaton se ladta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-7",
    word: "Jurassic Park",
    hint: "Cloned dinosaurs se bhara ek theme park tabahi ka shikar ho jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-8",
    word: "The Lion King",
    hint: "Ek jawan sher ko apni saltanat ka haq hasil karna hota hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-9",
    word: "Frozen",
    hint: "Do behne ek aisi magical kingdom mein phans jati hain jo baraf se dhak jati hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-10",
    word: "Iron Man",
    hint: "Ek billionaire powerful armored suit banakar hero ban jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-11",
    word: "Superman",
    hint: "Ek powerful hero doosre planet se aakar Earth ko bachata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-12",
    word: "Batman",
    hint: "Ek billionaire apni daulat aur skills se Gotham mein crime se ladta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-13",
    word: "Home Alone",
    hint: "Ek chhota larka ghalti se ghar mein akela reh jata hai jab family vacation par chali jati hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-14",
    word: "The Avengers",
    hint: "Marvel ke heroes duniya bachane ke liye mil kar kaam karte hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-15",
    word: "Toy Story",
    hint: "Jab insaan paas na hon to toys chupke se zinda ho jate hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-16",
    word: "Mission: Impossible",
    hint: "Ek secret agent duniya bhar mein dangerous missions karta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-17",
    word: "Fast & Furious",
    hint: "Drivers ka ek group fast cars aur dangerous missions mein shamil ho jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-18",
    word: "Star Wars",
    hint: "Heroes aur villains galaxy mein Force ki madad se ek doosre se ladte hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-19",
    word: "Baahubali",
    hint: "Ek legendary warrior ek saltanat ke liye jang mein shamil hota hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-20",
    word: "3 Idiots",
    hint: "Teen college dost dosti, taleem aur kamyabi ke pressure ka samna karte hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-movies-ur-21",
    word: "Interstellar",
    hint: "Astronauts insaniyat ke liye naya ghar dhoondne space mein safar karte hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-22",
    word: "Inception",
    hint: "Ek team khwabon mein ja kar kisi ke zehan mein idea dalne ki koshish karti hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-23",
    word: "Joker",
    hint: "Gotham ka ek pareshan aadmi dheere dheere khatarnak villain ban jata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-24",
    word: "Black Panther",
    hint: "Ek superhero king Wakanda naam ke chhupe hue African mulk ko protect karta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-25",
    word: "Deadpool",
    hint: "Healing powers wala sarcastic antihero ek experiment ke baad badla leta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-26",
    word: "Guardians of the Galaxy",
    hint: "Kuch ajeeb heroes galaxy ko bachane ke liye ek team banate hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-27",
    word: "Pirates of the Caribbean",
    hint: "Captain Jack Sparrow samandar mein dangerous adventures mein phans jata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-28",
    word: "The Hunger Games",
    hint: "Young contestants ko ek annual competition mein zinda rehne ke liye ladna padta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-29",
    word: "Transformers",
    hint: "Doosre planet ke giant robots Earth par ek doosre se ladte hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-30",
    word: "John Wick",
    hint: "Ek legendary hitman apni peaceful zindagi kharab hone ke baad wapas action mein aata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-31",
    word: "Oppenheimer",
    hint: "Ek scientist secret project lead karta hai jisme atomic bomb banaya jata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-32",
    word: "Dangal",
    hint: "Ek baap apni betiyon ko successful wrestlers banne ki training deta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-33",
    word: "RRR",
    hint: "Do revolutionaries British hukoomat ke khilaf ladte hue gehri dosti banate hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-34",
    word: "KGF",
    hint: "Ek determined aadmi ghurbat se nikal kar dangerous gold mines mein taqat hasil karta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-35",
    word: "Koi... Mil Gaya",
    hint: "Ek jawan aadmi Earth par ane wale alien se dosti kar leta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-movies-ur-36",
    word: "The Prestige",
    hint: "Do rival magicians sab se behtareen magic trick banane ke junoon mein mubtala ho jate hain.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-37",
    word: "The Departed",
    hint: "Ek undercover police officer aur criminal informant mukhalif groups ke liye secretly kaam karte hain.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-38",
    word: "Gladiator",
    hint: "Ek dhoka khaya hua Roman general gladiator ban kar badla leta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-39",
    word: "The Shawshank Redemption",
    hint: "Ek beqasoor qaid mein dala gaya aadmi saalon tak umeed nahi chhorta.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-40",
    word: "Pulp Fiction",
    hint: "Crime se judi kai kahaniyan ek unusual timeline mein aapas mein milti hain.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-41",
    word: "Forrest Gump",
    hint: "Ek seedha saadha aadmi American history ke kai important waqiat ka hissa banta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-42",
    word: "Parasite",
    hint: "Ek ghareeb family ek ameer gharane ki zindagi mein gehrai se shamil ho jati hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-43",
    word: "The Godfather",
    hint: "Ek powerful crime family wafadari, power aur aglay leader ke masle se guzarti hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-44",
    word: "Memento",
    hint: "Memory problems wala ek aadmi apne hamlawar ko dhoondne ki koshish karta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-45",
    word: "Everything Everywhere All at Once",
    hint: "Ek aurat discover karti hai ke uski zindagi ke mukhtalif versions alag universes mein mojood hain.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-46",
    word: "Tumbbad",
    hint: "Ek aadmi purani laanat se judi pur-asrar daulat ki talash karta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-47",
    word: "Andhadhun",
    hint: "Ek pianist ek complicated murder mystery mein phans jata hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-48",
    word: "Drishyam",
    hint: "Ek family ek khaufnaak waqia ke baad khud ko bachane ke liye ek plan banati hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-49",
    word: "Bhairava",
    hint: "Ek futuristic warrior ek khaas bache se judi jang mein shamil hota hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-50",
    word: "Dilwale Dulhania Le Jayenge",
    hint: "Raj aur Simran ek doosre se mohabbat karte hain lekin unke traditional families raasta rokti hain.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
