import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "nature" category (see
 * ./index.ts for the combined TIER 3 pipeline this feeds into).
 *
 * English and Roman Urdu cover the exact same easy/medium/hard grid --
 * see index.ts's doc comment for why that parity matters (Roman Urdu
 * must never silently fall back to English). The Roman Urdu *word*
 * deliberately stays the same common term as its English counterpart
 * -- only the hint is written in natural Roman Urdu.
 */
export const NATURE_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-nature-1",
    word: "Mountain",
    hint: "A very large natural rise of land, often with a rocky or snowy top.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-2",
    word: "River",
    hint: "A long stream of water that flows across the land.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-3",
    word: "Forest",
    hint: "A large area covered with many trees and plants.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-4",
    word: "Ocean",
    hint: "A huge body of salt water covering much of Earth.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-5",
    word: "Beach",
    hint: "A sandy or rocky area beside the sea or a lake.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-6",
    word: "Desert",
    hint: "A very dry place that receives very little rain.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-7",
    word: "Rainbow",
    hint: "A colorful arc that can appear in the sky after rain.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-8",
    word: "Thunder",
    hint: "A loud sound heard in the sky during a storm.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-9",
    word: "Lightning",
    hint: "A bright flash of electricity that appears during a storm.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-10",
    word: "Waterfall",
    hint: "Water drops from a high place down to a lower area.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-11",
    word: "Volcano",
    hint: "A mountain that can release lava, ash, and hot gases.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-12",
    word: "Lake",
    hint: "A large area of water surrounded by land.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-13",
    word: "Tree",
    hint: "A tall plant with a trunk, branches, and leaves.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-14",
    word: "Flower",
    hint: "The colorful part of many plants that can produce seeds.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-15",
    word: "Cloud",
    hint: "A visible group of tiny water drops or ice particles in the sky.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-16",
    word: "Moon",
    hint: "Earth's natural satellite that shines in the night sky.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-17",
    word: "Sun",
    hint: "The star that gives Earth light and heat.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-18",
    word: "Island",
    hint: "A piece of land completely surrounded by water.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-19",
    word: "Cave",
    hint: "A natural opening or chamber found inside rock or underground.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-nature-20",
    word: "Butterfly",
    hint: "A flying insect known for its colorful wings.",
    category: "nature",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-nature-21",
    word: "Glacier",
    hint: "A huge mass of ice that slowly moves across the land.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-22",
    word: "Valley",
    hint: "Low land lying between mountains or hills.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-23",
    word: "Meadow",
    hint: "An open grassy field often filled with wildflowers.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-24",
    word: "Jungle",
    hint: "A thick forest with many plants and animals, usually in a warm region.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-25",
    word: "Cliff",
    hint: "A steep, high face of rock or earth.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-26",
    word: "Canyon",
    hint: "A deep valley with steep sides, often formed by a river.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-27",
    word: "Tornado",
    hint: "A powerful spinning column of air that reaches from a storm toward the ground.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-28",
    word: "Earthquake",
    hint: "Sudden shaking of the ground caused by movement beneath Earth's surface.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-29",
    word: "Tsunami",
    hint: "A series of huge sea waves usually caused by movement under the ocean.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-30",
    word: "Avalanche",
    hint: "A large mass of snow and ice that suddenly rushes down a mountain.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-31",
    word: "Rainforest",
    hint: "A dense forest that receives a very large amount of rain.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-32",
    word: "Pond",
    hint: "A small body of still water surrounded by land.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-33",
    word: "Drought",
    hint: "A long period when an area receives much less rain than normal.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-34",
    word: "Frost",
    hint: "A thin layer of ice that forms when water vapor freezes on cold surfaces.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-nature-35",
    word: "Mangrove",
    hint: "A tree or shrub that grows in salty coastal water and muddy areas.",
    category: "nature",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-nature-36",
    word: "Coral Reef",
    hint: "A colorful underwater ecosystem built mainly by tiny marine animals.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-37",
    word: "Geyser",
    hint: "A natural hot spring that periodically shoots hot water and steam into the air.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-38",
    word: "Aurora",
    hint: "A colorful natural light display that appears in the night sky near the poles.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-39",
    word: "Tundra",
    hint: "A cold, treeless region where the ground can remain frozen for long periods.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-40",
    word: "Estuary",
    hint: "A place where a river meets the sea and fresh water mixes with salt water.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-41",
    word: "Lagoon",
    hint: "A shallow body of water separated from a larger sea by sand or a reef.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-42",
    word: "Fjord",
    hint: "A long, narrow sea inlet surrounded by steep cliffs, usually formed by glaciers.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-43",
    word: "Oasis",
    hint: "A fertile place with water found in an otherwise dry desert.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-44",
    word: "Archipelago",
    hint: "A group or chain of islands located close together.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-45",
    word: "Stalactite",
    hint: "A mineral formation that hangs down from the ceiling of a cave.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-46",
    word: "Stalagmite",
    hint: "A mineral formation that rises from the floor of a cave.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-47",
    word: "Bioluminescence",
    hint: "Natural light produced by living organisms such as some jellyfish and insects.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-48",
    word: "Permafrost",
    hint: "Ground that remains frozen for at least two consecutive years.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-49",
    word: "Whirlpool",
    hint: "A powerful circular movement of water that can pull objects toward its center.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-nature-50",
    word: "Erosion",
    hint: "The gradual wearing away of rock or soil by wind, water, or ice.",
    category: "nature",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-nature-ur-1",
    word: "Mountain",
    hint: "Zameen ka bohat bara ubhra hua hissa jo aksar patharon ya baraf se dhaka hota hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-2",
    word: "River",
    hint: "Pani ka lamba rasta jo zameen par behta hua aage jata hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-3",
    word: "Forest",
    hint: "Aik bara ilaqa jahan bohat se darakht aur poday hote hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-4",
    word: "Ocean",
    hint: "Namak wale pani ka bohat bara samandar jo zameen ke bohat se hisay ko dhakhta hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-5",
    word: "Beach",
    hint: "Samandar ya jheel ke kinare ret ya patharon wali jagah.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-6",
    word: "Desert",
    hint: "Aik bohat khushk ilaqa jahan barish bohat kam hoti hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-7",
    word: "Rainbow",
    hint: "Barish ke baad aasman mein nazar aane wala rangon ka khoobsurat daira.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-8",
    word: "Thunder",
    hint: "Toofan ke waqt aasman se aane wali bohat tez garaj ki awaaz.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-9",
    word: "Lightning",
    hint: "Toofan ke waqt aasman mein nazar aane wali bijli ki tez chamak.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-10",
    word: "Waterfall",
    hint: "Pani ka buland jagah se neeche girna.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-11",
    word: "Volcano",
    hint: "Aik pahaar jo lava, raakh aur garam gases bahar nikal sakta hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-12",
    word: "Lake",
    hint: "Zameen se ghiri hui pani ki bari jagah.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-13",
    word: "Tree",
    hint: "Aik lamba poda jiska tana, shaakhein aur pattay hote hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-14",
    word: "Flower",
    hint: "Poday ka rangeen hissa jo aksar beej banane mein madad karta hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-15",
    word: "Cloud",
    hint: "Aasman mein pani ke bohat chhotay qatron ya baraf ke zarraat ka majmua.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-16",
    word: "Moon",
    hint: "Zameen ka qudrati satellite jo raat ko aasman mein nazar aata hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-17",
    word: "Sun",
    hint: "Woh sitara jo Zameen ko roshni aur garmi deta hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-18",
    word: "Island",
    hint: "Zameen ka aisa tukra jo har taraf se pani se ghira hota hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-19",
    word: "Cave",
    hint: "Pathar ya zameen ke andar bani hui qudrati surang ya jagah.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-20",
    word: "Butterfly",
    hint: "Aik urrne wala keera jiske par aksar bohat rangeen hote hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-nature-ur-21",
    word: "Glacier",
    hint: "Baraf ka bohat bara dher jo zameen par bohat aahista move karta hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-22",
    word: "Valley",
    hint: "Do paharon ya pahariyon ke darmiyan neecha ilaqa.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-23",
    word: "Meadow",
    hint: "Khula hara maidan jahan aksar jangli phool khile hote hain.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-24",
    word: "Jungle",
    hint: "Ghana darakhton aur podon wala jangal jahan aksar garam mausam hota hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-25",
    word: "Cliff",
    hint: "Pathar ya zameen ka bohat uncha aur seedha kinara.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-26",
    word: "Canyon",
    hint: "Gehri aur tang wadi jiske kinare bohat kharay hote hain.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-27",
    word: "Tornado",
    hint: "Hawa ka bohat taqatwar ghoomta hua column jo toofan se zameen tak pohanchta hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-28",
    word: "Earthquake",
    hint: "Zameen ka achanak hilna jo zameen ke neeche harkat ki wajah se hota hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-29",
    word: "Tsunami",
    hint: "Samandar mein hone wali harkat se paida hone wali bohat bari lehron ka silsila.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-30",
    word: "Avalanche",
    hint: "Baraf aur snow ka bohat bara dher jo pahaar se achanak neeche girta hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-31",
    word: "Rainforest",
    hint: "Aisa ghana jangal jahan bohat zyada barish hoti hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-32",
    word: "Pond",
    hint: "Zameen se ghiri hui pani ki chhoti aur pur-sukoon jagah.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-33",
    word: "Drought",
    hint: "Aisa lamba arsa jab kisi ilaqay mein aam se bohat kam barish hoti hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-34",
    word: "Frost",
    hint: "Sardi mein thandi satahon par pani ke jamne se banne wali baraf ki patli teh.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-35",
    word: "Mangrove",
    hint: "Aisa darakht ya poda jo kharay pani aur samandar ke qareeb kichar mein ugta hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-nature-ur-36",
    word: "Coral Reef",
    hint: "Samandar ke andar aik rangeen ecosystem jo chhotay samandari janwaron se banta hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-37",
    word: "Geyser",
    hint: "Qudrati garam pani ka chashma jo waqt waqt par garam pani aur bhaap hawa mein uchalta hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-38",
    word: "Aurora",
    hint: "Qutbi ilaqon ke qareeb raat ke aasman mein nazar aane wali rangon ki qudrati roshni.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-39",
    word: "Tundra",
    hint: "Bohat thanda aur aam tor par darakhton se khaali ilaqa jahan zameen lambi muddat tak jami rehti hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-40",
    word: "Estuary",
    hint: "Woh jagah jahan darya samandar se milta hai aur meetha pani namak wale pani mein mil jata hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-41",
    word: "Lagoon",
    hint: "Samandar se rait ya reef ki wajah se alag hui pani ki kam gehrai wali jagah.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-42",
    word: "Fjord",
    hint: "Paharon aur khari chattanon ke darmiyan samandar ka lamba aur tang hissa jo glacier se bana hota hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-43",
    word: "Oasis",
    hint: "Sehra ke beech aik aisi zarkhez jagah jahan pani mojood hota hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-44",
    word: "Archipelago",
    hint: "Qareeb qareeb mojood jaziron ke aik group ya silsilay ko kehte hain.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-45",
    word: "Stalactite",
    hint: "Ghaar ki chhat se neeche latakti hui mineral ki qudrati formation.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-46",
    word: "Stalagmite",
    hint: "Ghaar ki zameen se upar ki taraf banne wali mineral ki formation.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-47",
    word: "Bioluminescence",
    hint: "Jandar makhlooq ki taraf se qudrati roshni paida hone ka amal.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-48",
    word: "Permafrost",
    hint: "Aisi zameen jo kam az kam do saal tak musalsal jami hui rehti hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-49",
    word: "Whirlpool",
    hint: "Pani ki taqatwar gol gardish jo cheezon ko apne markaz ki taraf kheench sakti hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-50",
    word: "Erosion",
    hint: "Hawa, pani ya baraf ki wajah se pathar ya mitti ka dheere dheere ghisna.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
