import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "places" category.
 *
 * English and Roman Urdu cover the exact same easy/medium/hard grid.
 * Roman Urdu keeps common place names/terms where appropriate;
 * only the hints are written in natural Roman Urdu.
 */
export const PLACES_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-places-1",
    word: "School",
    hint: "A place where students go to learn.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-2",
    word: "Hospital",
    hint: "A place where doctors and nurses care for patients.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-3",
    word: "Park",
    hint: "A public outdoor place where people relax, walk, or play.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-4",
    word: "Library",
    hint: "A place where people can read or borrow books.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-5",
    word: "Restaurant",
    hint: "A place where people go to eat meals.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-6",
    word: "Hotel",
    hint: "A place where travelers stay for a short time.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-7",
    word: "Bank",
    hint: "A place where people keep, withdraw, or deposit money.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-8",
    word: "Airport",
    hint: "A place where airplanes take off and land.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-9",
    word: "Museum",
    hint: "A place where historical, artistic, or scientific objects are displayed.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-10",
    word: "Cinema",
    hint: "A place where people go to watch movies on a big screen.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-11",
    word: "Market",
    hint: "A place where people buy and sell different goods.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-12",
    word: "Supermarket",
    hint: "A large store where people buy food and household items.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-13",
    word: "Bakery",
    hint: "A place where bread, cakes, and pastries are made or sold.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-14",
    word: "Pharmacy",
    hint: "A place where people buy medicines and health products.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-15",
    word: "Zoo",
    hint: "A place where many different animals are kept for people to see.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-16",
    word: "Beach",
    hint: "A place beside the sea or ocean, often covered with sand.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-17",
    word: "Stadium",
    hint: "A large place where people watch sports and other events.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-18",
    word: "Playground",
    hint: "A place where children play on swings, slides, and other equipment.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-19",
    word: "Hotel",
    hint: "A building where visitors can rent a room while traveling.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-20",
    word: "Bridge",
    hint: "A structure that allows people or vehicles to cross over water or roads.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-places-21",
    word: "Train Station",
    hint: "A place where trains arrive, depart, and pick up passengers.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-22",
    word: "Bus Station",
    hint: "A place where buses arrive and leave for different destinations.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-23",
    word: "Post Office",
    hint: "A place where people send and receive letters and packages.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-24",
    word: "Police Station",
    hint: "A place where police officers work and handle reports and emergencies.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-25",
    word: "Fire Station",
    hint: "A place where firefighters and fire engines are based.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-26",
    word: "Shopping Mall",
    hint: "A large building containing many shops, restaurants, and services.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-27",
    word: "Amusement Park",
    hint: "A place with rides, games, and attractions for entertainment.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-28",
    word: "Art Gallery",
    hint: "A place where paintings, sculptures, and other artworks are displayed.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-29",
    word: "Theater",
    hint: "A place where people watch plays, performances, or live shows.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-30",
    word: "University",
    hint: "A place where students study advanced subjects after school.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-31",
    word: "Gym",
    hint: "A place where people exercise and work on their fitness.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-32",
    word: "Aquarium",
    hint: "A place where people can see fish and other aquatic animals.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-33",
    word: "Swimming Pool",
    hint: "A place filled with water where people go swimming.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-34",
    word: "Castle",
    hint: "A large fortified building where kings or nobles once lived.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-35",
    word: "Harbor",
    hint: "A sheltered place where ships and boats can dock safely.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-places-36",
    word: "Observatory",
    hint: "A place equipped for observing stars, planets, and other objects in space.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-37",
    word: "Amphitheater",
    hint: "A large open or partly open venue with seats arranged around a central area.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-38",
    word: "Cathedral",
    hint: "A large and important Christian church, usually associated with a bishop.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-39",
    word: "Monastery",
    hint: "A place where a community of monks lives and practices their religion.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-40",
    word: "Embassy",
    hint: "An official place representing one country in another country.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-41",
    word: "Courthouse",
    hint: "A place where legal cases are heard and decided.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-42",
    word: "Skyscraper",
    hint: "A very tall building with many floors, usually found in large cities.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-43",
    word: "Convention Center",
    hint: "A large venue where conferences, exhibitions, and major events are held.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-44",
    word: "Botanical Garden",
    hint: "A garden where many different kinds of plants are collected and displayed.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-45",
    word: "Historical Site",
    hint: "A place preserved because of its importance in history.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-46",
    word: "Fortress",
    hint: "A heavily protected building or place designed for defense.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-47",
    word: "Archaeological Site",
    hint: "A place where remains and objects from past civilizations are discovered.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-48",
    word: "Planetarium",
    hint: "A place where special equipment creates a realistic view of the night sky.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-49",
    word: "Port",
    hint: "A place on the coast where large ships load, unload, or stop.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-50",
    word: "Underground Station",
    hint: "A station below the ground where subway or metro trains stop.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-places-ur-1",
    word: "School",
    hint: "Ek jagah jahan students parhne ke liye jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-2",
    word: "Hospital",
    hint: "Ek jagah jahan doctors aur nurses mareezon ka ilaaj karte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-3",
    word: "Park",
    hint: "Ek khuli jagah jahan log sair, araam ya khel ke liye jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-4",
    word: "Library",
    hint: "Ek jagah jahan log kitabein parh ya udhaar le sakte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-5",
    word: "Restaurant",
    hint: "Ek jagah jahan log khana khane ke liye jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-6",
    word: "Hotel",
    hint: "Ek jagah jahan musafir kuch arsay ke liye rehte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-7",
    word: "Bank",
    hint: "Ek jagah jahan log paisay jama, nikal ya mehfooz rakhte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-8",
    word: "Airport",
    hint: "Ek jagah jahan airplanes urtay aur land karte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-9",
    word: "Museum",
    hint: "Ek jagah jahan tareekhi, funni ya science se related cheezen rakhi jati hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-10",
    word: "Cinema",
    hint: "Ek jagah jahan log bari screen par movies dekhne jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-11",
    word: "Market",
    hint: "Ek jagah jahan log mukhtalif cheezen khareedte aur bechte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-12",
    word: "Supermarket",
    hint: "Ek bara store jahan khanay peenay aur ghar ki cheezen milti hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-13",
    word: "Bakery",
    hint: "Ek jagah jahan bread, cakes aur pastries banaye ya beche jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-14",
    word: "Pharmacy",
    hint: "Ek jagah jahan medicines aur sehat se related cheezen milti hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-15",
    word: "Zoo",
    hint: "Ek jagah jahan log mukhtalif janwar dekhne jate hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-16",
    word: "Beach",
    hint: "Samandar ke kinare aik jagah jo aksar ret se dhaki hoti hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-17",
    word: "Stadium",
    hint: "Ek bari jagah jahan log sports aur doosre events dekhte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-18",
    word: "Playground",
    hint: "Ek jagah jahan bachay swings, slides aur doosri cheezon par khelte hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-19",
    word: "Hotel",
    hint: "Ek building jahan musafir safar ke dauran kamra kiraye par lete hain.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-20",
    word: "Bridge",
    hint: "Ek structure jo logon ya gaariyon ko pani ya road ke upar se guzarnay deta hai.",
    category: "places",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-places-ur-21",
    word: "Train Station",
    hint: "Ek jagah jahan trains aati, jati aur passengers ko sawar karti hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-22",
    word: "Bus Station",
    hint: "Ek jagah jahan buses mukhtalif jagahon ke liye aati aur rawana hoti hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-23",
    word: "Post Office",
    hint: "Ek jagah jahan log letters aur packages bhejte aur receive karte hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-24",
    word: "Police Station",
    hint: "Ek jagah jahan police officers kaam karte aur reports handle karte hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-25",
    word: "Fire Station",
    hint: "Ek jagah jahan firefighters aur fire engines mojood hoti hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-26",
    word: "Shopping Mall",
    hint: "Ek bari building jahan bohat si shops, restaurants aur services hoti hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-27",
    word: "Amusement Park",
    hint: "Ek jagah jahan rides, games aur tafreeh ke mukhtalif attractions hote hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-28",
    word: "Art Gallery",
    hint: "Ek jagah jahan paintings, sculptures aur doosre artworks display kiye jate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-29",
    word: "Theater",
    hint: "Ek jagah jahan log plays, performances aur live shows dekhte hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-30",
    word: "University",
    hint: "Ek jagah jahan students school ke baad advanced taleem hasil karte hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-31",
    word: "Gym",
    hint: "Ek jagah jahan log exercise aur fitness ke liye jate hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-32",
    word: "Aquarium",
    hint: "Ek jagah jahan log machhliyan aur doosre pani ke janwar dekhte hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-33",
    word: "Swimming Pool",
    hint: "Ek jagah jo pani se bhari hoti hai aur log wahan swimming karte hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-34",
    word: "Castle",
    hint: "Ek bara mazboot mahal jahan purane zamane mein badshah ya nawab rehte thay.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-35",
    word: "Harbor",
    hint: "Samandar ke kinare mehfooz jagah jahan ships aur boats rukti hain.",
    category: "places",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-places-ur-36",
    word: "Observatory",
    hint: "Ek jagah jahan sitaron, planets aur space ki doosri cheezon ka mushahida kiya jata hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-37",
    word: "Amphitheater",
    hint: "Ek bara venue jahan beech mein jagah aur uske gird darjon mein seats hoti hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-38",
    word: "Cathedral",
    hint: "Ek bari aur aham Christian church jo aam tor par bishop se related hoti hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-39",
    word: "Monastery",
    hint: "Ek jagah jahan monks ka aik group rehta aur ibadat karta hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-40",
    word: "Embassy",
    hint: "Ek official jagah jo kisi mulk ki doosre mulk mein numaindagi karti hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-41",
    word: "Courthouse",
    hint: "Ek jagah jahan qanooni muqadme sune aur faislay kiye jate hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-42",
    word: "Skyscraper",
    hint: "Ek bohat unchi building jisme bohat si manzilein hoti hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-43",
    word: "Convention Center",
    hint: "Ek bara venue jahan conferences, exhibitions aur bade events hote hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-44",
    word: "Botanical Garden",
    hint: "Ek garden jahan mukhtalif qisam ke poday jama karke display kiye jate hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-45",
    word: "Historical Site",
    hint: "Ek aisi jagah jo tareekh mein apni ahmiyat ki wajah se mehfooz rakhi jati hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-46",
    word: "Fortress",
    hint: "Ek bohat mazboot aur mehfooz jagah jo difa ke liye banayi jati hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-47",
    word: "Archaeological Site",
    hint: "Ek jagah jahan purani tehzeebon ke asaar aur cheezen daryaft hoti hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-48",
    word: "Planetarium",
    hint: "Ek jagah jahan special equipment se raat ke aasman ka manzar dikhaya jata hai.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-49",
    word: "Port",
    hint: "Samandar ke kinare aik jagah jahan bari ships saman load ya unload karti hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-places-ur-50",
    word: "Underground Station",
    hint: "Zameen ke neeche aik station jahan subway ya metro trains rukti hain.",
    category: "places",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
