import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "random-objects" category.
 *
 * English and Roman Urdu cover the exact same easy/medium/hard grid.
 * Roman Urdu keeps common object names in their familiar form;
 * only the hints are written in natural Roman Urdu.
 */
export const RANDOM_OBJECTS_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-random-objects-1",
    word: "Umbrella",
    hint: "An object used to stay dry when it rains.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-2",
    word: "Backpack",
    hint: "A bag carried on your back to hold personal items.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-3",
    word: "Phone",
    hint: "A small electronic device used to call and message people.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-4",
    word: "Wallet",
    hint: "A small case used to carry money and cards.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-5",
    word: "Key",
    hint: "A small object used to open or lock something.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-6",
    word: "Bottle",
    hint: "A container commonly used to hold liquids.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-7",
    word: "Book",
    hint: "A group of pages containing words, pictures, or information.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-8",
    word: "Pencil",
    hint: "A writing tool that leaves marks using a graphite core.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-9",
    word: "Pen",
    hint: "A writing tool that uses ink to make marks.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-10",
    word: "Watch",
    hint: "A small device worn on the wrist that shows the time.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-11",
    word: "Glasses",
    hint: "An object worn on the face to help improve vision.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-12",
    word: "Chair",
    hint: "A piece of furniture designed for one person to sit on.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-13",
    word: "Pillow",
    hint: "A soft object placed under your head while sleeping.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-14",
    word: "Mirror",
    hint: "A smooth surface that reflects your image.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-15",
    word: "Clock",
    hint: "An object that shows the current time.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-16",
    word: "Scissors",
    hint: "A tool with two blades used for cutting things.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-17",
    word: "Flashlight",
    hint: "A small portable device that produces light.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-18",
    word: "Candle",
    hint: "An object made of wax that produces light when burned.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-19",
    word: "Comb",
    hint: "An object with narrow teeth used to arrange hair.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-20",
    word: "Toothbrush",
    hint: "A small brush used to clean your teeth.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-random-objects-21",
    word: "Compass",
    hint: "A tool used to find direction, especially north.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-22",
    word: "Hourglass",
    hint: "A timer that measures time using sand falling through a narrow opening.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-23",
    word: "Thermometer",
    hint: "An instrument used to measure temperature.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-24",
    word: "Binoculars",
    hint: "An optical device used to see distant objects more clearly.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-25",
    word: "Stapler",
    hint: "A small tool used to fasten sheets of paper together with staples.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-26",
    word: "Calculator",
    hint: "An electronic device used to perform mathematical calculations.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-27",
    word: "Headphones",
    hint: "A device worn over or in the ears for listening to sound.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-28",
    word: "Remote Control",
    hint: "A handheld device used to operate another electronic device from a distance.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-29",
    word: "Thermos",
    hint: "A container designed to keep drinks hot or cold for a long time.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-30",
    word: "Magnifying Glass",
    hint: "A lens that makes small objects appear larger.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-31",
    word: "Tape Measure",
    hint: "A flexible tool used to measure length or distance.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-32",
    word: "Screwdriver",
    hint: "A tool used to tighten or loosen screws.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-33",
    word: "Hammer",
    hint: "A tool with a heavy head used for hitting nails and other objects.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-34",
    word: "Pliers",
    hint: "A handheld tool used to grip, bend, or cut materials.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-35",
    word: "Glue Gun",
    hint: "A tool that heats and applies sticks of adhesive.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-random-objects-36",
    word: "Kaleidoscope",
    hint: "A tube that creates changing patterns using mirrors and colored pieces.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-37",
    word: "Metronome",
    hint: "A device that produces regular beats to help keep musical time.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-38",
    word: "Gyroscope",
    hint: "A device that uses a spinning wheel to help measure or maintain orientation.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-39",
    word: "Periscope",
    hint: "An optical instrument that lets someone see objects from a hidden or lower position.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-40",
    word: "Stethoscope",
    hint: "An instrument doctors use to listen to sounds inside the body.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-41",
    word: "Pendulum",
    hint: "A weighted object that swings back and forth from a fixed point.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-42",
    word: "Sundial",
    hint: "An object that uses the position of the sun's shadow to tell time.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-43",
    word: "Abacus",
    hint: "A counting device made with rows of movable beads.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-44",
    word: "Hour Counter",
    hint: "A device designed to record how many hours a machine or activity has been operating.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-45",
    word: "Tuning Fork",
    hint: "A metal instrument that produces a specific musical pitch when struck.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-46",
    word: "Mortar and Pestle",
    hint: "A bowl and heavy tool used together to crush and grind materials.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-47",
    word: "Typewriter",
    hint: "A mechanical or electronic machine used to produce text on paper.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-48",
    word: "Vinyl Record",
    hint: "A flat disc that stores recorded sound in grooves and is played on a turntable.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-49",
    word: "Pocket Watch",
    hint: "A small clock designed to be carried in a pocket.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-50",
    word: "Mechanical Pencil",
    hint: "A pencil that uses a thin replaceable graphite lead instead of being sharpened.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-random-objects-ur-1",
    word: "Umbrella",
    hint: "Barish mein khud ko geela hone se bachane ke liye istemal hoti hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-2",
    word: "Backpack",
    hint: "Ek bag jo peeth par uthaya jata hai aur is mein samaan rakha jata hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-3",
    word: "Phone",
    hint: "Ek chhota electronic device jo call aur messages ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-4",
    word: "Wallet",
    hint: "Ek chhota purse jisme paisay aur cards rakhe jate hain.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-5",
    word: "Key",
    hint: "Ek chhoti cheez jo kisi cheez ko kholne ya lock karne ke liye istemal hoti hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-6",
    word: "Bottle",
    hint: "Ek container jisme aam tor par liquids rakhe jate hain.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-7",
    word: "Book",
    hint: "Kaghaz ke pages ka majmua jisme alfaaz, tasaveer ya maloomat hoti hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-8",
    word: "Pencil",
    hint: "Ek likhne ka tool jo graphite ki madad se nishan banata hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-9",
    word: "Pen",
    hint: "Ek likhne ka tool jo ink se nishan banata hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-10",
    word: "Watch",
    hint: "Ek chhoti device jo kalai par pehni jati hai aur waqt batati hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-11",
    word: "Glasses",
    hint: "Ek cheez jo aankhon par pehni jati hai taake dekhne mein madad mile.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-12",
    word: "Chair",
    hint: "Furniture ki aik cheez jis par aik shakhs baithta hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-13",
    word: "Pillow",
    hint: "Ek naram cheez jo sotay waqt sar ke neeche rakhi jati hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-14",
    word: "Mirror",
    hint: "Ek chikni satah jo aapki soorat ka aks dikhati hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-15",
    word: "Clock",
    hint: "Ek cheez jo waqt batati hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-16",
    word: "Scissors",
    hint: "Do blades wala tool jo cheezen kaatne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-17",
    word: "Flashlight",
    hint: "Ek chhoti portable device jo roshni paida karti hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-18",
    word: "Candle",
    hint: "Mom ki bani hui cheez jo jalne par roshni deti hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-19",
    word: "Comb",
    hint: "Danton jaisi cheezon wala object jo baal theek karne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-20",
    word: "Toothbrush",
    hint: "Ek chhota brush jo daant saaf karne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-random-objects-ur-21",
    word: "Compass",
    hint: "Ek tool jo simt ka pata lagane ke liye istemal hota hai, khaas taur par north ka.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-22",
    word: "Hourglass",
    hint: "Ek timer jo patli jagah se girti hui rait ke zariye waqt naapta hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-23",
    word: "Thermometer",
    hint: "Ek instrument jo temperature naapne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-24",
    word: "Binoculars",
    hint: "Ek optical device jo door ki cheezon ko qareeb aur saaf dekhne mein madad karti hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-25",
    word: "Stapler",
    hint: "Ek chhota tool jo kaghaz ke pages ko staples se jorne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-26",
    word: "Calculator",
    hint: "Ek electronic device jo hisaab kitab karne ke liye istemal hoti hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-27",
    word: "Headphones",
    hint: "Ek device jo kaanon par ya kaanon mein pehni jati hai aur sound sunne ke liye hoti hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-28",
    word: "Remote Control",
    hint: "Ek handheld device jo door se kisi electronic device ko control karne ke liye hoti hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-29",
    word: "Thermos",
    hint: "Ek container jo drinks ko lambi dair tak garam ya thanda rakhta hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-30",
    word: "Magnifying Glass",
    hint: "Ek lens jo chhoti cheezon ko bara dikhata hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-31",
    word: "Tape Measure",
    hint: "Ek lachila tool jo lambai ya faasla naapne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-32",
    word: "Screwdriver",
    hint: "Ek tool jo screws ko tight ya loose karne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-33",
    word: "Hammer",
    hint: "Ek tool jiske bhaari siray se nails aur doosri cheezon par maara jata hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-34",
    word: "Pliers",
    hint: "Ek handheld tool jo cheezon ko pakarne, morne ya kaatne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-35",
    word: "Glue Gun",
    hint: "Ek tool jo glue sticks ko garam karke adhesive lagata hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-random-objects-ur-36",
    word: "Kaleidoscope",
    hint: "Ek tube jo mirrors aur rang birangi cheezon ki madad se badalte hue patterns banati hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-37",
    word: "Metronome",
    hint: "Ek device jo music ka waqt barqarar rakhne ke liye regular beats deta hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-38",
    word: "Gyroscope",
    hint: "Ek device jo ghoomte hue wheel ki madad se direction ya position ko naapne ya barqarar rakhne mein madad karti hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-39",
    word: "Periscope",
    hint: "Ek optical instrument jo chhupi ya neeche wali jagah se door ki cheez dekhne mein madad karta hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-40",
    word: "Stethoscope",
    hint: "Ek instrument jo doctors jism ke andar ki awaazein sunne ke liye istemal karte hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-41",
    word: "Pendulum",
    hint: "Ek bhaari cheez jo aik fixed point se aage peeche jhoolti rehti hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-42",
    word: "Sundial",
    hint: "Ek object jo suraj ke saaye ki position se waqt batata hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-43",
    word: "Abacus",
    hint: "Ginti karne ka aik tool jo hilne wale motiyon ki rows par mushtamil hota hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-44",
    word: "Hour Counter",
    hint: "Ek device jo record karti hai ke machine ya activity kitne ghante chali hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-45",
    word: "Tuning Fork",
    hint: "Ek dhati instrument jo hit karne par aik khaas musical awaaz paida karta hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-46",
    word: "Mortar and Pestle",
    hint: "Ek bowl aur bhaari tool ka jora jo cheezon ko peesne aur kuchalne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-47",
    word: "Typewriter",
    hint: "Ek mechanical ya electronic machine jo kaghaz par text likhne ke liye istemal hoti hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-48",
    word: "Vinyl Record",
    hint: "Ek flat disc jisme grooves ke andar recorded sound hoti hai aur jo turntable par chalti hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-49",
    word: "Pocket Watch",
    hint: "Ek chhoti ghari jo pocket mein rakhne ke liye banayi jati hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-50",
    word: "Mechanical Pencil",
    hint: "Ek pencil jisme patli replaceable graphite lead hoti hai aur isay sharpen nahi karna parta.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
