import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "sports" category.
 *
 * English and Roman Urdu cover the exact same easy/medium/hard grid.
 * Roman Urdu keeps common sport names in their familiar form;
 * only the hints are written in natural Roman Urdu.
 */
export const SPORTS_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-sports-1",
    word: "Football",
    hint: "A team sport where players try to kick a ball into the opponent's goal.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-2",
    word: "Basketball",
    hint: "A game where players try to throw a ball through a high hoop.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-3",
    word: "Cricket",
    hint: "A bat-and-ball game played between two teams.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-4",
    word: "Tennis",
    hint: "A racket sport played over a net with a small ball.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-5",
    word: "Badminton",
    hint: "A racket sport played with a lightweight shuttlecock.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-6",
    word: "Hockey",
    hint: "A sport played with sticks and a ball or puck.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-7",
    word: "Volleyball",
    hint: "A team game where players hit a ball over a net.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-8",
    word: "Swimming",
    hint: "A sport where people race through water using their arms and legs.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-9",
    word: "Boxing",
    hint: "A combat sport where two competitors fight using padded gloves.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-10",
    word: "Golf",
    hint: "A sport where players hit a small ball toward a series of holes.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-11",
    word: "Baseball",
    hint: "A bat-and-ball game where players run around four bases.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-12",
    word: "Running",
    hint: "A sport based on moving quickly on foot over a set distance.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-13",
    word: "Cycling",
    hint: "A sport where people race or ride bicycles.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-14",
    word: "Wrestling",
    hint: "A combat sport involving grappling, holds, and throws.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-15",
    word: "Skiing",
    hint: "A winter sport where people slide over snow using long skis.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-16",
    word: "Bowling",
    hint: "A sport where a heavy ball is rolled toward pins.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-17",
    word: "Table Tennis",
    hint: "A fast racket game played on a table divided by a net.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-18",
    word: "Skateboarding",
    hint: "A sport performed while riding and doing tricks on a board with wheels.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-19",
    word: "Surfing",
    hint: "A water sport where people ride waves on a board.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-20",
    word: "Gymnastics",
    hint: "A sport involving strength, balance, flexibility, and controlled movements.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-sports-21",
    word: "Archery",
    hint: "A sport where competitors shoot arrows at a target using a bow.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-22",
    word: "Boxing",
    hint: "Competitors use punches and defensive movements while wearing gloves.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-23",
    word: "Fencing",
    hint: "A combat sport where competitors score points using specialized swords.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-24",
    word: "Judo",
    hint: "A martial art that focuses on throws, holds, and using an opponent's force.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-25",
    word: "Karate",
    hint: "A martial art that uses punches, kicks, blocks, and defensive techniques.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-26",
    word: "Kabaddi",
    hint: "A team sport where a raider enters the opposing side and tries to tag players.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-27",
    word: "Handball",
    hint: "A team game where players pass and throw a ball into a goal.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-28",
    word: "Rugby",
    hint: "A team sport where players carry, pass, and kick an oval-shaped ball.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-29",
    word: "Squash",
    hint: "A racket sport where players hit a ball against the walls of a court.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-30",
    word: "Diving",
    hint: "A sport where athletes jump or fall into water while performing controlled movements.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-31",
    word: "Rowing",
    hint: "A sport where athletes propel a boat through water using oars.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-32",
    word: "Equestrian",
    hint: "A group of sports that involve riding and competing with horses.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-33",
    word: "Taekwondo",
    hint: "A Korean martial art especially known for powerful kicking techniques.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-34",
    word: "Weightlifting",
    hint: "A strength sport where athletes lift heavy weights in controlled movements.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-35",
    word: "Water Polo",
    hint: "A team sport played in a swimming pool where players try to score goals.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-sports-36",
    word: "Curling",
    hint: "Players slide heavy stones across ice while teammates sweep the surface.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-37",
    word: "Sumo",
    hint: "Japanese wrestlers try to force each other outside a circular ring.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-38",
    word: "Fencing",
    hint: "A precision combat sport using foil, épée, or sabre.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-39",
    word: "Triathlon",
    hint: "An endurance event combining swimming, cycling, and running.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-40",
    word: "Decathlon",
    hint: "A track and field competition consisting of ten different events.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-41",
    word: "Pentathlon",
    hint: "A multi-event competition traditionally combining five different disciplines.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-42",
    word: "Bobsleigh",
    hint: "Teams race down an icy track inside a streamlined sled.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-43",
    word: "Biathlon",
    hint: "A winter sport combining cross-country skiing and rifle shooting.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-44",
    word: "Lacrosse",
    hint: "Players use a stick with a netted head to carry and throw a ball.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-45",
    word: "Polo",
    hint: "A team sport where players on horseback use long mallets to hit a ball.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-46",
    word: "Futsal",
    hint: "A fast indoor version of football played on a smaller court.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-47",
    word: "Sport Climbing",
    hint: "Athletes climb specially designed walls while racing or testing their technique.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-48",
    word: "Sailing",
    hint: "A sport where competitors use wind-powered boats to race across water.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-49",
    word: "Modern Pentathlon",
    hint: "A multi-sport event combining fencing, swimming, equestrian, and running-shooting disciplines.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-50",
    word: "Trampolining",
    hint: "A gymnastics discipline where athletes perform controlled movements while bouncing on a trampoline.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-sports-ur-1",
    word: "Football",
    hint: "Is game mein players ball ko kick karke doosri team ke goal mein dalne ki koshish karte hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-2",
    word: "Basketball",
    hint: "Is game mein players ball ko oonchay hoop mein dalne ki koshish karte hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-3",
    word: "Cricket",
    hint: "Do teams ke darmiyan bat aur ball se khela jane wala game hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-4",
    word: "Tennis",
    hint: "Chhoti ball ko racket se net ke upar se maar kar khela jata hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-5",
    word: "Badminton",
    hint: "Racket se halka shuttlecock net ke upar se maara jata hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-6",
    word: "Hockey",
    hint: "Is sport mein sticks aur ball ya puck ka istemal hota hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-7",
    word: "Volleyball",
    hint: "Team game jisme players ball ko net ke upar se maarte hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-8",
    word: "Swimming",
    hint: "Pani mein arms aur legs ki madad se race ki jati hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-9",
    word: "Boxing",
    hint: "Do players gloves pehen kar aik doosre ke khilaf punches lagate hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-10",
    word: "Golf",
    hint: "Is game mein chhoti ball ko clubs se holes mein pahunchaya jata hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-11",
    word: "Baseball",
    hint: "Bat aur ball ka game jisme players chaar bases ke gird run karte hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-12",
    word: "Running",
    hint: "Pairon par aik muqarrar faaslay tak tezi se daurna is sport ka hissa hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-13",
    word: "Cycling",
    hint: "Is sport mein log bicycle chala kar race ya riding karte hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-14",
    word: "Wrestling",
    hint: "Is combat sport mein pakarna, girana aur holds lagana shamil hota hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-15",
    word: "Skiing",
    hint: "Baraf par lambi skis ki madad se slide karne wala winter sport hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-16",
    word: "Bowling",
    hint: "Ek bhaari ball ko pins ki taraf roll kiya jata hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-17",
    word: "Table Tennis",
    hint: "Table par net ke dono taraf racket se khela jane wala tez game hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-18",
    word: "Skateboarding",
    hint: "Wheels wale board par sawar hokar tricks karne wala sport hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-19",
    word: "Surfing",
    hint: "Samundar ki lehron par board ki madad se ride ki jati hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-20",
    word: "Gymnastics",
    hint: "Is sport mein strength, balance, flexibility aur controlled movements zaroori hote hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-sports-ur-21",
    word: "Archery",
    hint: "Bow ki madad se arrows ko target par maarne wala sport hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-22",
    word: "Boxing",
    hint: "Players gloves pehen kar punches aur defensive movements ka istemal karte hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-23",
    word: "Fencing",
    hint: "Aik combat sport jisme players khaas talwaron se points score karte hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-24",
    word: "Judo",
    hint: "Aik martial art jisme throws, holds aur opponent ki force ka istemal hota hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-25",
    word: "Karate",
    hint: "Aik martial art jisme punches, kicks aur blocks ka istemal hota hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-26",
    word: "Kabaddi",
    hint: "Aik team sport jisme raider doosri team ke area mein ja kar players ko touch karta hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-27",
    word: "Handball",
    hint: "Team game jisme players ball pass karke goal mein throw karte hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-28",
    word: "Rugby",
    hint: "Team sport jisme oval shape ki ball ko carry, pass aur kick kiya jata hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-29",
    word: "Squash",
    hint: "Racket sport jisme ball ko court ki deewaron par maara jata hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-30",
    word: "Diving",
    hint: "Pani mein jump ya dive karte waqt controlled movements ki jati hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-31",
    word: "Rowing",
    hint: "Oars ki madad se boat ko pani mein aage chalane wala sport hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-32",
    word: "Equestrian",
    hint: "Aise sports ka group jisme ghore par sawari karke competitions hoti hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-33",
    word: "Taekwondo",
    hint: "Korean martial art jo khaas taur par powerful kicks ke liye mashhoor hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-34",
    word: "Weightlifting",
    hint: "Strength ka sport jisme athletes bhaari weights ko controlled tareeqe se uthate hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-35",
    word: "Water Polo",
    hint: "Swimming pool mein khela jane wala team sport jisme goal score kiye jate hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-sports-ur-36",
    word: "Curling",
    hint: "Players baraf par bhaari stones slide karte hain aur teammates surface ko sweep karte hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-37",
    word: "Sumo",
    hint: "Japanese wrestlers aik doosre ko gol ring se bahar nikalne ki koshish karte hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-38",
    word: "Fencing",
    hint: "Aik precise combat sport jisme foil, epee ya sabre ka istemal hota hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-39",
    word: "Triathlon",
    hint: "Aik endurance event jisme swimming, cycling aur running teenon shamil hote hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-40",
    word: "Decathlon",
    hint: "Track aur field ki competition jisme das mukhtalif events hote hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-41",
    word: "Pentathlon",
    hint: "Aik multi-event competition jisme aam tor par paanch mukhtalif disciplines hoti hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-42",
    word: "Bobsleigh",
    hint: "Teams baraf ki track par aik khaas sled mein race karti hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-43",
    word: "Biathlon",
    hint: "Winter sport jisme cross-country skiing aur rifle shooting dono shamil hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-44",
    word: "Lacrosse",
    hint: "Players net wali stick se ball ko carry aur throw karte hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-45",
    word: "Polo",
    hint: "Ghoron par sawar players lambi mallets se ball ko hit karte hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-46",
    word: "Futsal",
    hint: "Football ka aik fast indoor version jo chhoti court par khela jata hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-47",
    word: "Sport Climbing",
    hint: "Athletes specially designed walls par chadhte hain aur speed ya technique test karte hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-48",
    word: "Sailing",
    hint: "Hawa se chalne wali boats ko use karke pani par race ki jati hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-49",
    word: "Modern Pentathlon",
    hint: "Aik multi-sport event jisme fencing, swimming, equestrian aur running-shooting disciplines shamil hoti hain.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-50",
    word: "Trampolining",
    hint: "Gymnastics ki aik discipline jisme athlete trampoline par uchal kar controlled movements karta hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
