import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "technology" category.
 *
 * English and Roman Urdu cover the exact same easy/medium/hard grid.
 * Roman Urdu keeps common technology terms in their familiar form;
 * only the hints are written in natural Roman Urdu.
 */
export const TECHNOLOGY_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-technology-1",
    word: "Computer",
    hint: "A machine used to process information and run programs.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-2",
    word: "Keyboard",
    hint: "A device with keys used for typing.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-3",
    word: "Mouse",
    hint: "A small device used to move a pointer and select things on a computer.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-4",
    word: "Monitor",
    hint: "A screen that displays information from a computer.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-5",
    word: "Printer",
    hint: "A device that puts digital documents or pictures onto paper.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-6",
    word: "Laptop",
    hint: "A portable computer that can be used without a desk.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-7",
    word: "Smartphone",
    hint: "A pocket-sized device used for calls, apps, and the internet.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-8",
    word: "Tablet",
    hint: "A portable touchscreen device larger than most phones.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-9",
    word: "Camera",
    hint: "A device used to capture photos and videos.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-10",
    word: "Battery",
    hint: "A device that stores energy to power electronic equipment.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-11",
    word: "Internet",
    hint: "A worldwide network that connects computers and other devices.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-12",
    word: "Website",
    hint: "A collection of pages that can be accessed on the internet.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-13",
    word: "App",
    hint: "A software program designed to perform a specific task on a device.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-14",
    word: "Wi-Fi",
    hint: "A wireless technology used to connect devices to a network.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-15",
    word: "USB",
    hint: "A common connection used to transfer data or connect electronic devices.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-technology-16",
    word: "Bluetooth",
    hint: "A short-range wireless technology for connecting devices.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-17",
    word: "Router",
    hint: "A device that directs network traffic and connects devices to a network.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-18",
    word: "Browser",
    hint: "Software used to open and view websites on the internet.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-19",
    word: "Database",
    hint: "An organized collection of information that can be stored and searched.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-20",
    word: "Server",
    hint: "A computer or system that provides data or services to other devices.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-21",
    word: "Cloud",
    hint: "Remote computers and storage that can be accessed through the internet.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-22",
    word: "GPS",
    hint: "A system used to determine the location of a device on Earth.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-23",
    word: "QR Code",
    hint: "A square pattern that can be scanned to quickly access digital information.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-24",
    word: "Webcam",
    hint: "A camera designed to capture video for a computer or online communication.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-25",
    word: "Microphone",
    hint: "A device that captures sound and converts it into an electronic signal.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-26",
    word: "Touchscreen",
    hint: "A display that lets users control a device by touching the screen.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-27",
    word: "Operating System",
    hint: "Software that manages a device's hardware and allows other programs to run.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-28",
    word: "Processor",
    hint: "The component that carries out instructions and performs calculations.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-29",
    word: "RAM",
    hint: "Temporary memory used by a device while programs are running.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-30",
    word: "Firewall",
    hint: "A security system that helps block unauthorized network access.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-technology-31",
    word: "Algorithm",
    hint: "A step-by-step method used to solve a problem or complete a task.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-32",
    word: "Encryption",
    hint: "A method of protecting information by converting it into a coded form.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-33",
    word: "Artificial Intelligence",
    hint: "Technology that enables machines to perform tasks that normally require human intelligence.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-34",
    word: "Blockchain",
    hint: "A distributed digital record that stores information in linked blocks.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-35",
    word: "Cybersecurity",
    hint: "The practice of protecting computers, networks, and data from digital threats.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-36",
    word: "Malware",
    hint: "Software designed to damage, disrupt, or gain unauthorized access to a system.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-37",
    word: "Phishing",
    hint: "A scam that tricks people into revealing sensitive information through fake messages or websites.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-38",
    word: "Cloud Computing",
    hint: "Using remote internet-based computers to provide storage, software, or processing power.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-39",
    word: "Virtual Reality",
    hint: "Technology that creates a computer-generated environment that users can interact with.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-40",
    word: "Machine Learning",
    hint: "A method where computers learn patterns from data instead of being given every rule directly.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-41",
    word: "API",
    hint: "A set of rules that allows different software systems to communicate with each other.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-42",
    word: "Database",
    hint: "A structured system used to store, organize, and retrieve large amounts of information.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-43",
    word: "Authentication",
    hint: "The process of verifying that a user or device is really who or what it claims to be.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-44",
    word: "Two-Factor Authentication",
    hint: "A security method that requires two different forms of verification to access an account.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-45",
    word: "Virtual Machine",
    hint: "A software-based computer that runs inside another physical computer.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-technology-ur-1",
    word: "Computer",
    hint: "Ek machine jo maloomat process karti hai aur programs chalati hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-2",
    word: "Keyboard",
    hint: "Ek device jis par keys hoti hain aur typing ki jati hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-3",
    word: "Mouse",
    hint: "Ek chhota device jo computer par pointer move aur cheezen select karne ke liye hota hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-4",
    word: "Monitor",
    hint: "Ek screen jo computer ki information dikhati hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-5",
    word: "Printer",
    hint: "Ek device jo digital documents ya pictures ko paper par print karta hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-6",
    word: "Laptop",
    hint: "Ek portable computer jo asani se kahin bhi use kiya ja sakta hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-7",
    word: "Smartphone",
    hint: "Jeb mein rakha jane wala device jo calls, apps aur internet ke liye hota hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-8",
    word: "Tablet",
    hint: "Ek portable touchscreen device jo aam phone se bara hota hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-9",
    word: "Camera",
    hint: "Ek device jo photos aur videos banane ke liye istemal hota hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-10",
    word: "Battery",
    hint: "Ek device jo electronic cheezon ko power dene ke liye energy store karti hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-11",
    word: "Internet",
    hint: "Duniya bhar ka network jo computers aur doosre devices ko connect karta hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-12",
    word: "Website",
    hint: "Pages ka aik collection jo internet par access kiya ja sakta hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-13",
    word: "App",
    hint: "Ek software program jo device par kisi khaas kaam ke liye hota hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-14",
    word: "Wi-Fi",
    hint: "Ek wireless technology jo devices ko network se connect karti hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-15",
    word: "USB",
    hint: "Ek common connection jo data transfer ya devices connect karne ke liye use hota hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-technology-ur-16",
    word: "Bluetooth",
    hint: "Ek short-range wireless technology jo qareeb devices ko connect karti hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-17",
    word: "Router",
    hint: "Ek device jo network traffic ko direct karta hai aur devices ko network se connect karta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-18",
    word: "Browser",
    hint: "Ek software jo internet par websites kholne aur dekhne ke liye use hota hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-19",
    word: "Database",
    hint: "Maloomat ka aik munazzam collection jo store aur search kiya ja sakta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-20",
    word: "Server",
    hint: "Ek computer ya system jo doosre devices ko data ya services provide karta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-21",
    word: "Cloud",
    hint: "Internet ke zariye access kiye jane wale remote computers aur storage.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-22",
    word: "GPS",
    hint: "Ek system jo zameen par device ki location maloom karne ke liye use hota hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-23",
    word: "QR Code",
    hint: "Aik square pattern jise scan karke digital information tak jaldi pohancha ja sakta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-24",
    word: "Webcam",
    hint: "Ek camera jo computer ya online communication ke liye video banata hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-25",
    word: "Microphone",
    hint: "Ek device jo awaaz ko capture karke electronic signal mein badalta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-26",
    word: "Touchscreen",
    hint: "Ek display jise screen ko touch karke control kiya ja sakta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-27",
    word: "Operating System",
    hint: "Software jo device ke hardware ko manage karta hai aur doosre programs chalata hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-28",
    word: "Processor",
    hint: "Computer ka woh component jo instructions ko process aur calculations karta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-29",
    word: "RAM",
    hint: "Temporary memory jo programs chalne ke waqt device use karta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-30",
    word: "Firewall",
    hint: "Ek security system jo ghair-majaz network access ko rokne mein madad karta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-technology-ur-31",
    word: "Algorithm",
    hint: "Kisi maslay ko hal karne ya kaam mukammal karne ke liye steps ka tareeqa.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-32",
    word: "Encryption",
    hint: "Maloomat ko coded form mein badal kar mehfooz rakhne ka tareeqa.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-33",
    word: "Artificial Intelligence",
    hint: "Aisi technology jo machines ko insani aqal wale kaam karne ke qabil banati hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-34",
    word: "Blockchain",
    hint: "Aik distributed digital record jo maloomat ko linked blocks mein store karta hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-35",
    word: "Cybersecurity",
    hint: "Computers, networks aur data ko digital threats se mehfooz rakhne ka amal.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-36",
    word: "Malware",
    hint: "Aisa software jo system ko nuqsan pohanchane ya ghair-majaz access hasil karne ke liye banaya jata hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-37",
    word: "Phishing",
    hint: "Aik fraud jisme fake messages ya websites ke zariye logon se sensitive information hasil ki jati hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-38",
    word: "Cloud Computing",
    hint: "Internet par maujood remote computers se storage, software ya processing power hasil karna.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-39",
    word: "Virtual Reality",
    hint: "Aisi technology jo computer se banaya gaya aik environment create karti hai jisme user interact kar sakta hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-40",
    word: "Machine Learning",
    hint: "Aisa tareeqa jisme computers data se patterns seekhte hain bina har rule manually bataye.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-41",
    word: "API",
    hint: "Rules ka aik set jo different software systems ko aik doosre se communicate karne deta hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-42",
    word: "Database",
    hint: "Aik structured system jo bohat sari maloomat ko store, organize aur retrieve karta hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-43",
    word: "Authentication",
    hint: "User ya device ki asli pehchan verify karne ka process.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-44",
    word: "Two-Factor Authentication",
    hint: "Security ka tareeqa jisme account access karne ke liye do mukhtalif verification methods chahiye hote hain.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-45",
    word: "Virtual Machine",
    hint: "Aik software-based computer jo kisi doosre physical computer ke andar run hota hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
