import type { FallbackWordEntry } from "./types";

/**
 * TIER 3 static fallback entries for the "vehicles" category (see
 * ./index.ts for the combined TIER 3 pipeline this feeds into).
 *
 * English and Roman Urdu cover the exact same easy/medium/hard grid.
 * Roman Urdu keeps common vehicle names in their familiar form;
 * only the hints are written in natural Roman Urdu.
 */
export const VEHICLES_FALLBACK_WORDS: FallbackWordEntry[] = [
  // ---------------------------------------------------------------
  // English
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-vehicles-1",
    word: "Car",
    hint: "A common road vehicle used to carry people.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-2",
    word: "Bus",
    hint: "A large road vehicle that carries many passengers.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-3",
    word: "Bicycle",
    hint: "You balance and pedal to keep it moving.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-4",
    word: "Motorcycle",
    hint: "A two-wheeled vehicle powered by an engine.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-5",
    word: "Train",
    hint: "It travels along tracks and can carry many passengers.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-6",
    word: "Airplane",
    hint: "It flies through the sky using wings and engines.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-7",
    word: "Helicopter",
    hint: "It can hover in place using spinning blades.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-8",
    word: "Boat",
    hint: "It travels on water and can carry people or goods.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-9",
    word: "Truck",
    hint: "A large road vehicle commonly used to carry goods.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-10",
    word: "Van",
    hint: "A box-shaped vehicle often used to carry people or cargo.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-11",
    word: "Taxi",
    hint: "A vehicle that carries passengers for a fare.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-12",
    word: "Scooter",
    hint: "A small two-wheeled vehicle that is easy to ride around town.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-13",
    word: "Ambulance",
    hint: "A vehicle used to transport sick or injured people.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-14",
    word: "Tractor",
    hint: "A farm vehicle built for pulling heavy equipment.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-15",
    word: "Rickshaw",
    hint: "A small passenger vehicle commonly used for short trips.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },

  // Medium
  {
    id: "fallback-vehicles-16",
    word: "Submarine",
    hint: "Built to travel far below the surface of the water.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-17",
    word: "Ferry",
    hint: "A boat or ship that carries people or vehicles across water.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-18",
    word: "Yacht",
    hint: "A private boat often used for leisure and luxury trips.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-19",
    word: "Tram",
    hint: "A passenger vehicle that usually runs on rails through a city.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-20",
    word: "Metro",
    hint: "A city train system that often travels underground.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-21",
    word: "Bulldozer",
    hint: "A powerful vehicle with a large blade used to push earth and rubble.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-22",
    word: "Forklift",
    hint: "A vehicle with lifting forks used to move heavy loads.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-23",
    word: "Canoe",
    hint: "A narrow boat usually moved with a paddle.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-24",
    word: "Kayak",
    hint: "A small narrow boat usually controlled with a double-bladed paddle.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-25",
    word: "Jet Ski",
    hint: "A small motorized vehicle designed to travel across water.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-26",
    word: "Hovercraft",
    hint: "It moves over land or water on a cushion of air.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-27",
    word: "Glider",
    hint: "An aircraft that flies without a traditional engine.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-28",
    word: "Drone",
    hint: "A flying vehicle that can be controlled remotely without a pilot inside.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-29",
    word: "Cable Car",
    hint: "A passenger vehicle pulled along by a cable, often in hilly areas.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-30",
    word: "Monorail",
    hint: "A train that travels along a single rail.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },

  // Hard
  {
    id: "fallback-vehicles-31",
    word: "Gondola",
    hint: "A long narrow boat traditionally guided through canals with one oar.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-32",
    word: "Zeppelin",
    hint: "A large rigid airship once used for passenger travel.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-33",
    word: "Catamaran",
    hint: "A boat with two parallel hulls joined together.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-34",
    word: "Hoverboard",
    hint: "A small personal vehicle that appears to glide while the rider stands on it.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-35",
    word: "Snowmobile",
    hint: "A motorized vehicle designed to travel across snow.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-36",
    word: "Amphibious Vehicle",
    hint: "A vehicle designed to travel both on land and through water.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-37",
    word: "Airship",
    hint: "A powered aircraft that stays in the air using a large gas-filled body.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-38",
    word: "Seaplane",
    hint: "An airplane designed to take off from and land on water.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-39",
    word: "Spacecraft",
    hint: "A vehicle designed to travel beyond Earth's atmosphere.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-40",
    word: "Rocket",
    hint: "A vehicle powered by engines that can carry payloads into space.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-41",
    word: "Icebreaker",
    hint: "A powerful ship built to break through thick ice.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-42",
    word: "Catapult Aircraft",
    hint: "An aircraft launched from a ship using a special launching system.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-43",
    word: "Tugboat",
    hint: "A small powerful boat used to push or pull larger ships.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-44",
    word: "Funicular",
    hint: "A railway vehicle that travels up and down steep slopes using cables.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-45",
    word: "Maglev",
    hint: "A train that uses magnetic forces to reduce contact with the track.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },

  // ---------------------------------------------------------------
  // Roman Urdu
  // ---------------------------------------------------------------

  // Easy
  {
    id: "fallback-vehicles-ur-1",
    word: "Car",
    hint: "Ek aam sawari jo logon ko road par le jane ke liye use hoti hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-2",
    word: "Bus",
    hint: "Ek bari sawari jo bohat se passengers ko le kar jati hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-3",
    word: "Bicycle",
    hint: "Do pahiye wali sawari jise balance bana kar pedal se chalate hain.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-4",
    word: "Motorcycle",
    hint: "Do pahiyon wali sawari jo engine se chalti hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-5",
    word: "Train",
    hint: "Yeh tracks par chalti hai aur bohat se passengers ko le ja sakti hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-6",
    word: "Airplane",
    hint: "Yeh paron aur engines ki madad se aasman mein urta hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-7",
    word: "Helicopter",
    hint: "Ghoomte hue blades ki madad se ek hi jagah hawa mein ruk sakta hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-8",
    word: "Boat",
    hint: "Yeh pani par chalti hai aur logon ya samaan ko le ja sakti hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-9",
    word: "Truck",
    hint: "Ek bari road sawari jo aksar samaan le jane ke liye use hoti hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-10",
    word: "Van",
    hint: "Ek dabbe jaisi sawari jo logon ya samaan ko le jane ke liye hoti hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-11",
    word: "Taxi",
    hint: "Ek sawari jo kiraye ke badlay passengers ko le kar jati hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-12",
    word: "Scooter",
    hint: "Choti do pahiyon wali sawari jo shehar mein asani se chalai jati hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-13",
    word: "Ambulance",
    hint: "Ek sawari jo mareez ya zakhmi logon ko hospital le jati hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-14",
    word: "Tractor",
    hint: "Kheton mein bhari samaan ya equipment kheenchne ke liye use hota hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-15",
    word: "Rickshaw",
    hint: "Choti sawari jo aam tor par logon ko qareebi jagahon tak le jati hai.",
    category: "vehicles",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // Medium
  {
    id: "fallback-vehicles-ur-16",
    word: "Submarine",
    hint: "Samundar ki satah se bohat neeche safar karne ke liye banayi jati hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-17",
    word: "Ferry",
    hint: "Ek boat ya ship jo logon ya gaariyon ko pani ke paar le jati hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-18",
    word: "Yacht",
    hint: "Ek private boat jo aksar sair aur luxury safar ke liye use hoti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-19",
    word: "Tram",
    hint: "Ek passenger sawari jo aam tor par shehar mein tracks par chalti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-20",
    word: "Metro",
    hint: "Shehar ki train service jo aksar zameen ke neeche chalti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-21",
    word: "Bulldozer",
    hint: "Ek taqatwar vehicle jis ke aage bara blade hota hai aur yeh mitti dhakelta hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-22",
    word: "Forklift",
    hint: "Ek vehicle jis ke forks bhari samaan ko uthane ke kaam aate hain.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-23",
    word: "Canoe",
    hint: "Ek patli boat jo aam tor par paddle se chalai jati hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-24",
    word: "Kayak",
    hint: "Ek choti patli boat jo aam tor par dono taraf blades wale paddle se chalti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-25",
    word: "Jet Ski",
    hint: "Ek choti motor wali sawari jo pani par chalti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-26",
    word: "Hovercraft",
    hint: "Hawa ke cushion par zameen ya pani ke upar chal sakti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-27",
    word: "Glider",
    hint: "Ek aircraft jo aam engine ke baghair hawa mein urta hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-28",
    word: "Drone",
    hint: "Ek flying vehicle jise andar pilot ke baghair door se control kiya ja sakta hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-29",
    word: "Cable Car",
    hint: "Ek passenger vehicle jo cable ki madad se chalti hai aur aksar pahari ilaqon mein hoti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-30",
    word: "Monorail",
    hint: "Ek train jo sirf aik rail par chalti hai.",
    category: "vehicles",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // Hard
  {
    id: "fallback-vehicles-ur-31",
    word: "Gondola",
    hint: "Ek lambi patli boat jo riwayati tor par nehron mein aik chappu se chalai jati hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-32",
    word: "Zeppelin",
    hint: "Ek bara rigid airship jo pehle passengers ko safar karwane ke liye use hota tha.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-33",
    word: "Catamaran",
    hint: "Ek boat jis ke do parallel hulls aapas mein jude hote hain.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-34",
    word: "Hoverboard",
    hint: "Ek choti personal sawari jisme rider kharay ho kar glide karta hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-35",
    word: "Snowmobile",
    hint: "Ek motor wali sawari jo baraf par chalne ke liye banayi jati hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-36",
    word: "Amphibious Vehicle",
    hint: "Aisi sawari jo zameen aur pani dono par chal sakti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-37",
    word: "Airship",
    hint: "Ek powered aircraft jo gas se bhare bare body ki madad se hawa mein rehta hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-38",
    word: "Seaplane",
    hint: "Ek airplane jo pani se take off aur pani par land kar sakta hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-39",
    word: "Spacecraft",
    hint: "Ek vehicle jo zameen ke atmosphere se bahar space mein safar ke liye banaya jata hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-40",
    word: "Rocket",
    hint: "Engine se chalne wali sawari jo payload ko space tak le ja sakti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-41",
    word: "Icebreaker",
    hint: "Ek taqatwar ship jo moti baraf ko tod kar aage barhti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-42",
    word: "Catapult Aircraft",
    hint: "Ek aircraft jo ship se special launching system ki madad se uraya jata hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-43",
    word: "Tugboat",
    hint: "Ek choti lekin taqatwar boat jo bari ships ko dhakka ya khenchti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-44",
    word: "Funicular",
    hint: "Ek railway vehicle jo cable ki madad se bohat khari dhalan par upar neeche jata hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-vehicles-ur-45",
    word: "Maglev",
    hint: "Ek train jo magnetic force ki madad se track ke qareeb contact ke baghair chalti hai.",
    category: "vehicles",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
