import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "movies" category -- Roman Urdu.
 *
 * 100 words drawn from famous Bollywood and Pakistani cinema that an
 * average Roman Urdu-speaking player would instantly recognize.
 * As with the English list, difficulty only changes how directly the hint
 * points at the word, never how obscure the word itself is.
 * Hints are written in natural Roman Urdu using only Latin letters.
 */
export const MOVIES_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-movies-ur-1",
    word: "Sholay",
    hint: "Do dost mil kar ek gaon ko daku se bachate hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-2",
    word: "Dilwale Dulhania Le Jayenge",
    hint: "Ek larka Europe trip par larki ko pasand karta hai aur uske baap ko manata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-3",
    word: "Three Idiots",
    hint: "Engineering ke talib ilm apne college ke dino mein system ke khilaf baghawat karte hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-4",
    word: "PK",
    hint: "Ek alien zameen par apna locket kho deta hai aur mazhab ko samajhne lagta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-5",
    word: "Dangal",
    hint: "Ek pehlwan apni do betiyon ko gold medal jeetne ke liye tayyar karta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-6",
    word: "Bajrangi Bhaijaan",
    hint: "Ek seedha sadha aadmi ek gungi bachi ko wapis uske mulk chhorne jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-7",
    word: "Kabhi Khushi Kabhie Gham",
    hint: "Ek ameer baap apne bete ko nikal deta hai kyunke wo ghareeb larki se shadi karta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-8",
    word: "Kuch Kuch Hota Hai",
    hint: "College ki dosti pyar mein badalti hai lekin ek teesri larki ke aane se sab badal jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-9",
    word: "Munna Bhai MBBS",
    hint: "Ek local gunda doctor banne ka jhoot bolta hai aur phir sach mein hospital mein admission le leta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-10",
    word: "Lagaan",
    hint: "Gaon wale angrezon ke khilaf cricket match khailte hain takay unka tax maaf ho jaye.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-11",
    word: "Devdas",
    hint: "Ek aashiq sharaab mein doob jata hai jab uski mohabbat ki shadi kisi aur se ho jati hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-12",
    word: "Zindagi Na Milegi Dobara",
    hint: "Teen dost shadi se pehle Spain ke safar par jate hain aur apne darr ka samna karte hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-13",
    word: "Yeh Jawaani Hai Deewani",
    hint: "Kuch dost Manali ke trip par jate hain aur phir saalon baad ek shadi mein milte hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-14",
    word: "My Name is Khan",
    hint: "Ek khusoosi bimari wala musalman America mein president se milne ke safar par nikalta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-15",
    word: "Taare Zameen Par",
    hint: "Ek art teacher ek bachay ki madad karta hai jise parhai mein masla hota hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-16",
    word: "The Legend of Maula Jatt",
    hint: "Ek gaon ka bahadur aur ek zalim sardar ke beech sadiyon purani dushmani ki kahani.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-17",
    word: "Waar",
    hint: "Pakistani fauj ka major mulk ko dehshatgardon ke attacks se bachane ke liye operation karta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-18",
    word: "Bol",
    hint: "Ek beti apne sakht mazhabi baap ke khilaf ja kar qanoon ka samna karti hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-19",
    word: "Khuda Kay Liye",
    hint: "Do bhaiyon ki kahani jin mein se ek mazhabi extremism ki taraf chala jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-20",
    word: "Punjab Nahi Jaungi",
    hint: "Ek desi zameendar ko modern shehri larki se mohabbat ho jati hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-21",
    word: "Jawani Phir Nahi Ani",
    hint: "Shadi shuda dost apni biwiyon se chhup kar Thailand ghoomne chale jate hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-22",
    word: "Teefa in Trouble",
    hint: "Ek pakistani gunda kisi ko kidnap karne Poland jata hai lekin khud phans jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-23",
    word: "Bin Roye",
    hint: "Ek larki apne cousin se mohabbat karti hai lekin uski shadi uski behen se ho jati hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-24",
    word: "Chooriyan",
    hint: "Punjab ke ek shehri babu ko gaon ki larki se pyar ho jata hai jis ki mangni pehle ho chuki hoti hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-25",
    word: "Don",
    hint: "Police ek criminal ko pakarney ke liye uske humshakal ko gang mein shamil kar deti hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-26",
    word: "Deewaar",
    hint: "Do bhaiyan mukhalif rastay chunte hain, ek police wala banta hai aur dusra underworld don.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-27",
    word: "Mr India",
    hint: "Ek ghareeb aadmi ko ghayab hone wali ghari milti hai aur wo villains ko maza chakhata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-28",
    word: "Andaz Apna Apna",
    hint: "Do bewaqoof larke ek ameer larki se shadi karne ke chakkar mein gundon se takra jate hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-29",
    word: "Hera Pheri",
    hint: "Teen log jo kiraye ke ghar mein rehte hain, ek ghalat phone call se ameer hone ka plan banate hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-30",
    word: "Welcome",
    hint: "Ek shareef khandan ka larka kisi underworld don ki behen se shadi karne ki koshish karta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-31",
    word: "Dhamaal",
    hint: "Kuch doston ko ek marte hue aadmi se khazane ke baare mein pata chalta hai aur sab wahan bhagte hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-32",
    word: "Golmaal",
    hint: "Chaar dost chuttiyan manane ek andhe aur behre uncle ke ghar mein ghus jate hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-33",
    word: "Bhool Bhulaiyaa",
    hint: "Ek purani haveli mein jadoo tona aur bhoot hone ka raaz ek doctor solve karta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-34",
    word: "Chennai Express",
    hint: "Ek aadmi apne dada ki rakh bahane train mein chadhta hai aur south indian gundon mein phans jata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-35",
    word: "Dhoom",
    hint: "Chor bikes par aakar bank loot tay hain aur police unke peechay bhagti hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-36",
    word: "Krrish",
    hint: "Ek superhero jo paharon se aya hai aur shehar mein logon ko bachata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-37",
    word: "Koi Mil Gaya",
    hint: "Ek special bacha computer ke zariye aliens se dosti kar leta hai jo use taqatwar bana dete hain.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-38",
    word: "Baahubali",
    hint: "Ek taqatwar mard apni purani sultanat ko zalim hukmaran se wapis cheenta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-39",
    word: "Chak De India",
    hint: "Ek nakaam khiladi larkiyon ki hockey team ka coach ban kar unhe world cup jitwata hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-40",
    word: "Swades",
    hint: "Ek NASA scientist gaon wapis ata hai aur wahan bijli lane ki koshish karta hai.",
    category: "movies",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-movies-ur-41",
    word: "Rang De Basanti",
    hint: "Kuch university ke larke ek documentary shoot karte karte hukumat ke khilaf kharay ho jate hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-42",
    word: "Dil Chahta Hai",
    hint: "Teen jigri dost aur unke aapas ke maslay jab wo apni zindagi ke alag raston par jate hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-43",
    word: "Kal Ho Naa Ho",
    hint: "Ek bemar aadmi apne shehar ki parosan ki life mein khushiyan lane ki koshish karta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-44",
    word: "Veer Zaara",
    hint: "Ek sarhad paar ki mohabbat jis mein ek fauji barson tak jail mein rehta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-45",
    word: "Mohabbatein",
    hint: "Gurukul ke strict principal ko ek naya music teacher pyar sikhane ata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-46",
    word: "Dil To Pagal Hai",
    hint: "Dance troupe ke log aapas mein mohabbat karne lagte hain aur love triangle ban jata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-47",
    word: "Hum Aapke Hain Koun",
    hint: "Shadi ke ek taweel function mein ladkay aur ladki ko mohabbat ho jati hai, lekin bhabi guzar jati hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-48",
    word: "Maine Pyar Kiya",
    hint: "Dosti mohabbat mein badal jati hai lekin ameer baap ghareeb beti ko qabool nahi karta.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-49",
    word: "Baazigar",
    hint: "Ek larka apne baap ka badla lene ke liye dusman ki betiyon ke sath khail khailta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-50",
    word: "Darr",
    hint: "Ek pagal aashiq larki ko phone par darata hai aur uske fiancé ko maarne ki koshish karta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-51",
    word: "Karan Arjun",
    hint: "Maa ka kehna hota hai ke mere bete aayenge, aur wo waqai dusra janam le kar badla lene aate hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-52",
    word: "Hum Dil De Chuke Sanam",
    hint: "Shadi ke baad shohar apni biwi ko uske pehle pyar se milwane Italy le jata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-53",
    word: "Ludo",
    hint: "Chaar mukhtalif kahaniyan aur log jo ek criminal ke paise aur raaz ki wajah se jud jate hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-54",
    word: "Queen",
    hint: "Shadi tootne ke baad ek bholi larki akele Europe apne honeymoon par nikal jati hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-55",
    word: "Kahaani",
    hint: "Ek hamilah aurat Kolkata mein apne gumshuda shohar ko dhoondhne ati hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-56",
    word: "Barfi",
    hint: "Ek gunga behra aadmi apni zindadil fitrat se do mukhtalif larkiyon ke dil jeet leta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-57",
    word: "Piku",
    hint: "Ek beti aur uska chirchira baap road trip karke Kolkata ki taraf safar karte hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-58",
    word: "Pink",
    hint: "Ek retired wakeel teen larkiyon ko adaalat mein bachata hai jin par jhuta ilzam laga hota hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-59",
    word: "Andhadhun",
    hint: "Ek piano bajane wala aadmi andha hone ka naatak karta hai aur murder dekh leta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-60",
    word: "Drishyam",
    hint: "Ek simple family man cable tv ke natak se ideas le kar apni family ko murder case se bachata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-61",
    word: "Kabir Singh",
    hint: "Ek medical student apni girlfriend ki shadi kisi aur se hone ke baad sharaabi aur ghussail ban jata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-62",
    word: "Animal",
    hint: "Ek beta apne baap ki mohabbat mein kisi bhi hadd tak jane aur khoon kharaba karne ke liye tayyar rehta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-63",
    word: "Jawan",
    hint: "Ek aadmi larkiyon ki team ke sath system se larta hai aur awam ka haq dilwata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-64",
    word: "Pathaan",
    hint: "Ek jasoos mulk ko bachaney ke liye virus failane wale gundon se jang karta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-65",
    word: "Gadar",
    hint: "Partition ke waqt ek aadmi sarhad par ja kar apni bivi aur bete ko wapis lata hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-66",
    word: "Border",
    hint: "Jang ke maidan mein mutthi bhar fauji dushman ki puri regiment ko rokay rakhte hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-67",
    word: "Na Maloom Afraad",
    hint: "Teen ghareeb log ameer hone ke chakar mein strike ke din bank lootne ka plan banate hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-68",
    word: "Actor In Law",
    hint: "Ek nakam actor court mein jhoota wakeel ban kar logo ko insaaf dilwane lagta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-69",
    word: "Cake",
    hint: "Do behne apne abba ki bimari ki wajah se milti hain aur khandan ke puraane raaz khulne lagte hain.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-70",
    word: "Joyland",
    hint: "Lahore ke ek traditional gharane mein beta chup kar theater mein dance karne lagta hai.",
    category: "movies",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-movies-ur-71",
    word: "Tumbbad",
    hint: "Gaon mein purane mandir ke paas barish mein chipa hua lalchi devta soney ki mohar deta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-72",
    word: "Masaan",
    hint: "Banaras ke ghat par aag lagane walon aur dusre kiradaron ki zindagiyan gham mein phansi hain.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-73",
    word: "The Lunchbox",
    hint: "Mumbai mein khane ka ek ghalat dabba do bilkul ajnabi logon ki khat o kitabat shuru karwa deta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-74",
    word: "Gangs of Wasseypur",
    hint: "Koylay ki khano mein aur desi katoon ke sath naslon se chalti aarahi dushmani aur badla.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-75",
    word: "Satya",
    hint: "Mumbai underworld mein ek aam aadmi ka bhaigiri aur gun crime mein upper tak jana.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-76",
    word: "Haider",
    hint: "Kashmir ki wadiyon mein ek talib ilm apne baap ke gayab hone ka badla chacha se leta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-77",
    word: "Omkara",
    hint: "UP ke badmashon ke beech shak aur jhoot ek shakhs ko apni hi biwi ko maarne par majboor kar deta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-78",
    word: "Maqbool",
    hint: "Ek don ka bouncer uski bivi ki baaton mein akar usay maar deta hai taake khud don ban sake.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-79",
    word: "A Wednesday",
    hint: "Ek aam aadmi shehar mein bomb plant karne ka jhoot bol kar police se terrorists release karwata hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-80",
    word: "Khosla Ka Ghosla",
    hint: "Middle class family apni qabza ki hui zameen property dealer se chalanay ke liye chuna lagati hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-81",
    word: "Oye Lucky Lucky Oye",
    hint: "Ek bohat shaana chor bade maze se car aur tv chori karta hai bina pakre jaye.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-82",
    word: "Dev D",
    hint: "Modern waqt ka aashiq vodka aur drugs mein apni barbadi ko apne gaon aur shehar mein jashn banata hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-83",
    word: "Delhi Belly",
    hint: "Kharab khana khane ki wajah se pait kharab hota hai aur diamondon ki smuggling ka chakkar ulajh jata hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-84",
    word: "Rockstar",
    hint: "Bara singer banne ke liye ladka khud apni mohabbat ka dil torta hai taake awaz mein dard aa sake.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-85",
    word: "Tamasha",
    hint: "Corsica mein do log pehchan chupate hain lekin real life mein society ka pressure aadmi ko pagal kar deta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-86",
    word: "Highway",
    hint: "Kidnap hone ke baad ameer ghar ki larki ko apne gunde kidnapper ke sath azaadi mehsus hoti hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-87",
    word: "Jab We Met",
    hint: "Ek shant businessman ek batuni larki ko rat ki train mein chootne ke baad uske gao chhorne lagta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-88",
    word: "Love Aaj Kal",
    hint: "Purane zamane ki mohabbat aur naye zamane ke confused rishton ko apas mein milaya gaya hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-89",
    word: "Cocktail",
    hint: "London mein room share karne wale dost apas mein ulajh jate hain jab desi banawat maghribi rehan sehan se takrati hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-90",
    word: "Kapoor and Sons",
    hint: "Dada ka aakhri waqt kareeb anay par ek khandan ke tamam jhote raaz khulna shuru ho jate hain.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-91",
    word: "Dear Zindagi",
    hint: "Ek pareshan camerawoman apne dimaghi aur jazbati masail hal karne ke liye Goa mein therapist dhoondti hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-92",
    word: "Zinda Bhaag",
    hint: "Lahore ke nojawan illegal tareeqe se bahar jane ka khwab dekhte hain aur unka ticket lene wala mafia.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-93",
    word: "Moor",
    hint: "Balochistan ke barfeele paharon mein ek railway station master apni bad-unwani aur zameer se larta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-94",
    word: "Dukhtar",
    hint: "Ek maa apni chhoti beti ko kabaili dushmani mein zabardasti ki shadi se bachaney ke liye bhag jati hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-95",
    word: "Kamli",
    hint: "Jungle mein chupi aurten jin ke shohar bahar gaey hain aur unki ghutan ka jadooi anjam.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-96",
    word: "Laal Kabootar",
    hint: "Karachi ki sarkon par ek larki apne shohar ka qatal solve karne ke liye tax walon ke sath milti hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-97",
    word: "Mah e Mir",
    hint: "Ek naya shayar classic shairi mein doob kar purane asaatza ke khayalat khud jeene lagta hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-98",
    word: "Ramchand Pakistani",
    hint: "Ghalti se border par hone ki wajah se ek baap aur beta bharti jail mein phans jate hain.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-99",
    word: "Verna",
    hint: "Ziadti ka shikar ek aurat system aur siyasatdano ko ankhon mein ankhen daal kar insaaf chheenti hai.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-movies-ur-100",
    word: "Parchi",
    hint: "Chaar bewakoof doston ki mafia ko paise wapis karne ki struggle aur unki thori c comedy.",
    category: "movies",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
