import type {
  Category,
  Difficulty,
  GeneratedRoundContent,
} from "@/game/game-types";
import { getRandomCachedWord } from "@/lib/db";
import type { WordProvider } from "./word-provider";

/**
 * TIER 2 -- IndexedDB AI cache (see lib/db.ts). Only ever returns
 * content that was previously generated by the AI provider and cached
 * on success -- this class never fabricates content of its own.
 *
 * Throws when the cache has nothing suitable (including "the cache is
 * completely empty," which is the normal state until the first AI
 * round has ever succeeded on this device). The caller
 * (game/game-engine.ts) treats that the same as any other tier-2
 * failure and falls through to the tier-3 static provider.
 */
export class IndexedDbCacheProvider implements WordProvider {
  async generateRoundContent(
    category: Category,
    difficulty: Difficulty,
  ): Promise<GeneratedRoundContent> {
    const cached = await getRandomCachedWord(category, difficulty);
    if (!cached) {
      throw new Error("No suitable cached round available.");
    }
    return { word: cached.word, hint: cached.hint, source: "cache" };
  }
}
