import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "technology" category -- English.
 *
 * All 100 words are common, everyday technology items and concepts an average
 * international player would instantly recognize. Difficulty here changes ONLY
 * how directly the hint points at the word:
 *   - easy (40):   the hint states the tech's main function directly.
 *   - medium (30): the hint points at a related digital detail, context, or association.
 *   - hard (30):   the hint is oblique -- an unusual angle, background process, or consequence.
 */
export const TECHNOLOGY_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-technology-en-1",
    word: "Smartphone",
    hint: "A pocket-sized touchscreen computer that you also use to make phone calls.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-2",
    word: "Laptop",
    hint: "A portable computer with a folding screen and an attached keyboard.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-3",
    word: "Tablet",
    hint: "A flat mobile device consisting of just a large touchscreen without a physical keyboard.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-4",
    word: "Desktop",
    hint: "A personal computer designed to stay permanently on an office desk.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-5",
    word: "Keyboard",
    hint: "A board covered in buttons with letters and numbers used to type text.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-6",
    word: "Mouse",
    hint: "A small device you move with your hand to control the pointer on a screen.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-7",
    word: "Monitor",
    hint: "The external digital screen that displays a computer's visual output.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-8",
    word: "Printer",
    hint: "A machine that transfers digital documents onto physical sheets of paper.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-9",
    word: "Headphones",
    hint: "A pair of small speakers worn over the ears to listen to audio privately.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-10",
    word: "Microphone",
    hint: "A device you speak into that captures and records your voice.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-11",
    word: "Camera",
    hint: "A digital lens used to capture high-quality photographs and record videos.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-12",
    word: "Battery",
    hint: "The internal power source that keeps a wireless device running.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-13",
    word: "Charger",
    hint: "The plug and cable used to refill a device's electrical power.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-14",
    word: "Screen",
    hint: "The flat glass surface on your device where images and text are displayed.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-15",
    word: "Password",
    hint: "A secret combination of letters and numbers used to protect your account.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-16",
    word: "Internet",
    hint: "The global digital network connecting millions of computers worldwide.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-17",
    word: "Website",
    hint: "A collection of digital pages accessed through a specific web address.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-18",
    word: "Application",
    hint: "A specialized software program downloaded to perform a specific task on a mobile device.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-19",
    word: "Video Game",
    hint: "An interactive digital entertainment program played on a console or computer.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-20",
    word: "Robot",
    hint: "A programmable mechanical machine capable of carrying out complex physical actions.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-21",
    word: "Drone",
    hint: "An unmanned flying vehicle controlled remotely from the ground.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-22",
    word: "Hacker",
    hint: "A person who secretly breaks into computer systems to steal data.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-23",
    word: "Virus",
    hint: "A malicious software program designed to infect and damage your computer.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-24",
    word: "Email",
    hint: "A digital letter sent across the internet to another person's inbox.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-25",
    word: "Text Message",
    hint: "A short written note sent directly from one mobile phone to another.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-26",
    word: "Emoji",
    hint: "A small digital icon used to express emotion in a chat.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-27",
    word: "Search Engine",
    hint: "A website where you type a question to find information across the internet.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-28",
    word: "Social Media",
    hint: "Platforms where users create profiles to share photos and communicate with friends.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-29",
    word: "Folder",
    hint: "A digital directory icon where you organize and store multiple related files.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-30",
    word: "File",
    hint: "A single digital document, image, or piece of stored information.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-31",
    word: "Download",
    hint: "To copy data from the internet directly onto your personal device.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-32",
    word: "Upload",
    hint: "To send data from your personal device up to a website or server.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-33",
    word: "Server",
    hint: "A powerful central computer that hosts websites and stores network data.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-34",
    word: "Cloud",
    hint: "A network of remote servers used to store data over the internet instead of locally.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-35",
    word: "Calculator",
    hint: "A digital tool used to solve complex mathematical equations instantly.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-36",
    word: "Television",
    hint: "A large electronic screen used primarily for broadcasting news and entertainment channels.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-37",
    word: "Radio",
    hint: "A device that receives invisible waves to broadcast audio programming and music.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-38",
    word: "Satellite",
    hint: "A human-made machine orbiting the Earth to beam communication signals down.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-39",
    word: "Laser",
    hint: "A highly focused, intense beam of single-colored light.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-technology-en-40",
    word: "Algorithm",
    hint: "A specific set of mathematical rules a computer follows to solve a problem.",
    category: "technology",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-technology-en-41",
    word: "Router",
    hint: "A blinking box in your living room that you restart when the wireless connection drops.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-42",
    word: "Processor",
    hint: "The central brain of a computer that performs all the high-speed calculations.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-43",
    word: "Memory",
    hint: "The short-term digital storage space a computer uses while actively running programs.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-44",
    word: "Hard Drive",
    hint: "The physical component inside a computer where all your permanent files are stored.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-45",
    word: "Motherboard",
    hint: "The main circuit board that connects all the different internal computer parts together.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-46",
    word: "Software",
    hint: "The invisible programs and code that tell a computer hardware what to do.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-47",
    word: "Hardware",
    hint: "The physical, touchable components and wiring that make up a computer system.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-48",
    word: "Coding",
    hint: "The process of writing specialized text commands to build software programs.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-49",
    word: "Database",
    hint: "A highly organized digital filing system used to store massive amounts of user information.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-50",
    word: "Firewall",
    hint: "A digital security barrier designed to block unauthorized access to a private network.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-51",
    word: "Encryption",
    hint: "The process of scrambling sensitive data into unreadable text to protect it from thieves.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-52",
    word: "Biometrics",
    hint: "Using unique physical traits like your face or eyes to unlock a secure device.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-53",
    word: "Fingerprint Scanner",
    hint: "You press your thumb firmly against this small sensor to instantly unlock your phone.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-54",
    word: "Smartwatch",
    hint: "A wearable digital device on your wrist that counts your steps and shows notifications.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-55",
    word: "Thermostat",
    hint: "A smart wall dial that automatically connects to your phone to adjust the house temperature.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-56",
    word: "Virtual Reality",
    hint: "Wearing a thick headset over your eyes to fully immerse yourself in a simulated 3D world.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-57",
    word: "Artificial Intelligence",
    hint: "Computer systems designed to mimic human learning, reasoning, and problem-solving.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-58",
    word: "Ecommerce",
    hint: "The digital industry of buying and selling physical products entirely through online stores.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-59",
    word: "Cryptocurrency",
    hint: "A decentralized digital money system that operates independently of any central bank.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-60",
    word: "Streaming",
    hint: "Watching a long movie on the internet without needing to save the entire file first.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-61",
    word: "Podcast",
    hint: "An episodic digital audio show that you listen to on your phone during a commute.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-62",
    word: "Blogger",
    hint: "A person who regularly writes and publishes personal articles on their own website.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-63",
    word: "Influencer",
    hint: "Someone who builds a massive online following to promote products and lifestyle choices.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-64",
    word: "Spam",
    hint: "Unwanted, mass-produced junk emails cluttering up your digital inbox.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-65",
    word: "Phishing",
    hint: "A deceptive email tricking you into clicking a fake link to steal your password.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-66",
    word: "Antivirus",
    hint: "A background program constantly scanning your computer to detect and destroy digital threats.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-67",
    word: "Update",
    hint: "A software patch you install to fix bugs and add new features to your device.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-68",
    word: "Reboot",
    hint: "The act of turning a frozen device completely off and then back on again.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-69",
    word: "Backup",
    hint: "Creating an exact copy of your important files just in case your computer breaks.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-technology-en-70",
    word: "Pixel",
    hint: "A single tiny square of colored light that makes up a digital display.",
    category: "technology",
    difficulty: "medium",
    language: "english",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-technology-en-71",
    word: "Network",
    hint: "A web of interconnected machines constantly talking and sharing resources with each other.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-72",
    word: "Bandwidth",
    hint: "The maximum capacity of data that can travel through your internet connection at once.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-73",
    word: "Resolution",
    hint: "Upgrading this setting makes the image on your screen look incredibly sharp and detailed.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-74",
    word: "Interface",
    hint: "The visual layout of buttons and menus that lets a human interact with a machine.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-75",
    word: "Operating System",
    hint: "The foundational software that manages all the background processes on your phone or PC.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-76",
    word: "Browser",
    hint: "The primary application you open when you want to visit different pages on the web.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-77",
    word: "Cookie",
    hint: "A tiny text file left by a website to remember your preferences for your next visit.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-78",
    word: "Domain",
    hint: "The custom, human-readable name you purchase to identify your unique address on the web.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-79",
    word: "URL",
    hint: "The exact, complete text string you type into the top bar to visit a specific webpage.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-80",
    word: "Hyperlink",
    hint: "Clickable blue text that instantly transports you to a completely different web page.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-81",
    word: "Compression",
    hint: "Magically shrinking the size of a massive digital file so it can be emailed easily.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-82",
    word: "Extension",
    hint: "A small software add-on you install to give your web browser extra capabilities.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-83",
    word: "Bug",
    hint: "A frustrating flaw in the code that causes a program to suddenly crash or misbehave.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-84",
    word: "Patch",
    hint: "A quick software fix released by developers to repair a specific broken feature.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-85",
    word: "Glitch",
    hint: "A temporary, unexpected visual stutter or malfunction in an otherwise working system.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-86",
    word: "Automation",
    hint: "Setting up machines to perform repetitive tasks entirely on their own without human help.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-87",
    word: "Machine Learning",
    hint: "Teaching a computer to recognize patterns by feeding it massive amounts of raw data.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-88",
    word: "Nanotechnology",
    hint: "Engineering incredibly tiny devices and materials at the atomic and molecular level.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-89",
    word: "Quantum Computer",
    hint: "An experimental, immensely powerful machine that calculates using subatomic particles instead of standard bits.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-90",
    word: "Fiber Optics",
    hint: "Transmitting high-speed data across continents using pulses of light through thin glass threads.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-91",
    word: "Microchip",
    hint: "A tiny wafer of silicon holding millions of microscopic electrical pathways.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-92",
    word: "Semiconductor",
    hint: "The critical base material, usually silicon, used to manufacture modern electronics.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-93",
    word: "Circuit Board",
    hint: "A flat green plate covered in silver lines connecting various electronic components.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-94",
    word: "Transistor",
    hint: "A microscopic electronic switch that controls the flow of electricity inside a processor.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-95",
    word: "Capacitor",
    hint: "A small electronic component that temporarily stores and releases electrical energy on a board.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-96",
    word: "Sensor",
    hint: "A hardware component that detects changes in the environment like temperature, motion, or light.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-97",
    word: "Antenna",
    hint: "A metallic rod or wire that captures invisible radio signals out of the air.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-98",
    word: "Cable",
    hint: "You trip over this long, annoying cord stretching from the wall outlet to your machine.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-99",
    word: "Webcam",
    hint: "The small, unblinking lens at the top of your monitor staring at you during virtual meetings.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-technology-en-100",
    word: "USB Drive",
    hint: "A small plastic stick you plug into the side of your laptop to quickly transfer files.",
    category: "technology",
    difficulty: "hard",
    language: "english",
  },
];
