// lib/fallback-words/nature/urdu/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "nature" category -- Roman Urdu.
 *
 * 100 well-known words about nature, weather, seasons, and elements
 * instantly recognizable in everyday Pakistani vocabulary.
 * Difficulty changes ONLY how directly the hint points at the word.
 * Hints are written in natural conversational Roman Urdu using ONLY
 * Latin letters.
 */
export const NATURE_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-nature-ur-1",
    word: "Suraj",
    hint: "Din ke waqt asmaan par chamakne wali garam aur be-had roshan cheez.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-2",
    word: "Chand",
    hint: "Raat ke waqt chamakne wala safed gola jis ki roshni thandi hoti hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-3",
    word: "Sitara",
    hint: "Raat ke asmaan mein chamakne wala chota sa tim-timata hua nuqta.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-4",
    word: "Asmaan",
    hint: "Hamare sar ke upar phela hua neela aur intehai waseeh hissa.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-5",
    word: "Zameen",
    hint: "Wo matti aur farsh jis par hum sab insaan aur janwar chalte phirte hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-6",
    word: "Pani",
    hint: "Pyaas bujhane wali aur zinda rehne ke liye sab se zaroori maya.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-7",
    word: "Hawa",
    hint: "Urti hui aur chalne wali cheez jo nazar nahi ati par mehsoos hoti hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-8",
    word: "Aag",
    hint: "Sardiyon mein hath senkne aur khana pakane ke liye jalai jane wali cheez.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-9",
    word: "Barish",
    hint: "Kaalay badlon se qatron ki shakal mein barasne wala taaza pani.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-10",
    word: "Baraf",
    hint: "Sardiyon ki thand mein murree aur naraan mein girne wali safed tui.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-11",
    word: "Pahaar",
    hint: "Zameen ka sab se ooncha aur pathrila hissa jis par charhna mushkil hota hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-12",
    word: "Darya",
    hint: "Pahaaron se nikal kar behne wala taaza pani jo samundar tak jata hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-13",
    word: "Samundar",
    hint: "Khare aur namkeen pani ka be-tahasha bara aur gehra hissa jis ka kinara nahi milta.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-14",
    word: "Ghaas",
    hint: "Baghiche mein ugne wali choti aur sabz rang ki hariyali jis par bachay khelte hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-15",
    word: "Darakht",
    hint: "Shady par lamba aur bhari tana rakhne wala pauda jo chhaon deta hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-16",
    word: "Patta",
    hint: "Darakht ki shakh par lagne wala sabz hissa jo khizaan mein neechay gir jata hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-17",
    word: "Phool",
    hint: "Khushboo dar aur khubsurat rangon wali kali jo bagh mein khilti hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-18",
    word: "Mitti",
    hint: "Bhooray rang ki khaak jis mein har tarah ke pauday ugaye jate hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-19",
    word: "Rait",
    hint: "Samundar ke sahil aur sehra mein milne wali choti aur kir-kiri dhool.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-20",
    word: "Pathar",
    hint: "Sakht aur thos tukra jo pahaar se toot kar zameen par bikhra hota hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-21",
    word: "Jungle",
    hint: "Ghane darakhton aur khatarnak janwaron se bhara hua weeraan aur pur-israr ilaqah.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-22",
    word: "Khet",
    hint: "Gaon mein wo khuli zameen jahan kisaan fasal aur gandum ugate hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-23",
    word: "Baagh",
    hint: "Wo haseen jagah jahan bohut sare phaldar darakht aur rang birange phool hon.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-24",
    word: "Kinara",
    hint: "Pani aur khushki ke milne ki jagah jahan kharay ho kar lehrein dekhi jati hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-25",
    word: "Jheel",
    hint: "Pahaaron ke darmiyan jama hua khoobsurat saf pani ka chota hissa saiful malook ki tarah.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-26",
    word: "Toofan",
    hint: "Bohat tez hawa aur shadesed barish ka silsila jo kache ghar gira deta hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-27",
    word: "Bijli",
    hint: "Barish se theek pehle kaalay badlon ke darmiyan chamakne wali roshni.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-28",
    word: "Garaj",
    hint: "Asman par badlon ke takrane se aane wali intehai onchi aur darawni awaz.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-29",
    word: "Andhera",
    hint: "Jab roshni bilkul khatam ho jaye aur kuch bhi nazar aana band ho jaye.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-30",
    word: "Ujala",
    hint: "Suraj ke nikalte hi har taraf phelne wali khoobsurat aur chmakdar roshni.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-31",
    word: "Din",
    hint: "Subah se le kar shaam tak ka roshan hissa jab sab daftar jate hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-32",
    word: "Raat",
    hint: "Andhera hone ke baad ka waqt jab sab thak kar bistar par so jate hain.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-33",
    word: "Subah",
    hint: "Fajar ki azaan aur suraj nikalne ka ibtadai waqt jab taza hawa chalti hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-34",
    word: "Shaam",
    hint: "Suraj doobne se theek pehle ka waqt jab asmaan par narangi rang chha jata hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-35",
    word: "Garmi",
    hint: "June aur july ke maheene mein pasina nikalne wala shadeed tapish ka mosam.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-36",
    word: "Sardi",
    hint: "December mein thiturte hue logo aur garam kapre pehnne wala mosam.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-37",
    word: "Kanta",
    hint: "Gulab ki tehni par ugne wali nukili cheez jo ungli mein chubh sakti hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-38",
    word: "Lakri",
    hint: "Darakht ke tane ko kaat kar milne wala sakht mawaad jis se furniture banta hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-39",
    word: "Jhaari",
    hint: "Chotay qad aur ghanay patton wala jungli pauda jo rastay mein aksar ug jata hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-40",
    word: "Pauda",
    hint: "Ghamle mein lagaya gaya chota aur naram jandar jo mitti aur pani se barhta hai.",
    category: "nature",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (30)
  {
    id: "fallback-nature-ur-41",
    word: "Lehar",
    hint: "Samundar ki satah par uthne wali aur kinare tak shor machati hui anay wali ufaan.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-42",
    word: "Jhaag",
    hint: "Lehron ke kinare se takrane ke baad banne wali safed aur naram bubblon ki theh.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-43",
    word: "Oos",
    hint: "Sardiyon ki subah ghaas aur gariyon ke shishay par thehri hui pani ki barik boondein.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-44",
    word: "Dhund",
    hint: "Shadeed sardi mein subah savere nazar aanay wala gehra kohar jis se kuch theek na dikhe.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-45",
    word: "Aandhi",
    hint: "Khushk aur mitti udane wali bohut teez hawa jo cheezon ko apni jagah se hila de.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-46",
    word: "Sailaab",
    hint: "Darya mein pani ka satah se zyada barh kar aas paas ke gaon ko dobo dena.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-47",
    word: "Sookha",
    hint: "Arsa daraz tak barish na hone se zameen ka phat jana aur qehat par jana.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-48",
    word: "Zalzala",
    hint: "Zameen ke neechay platein takrane se peda hone wala darawna jhatka jo amarton ko hila deta hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-49",
    word: "Aatish Fashan",
    hint: "Wo pahaar jis ke pighalne aur phatne se intehai garam aur surkh laawa bahar nikalta hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-50",
    word: "Ghaar",
    hint: "Pahaar ke andar qadarati tor par banne wali andheri surang jahan jungli janwar rehte hain.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-51",
    word: "Waadi",
    hint: "Do baray pahaaron ke darmiyan ghiri hui khoobsurat aur gehri nichi jagah.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-52",
    word: "Abshaar",
    hint: "Unchai aur pahaar ki choti se neechay theek darya mein girne wala khubsurat pani ka jhar-na.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-53",
    word: "Jazeera",
    hint: "Charon taraf se samundar ke gehray pani se ghira hua khushki ka chota sa khitta.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-54",
    word: "Sehra",
    hint: "Jahan tak nazar jaye sirf udarti hui garm rait nazar ati hai aur paani nahi milta.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-55",
    word: "Chashma",
    hint: "Zameen ke andar se khud ba khud phoot kar nikalne wala saf aur meetha pani.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-56",
    word: "Kichar",
    hint: "Tez barish ke baad mitti aur pani ke milne se banne wali phisalan aur lais dar zameen.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-57",
    word: "Dhool",
    hint: "Hawa chalne par mitti ke chotay aur barik zarre jo ankhon mein par jatay hain.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-58",
    word: "Chatan",
    hint: "Intehai bara, mazboot aur wazni pathar jisay insani taqat se hilana theek namumkin hota hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-59",
    word: "Tehni",
    hint: "Darakht ke main tane se bahar nikalne wala wo patla bazu jis par pattay ugte hain.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-60",
    word: "Jar",
    hint: "Zameen ke neechay chupi hui paude ki bunyad jo mitti ko theek mazbooti se pakre rakhti hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-61",
    word: "Tana",
    hint: "Darakht ka darmiyani lakri wala sab se mota aur bhari hissa jo zameen se upper hota hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-62",
    word: "Chhal",
    hint: "Darakht ke tane ke upar lagi hui sakht aur khurduri jildi patti jo hifazat karti hai.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-63",
    word: "Beej",
    hint: "Khaane wale phal ke andar se nikalne wala chota dana jisay bone se naya pooda nikle.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-64",
    word: "Kali",
    hint: "Phool ke theek mukammal khilne se pehle us ki choti, band aur ibtadai halat.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-65",
    word: "Khushboo",
    hint: "Baghiche mein taaza phoolon se hawa ke zariye naak tak pohanchne wali theek mehek.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-66",
    word: "Sayah",
    hint: "Kari dhoop mein darakht ke theek neechay farsh par thehrne wala thanda andhera hissa.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-67",
    word: "Dhanak",
    hint: "Barish theek rukne ke fauran baad asman par ubharne wala saat rangon ka haseen qaus.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-68",
    word: "Qatra",
    hint: "Pani ka chota sa hissa jo nalke se tapakta hai ya barish ki shuruaat mein girtay hain.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-69",
    word: "Badal",
    hint: "Asmaan mein theek rui ki tarah urne wale safed aur kaale pani ke zakheere.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-70",
    word: "Baaghban",
    hint: "Baghiche aur fasal mein phool aur paudon ka theek se khayal rakhne aur pani dene wala.",
    category: "nature",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (30)
  {
    id: "fallback-nature-ur-71",
    word: "Shola",
    hint: "Jalti hui aag se nikalne wali theek lambi aur garam naranji laptain jis se aag phailti hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-72",
    word: "Raakh",
    hint: "Lakri aur koylalay ke jal kar bilkul mukammal theek thandi ho jane ke baad bachi hui safed mitti.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-73",
    word: "Dhuan",
    hint: "Aag lagne ke theek baad hawa mein upar ki taraf uthne wala kala aur theek ghootan zada mawaad.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-74",
    word: "Grahn",
    hint: "Aftab ya mehtab ke theek samne kisi aur theek sayyare ke aa jane se lagne wala makhsoos sayah parda.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-75",
    word: "Tulu",
    hint: "Mashriq se suraj ke theek ooper aane aur asmaan par fajar ke waqt theek pehli roshni phelne ka amal.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-76",
    word: "Ghuroob",
    hint: "Maghrib ke aakhri lamhaat jab aftaab pahaaron ya samundar ke theek peechay chup kar ghayab ho jata hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-77",
    word: "Bahaar",
    hint: "Sardi theek guzar jane ke baad aane wala wo rut jis mein har taraf naye phool theek zor se khilte hain.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-78",
    word: "Khizaan",
    hint: "Darakhton ke pattay zard aur theek sookh kar zameen par girne wale udas rut ka aaghaz.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-79",
    word: "Sawan",
    hint: "Tez garmi ke theek baas aane wala mon-soon ka rut jis mein musalsal theek rim-jhim barishen hoti hain.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-80",
    word: "Habas",
    hint: "Hawa theek rukk jane par aur theek ghutan mehsoos hone ki wo ajeeb kaifiyat jab pasina theek se khushk na ho.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-81",
    word: "Loo",
    hint: "June mein theek sarak par chalne wali shadeed jhulsa dene wali aur theek be-dard garam tapat.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-82",
    word: "Kehkashan",
    hint: "Raat ke theek gehre andhere mein asmaan par lakhon sitaron ka mil kar theek chamakta hua jhurmat.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-83",
    word: "Sayyara",
    hint: "Khalai dunya ka wo theek bara gola jo aftaab ke gird theek mudat par ghoomta rehta hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-84",
    word: "Heera",
    hint: "Zameen ki gehrayi mein theek dabay hue koilay se banne wala aur dunya ka sab se theek sakht chamakta pathar.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-85",
    word: "Koila",
    hint: "Sadion tak lakri ke theek mitti mein dabay rehne se nikalne wala theek siyah indhan.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-86",
    word: "Sona",
    hint: "Khaan se nikalne wali theek peeli aur theek qeemti dhaat jis se khubsurat theek zewarat bantay hain.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-87",
    word: "Chandi",
    hint: "Sufaid theek chamakti dhaat jis ki theek ashiay aur anghoti awam mein theek aam pehni jati hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-88",
    word: "Loha",
    hint: "Kacchy theek pahaaron se hasil kardah sakht theek maadah jis se tamam bhari theek masheenain theek banti hain.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-89",
    word: "Namak",
    hint: "Khewara ki khaan aur theek samundari theek pani ko sukha kar theek hasil kardah zaroori theek masala.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-90",
    word: "Seep",
    hint: "Samundar ki theek gehrayi mein khol-dar keroo ka theek pathrila ghilaaf jis mein naya theek moti banta hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-91",
    word: "Moti",
    hint: "Samundar ki theek satah ke theek neeche nikalne wala theek chota aur besh-qeemat theek roshan gol theek dana.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-92",
    word: "Moonga",
    hint: "Samundar ke theek neeche milne wali theek sakht aur rang dar theek chatanein jin ki apni theek hayaat hoti hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-93",
    word: "Khaan",
    hint: "Pahaar ke theek andar tak theek khod kar theek qeemti theek madniyaat nikalne ka theek silsila.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-94",
    word: "Surang",
    hint: "Pahaar ka seena theek cheer kar ek side se doosri side jane ke liye theek banaya gaya rasta.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-95",
    word: "Daldal",
    hint: "Aisi dangerous kachari theek mitti jis mein paon theek rakhne se insan theek neeche ki taraf theek dhansne lagta hai.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-96",
    word: "Registan",
    hint: "Jidhar dekho bas theek khushk rait nazar theek ati hai aur kanton walay theek pooday hain.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-97",
    word: "Tila",
    hint: "Sehra mein theek hawa udne ki theek wajah se khud theek banne wala theek rait ka chota sa pahaari theek dher.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-98",
    word: "Gird",
    hint: "Bohut theek waqt ki purani theek hawa ke zariye fiza mein milti theek hui barik theek gard aur ghubaar.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-99",
    word: "Pighlao",
    hint: "Baraf aur glacier ko garmi ki theek shiddat se theek pani mein theek tabdeel hone ki makhsoos theek kaifiyat.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-nature-ur-100",
    word: "Bhaap",
    hint: "Pani ke bilkul theek ubalne ke theek darjay par pohanch kar theek safed dhuan theek ban jane ki halat.",
    category: "nature",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
