import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "places" category -- English.
 *
 * All 100 words are common, everyday places an average person would
 * instantly recognize, regardless of difficulty. Difficulty here changes ONLY
 * how directly the hint points at the word -- never how obscure the word itself is:
 *   - easy (40):   the hint states the place's most obvious purpose directly.
 *   - medium (30): the hint points at a related detail/context instead
 *                  of the defining trait, so it takes a moment of thought.
 *   - hard (30):   the hint is oblique -- an unusual angle, minor detail,
 *                  or consequence -- without ever naming the obvious purpose.
 */
export const PLACES_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-places-en-1",
    word: "Hospital",
    hint: "A large building where doctors and nurses treat sick or injured people.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-2",
    word: "School",
    hint: "An institution where children sit in classrooms to learn from teachers.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-3",
    word: "Airport",
    hint: "A facility with runways where passengers board flights to travel overseas.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-4",
    word: "Library",
    hint: "A quiet public building filled with books that you can borrow for free.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-5",
    word: "Bakery",
    hint: "A shop where fresh bread, cakes, and pastries are made and sold.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-6",
    word: "Gym",
    hint: "A building filled with weights and exercise machines for working out.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-7",
    word: "Park",
    hint: "A large public green space with trees, grass, and often a playground.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-8",
    word: "Beach",
    hint: "A sandy shore by the ocean where people go to swim and sunbathe.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-9",
    word: "Supermarket",
    hint: "A large store where you push a cart to buy groceries and household items.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-10",
    word: "Bank",
    hint: "A financial institution where you go to deposit or withdraw money.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-11",
    word: "Post Office",
    hint: "A building where you go to buy stamps and mail letters or packages.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-12",
    word: "Restaurant",
    hint: "A place where you sit down, order food from a menu, and are served by a waiter.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-13",
    word: "Cinema",
    hint: "A theater with a massive screen where audiences watch new movie releases.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-14",
    word: "Zoo",
    hint: "A large park where wild animals are kept in enclosures for public viewing.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-15",
    word: "Hotel",
    hint: "A building where travelers pay to sleep in rented rooms for a few nights.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-16",
    word: "Kitchen",
    hint: "The room in a house equipped with a stove and sink for cooking meals.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-17",
    word: "Bathroom",
    hint: "The room in a house containing a toilet, sink, and shower or tub.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-18",
    word: "Bedroom",
    hint: "The private room in a house where you go to sleep at night.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-19",
    word: "Garage",
    hint: "The enclosed part of a house where you park your car to protect it from the weather.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-20",
    word: "Stadium",
    hint: "A massive outdoor arena with tiered seating for watching professional sports.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-21",
    word: "Cafe",
    hint: "A small, casual establishment that primarily serves coffee, tea, and light snacks.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-22",
    word: "Farm",
    hint: "A large area of land used for growing crops and raising livestock.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-23",
    word: "Office",
    hint: "A professional workspace filled with desks, computers, and meeting rooms.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-24",
    word: "Police Station",
    hint: "The headquarters where law enforcement officers work and hold suspects.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-25",
    word: "Fire Station",
    hint: "A building where emergency responders park their big red trucks and wait for alarms.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-26",
    word: "Prison",
    hint: "A highly secure facility where convicted criminals are locked up to serve their sentences.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-27",
    word: "Playground",
    hint: "An outdoor area specifically designed for children with swings and slides.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-28",
    word: "Swimming Pool",
    hint: "A large man-made basin filled with chlorinated water for aquatic exercise or fun.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-29",
    word: "Train Station",
    hint: "A transport hub with platforms where passengers wait for locomotives.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-30",
    word: "Gas Station",
    hint: "A roadside business where drivers pull in to refuel their vehicles.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-31",
    word: "Mall",
    hint: "A massive indoor shopping complex containing dozens of different retail stores.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-32",
    word: "Barbershop",
    hint: "A specialized salon where men go to get their hair cut and beards trimmed.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-33",
    word: "Amusement Park",
    hint: "A large entertainment venue featuring roller coasters and carnival games.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-34",
    word: "Forest",
    hint: "A large natural area heavily covered with trees and undergrowth.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-35",
    word: "Mountain",
    hint: "A massive natural elevation of the earth's surface, much taller than a hill.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-36",
    word: "River",
    hint: "A large, natural stream of flowing water that runs into an ocean or lake.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-37",
    word: "Island",
    hint: "A piece of land that is completely surrounded by water on all sides.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-38",
    word: "Bridge",
    hint: "A structure built to span across a physical obstacle like a body of water or a valley.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-39",
    word: "Castle",
    hint: "A large, heavily fortified medieval building made of stone, often with a moat.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-places-en-40",
    word: "Graveyard",
    hint: "A dedicated plot of land where dead bodies are buried beneath tombstones.",
    category: "places",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-places-en-41",
    word: "Pharmacy",
    hint: "You hand a slip of paper from your doctor to the counter here to get your pills.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-42",
    word: "Museum",
    hint: "Visitors walk quietly past glass display cases looking at ancient artifacts and dinosaur bones.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-43",
    word: "Aquarium",
    hint: "Families walk through curved glass tunnels while sharks and stingrays swim directly overhead.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-44",
    word: "Basement",
    hint: "The lowest floor of a house, completely below ground level, often used for storage.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-45",
    word: "Attic",
    hint: "The dusty, cramped space just below the sloping roof of a house.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-46",
    word: "Garden",
    hint: "A dedicated patch of soil in the backyard where someone carefully cultivates flowers or vegetables.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-47",
    word: "Balcony",
    hint: "An elevated platform protruding from the side of an apartment building, enclosed by a railing.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-48",
    word: "Theater",
    hint: "People take their assigned seats in the dark as the heavy red curtains pull back from the stage.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-49",
    word: "Factory",
    hint: "Workers in safety gear operate heavy machinery on a massive assembly line.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-50",
    word: "Courtroom",
    hint: "A serious room where a judge bangs a gavel and a jury listens to lawyers argue.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-51",
    word: "Church",
    hint: "A building with a tall steeple, stained glass windows, and rows of wooden pews.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-52",
    word: "Dentist",
    hint: "You lie back in a special chair under a bright light while someone inspects your teeth.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-53",
    word: "Bus Stop",
    hint: "A small covered shelter on the side of the street where commuters wait in the rain.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-54",
    word: "Subway",
    hint: "Commuters swipe a card and descend underground to travel quickly across the city.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-55",
    word: "Car Wash",
    hint: "You sit inside your vehicle while giant soapy brushes aggressively scrub the exterior.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-56",
    word: "Spa",
    hint: "Guests in fluffy white robes come here for massages, mud masks, and relaxation.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-57",
    word: "Casino",
    hint: "A noisy, windowless building filled with flashing slot machines and card tables.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-58",
    word: "Arcade",
    hint: "A loud entertainment center where kids feed tokens into machines to win tickets.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-59",
    word: "Bowling Alley",
    hint: "You must rent special, slippery shoes before throwing a heavy sphere down a wooden lane here.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-60",
    word: "Golf Course",
    hint: "Vast expanses of highly manicured grass featuring sand traps and small holes with flags.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-61",
    word: "Lighthouse",
    hint: "A tall coastal tower that shines a rotating beam into the fog to warn ships away from rocks.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-62",
    word: "Cave",
    hint: "A dark, natural underground chamber filled with stalactites and sleeping bats.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-63",
    word: "Desert",
    hint: "A vast, barren landscape of sand dunes where daytime temperatures soar and water is scarce.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-64",
    word: "Waterfall",
    hint: "A steep drop in a river where the rushing current plunges over a vertical cliff.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-65",
    word: "Lake",
    hint: "A large, still body of fresh water completely surrounded by land, popular for canoeing.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-66",
    word: "Ocean",
    hint: "The massive, unbroken expanse of saltwater that covers most of the Earth's surface.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-67",
    word: "Tunnel",
    hint: "An artificial underground passage dug through a mountain so traffic can pass directly through.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-68",
    word: "Palace",
    hint: "An incredibly grand and opulent residence built specifically to house a monarch or royal family.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-69",
    word: "Laundromat",
    hint: "People without a washer at home bring baskets of dirty clothes and a roll of quarters here.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-places-en-70",
    word: "Bookstore",
    hint: "A retail shop where you can browse the latest hardcover novels before purchasing them.",
    category: "places",
    difficulty: "medium",
    language: "english",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-places-en-71",
    word: "Pet Store",
    hint: "People often come in just to press their faces against the glass and watch the sleeping puppies.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-72",
    word: "Hardware Store",
    hint: "A homeowner attempting a simple plumbing repair on a weekend will inevitably make three trips here.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-73",
    word: "Toy Store",
    hint: "Parents actively try to avoid walking past the entrance so their toddlers don't throw a tantrum.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-74",
    word: "Jewelry Store",
    hint: "Couples nervous about getting engaged will slowly browse the sparkling items in these glass counters.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-75",
    word: "Tailor",
    hint: "You stand on a small pedestal in front of mirrors while someone marks your pant legs with chalk.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-76",
    word: "Butcher",
    hint: "A severely cold room smelling of iron where a worker in a thick apron wields a cleaver.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-77",
    word: "Greenhouse",
    hint: "A completely glass structure that traps heat so delicate tropical flora can survive winter.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-78",
    word: "Barn",
    hint: "A large, rustic wooden structure smelling strongly of hay and manure.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-79",
    word: "Tent",
    hint: "A temporary canvas shelter that relies on aluminum poles and pegs driven into the dirt.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-80",
    word: "Cabin",
    hint: "A remote, rustic dwelling built entirely out of interlocking logs, usually featuring a wood-burning stove.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-81",
    word: "Mansion",
    hint: "An absurdly large and luxurious private residence that likely requires a full-time cleaning staff.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-82",
    word: "Apartment",
    hint: "If your upstairs neighbor is heavy-footed, you will hear their every footstep in this living space.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-83",
    word: "Skyscraper",
    hint: "A towering architectural marvel of steel and glass that dramatically alters a city's skyline.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-84",
    word: "Studio",
    hint: "A highly soundproofed room filled with microphones, mixing boards, and thick acoustic foam on the walls.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-85",
    word: "Laboratory",
    hint: "A sterile environment where professionals in white coats and goggles peer into microscopes and handle beakers.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-86",
    word: "Space Station",
    hint: "A pressurized, orbiting research facility where gravity is non-existent and the views are extraterrestrial.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-87",
    word: "Submarine",
    hint: "A cramped, steel cylinder operating under immense pressure deep beneath the ocean's surface.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-88",
    word: "Ship",
    hint: "A massive, buoyant vessel capable of navigating rough seas for months at a time.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-89",
    word: "Airplane",
    hint: "A pressurized metal tube moving at hundreds of miles per hour thousands of feet in the air.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-90",
    word: "Elevator",
    hint: "People usually stare silently at the changing numbers above the door while standing awkwardly close in here.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-91",
    word: "Escalator",
    hint: "Moving metal stairs that automatically carry shoppers between the different floors of a department store.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-92",
    word: "Rooftop",
    hint: "The highest exterior surface of a building, sometimes converted into a stylish open-air bar in cities.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-93",
    word: "Alleyway",
    hint: "A narrow, often dark passage between brick buildings where restaurants typically leave their dumpsters.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-94",
    word: "Highway",
    hint: "A multi-lane road designed specifically for vehicles traveling at high speeds between cities.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-95",
    word: "Sidewalk",
    hint: "A paved concrete path running directly alongside a road, meant purely for pedestrians.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-96",
    word: "Crosswalk",
    hint: "A set of thick white lines painted on the asphalt indicating where pedestrians have the right-of-way.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-97",
    word: "Roundabout",
    hint: "A circular traffic intersection that often confuses nervous drivers who don't know when to merge.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-98",
    word: "Parking Lot",
    hint: "A vast expanse of asphalt painted with hundreds of parallel white lines.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-99",
    word: "Driveway",
    hint: "The short strip of pavement connecting a residential home's garage to the public street.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-places-en-100",
    word: "Cellar",
    hint: "A dark, cool room beneath a house prized for keeping expensive bottles of wine at the perfect temperature.",
    category: "places",
    difficulty: "hard",
    language: "english",
  },
];
