// lib/fallback-words/jobs/english/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "jobs" category -- English.
 *
 * All 100 words are common, universally recognizable jobs and professions.
 * Difficulty controls ONLY how directly the hint points at the word:
 *   - easy (40):   states the most obvious daily duty or workplace.
 *   - medium (30): points to secondary tools, industry context, or associations.
 *   - hard (30):   oblique angles, indirect consequences, or niche trivia about the role.
 */
export const JOBS_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-jobs-en-1",
    word: "Doctor",
    hint: "A medical professional who diagnoses illnesses and prescribes medicine to sick patients.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-2",
    word: "Teacher",
    hint: "A person who works in a school classroom educating students every day.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-3",
    word: "Police",
    hint: "A uniformed law enforcement officer who catches criminals and patrols the streets.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-4",
    word: "Firefighter",
    hint: "A brave rescue worker who rides a red truck to put out burning buildings.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-5",
    word: "Nurse",
    hint: "A hospital worker who assists doctors and directly cares for recovering patients.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-6",
    word: "Chef",
    hint: "The head cook who prepares all the delicious meals in a restaurant kitchen.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-7",
    word: "Pilot",
    hint: "The highly trained person who flies a massive commercial airplane through the sky.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-8",
    word: "Farmer",
    hint: "An agricultural worker who plants crops, drives a tractor, and raises livestock.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-9",
    word: "Bus Driver",
    hint: "The person who sits behind the large steering wheel taking kids to school.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-10",
    word: "Baker",
    hint: "A person who wakes up incredibly early to make fresh bread and pastries.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-11",
    word: "Waiter",
    hint: "The person who takes your food order and brings plates to your restaurant table.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-12",
    word: "Dentist",
    hint: "A medical specialist who checks your teeth for cavities and cleans them.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-13",
    word: "Actor",
    hint: "A performer who memorizes scripts to play characters in movies and plays.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-14",
    word: "Singer",
    hint: "A musical performer who holds a microphone and performs hit songs on stage.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-15",
    word: "Cashier",
    hint: "The store employee who scans your groceries and hands you your change.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-16",
    word: "Mechanic",
    hint: "A worker covered in grease who repairs broken engines and fixes flat tires.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-17",
    word: "Plumber",
    hint: "The person you urgently call when a water pipe bursts or the toilet overflows.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-18",
    word: "Barber",
    hint: "A professional who uses sharp scissors and clippers to cut men's hair.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-19",
    word: "Carpenter",
    hint: "A skilled builder who uses a hammer and saw to construct things out of wood.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-20",
    word: "Librarian",
    hint: "The person who organizes books and tells people to be quiet in the reading room.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-21",
    word: "Mailman",
    hint: "The postal worker who walks door-to-door delivering letters and packages every day.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-22",
    word: "Astronaut",
    hint: "A highly trained space explorer who wears a pressurized suit and travels in rockets.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-23",
    word: "Lawyer",
    hint: "A legal professional who argues cases in front of a judge to defend their client.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-24",
    word: "Judge",
    hint: "The person wearing a black robe who bangs a gavel to maintain order in the courtroom.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-25",
    word: "Janitor",
    hint: "A custodian who mops the floors, empties the trash, and keeps the building clean.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-26",
    word: "Soldier",
    hint: "A member of the military who wears camouflage and defends their country in combat.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-27",
    word: "Artist",
    hint: "A creative person who uses paintbrushes and canvases to create beautiful paintings.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-28",
    word: "Writer",
    hint: "A person whose entire career consists of typing words to publish novels and stories.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-29",
    word: "Photographer",
    hint: "A person who looks through a lens to capture beautiful pictures with a camera.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-30",
    word: "Vet",
    hint: "An animal doctor who treats sick puppies, kittens, and injured wildlife.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-31",
    word: "Butcher",
    hint: "The professional who uses heavy cleavers to chop and prepare fresh raw meat.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-32",
    word: "Tailor",
    hint: "A person who measures you with a tape and sews custom clothing to fit perfectly.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-33",
    word: "Security",
    hint: "A guard who stands at the entrance of a building to ensure everyone stays safe.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-34",
    word: "Cleaner",
    hint: "A person hired specifically to dust, vacuum, and scrub a house until it sparkles.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-35",
    word: "Architect",
    hint: "The professional who draws up the complex blueprints used to build massive skyscrapers.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-36",
    word: "Electrician",
    hint: "The tradesperson you call when your house loses power or the wiring is sparking.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-37",
    word: "Pharmacist",
    hint: "The person in the white coat behind the drugstore counter who fills your prescriptions.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-38",
    word: "Accountant",
    hint: "A numbers expert who manages finances, balances budgets, and calculates your yearly taxes.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-39",
    word: "Secretary",
    hint: "An office worker who answers phone calls, schedules meetings, and manages the front desk.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-jobs-en-40",
    word: "Surgeon",
    hint: "A specialized doctor who performs complex operations on patients in an operating room.",
    category: "jobs",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (30)
  {
    id: "fallback-jobs-en-41",
    word: "Paramedic",
    hint: "This incredibly fast responder works in the back of a speeding ambulance saving lives.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-42",
    word: "Coach",
    hint: "The person standing on the sidelines with a whistle yelling out plays to the sports team.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-43",
    word: "Referee",
    hint: "The neutral official wearing a striped shirt who throws flags when a game rule is broken.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-44",
    word: "Reporter",
    hint: "The person holding a microphone outside in the rain telling viewers about breaking news on TV.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-45",
    word: "Politician",
    hint: "A public figure who constantly campaigns for your vote to pass new laws in the government.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-46",
    word: "Mayor",
    hint: "The highest-ranking elected official who is entirely in charge of running a single city.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-47",
    word: "President",
    hint: "The elected head of state who lives in the White House and leads the entire nation.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-48",
    word: "Detective",
    hint: "An investigator looking for hidden clues at a crime scene to solve a difficult mystery.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-49",
    word: "Programmer",
    hint: "A tech expert who types thousands of lines of complex code to create computer software.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-50",
    word: "Florist",
    hint: "A shop owner who spends all day trimming stems to arrange beautiful bouquets for weddings.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-51",
    word: "Jeweler",
    hint: "A specialist who uses tiny tools to set sparkling diamonds into expensive gold rings.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-52",
    word: "Zookeeper",
    hint: "The person responsible for feeding the exotic animals and cleaning the enclosures at a wildlife park.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-53",
    word: "Miner",
    hint: "A worker wearing a hard hat with a flashlight who digs deep underground looking for coal.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-54",
    word: "Realtor",
    hint: "The professional who happily gives you a tour of an open house hoping you will buy it.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-55",
    word: "Flight Attendant",
    hint: "The crew member who demonstrates the oxygen masks and serves drinks thousands of feet in the air.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-56",
    word: "Garbage Collector",
    hint: "The essential worker who hangs onto the back of a smelly truck emptying neighborhood bins.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-57",
    word: "Truck Driver",
    hint: "A person who hauls heavy freight across the entire country in an eighteen-wheeler.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-58",
    word: "Taxi Driver",
    hint: "The person you pay to navigate busy city streets to quickly drop you off at the airport.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-59",
    word: "Bartender",
    hint: "The person standing behind the pub counter mixing complicated cocktails and pouring draft beers.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-60",
    word: "Lifeguard",
    hint: "The person wearing sunglasses sitting on a tall chair watching swimmers to prevent anyone from drowning.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-61",
    word: "Valet",
    hint: "The sharply dressed worker who takes your car keys at the restaurant entrance to go park it.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-62",
    word: "Bellhop",
    hint: "The hotel employee who loads all your heavy suitcases onto a brass cart to take them upstairs.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-63",
    word: "Landlord",
    hint: "The person who owns the apartment building and expects you to pay rent on the first of the month.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-64",
    word: "Musician",
    hint: "An artist who spends hours practicing their instrument before performing a live concert.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-65",
    word: "Dancer",
    hint: "A highly athletic performer who learns complex choreography to move perfectly to the music's rhythm.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-66",
    word: "Magician",
    hint: "An illusionist who uses sleight of hand to pull a rabbit out of a hat and amaze the crowd.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-67",
    word: "Clown",
    hint: "A circus performer wearing giant shoes and face paint whose only job is to make children laugh.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-68",
    word: "Scientist",
    hint: "A researcher in a white lab coat looking through a microscope at a petri dish.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-69",
    word: "Designer",
    hint: "A creative professional who sketches out exactly how a new clothing line will look on the runway.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-jobs-en-70",
    word: "Therapist",
    hint: "A mental health professional who listens to your problems and helps you work through emotional issues.",
    category: "jobs",
    difficulty: "medium",
    language: "english",
  },

  // HARD (30)
  {
    id: "fallback-jobs-en-71",
    word: "CEO",
    hint: "The absolute highest-ranking executive sitting in the corner office who makes all major corporate decisions.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-72",
    word: "Translator",
    hint: "A language expert heavily relied upon during international meetings to instantly repeat spoken words in a different tongue.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-73",
    word: "Diplomat",
    hint: "A government official sent entirely to a foreign embassy to peacefully negotiate delicate treaties.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-74",
    word: "Critic",
    hint: "A person whose entire livelihood depends on writing harsh reviews about a newly opened restaurant or movie.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-75",
    word: "Editor",
    hint: "The person behind the scenes ruthlessly cutting paragraphs out of a manuscript to make a book better.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-76",
    word: "Animator",
    hint: "An artist who meticulously draws thousands of sequential frames to bring a cartoon mouse to life.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-77",
    word: "Director",
    hint: 'The person sitting in a canvas chair yelling "Action!" and completely controlling the vision of a film.',
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-78",
    word: "Producer",
    hint: "The person who actually secures the funding, manages the budget, and hires the talent for a massive movie.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-79",
    word: "Choreographer",
    hint: "The unseen visionary who completely maps out the exact sequence of steps for the backup dancers.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-80",
    word: "Stuntman",
    hint: "The highly athletic professional hired to safely jump out of moving cars so the main actor doesn't get hurt.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-81",
    word: "Auditor",
    hint: "The terrifying financial inspector sent by the government to rigorously examine a company's past tax records.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-82",
    word: "Broker",
    hint: "The loud professional on the chaotic trading floor frantically buying and selling stocks for their wealthy clients.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-83",
    word: "Bank Teller",
    hint: "The person standing behind bulletproof glass who counts your cash when you want to make a large deposit.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-84",
    word: "Archaeologist",
    hint: "A researcher who carefully brushes dirt off ancient pottery shards attempting to understand completely ruined civilizations.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-85",
    word: "Geologist",
    hint: "A scientist who constantly studies seismic activity, tectonic plates, and the historical layers hidden inside massive rocks.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-86",
    word: "Meteorologist",
    hint: "The expert analyzing complex radar maps to accurately predict exactly what time a massive hurricane will make landfall.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-87",
    word: "Auctioneer",
    hint: "The incredibly fast-talking person pointing a gavel at the crowd to squeeze the highest possible bid out of them.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-88",
    word: "Coroner",
    hint: "The medical official entirely responsible for examining a deceased body to legally determine the exact cause of death.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-89",
    word: "Conductor",
    hint: "The person holding a thin baton who waves their arms to keep an entire orchestra playing perfectly in sync.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-90",
    word: "Composer",
    hint: "A musical genius who sits completely alone staring at blank sheet music, writing notes that will become a symphony.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-91",
    word: "Sculptor",
    hint: "An artist who spends months continuously chipping away at a massive block of heavy marble with a sharp chisel.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-92",
    word: "Optometrist",
    hint: "The specialist who asks you to stare at a glowing chart and asks 'which lens looks clearer, one or two?'",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-93",
    word: "Dietitian",
    hint: "The professional expert you consult when you need a highly specific meal plan to massively improve your physical health.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-94",
    word: "Biologist",
    hint: "A researcher deeply fascinated by genetics, attempting to understand exactly how living cellular organisms reproduce and evolve.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-95",
    word: "Astronomer",
    hint: "A scientist who works entirely at night, peering through a massive observatory telescope attempting to locate new galaxies.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-96",
    word: "Sailor",
    hint: "A worker who spends months completely isolated on the open ocean swabbing the deck of a massive ship.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-97",
    word: "Welder",
    hint: "A tradesperson wearing a dark protective mask while using intensely hot sparks to fuse two heavy steel plates together.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-98",
    word: "Blacksmith",
    hint: "A traditional artisan who violently hammers glowing hot iron on a heavy anvil to forge metal tools.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-99",
    word: "Lumberjack",
    hint: 'The heavily flannel-clad worker shouting "timber!" right before a massive pine tree completely crashes to the forest floor.',
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-jobs-en-100",
    word: "Exterminator",
    hint: "The person in the hazmat suit you frantically call when you discover a massive termite infestation destroying your walls.",
    category: "jobs",
    difficulty: "hard",
    language: "english",
  },
];
