"use client";

import {
  createContext,
  useCallback,
  useContext,
  useMemo,
  useState,
} from "react";
import type {
  Category,
  Difficulty,
  GameConfig,
  GameMode,
  Player,
  TimerSettings,
} from "@/game/game-types";
import {
  DEFAULT_GAME_CONFIG,
  MAX_PLAYERS,
  validatePlayerName,
} from "@/game/game-rules";
import { generateId } from "@/lib/id";
import { shuffle } from "@/lib/shuffle";

export type PlayerActionResult = { ok: true } | { ok: false; error: string };

type GameSetupContextValue = {
  config: GameConfig;
  setMode: (mode: GameMode) => void;
  setCategory: (category: Category) => void;
  setDifficulty: (difficulty: Difficulty) => void;
  setDiscussionTimer: (patch: Partial<TimerSettings>) => void;
  setVotingTimer: (patch: Partial<TimerSettings>) => void;
  resetConfig: () => void;

  players: Player[];
  addPlayer: (name: string) => PlayerActionResult;
  editPlayer: (id: string, name: string) => PlayerActionResult;
  removePlayer: (id: string) => void;
  randomizePlayers: () => void;
  resetPlayers: () => void;
};

const GameSetupContext = createContext<GameSetupContextValue | null>(null);

/**
 * Holds the in-progress `GameConfig` while the player moves through the
 * setup flow (Setup -> Players -> ...). This is plain React state living
 * in a provider mounted in the root layout, so it survives client-side
 * navigation between routes without needing a state library, a server
 * round-trip, or URL query strings.
 *
 * A hard refresh intentionally resets to defaults for the MVP (see
 * DEFAULT_GAME_CONFIG) -- nothing here is persisted to disk.
 */
export function GameSetupProvider({ children }: { children: React.ReactNode }) {
  const [config, setConfig] = useState<GameConfig>(DEFAULT_GAME_CONFIG);

  const setMode = useCallback((mode: GameMode) => {
    setConfig((prev) => ({ ...prev, mode }));
  }, []);

  const setCategory = useCallback((category: Category) => {
    setConfig((prev) => ({ ...prev, category }));
  }, []);

  const setDifficulty = useCallback((difficulty: Difficulty) => {
    setConfig((prev) => ({ ...prev, difficulty }));
  }, []);

  const setDiscussionTimer = useCallback((patch: Partial<TimerSettings>) => {
    setConfig((prev) => ({
      ...prev,
      options: {
        ...prev.options,
        discussionTimer: { ...prev.options.discussionTimer, ...patch },
      },
    }));
  }, []);

  const setVotingTimer = useCallback((patch: Partial<TimerSettings>) => {
    setConfig((prev) => ({
      ...prev,
      options: {
        ...prev.options,
        votingTimer: { ...prev.options.votingTimer, ...patch },
      },
    }));
  }, []);

  const resetConfig = useCallback(() => {
    setConfig(DEFAULT_GAME_CONFIG);
  }, []);

  // Players (Screen 3). Kept in the same provider as `config` -- both are
  // just in-progress setup state that needs to survive client-side
  // navigation between /setup and /players without a state library.
  const [players, setPlayers] = useState<Player[]>([]);

  const addPlayer = useCallback((name: string): PlayerActionResult => {
    let result: PlayerActionResult = {
      ok: false,
      error: "Enter a player name.",
    };
    setPlayers((prev) => {
      if (prev.length >= MAX_PLAYERS) {
        result = { ok: false, error: "Maximum 12 players." };
        return prev;
      }
      const check = validatePlayerName(name, prev);
      if (!check.valid) {
        result = { ok: false, error: check.error };
        return prev;
      }
      result = { ok: true };
      return [...prev, { id: generateId(), name: check.value }];
    });
    return result;
  }, []);

  const editPlayer = useCallback(
    (id: string, name: string): PlayerActionResult => {
      let result: PlayerActionResult = {
        ok: false,
        error: "Enter a player name.",
      };
      setPlayers((prev) => {
        const check = validatePlayerName(name, prev, id);
        if (!check.valid) {
          result = { ok: false, error: check.error };
          return prev;
        }
        result = { ok: true };
        return prev.map((p) => (p.id === id ? { ...p, name: check.value } : p));
      });
      return result;
    },
    [],
  );

  const removePlayer = useCallback((id: string) => {
    setPlayers((prev) => prev.filter((p) => p.id !== id));
  }, []);

  // Reorders the player array only -- IDs (and therefore identity) are
  // never regenerated by a shuffle. See lib/shuffle.ts.
  const randomizePlayers = useCallback(() => {
    setPlayers((prev) => shuffle(prev));
  }, []);

  const resetPlayers = useCallback(() => {
    setPlayers([]);
  }, []);

  const value = useMemo(
    () => ({
      config,
      setMode,
      setCategory,
      setDifficulty,
      setDiscussionTimer,
      setVotingTimer,
      resetConfig,
      players,
      addPlayer,
      editPlayer,
      removePlayer,
      randomizePlayers,
      resetPlayers,
    }),
    [
      config,
      setMode,
      setCategory,
      setDifficulty,
      setDiscussionTimer,
      setVotingTimer,
      resetConfig,
      players,
      addPlayer,
      editPlayer,
      removePlayer,
      randomizePlayers,
      resetPlayers,
    ],
  );

  return (
    <GameSetupContext.Provider value={value}>
      {children}
    </GameSetupContext.Provider>
  );
}

export function useGameSetup() {
  const ctx = useContext(GameSetupContext);
  if (!ctx) {
    throw new Error("useGameSetup must be used within a GameSetupProvider");
  }
  return ctx;
}
