import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "food" category -- English.
 *
 * All 100 words are common, everyday foods an average person would
 * instantly recognize, regardless of difficulty (see WORD_QUALITY_RULE
 * in app/api/round/generate/route.ts for the same rule applied to
 * AI-generated rounds). Difficulty here changes ONLY how directly the
 * hint points at the word -- never how obscure the word itself is:
 *   - easy (40):   the hint states the word's most obvious trait directly.
 *   - medium (30): the hint points at a related detail/context instead
 *                  of the defining trait, so it takes a moment of thought.
 *   - hard (30):   the hint is oblique -- an unusual angle, association,
 *                  or consequence -- without ever naming the word.
 */
export const FOOD_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  {
    id: "fallback-food-en-1",
    word: "Apple",
    hint: "A common fruit that can be red, green, or yellow.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-2",
    word: "Banana",
    hint: "A soft yellow fruit that is easy to peel.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-3",
    word: "Mango",
    hint: "A sweet, juicy fruit that is very popular in summer.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-4",
    word: "Orange",
    hint: "A round citrus fruit with a bright orange peel.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-5",
    word: "Grapes",
    hint: "Small round fruits that grow together in bunches.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-6",
    word: "Watermelon",
    hint: "A large green fruit with juicy red flesh inside.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-7",
    word: "Strawberry",
    hint: "A small red fruit covered in tiny seeds.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-8",
    word: "Pineapple",
    hint: "A spiky tropical fruit with a sweet yellow inside.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-9",
    word: "Pear",
    hint: "A green or yellow fruit shaped wider at the bottom.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-10",
    word: "Peach",
    hint: "A soft, fuzzy-skinned fruit with a pit inside.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-11",
    word: "Lemon",
    hint: "A sour yellow citrus fruit.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-12",
    word: "Coconut",
    hint: "A large hard fruit with white flesh and water inside.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-13",
    word: "Bread",
    hint: "A baked food often eaten with breakfast or used for sandwiches.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-14",
    word: "Rice",
    hint: "A staple grain that is boiled and eaten as a side dish.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-15",
    word: "Pasta",
    hint: "An Italian food made from wheat and shaped into noodles.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-16",
    word: "Pizza",
    hint: "A round baked dish topped with cheese and sauce.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-17",
    word: "Burger",
    hint: "A sandwich with a round bun and a meat patty inside.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-18",
    word: "Sandwich",
    hint: "Two slices of bread with filling in between.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-19",
    word: "Cheese",
    hint: "A dairy product made from milk, often used on pizza.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-20",
    word: "Egg",
    hint: "Laid by hens, often boiled or fried for breakfast.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-21",
    word: "Milk",
    hint: "A white drink that comes from cows.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-22",
    word: "Cake",
    hint: "A sweet baked dessert often served at birthdays.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-23",
    word: "Cookie",
    hint: "A small, sweet baked treat.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-24",
    word: "Chocolate",
    hint: "A sweet treat made from cocoa.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-25",
    word: "Ice Cream",
    hint: "A frozen sweet dessert served in cones or bowls.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-26",
    word: "Popcorn",
    hint: "Corn kernels that puff up when heated, often eaten at movies.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-27",
    word: "Chips",
    hint: "Thin, crispy slices of fried or baked potato.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-28",
    word: "Chicken",
    hint: "A common type of poultry meat.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-29",
    word: "Fish",
    hint: "A type of seafood that lives in water.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-30",
    word: "Potato",
    hint: "A starchy vegetable that grows underground.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-31",
    word: "Tomato",
    hint: "A red, round fruit often used in salads and sauces.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-32",
    word: "Onion",
    hint: "A vegetable that often makes people cry when cut.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-33",
    word: "Carrot",
    hint: "A long orange vegetable that rabbits are said to love.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-34",
    word: "Coffee",
    hint: "A hot dark drink made from roasted beans.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-35",
    word: "Tea",
    hint: "A hot drink made by steeping leaves in water.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-36",
    word: "Juice",
    hint: "A drink made by squeezing fruit.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-37",
    word: "Water",
    hint: "A clear drink everyone needs to survive.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-38",
    word: "Butter",
    hint: "A soft yellow spread made from milk.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-39",
    word: "Honey",
    hint: "A sweet golden liquid made by bees.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-40",
    word: "Sugar",
    hint: "A sweet white substance used to sweeten food.",
    category: "food",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-food-en-41",
    word: "Kiwi",
    hint: "Its fuzzy brown skin hides a bright green center.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-42",
    word: "Papaya",
    hint: "This orange-fleshed fruit is often paired with lime for breakfast.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-43",
    word: "Pomegranate",
    hint: "Cutting this open reveals hundreds of small, juicy seeds.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-44",
    word: "Plum",
    hint: "A small stone fruit often dried to make a wrinkly snack.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-45",
    word: "Guava",
    hint: "A tropical fruit whose seeds are often eaten along with the flesh.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-46",
    word: "Yogurt",
    hint: "This thick, tangy dairy food is often eaten with granola.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-47",
    word: "Pancake",
    hint: "Stacked and drizzled with syrup for a weekend breakfast.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-48",
    word: "Waffle",
    hint: "Known for its grid-shaped pockets that hold syrup well.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-49",
    word: "Donut",
    hint: "A fried, ring-shaped treat often glazed or sprinkled.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-50",
    word: "Muffin",
    hint: "A single-serving baked good, often studded with berries.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-51",
    word: "Ketchup",
    hint: "A tangy red condiment squeezed onto fries.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-52",
    word: "Mustard",
    hint: "A tangy yellow condiment often paired with hot dogs.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-53",
    word: "Mayonnaise",
    hint: "A creamy white spread used in many sandwiches.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-54",
    word: "Jam",
    hint: "Made by cooking fruit down with sugar, then spread on toast.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-55",
    word: "Cereal",
    hint: "Eaten from a bowl in the morning, usually with milk.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-56",
    word: "Oatmeal",
    hint: "A warm breakfast made from boiled grains.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-57",
    word: "Toast",
    hint: "Bread that has been browned by heat.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-58",
    word: "Bacon",
    hint: "A crispy strip of meat often served alongside eggs.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-59",
    word: "Sausage",
    hint: "Ground meat stuffed into a long casing.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-60",
    word: "Beef",
    hint: "Meat that comes from cattle.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-61",
    word: "Shrimp",
    hint: "A small curled shellfish often grilled or fried.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-62",
    word: "Steak",
    hint: "A thick cut of meat often grilled to a specific level of doneness.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-63",
    word: "Curry",
    hint: "A saucy dish flavored heavily with spices, often served with rice.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-64",
    word: "Noodles",
    hint: "Long thin strands often stir-fried or served in broth.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-65",
    word: "Sushi",
    hint: "Rolled and often served with a side of soy sauce.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-66",
    word: "Taco",
    hint: "A folded shell filled with meat, cheese, and vegetables.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-67",
    word: "Cucumber",
    hint: "A cool, watery vegetable often sliced into salads.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-68",
    word: "Spinach",
    hint: "A leafy green vegetable that made a famous cartoon sailor strong.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-69",
    word: "Broccoli",
    hint: "A tree-shaped green vegetable many kids try to avoid.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-70",
    word: "Corn",
    hint: "Grows on a tall stalk and is often eaten on the cob.",
    category: "food",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-food-en-71",
    word: "Cherry",
    hint: "Often placed on top as the finishing touch of a dessert.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-72",
    word: "Fig",
    hint: "A soft fruit whose dried version is a popular snack in baked goods.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-73",
    word: "Blueberry",
    hint: "Small and round, this fruit stains fingers a deep shade.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-74",
    word: "Flour",
    hint: "Ground fine enough to disappear invisibly into dough.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-75",
    word: "Salt",
    hint: "So essential it was once used as currency in ancient trade.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-76",
    word: "Pepper",
    hint: "Its tiny grains bring a sharp bite when ground fresh.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-77",
    word: "Oil",
    hint: "Poured into a pan before anything else can be cooked.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-78",
    word: "Peanut Butter",
    hint: "A spread that famously sticks to the roof of the mouth.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-79",
    word: "Pickle",
    hint: "Started as one vegetable, then spent time soaking in brine.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-80",
    word: "Garlic",
    hint: "Said to keep vampires away in old folk tales.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-81",
    word: "Ginger",
    hint: "Its root has a sharp bite and settles an upset stomach.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-82",
    word: "Lentils",
    hint: "Tiny discs that swell up after simmering for a while.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-83",
    word: "Beans",
    hint: "A children's rhyme claims these make you toot.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-84",
    word: "Mushroom",
    hint: "Not a plant, though it often hides in the vegetable aisle.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-85",
    word: "Pumpkin",
    hint: "Carved into faces once a year, before being tossed in pies.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-86",
    word: "Eggplant",
    hint: "Deep purple on the outside, surprisingly spongy on the inside.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-87",
    word: "Chili",
    hint: "A tiny pod that can bring tears to an unsuspecting eater.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-88",
    word: "Dumpling",
    hint: "Wrapped, pleated, then steamed or fried until the edges crisp.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-89",
    word: "Burrito",
    hint: "Wrapped tightly enough to eat entirely with one hand.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-90",
    word: "Omelette",
    hint: "Whisked, poured, and folded over its own filling.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-91",
    word: "Kebab",
    hint: "Threaded onto a skewer before hitting the grill.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-92",
    word: "Smoothie",
    hint: "Blended until every chunk disappears into one thick drink.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-93",
    word: "Milkshake",
    hint: "Thick enough that a straw sometimes struggles to pull it up.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-94",
    word: "Lemonade",
    hint: "A childhood drink stand's signature offering on a hot day.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-95",
    word: "Soda",
    hint: "Its bubbles come from carbon dioxide trapped under pressure.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-96",
    word: "Soup",
    hint: "Best eaten with a spoon, straight from a warm bowl.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-97",
    word: "Salad",
    hint: "Tossed together cold, usually the healthy option on a menu.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-98",
    word: "Peas",
    hint: "Tiny green spheres that roll right off a fork.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-99",
    word: "Coconut Water",
    hint: "Drained straight from inside a tropical shell.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-food-en-100",
    word: "Cabbage",
    hint: "Layer after layer wraps around a tightly packed core.",
    category: "food",
    difficulty: "hard",
    language: "english",
  },
];
