// lib/fallback-words/animals/english/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "animals" category -- English.
 *
 * All 100 words are common, everyday animals an average person would
 * instantly recognize, regardless of difficulty. Difficulty here changes
 * ONLY how directly the hint points at the word:
 *   - easy (40):   the hint states the word's most obvious trait directly.
 *   - medium (30): the hint points at a related detail/context instead.
 *   - hard (30):   the hint is oblique -- an unusual angle, association,
 *                  or consequence -- without ever naming the word directly.
 */
export const ANIMALS_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-animals-en-1",
    word: "Dog",
    hint: "A highly popular household pet known for its loyalty and barking.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-2",
    word: "Cat",
    hint: "A small furry household pet that purrs and catches mice.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-3",
    word: "Lion",
    hint: "The large wild feline famously known as the king of the jungle.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-4",
    word: "Elephant",
    hint: "A massive gray mammal with a long trunk and large floppy ears.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-5",
    word: "Giraffe",
    hint: "A tall African animal with an incredibly long neck and spots.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-6",
    word: "Zebra",
    hint: "An African equine completely covered in distinct black and white stripes.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-7",
    word: "Monkey",
    hint: "A playful primate with a long tail that swings from trees.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-8",
    word: "Bear",
    hint: "A large, heavy wild mammal with thick fur that famously loves honey.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-9",
    word: "Horse",
    hint: "A large hooved animal traditionally used for riding and pulling carriages.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-10",
    word: "Cow",
    hint: "A farm animal that goes moo and provides milk.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-11",
    word: "Pig",
    hint: "A pink farm animal known for rolling around in mud.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-12",
    word: "Sheep",
    hint: "A fluffy farm animal whose thick coat is sheared for wool.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-13",
    word: "Goat",
    hint: "A horned farm animal known for eating almost anything it finds.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-14",
    word: "Duck",
    hint: "A common waterbird that quacks and has webbed feet.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-15",
    word: "Turkey",
    hint: "A large bird famously served as the main dish on Thanksgiving.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-16",
    word: "Eagle",
    hint: "A majestic bird of prey that serves as a symbol of American freedom.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-17",
    word: "Owl",
    hint: "A nocturnal bird that hoots and has very large, round eyes.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-18",
    word: "Penguin",
    hint: "A flightless bird that lives in the snow, waddles, and swims.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-19",
    word: "Dolphin",
    hint: "A highly intelligent, playful marine mammal known for leaping out of the water.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-20",
    word: "Whale",
    hint: "The absolute largest marine mammal in the ocean.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-21",
    word: "Shark",
    hint: "A fearsome ocean predator with a dorsal fin that sticks out of the water.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-22",
    word: "Octopus",
    hint: "An intelligent sea creature with a soft body and eight long tentacles.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-23",
    word: "Crab",
    hint: "A hard-shelled crustacean with pincers that walks sideways on the beach.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-24",
    word: "Frog",
    hint: "A small green amphibian that leaps and croaks near ponds.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-25",
    word: "Snake",
    hint: "A long, completely legless reptile that slithers and hisses.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-26",
    word: "Turtle",
    hint: "A slow-moving reptile carrying a hard, dome-like shell on its back.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-27",
    word: "Crocodile",
    hint: "A large, scaly aquatic reptile with a dangerous bite.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-28",
    word: "Rabbit",
    hint: "A small furry creature with long ears that hops and loves carrots.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-29",
    word: "Mouse",
    hint: "A tiny rodent with a long tail that famously loves cheese.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-30",
    word: "Squirrel",
    hint: "A bushy-tailed rodent that climbs trees and buries acorns in the yard.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-31",
    word: "Kangaroo",
    hint: "An Australian marsupial that hops and carries its babies in a pouch.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-32",
    word: "Panda",
    hint: "A large, black-and-white bear native to China that eats bamboo.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-33",
    word: "Gorilla",
    hint: "A massive, powerful ape known for walking on its knuckles and beating its chest.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-34",
    word: "Rhino",
    hint: "A large, heavily built mammal with a huge horn on the center of its nose.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-35",
    word: "Hippo",
    hint: "A massive, mostly aquatic river mammal with a huge yawning mouth.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-36",
    word: "Camel",
    hint: "A tall desert animal that stores fat in the humps on its back.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-37",
    word: "Spider",
    hint: "An eight-legged arachnid that spins sticky webs to catch prey.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-38",
    word: "Ant",
    hint: "A tiny, hardworking insect that lives in large underground colonies.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-39",
    word: "Bee",
    hint: "A buzzing flying insect that collects nectar to make honey.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-animals-en-40",
    word: "Butterfly",
    hint: "A colorful flying insect with large wings that develops from a caterpillar.",
    category: "animals",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (30)
  {
    id: "fallback-animals-en-41",
    word: "Tiger",
    hint: "This large jungle feline is completely covered in black stripes.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-42",
    word: "Wolf",
    hint: "Known for hunting in highly organized packs and howling at the full moon.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-43",
    word: "Fox",
    hint: "Frequently portrayed in ancient fables and fairytales as a very cunning trickster.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-44",
    word: "Deer",
    hint: "The males of this woodland species grow large, branching antlers every year.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-45",
    word: "Chicken",
    hint: "This specific bird is the absolute most common source of breakfast eggs globally.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-46",
    word: "Ostrich",
    hint: "The fastest runner on two legs in the entire world, though it cannot take flight.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-47",
    word: "Flamingo",
    hint: "This tall wading bird gets its vibrant pink color directly from its crustacean diet.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-48",
    word: "Parrot",
    hint: "A colorful tropical bird kept in cages, famous for mimicking human speech.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-49",
    word: "Pigeon",
    hint: "A common grey city bird frequently seen scavenging for crumbs in public squares.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-50",
    word: "Swan",
    hint: "A highly graceful, long-necked white bird often found elegantly swimming in ornamental lakes.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-51",
    word: "Lobster",
    hint: "A luxury seafood crustacean that turns bright red only when boiled.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-52",
    word: "Toad",
    hint: "An amphibian similar to its leaping cousin, but covered in dry, bumpy skin.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-53",
    word: "Alligator",
    hint: "A swamp reptile frequently confused with its larger cousin, distinguished by a wider, U-shaped snout.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-54",
    word: "Rat",
    hint: "A rodent heavily associated with city sewers and running through scientific mazes.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-55",
    word: "Beaver",
    hint: "A large river rodent famous for chewing down trees to build wooden dams.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-56",
    word: "Raccoon",
    hint: "A nocturnal scavenger recognized by a distinct, bandit-like mask pattern across its face.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-57",
    word: "Skunk",
    hint: "A black and white critter known entirely for spraying a terrible odor when threatened.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-58",
    word: "Porcupine",
    hint: "A slow-moving woodland creature completely covered in sharp, defensive quills.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-59",
    word: "Hedgehog",
    hint: "A small, spiky pet that instinctively rolls itself into a tight ball when scared.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-60",
    word: "Bat",
    hint: "The absolute only mammal in the world naturally capable of true and sustained flight.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-61",
    word: "Koala",
    hint: "A slow-moving Australian tree dweller that survives primarily by eating toxic eucalyptus leaves.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-62",
    word: "Chimpanzee",
    hint: "Considered our absolute closest living genetic relative in the primate family tree.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-63",
    word: "Cheetah",
    hint: "The absolute fastest land mammal on the planet during short sprints.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-64",
    word: "Leopard",
    hint: "A wild big cat famous for resting high up in trees and its distinct rosette-shaped spots.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-65",
    word: "Donkey",
    hint: "Often used as a reliable pack animal and easily recognized by its loud braying sound.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-66",
    word: "Buffalo",
    hint: "A large, heavily-built wild bovid that historically roamed the American plains in massive herds.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-67",
    word: "Moose",
    hint: "The largest living member of the deer family, sporting massive, broad, flat antlers.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-68",
    word: "Mosquito",
    hint: "A tiny flying pest mostly known for leaving intensely itchy, swollen bites on humans.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-69",
    word: "Fly",
    hint: "A highly common, winged nuisance constantly attracted to garbage bins and exposed food.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-animals-en-70",
    word: "Cockroach",
    hint: "An incredibly resilient household pest that famously scurries into the cracks when you turn the lights on.",
    category: "animals",
    difficulty: "medium",
    language: "english",
  },

  // HARD (30)
  {
    id: "fallback-animals-en-71",
    word: "Panther",
    hint: "A sleek, completely black big cat famous for its stealth in the jungle canopy.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-72",
    word: "Llama",
    hint: "High-altitude pack beasts from South America that are notoriously known to spit when annoyed.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-73",
    word: "Alpaca",
    hint: "Similar to their larger spitting cousins, but primarily bred for their incredibly soft, luxurious fiber.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-74",
    word: "Mule",
    hint: "A strong, famously stubborn, and sterile hybrid offspring created by crossing two different working equines.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-75",
    word: "Bison",
    hint: "Often historically hunted by Native Americans for winter hides and meat out on the great prairies.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-76",
    word: "Chipmunk",
    hint: "A tiny, striped woodland creature notorious for stuffing its cheek pouches absolutely full of nuts.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-77",
    word: "Orangutan",
    hint: "A highly intelligent, red-haired great ape native exclusively to the rainforests of Indonesia and Malaysia.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-78",
    word: "Hyena",
    hint: "A savanna scavenger heavily associated with a vocalization resembling unsettling, maniacal laughter.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-79",
    word: "Baboon",
    hint: "A large, aggressive, ground-dwelling primate recognized by its distinctively hairless, brightly colored rear end.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-80",
    word: "Meerkat",
    hint: "Highly social desert dwellers that stand completely upright on their hind legs to keep watch for danger.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-81",
    word: "Gazelle",
    hint: "A swift, slender leaping prey species frequently seen being chased by apex predators in nature documentaries.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-82",
    word: "Lemur",
    hint: "A wide-eyed, ring-tailed primate found entirely in the wild only on the isolated island of Madagascar.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-83",
    word: "Sloth",
    hint: "An incredibly lethargic rainforest canopy dweller that moves so slowly it occasionally grows green algae in its fur.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-84",
    word: "Armadillo",
    hint: "A creature protected by a unique leathery armor shell that can defensively roll itself into a tight sphere.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-85",
    word: "Platypus",
    hint: "An unusual venomous, egg-laying mammal with a flat bill resembling a famous quacking pond bird.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-86",
    word: "Walrus",
    hint: "A massive, blubbery Arctic marine mammal easily distinguished by its exceptionally long, impressive ivory tusks.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-87",
    word: "Seal",
    hint: "A sleek marine mammal that barks, historically popular for balancing rubber balls on its nose at old circuses.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-88",
    word: "Otter",
    hint: "A playful, water-loving mammal that famously holds hands with its partner while sleeping to avoid drifting apart.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-89",
    word: "Seahorse",
    hint: "A small, upright-swimming ocean creature where the male famously carries the eggs and gives birth to the young.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-90",
    word: "Stingray",
    hint: "A flat, bottom-dwelling sea creature equipped with a dangerously venomous barb on the end of its whip-like tail.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-91",
    word: "Squid",
    hint: "A deep-sea cephalopod that defends itself by suddenly shooting out a blinding cloud of dark ink.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-92",
    word: "Jellyfish",
    hint: "A translucent, entirely brainless ocean drifter equipped with long, trailing, stinging tentacles.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-93",
    word: "Starfish",
    hint: "A marine echinoderm typically possessing five arms, biologically capable of regenerating completely lost limbs.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-94",
    word: "Grasshopper",
    hint: "A leaping green insect known for creating a distinct chirping sound by rapidly rubbing its long legs together.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-95",
    word: "Cricket",
    hint: "A nocturnal insect whose persistent chirping is heavily used in pop culture to indicate an awkward silence.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-96",
    word: "Beetle",
    hint: "An incredibly diverse insect group characterized by having hard, shell-like front wings protecting their bodies.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-97",
    word: "Snail",
    hint: "A slow-moving garden gastropod that quickly retreats into a distinct spiral shell when touched.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-98",
    word: "Worm",
    hint: "A limbless, soft-bodied invertebrate vital for aerating garden soil, often seen covering sidewalks right after heavy rain.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-99",
    word: "Scorpion",
    hint: "An arachnid featuring grasping pincers and a segmented tail topped with a highly venomous stinger.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-animals-en-100",
    word: "Centipede",
    hint: "A long, segmented, venomous crawler notoriously named for allegedly having exactly one hundred legs.",
    category: "animals",
    difficulty: "hard",
    language: "english",
  },
];
