import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "random-objects" category -- Roman Urdu.
 *
 * 100 words drawn from everyday Pakistani household items, kitchen tools,
 * and cultural objects -- every one of them something an average Roman
 * Urdu-speaking player would instantly recognize.
 * As with the English list, difficulty only changes how directly the hint
 * points at the word, never how obscure the word itself is.
 * Hints are written in natural Roman Urdu using only Latin letters.
 */
export const RANDOM_OBJECTS_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-random-objects-ur-1",
    word: "Lota",
    hint: "Washroom mein istinja ke liye istemal hone wala plastic ka bartan.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-2",
    word: "Charpai",
    hint: "Sone aur baithne ke liye banayi gayi rassi aur lakri ki manji.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-3",
    word: "Jharoo",
    hint: "Ghar mein farsh ki safai aur kachra nikalne ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-4",
    word: "Tawa",
    hint: "Chulhe ke oopar rakha jane wala gol aur chapti lohe ka bartan jis par roti pakti hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-5",
    word: "Belan",
    hint: "Lakri ka danda jis se aate ke paere ko patli roti ki shakal di jati hai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-6",
    word: "Chimta",
    hint: "Garam roti ko tawe se pakarne aur palatne ke liye lohe ka tool.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-7",
    word: "Balti",
    hint: "Nahanay ke liye pani bhar kar rakhne wala bara plastic ka dabba.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-8",
    word: "Pankha",
    hint: "Garmi mein hawa lene ke liye chhat par lagne wali machine.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-9",
    word: "Istiri",
    hint: "Dhule hue kapron ki silwaten nikalne aur unhe press karne wali garm cheez.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-10",
    word: "Takkiya",
    hint: "Sote waqt sar ke neechay rakha jane wala naram aur gadday dar kapra.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-11",
    word: "Razai",
    hint: "Sardiyon ki raat mein thand se bachne ke liye oopar lene wala bhari cover.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-12",
    word: "Kambal",
    hint: "Sardiyon mein sote waqt ohrne wala garam aur mota kapra.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-13",
    word: "Chappal",
    hint: "Ghar ke andar paon mein pehnne wala mamooli joota.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-14",
    word: "Shalwar",
    hint: "Qameez ke neechay pehne jane wala hamara riwayati libaas.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-15",
    word: "Qameez",
    hint: "Jism ke oopari hissay par pehnne wala collar aur astin wala kapra.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-16",
    word: "Dupatta",
    hint: "Aurten sar dhakne aur gale mein dalne ke liye ye lamba kapra istemal karti hain.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-17",
    word: "Tasbeeh",
    hint: "Dhane aur motiyon ki lari jis par log zikr aur wird karte hain.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-18",
    word: "Janamaz",
    hint: "Namaz parhne ke liye zameen par bichaya jane wala pak kapra ya chatai.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-19",
    word: "Topi",
    hint: "Namaz parhte waqt mard apne sar par jo dhakkan pehnte hain.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-20",
    word: "Surma",
    hint: "Aankhon mein lagaya jane wala kala powder jo siliyon se lagate hain.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-21",
    word: "Mehndi",
    hint: "Hathon par khubsurat design banane ke liye cone se lagaya jane wala rang.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-22",
    word: "Chooriyan",
    hint: "Kalaai mein pehni jane wali sheeshe ki gol khubsurat zewar.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-23",
    word: "Jhumka",
    hint: "Kaan mein pehnne wala latakta hua khubsurat zewar.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-24",
    word: "Kangi",
    hint: "Uljhe hue balon ko theek karne aur banane wala danda numma plastic.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-25",
    word: "Sheesha",
    hint: "Subah tyar hote waqt apna chehra dekhne ke liye is mein dekhte hain.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-26",
    word: "Sabun",
    hint: "Nahanay ya hath dhone ke liye istemal hone wali jhaag dar tikiya.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-27",
    word: "Toiliya",
    hint: "Ghusl ke baad jism ko khushk karne wala mota kapra.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-28",
    word: "Miswak",
    hint: "Dant saaf karne ke liye sunnat ke mutabiq istemal hone wali peelu ki lakri.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-29",
    word: "Bori",
    hint: "Aanta ya chawal bhar kar rakhne wala patsan ka bara thela.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-30",
    word: "Rassi",
    hint: "Kapre sukhane ya kisi cheez ko mazbooti se bandhne wali doori.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-31",
    word: "Taala",
    hint: "Ghar se bahar jate waqt darwaze ko lock karne ke liye lagate hain.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-32",
    word: "Chabi",
    hint: "Lock ko kholne ke liye istemal hone wala lohe ka chota purza.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-33",
    word: "Daig",
    hint: "Shadi ya niyaz mein bohat zyada chawal pakanay wala bohut bada bartan.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-34",
    word: "Chamcha",
    hint: "Salan khane ya cheeni hilanay ke liye istemal hone wala chota bartan.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-35",
    word: "Pyala",
    hint: "Chai peenay ya soup khane ke liye chota aur gehra bartan.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-36",
    word: "Tokri",
    hint: "Phal ya sabziyan dhone aur rakhne ke liye chhed wala dabba.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-37",
    word: "Matka",
    hint: "Garmiyon mein pani ko thanda rakhne wala mitti ka gol bartan.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-38",
    word: "Surahi",
    hint: "Lambi gardan wala mitti ka bartan jis mein dastar khwan par pani pesh karte hain.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-39",
    word: "Gadda",
    hint: "Bed ke oopar bichaya jane wala naram aur mota form ka hissa.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-40",
    word: "Danda",
    hint: "Chor ko marne ya kuttay ko bhagane ke liye moti lakri ka tukra.",
    category: "random-objects",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-random-objects-ur-41",
    word: "Sil Batta",
    hint: "Chatni aur mirchain peesne ke liye farsh par rakha jane wala pathar.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-42",
    word: "Channi",
    hint: "Patti ko cup mein jane se roknay ke liye chai udelte waqt lagate hain.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-43",
    word: "Dastarkhwan",
    hint: "Zameen par bicha kar farsh par khana khane ke liye istemal hota hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-44",
    word: "Changer",
    hint: "Pakane ke baad tazi rotiyon ko bacha kar rakhne wali khajur ki bani tokri.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-45",
    word: "Peerhi",
    hint: "Sehan mein baith kar aanta ghoondne ya kapre dhone ki lakri ki choti kursi.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-46",
    word: "Moora",
    hint: "Bans aur kano ki bani hui baithne wali goal si riwayati kursi.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-47",
    word: "Sandooq",
    hint: "Jahaiz ka saman aur purane joray mehfooz rakhne wala purane zamane ka lohe ka box.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-48",
    word: "Almari",
    hint: "Kamre ke andar kapron ko latkane aur teh karke rakhne wali qabza dar cheez.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-49",
    word: "Mom Batti",
    hint: "Andhera hone par roshni ke liye isay jalaya jata hai jo ahista ahista pighalti hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-50",
    word: "Machis",
    hint: "Choti si dabiya jis ki tili ragar kar chulha jalaya jata hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-51",
    word: "Laltain",
    hint: "Mitti ka tel daal kar is shishay wali roshni ko purane zamane mein jalate thay.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-52",
    word: "UPS",
    hint: "Load shedding hone par light aur pankha is battery wali machine se chalte hain.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-53",
    word: "Generator",
    hint: "Shor machane wali machine jis mein petrol daal kar bijli banayi jati hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-54",
    word: "Switch",
    hint: "Deewar par laga plastic ka button jise dabane se light on ya off hoti hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-55",
    word: "Taar",
    hint: "Meter se le kar bulb tak current is cable ke zariye travel karta hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-56",
    word: "Shopper",
    hint: "Bazaar se khareedari ke baad samaan uthane wali plastic ki thaili.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-57",
    word: "Lifafa",
    hint: "Khat dalne ya shadi mein salami ke paise dene ka kaghaz ka cover.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-58",
    word: "Chatai",
    hint: "Plastic ya patton se bun kar banayi gayi sasti matt jo farsh par bichate hain.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-59",
    word: "Qaleen",
    hint: "Drawing room ki khubsurti barhane ke liye farsh par bichne wala dhagon wala carpet.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-60",
    word: "Parda",
    hint: "Khidkiyon par latkaya jane wala kapra takay bahar se koi andar na dekh sake.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-61",
    word: "Paranda",
    hint: "Aurten apne balon ki choti mein neechay lagane ke liye is rang barange dhage ko banti hain.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-62",
    word: "Toti",
    hint: "Basin ya sink par isko ghumanay se paani nikal kar neechay girta hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-63",
    word: "Wiper",
    hint: "Farsh dhone ke baad pani ko khainch kar nali mein dalne wala danda.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-64",
    word: "Petti",
    hint: "Trunk ki tarah ka aik lohe ka box jis mein ghareeb gharane saman rakhte hain.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-65",
    word: "Jhaaran",
    hint: "Kitchen ke slab ya table se mitti aur pani saaf karne wala maila kapra.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-66",
    word: "Poncha",
    hint: "Pani mein dip kar ke is dhagon walay tool se farsh par chamak laye jati hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-67",
    word: "Patang",
    hint: "Basant ke mausam mein hawa mein udai jane wali kaghaz aur tilli ki cheez.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-68",
    word: "Dor",
    hint: "Charkhi par lipti hui kanch lagi thread jis se udte hue pench laraey jate hain.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-69",
    word: "Lattoo",
    hint: "Dhaga lapait kar farsh par phenkne se larki ka ye khilona tezi se ghoomta hai.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-70",
    word: "Banta",
    hint: "Galiyon mein bachay kanch ki in choti goliyon ko angoothe se hit karke khailte hain.",
    category: "random-objects",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-random-objects-ur-71",
    word: "Mathani",
    hint: "Ghar mein dahi aur lassi ko phaint kar makhan nikalne wala lakri ka ala.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-72",
    word: "Charkha",
    hint: "Purane zamane mein aurten isay ghuma kar rui se sooti dhaga banati theen.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-73",
    word: "Gulel",
    hint: "Y shape ki lakri aur rubber band se bani jis se bachay chidiya marte thay.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-74",
    word: "Dholak",
    hint: "Shadi ke function mein aurten is chamre aur lakri ki cheez ko hathon se bajati hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-75",
    word: "Bansuri",
    hint: "Sorakh wali ek khokali lakri jis mein phoonk mar kar meethe sur nikalte hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-76",
    word: "Ghungroo",
    hint: "Raqs karte waqt paon mein bandhne wali choti choti peetal ki bajti hui goliyan.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-77",
    word: "Tarazu",
    hint: "Dukandar sauda dete waqt saman ka wazan aur taul karne ke liye ise pakarte hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-78",
    word: "Phawra",
    hint: "Mitti khodne aur utha kar dusri jagah phenkne ke liye kisan aur mazdoor ka hatyar.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-79",
    word: "Khurpa",
    hint: "Ghaas cheelne aur khet mein safai karne ka chota aur nok dar lohe ka auzar.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-80",
    word: "Daranti",
    hint: "Paki hui fasal aur gandum ko katne wali aadhay chand ki shakal ki sharp blade.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-81",
    word: "Kulhari",
    hint: "Darakht ke mote tano ko kaat kar girane ke liye taqat se mari jati hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-82",
    word: "Hathori",
    hint: "Deewar mein frame latkane ke liye is aozar se keel ko zor se thonkte hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-83",
    word: "Keel",
    hint: "Lohe ki patli si mekh jisko dande se maar kar lakri mein andar utarte hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-84",
    word: "Paich Kas",
    hint: "Screws ko kholne aur tight karne wala pichay plastic pakar wala hand tool.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-85",
    word: "Plass",
    hint: "Sakt taar ko pakar kar duba kar katne aur mohnay wala hath ka aozar.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-86",
    word: "Aari",
    hint: "Barhai is kantedar blade ko aage peechay chala kar lakri ko do hisson mein katte hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-87",
    word: "Sooi",
    hint: "Nokeeli aur bareek cheez jis ke sorakh mein dhaga daal kar kapra siya jata hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-88",
    word: "Dhaga",
    hint: "Machine ya hath se button lagate waqt is sooti bareek rassi ki zarurat parti hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-89",
    word: "Bukram",
    hint: "Qameez ke collar aur kaf ko sakht aur khara rakhne ke liye lagaya jane wala pishtha.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-90",
    word: "Inchi Tape",
    hint: "Darzi kapre seene se pehle apke jism ki lambaai aur chauraai is naram scale se napta hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-91",
    word: "Gajra",
    hint: "Khushbudar motiye ke phoolon ki lari jo aurten shadiyon mein apni kalai mein bandhti hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-92",
    word: "Bindiya",
    hint: "Dulhan banne ke liye peshani ke darmiyan lagaya jane wala chamakdar aur khoobsurat zewar.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-93",
    word: "Ubtan",
    hint: "Mayun ki rasm mein chehre ko gora aur nikhra karne ke liye malne wala peela leip.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-94",
    word: "Naara",
    hint: "Shalwar ko kamar ke sath mazbooti se bandhay rakhne ke liye daali jane wali suti dori.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-95",
    word: "Phoonkani",
    hint: "Lohay ka ek pipe jis mein se zor se hawa nikal kar aag ko tez kiya jata hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-96",
    word: "Tijori",
    hint: "Ghar mein qeemti zewar aur cash ko choron se mehfooz rakhne wali bhari lohay ki dabiya.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-97",
    word: "Kassi",
    hint: "Naliyo se mitti aur ghaas saf karne ke liye istamal hone wala lambay danday wala hatyar.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-98",
    word: "Sancha",
    hint: "Kulfi ya barf ko makhsoos shape mein jamane ke liye is metal ke container mein dala jata hai.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-99",
    word: "Gola",
    hint: "Oon se buni hui gol aur naram cheez jis ko khol kar sardiyon ke sweater bunte hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-random-objects-ur-100",
    word: "Baja",
    hint: "14 August par bachay galiyon mein shor machane ke liye is plastic instrument mein phoonk marte hain.",
    category: "random-objects",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
