// lib/fallback-words/vehicles/english/index.ts
import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "vehicles" category -- English.
 *
 * 100 everyday vehicle terms recognized internationally.
 * Difficulty breakdown:
 *   - easy (40):   states the most obvious defining trait directly.
 *   - medium (30): points at a related detail, context, or association.
 *   - hard (30):   oblique angle, indirect consequence, or secondary function.
 */
export const VEHICLES_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // --- EASY (40 words) ---
  {
    id: "fallback-vehicles-en-1",
    word: "Car",
    hint: "A four-wheeled motor vehicle used daily for personal road travel.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-2",
    word: "Bicycle",
    hint: "A two-wheeled vehicle powered entirely by pushing foot pedals.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-3",
    word: "Bus",
    hint: "A large passenger vehicle designed to carry dozens of commuters along set city routes.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-4",
    word: "Airplane",
    hint: "A winged flying machine powered by jet engines or propellers that carries people high in the sky.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-5",
    word: "Train",
    hint: "A long series of connected passenger cars running along metal railway tracks.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-6",
    word: "Motorcycle",
    hint: "A two-wheeled motorized road vehicle ridden by straddling the seat and gripping handlebars.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-7",
    word: "Helicopter",
    hint: "An aircraft with large spinning overhead blades that allows vertical takeoff and hovering.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-8",
    word: "Submarine",
    hint: "A specialized watercraft designed to travel entirely underwater beneath the ocean surface.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-9",
    word: "Ambulance",
    hint: "An emergency road vehicle equipped with flashing lights and sirens to transport sick or injured people.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-10",
    word: "Fire Truck",
    hint: "A emergency response vehicle carrying long ladders and water hoses to put out blazes.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-11",
    word: "Tractor",
    hint: "A heavy farm motor vehicle with large treaded rear tires used to pull plows and machinery.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-12",
    word: "Taxi",
    hint: "A hired car service where a driver takes passengers to their requested destination for a metered fare.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-13",
    word: "Scooter",
    hint: "A lightweight motor vehicle with a floorboard platform for the rider's feet.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-14",
    word: "Cruise Ship",
    hint: "A massive ocean passenger vessel featuring onboard hotels and entertainment for vacationers.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-15",
    word: "Hot Air Balloon",
    hint: "A large fabric envelope filled with heated air that floats gracefully through the sky with a basket beneath.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-16",
    word: "Dump Truck",
    hint: "A heavy-duty construction truck with an open-topped rear bed that tilts backward to unload materials.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-17",
    word: "Skateboard",
    hint: "A narrow wooden board mounted on four small wheels used for riding or performing tricks.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-18",
    word: "Van",
    hint: "A boxy, medium-sized motor vehicle used for carrying cargo or large groups of family members.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-19",
    word: "Golf Cart",
    hint: "A small motorized buggy designed to transport golfers and their equipment around a course.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-20",
    word: "Jet Ski",
    hint: "A small motorized personal watercraft that skims across the water like a motorcycle.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-21",
    word: "Canoe",
    hint: "A narrow open boat propelled by handheld single-bladed paddles.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-22",
    word: "Ferry",
    hint: "A merchant vessel used to shuttle passengers and vehicles across a river or bay regularly.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-23",
    word: "Garbage Truck",
    hint: "A large municipal utility vehicle that collects residential waste from roadside bins.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-24",
    word: "Tow Truck",
    hint: "A specialized road vehicle used to haul away broken-down or illegally parked automobiles.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-25",
    word: "Space Shuttle",
    hint: "A reusable rocket-powered spacecraft designed to fly crew into orbit and land like a glider.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-26",
    word: "Police Car",
    hint: "A emergency vehicle used by law enforcement officers to patrol streets and respond to emergency calls.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-27",
    word: "Tram",
    hint: "A rail transit vehicle that runs along tracks embedded directly into urban street pavement.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-28",
    word: "Sailboat",
    hint: "A sea vessel propelled primarily by wind pushing against large fabric sails.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-29",
    word: "Bulldozer",
    hint: "A heavy crawler tractor with a large front metal blade used to push massive amounts of earth.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-30",
    word: "Kayak",
    hint: "A low-seated, narrow watercraft propelled using a double-bladed paddle.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-31",
    word: "Snowmobile",
    hint: "A motorized winter land vehicle designed to travel over deep snow on front skis and rear treads.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-32",
    word: "Forklift",
    hint: "An industrial warehouse vehicle featuring two metal prongs on the front to lift heavy wooden pallets.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-33",
    word: "Cement Mixer",
    hint: "A construction truck fitted with a continuously rotating drum to keep concrete liquid during transport.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-34",
    word: "Blimp",
    hint: "A non-rigid giant airship filled with gas that floats overhead during major sporting events.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-35",
    word: "Gondola",
    hint: "A traditional long, flat-bottomed Venetian rowing boat navigated through narrow canals by a rower.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-36",
    word: "Golf Cart",
    hint: "A small open-sided electric or gas buggy used for moving short distances on managed grounds.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-37",
    word: "Rickshaw",
    hint: "A three-wheeled passenger vehicle widely used in Asian cities for short urban commutes.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-38",
    word: "Hovercraft",
    hint: "A amphibious craft that glides across both land and water on a cushion of high-pressure air.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-39",
    word: "Cable Car",
    hint: "A aerial cabin suspended from moving cables that carries alpine visitors up mountain peaks.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-40",
    word: "Sled",
    hint: "A wooden or plastic vehicle with smooth runners used for sliding down snowy hills.",
    category: "vehicles",
    difficulty: "easy",
    language: "english",
  },

  // --- MEDIUM (30 words) ---
  {
    id: "fallback-vehicles-en-41",
    word: "Car",
    hint: "Parallel parking this into a tight street spot can challenge new drivers.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-42",
    word: "Bicycle",
    hint: "Wearing a helmet and ringing a small handlebar bell are common habits when riding this.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-43",
    word: "Bus",
    hint: "Riders pull a overhead cord or press a red button to signal the driver for the next stop.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-44",
    word: "Airplane",
    hint: "Passengers switch their phones to a special mode before rolling down the runway.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-45",
    word: "Train",
    hint: "The rhythmic clickety-clack sound against steel rails is iconic to long distance journeys.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-46",
    word: "Motorcycle",
    hint: "Riders wear thick leather jackets and full-face helmets to protect against wind and asphalt.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-47",
    word: "Helicopter",
    hint: "This air transport can land directly on skyscraper rooftops equipped with a painted circle.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-48",
    word: "Submarine",
    hint: "Naval operators use active sonar pings to map out surroundings in pitch-black depths.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-49",
    word: "Ambulance",
    hint: "Other motorists immediately pull off to the side of the road when its blaring tone approaches.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-50",
    word: "Fire Truck",
    hint: "Firefighters hook heavy lines up to neighborhood hydrants from this red giant.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-51",
    word: "Tractor",
    hint: "You often see this moving slowly along rural highways between crop fields.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-52",
    word: "Taxi",
    hint: "A glowing yellow roof light indicates whether or not it is available for hailing.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-53",
    word: "Scooter",
    hint: "Commuters conveniently park these small two-wheelers in narrow city alleyways.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-54",
    word: "Cruise Ship",
    hint: "Vacationers gather on the top deck for midnight buffets and ocean views.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-55",
    word: "Hot Air Balloon",
    hint: "A propane burner periodically bursts with flame to keep the craft lifted above the canopy.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-56",
    word: "Dump Truck",
    hint: "A loud beeping sound alerts nearby workers whenever this heavy machine backs up.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-57",
    word: "Skateboard",
    hint: "Riders kick off the pavement with one foot while balancing on a wooden deck coated in grip tape.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-58",
    word: "Van",
    hint: "Sliding side doors make loading sports gear or energetic kids hassle-free.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-59",
    word: "Golf Cart",
    hint: "It moves quietly along paved pathways past sand traps and green fairways.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-60",
    word: "Jet Ski",
    hint: "Thrill-seekers spray up tall plumes of salt water while carving sharp turns in the bay.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-61",
    word: "Canoe",
    hint: "Campers carefully balance their weight in the center to avoid capsizing in peaceful lake waters.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-62",
    word: "Ferry",
    hint: "Commuters step out of their parked sedans to grab coffee in the passenger lounge during the crossing.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-63",
    word: "Garbage Truck",
    hint: "Mechanical hydraulic arms lift heavy curbside barrels high overhead early in the morning.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-64",
    word: "Tow Truck",
    hint: "Drivers use heavy steel chains and hydraulic lifts to haul disabled automobiles to repair shops.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-65",
    word: "Space Shuttle",
    hint: "It detached its solid booster tanks during launch before returning to touch down on a long runway.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-66",
    word: "Police Car",
    hint: "Loud speaker announcements and checkered side stripes announce its authority on the highway.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-67",
    word: "Tram",
    hint: "Overhead electric wires supply the power as this rail vehicle glides down busy avenues.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-68",
    word: "Sailboat",
    hint: "Skilled sailors trim ropes and tilt the vessel to harness crosswinds across open water.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-69",
    word: "Bulldozer",
    hint: "Heavy metal continuous tracks help this construction beast navigate muddy, uneven ground.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-70",
    word: "Kayak",
    hint: "Paddlers wear a waterproof skirt snapped around the cockpit rim to keep river spray out.",
    category: "vehicles",
    difficulty: "medium",
    language: "english",
  },

  // --- HARD (30 words) ---
  {
    id: "fallback-vehicles-en-71",
    word: "Car",
    hint: "Finding an open meter on a crowded downtown grid is a daily urban headache.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-72",
    word: "Bicycle",
    hint: "Greasy pant legs and rolled-up right cuffs are trademark signs of riding one daily.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-73",
    word: "Bus",
    hint: "Standing passengers grab overhead plastic straps to stay balanced during sudden stops.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-74",
    word: "Airplane",
    hint: "Cruising at thirty thousand feet leaves white condensation trails trailing across blue skies.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-75",
    word: "Train",
    hint: "Conductors walk down long narrow aisles punching paper tickets for seated travelers.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-76",
    word: "Motorcycle",
    hint: "Leaning hard into sharp turns while keeping your balance demands body co-ordination.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-77",
    word: "Helicopter",
    hint: "Strong downwash wind flattens surrounding grass whenever this machine touches down.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-78",
    word: "Submarine",
    hint: "Flooding internal ballast tanks causes this vessel to lose buoyancy and slip beneath the waves.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-79",
    word: "Ambulance",
    hint: "Traffic signals switch colors automatically when its emergency signal transponder approaches.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-80",
    word: "Fire Truck",
    hint: "Its long extensible arm unfolds high into the air to reach burning top-floor windows.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-81",
    word: "Tractor",
    hint: "It leaves deep tread patterns imprinted across soft, freshly turned soil.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-82",
    word: "Taxi",
    hint: "A dashboard digital counter calculates the cost based on distance traveled and idle time.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-83",
    word: "Scooter",
    hint: "Twisting the right handlebar grip controls acceleration while zip-lining through city lanes.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-84",
    word: "Cruise Ship",
    hint: "Its massive anchor weighs several tons when dropped in shallow tropical ports.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-85",
    word: "Hot Air Balloon",
    hint: "Pilots adjust altitude solely by controlling air temperature inside, relying on wind for direction.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-86",
    word: "Dump Truck",
    hint: "Heavy gravel hits the metal bed with a deafening rattle as loaders dump their quarry cargo.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-87",
    word: "Skateboard",
    hint: "Small polyurethane wheels grind against concrete edges during urban street tricks.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-88",
    word: "Van",
    hint: "Carpeted back interiors often host fold-out beds for long highway road trips.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-89",
    word: "Golf Cart",
    hint: "Surprising silence is key so nearby players can concentrate on their high-stakes swings.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-90",
    word: "Jet Ski",
    hint: "An engine-powered water jet nozzle at the rear provides steering and high-speed propulsion.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-91",
    word: "Canoe",
    hint: "Carrying this lightweight wooden hull upside down over your shoulders between lakes is called portage.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-92",
    word: "Ferry",
    hint: "Securing vehicle tires with chocks prevents movement on choppy sea passages.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-93",
    word: "Garbage Truck",
    hint: "Heavy hydraulic compactors crush bags with immense pressure into the rear hopper.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-94",
    word: "Tow Truck",
    hint: "Tilted flatbeds lower down to ground level so immobile vehicles can be winched up easily.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-95",
    word: "Space Shuttle",
    hint: "Thermal protection tiles on its belly absorbed intense friction heat during atmospheric re-entry.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-96",
    word: "Police Car",
    hint: "Mounted dash cameras capture road interactions while computers scan license plates automatically.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-97",
    word: "Tram",
    hint: "A roof-mounted pantograph maintains constant electrical contact with overhead cables.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-98",
    word: "Sailboat",
    hint: "A weighted keel underneath prevents the boat from tipping over when wind hits the canvas.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-99",
    word: "Bulldozer",
    hint: "A heavy ripper attachment on the rear shatters tough rock before leveling the site.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-vehicles-en-100",
    word: "Kayak",
    hint: "Flipping completely upside down requires a specialized hipsnap maneuver to upright the craft.",
    category: "vehicles",
    difficulty: "hard",
    language: "english",
  },
];
