import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "sports" category -- Roman Urdu.
 *
 * 100 words drawn from Pakistani street cricket vocabulary, traditional games
 * (like Kabaddi, Gulli Danda, Pithoo Garam), and common sporting jargon
 * that an average Roman Urdu-speaking player would instantly recognize.
 * As with the English list, difficulty only changes how directly the hint
 * points at the word, never how obscure the word itself is.
 * Hints are written in natural Roman Urdu using only Latin letters.
 */
export const SPORTS_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-sports-ur-1",
    word: "Chhakka",
    hint: "Cricket mein jab ball boundary line ke par hawai fire hoke jae to 6 runs milte hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-2",
    word: "Chauka",
    hint: "Ball jab zameen par tappa kha kar boundary line ke bahar jati hai to 4 runs milte hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-3",
    word: "Catch",
    hint: "Batsman ke shot marne par hawa mein jati ball ko zameen par girne se pehle pakarna.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-4",
    word: "Bowled",
    hint: "Bowler ki fenki hui ball jab seedha stumps par lagti hai aur bails gir jati hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-5",
    word: "Out",
    hint: "Jab koi batsman ghalti karke apni wicket kho deta hai aur use pavilion jana parta hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-6",
    word: "Batting",
    hint: "Khel mein bat pakar kar runs banane aur wicket bachane ka kaam karna.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-7",
    word: "Bowling",
    hint: "Batsman ki taraf tez ya spin ball fenk kar use out karne ki koshish karna.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-8",
    word: "Fielding",
    hint: "Maidan mein khare ho kar ball ko rokna aur runs banane se roknay ki koshish karna.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-9",
    word: "Umpire",
    hint: "Cricket match mein har ball par sahi faisla dene wala white shirt wala munsif.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-10",
    word: "Kabaddi",
    hint: "Desi khel jahan ek khiladi doke bolte hue dusri team mein ja kar touch karke bhagta hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-11",
    word: "Gulli Danda",
    hint: "Desi khel jahan choti lakri ko bari lakri ke dande se hawa mein uchhal kar mara jata hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-12",
    word: "Kanchay",
    hint: "Gali mein bachay zameen par chote gadhay bana kar sheeshe ki goliyan angoothe se marte hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-13",
    word: "Baraf Paani",
    hint: "Bachon ka khel jahan ek banda touch karke baraf kar deta hai aur doosra paani bol kar kholta hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-14",
    word: "Ankh Macholi",
    hint: "Aankhon par patti bandh kar baqi doston ko awaz se pehchanne aur pakarne ka khel.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-15",
    word: "Chhupan Chhai",
    hint: "Ek bacha ginti ginta hai aur baqi sab chhup jate hain jinhe dhoondna hota hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-16",
    word: "Pithoo Garam",
    hint: "Pithoo ke saat patharon ki minar ko ball se girana aur dobara jorna hota hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-17",
    word: "Kushti",
    hint: "Mitti ke akhare mein do pehlwan ek dusre ko patakhne ke liye zor azmai karte hain.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-18",
    word: "Ludo",
    hint: "Chaar rangon ki gotiyan aur paasa phenk kar 6 aane par patti kholne wala board game.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-19",
    word: "Carrom",
    hint: "Powder lage board par striker se safed aur kaali gotiyan pocket mein daalne ka khel.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-20",
    word: "Trophy",
    hint: "Match ya tournament jeetne par poori team ko milne wala metal ka cup.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-21",
    word: "Toss",
    hint: "Match shuru hone se pehle sikka uchhal kar batting ya bowling ka faisla karna.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-22",
    word: "Run Out",
    hint: "Batsman ke crease par pahunchne se pehle wicketkeeper ya fielder ka stumps par ball lagana.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-23",
    word: "Wide Ball",
    hint: "Bowler ki fenki hui ball jo batsman se bohut door ho aur us par 1 extra run mile.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-24",
    word: "No Ball",
    hint: "Bowler ka paon line se bahar nikalne ya hawa mein zyadah oonchi ball fenkne par milne wala foul.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-25",
    word: "Free Hit",
    hint: "No ball ke baad aane wali delivery jis par batsman catch out nahi ho sakta.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-26",
    word: "Goal",
    hint: "Football ko opponent team ki jaali ke andar phenk kar score karna.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-27",
    word: "Penalty",
    hint: "Foul hone par seedha goalkeeper ke samne se milne wala direct kick shot.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-28",
    word: "Yellow Card",
    hint: "Football mein ghalat tackle karne par referee ki taraf se di jane wali pehli warning.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-29",
    word: "Red Card",
    hint: "Football referee ka wo card jis ke dikhte hi khiladi ko ground se bahar jana parta hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-30",
    word: "Over",
    hint: "Cricket mein bowler ki taraf se fenki jane wali lagatar 6 legal balls.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-31",
    word: "Maiden Over",
    hint: "Poore 6 balls ka wo over jis mein batsman ek run bhi na bana sake.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-32",
    word: "Spin",
    hint: "Ball ka zameen par tappa kha kar batsman ko chakma dete hue ghoom jana.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-33",
    word: "Fast Bowling",
    hint: "Bohut tezi aur raftaar se batsman ki taraf ball fenkna.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-34",
    word: "Bouncer",
    hint: "Bowler ki bohut tez ball jo zameen se ucchal kar seedha batsman ke seene ya sar tak ati hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-35",
    word: "Century",
    hint: "Ek hi match mein kisi batsman ka 100 runs ka shandar score mukammal karna.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-36",
    word: "Hat Trick",
    hint: "Bowler ka lagatar teen balls par teen mukhtalif khiladiyon ko out karna.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-37",
    word: "Wicket Keeper",
    hint: "Stumps ke bilkul peechay dastane pehan kar har ball pakarne wala khiladi.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-38",
    word: "Captain",
    hint: "Team ka sarbrah jo toss karta hai aur ground mein sab ki jagah tay karta hai.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-39",
    word: "Tape Ball",
    hint: "Tennis ki halki ball par electrical tape lapet kar galiyon mein cricket khelan.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-40",
    word: "Gully Cricket",
    hint: "Mohallay ki tang galiyon mein gharon ki deewaron ke beech khili jane wali desi cricket.",
    category: "sports",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-sports-ur-41",
    word: "Deewar Ka Out",
    hint: "Mohallay ke match ka khaas usool ke ball agar seedha kisi ke ghar ki deewar par lage to out.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-42",
    word: "One Tip Out",
    hint: "Kache bachon ke sath khelte waqt zameen par aik tappa kha kar aane wala catch bhi out maana jana.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-43",
    word: "Baby Over",
    hint: "Chote bachon ko Khush karne ya waqt bachane ke liye sirf teen ya chaar balls ka over karwana.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-44",
    word: "Last Man Standing",
    hint: "Team ke saare khiladi out hone ke baad aakhri bacha hua batsman akele hi batting karta hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-45",
    word: "Trial Ball",
    hint: "Match ki pehli ball jis par agar batsman out bhi ho jaye to usay maaf kar diya jata hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-46",
    word: "Batta Bowling",
    hint: "Bowler ka kohni mor kar ball fenkna jise mohallay mein jhuta bowling keh kar roka jata hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-47",
    word: "Kacha Limbo",
    hint: "Gali ke khel mein sab se chota bacha jise dono teams mein bari bari baari milti hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-48",
    word: "Lagan",
    hint: "Khel se pehle dono teams ka aapas mein sharbat ya cold drink ki shart lagana.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-49",
    word: "Maidan",
    hint: "Shehar ka wo bara khula ground jahan itwar ke din hazaron larke match khelne ate hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-50",
    word: "Net Practice",
    hint: "Asli match se pehle jali ke andar ghus kar ghanton batting aur bowling ki mashq karna.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-51",
    word: "Match Point",
    hint: "Badminton ya tennis ka wo aakhri point jise jeette hi poora game khatam ho jata hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-52",
    word: "Extra Runs",
    hint: "Wo runs jo batsman ke bat se nahi balkay bowler ki ghalti ya wide se milti hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-53",
    word: "Foul",
    hint: "Khel ke dauran kisi doosre khiladi ko dhakka dena ya usool todna.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-54",
    word: "Kit Bag",
    hint: "Batsman ka bara sa thaila jis mein bat, pads, helmet aur dastane rakhe hote hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-55",
    word: "Jersey",
    hint: "Puri team ka ek hi rang aur number wala makhsoos khelne ka shirt.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-56",
    word: "Pads",
    hint: "Tez ball lagne se tangon ki haddiyon ko bachane ke liye pehne jane wale safed protectors.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-57",
    word: "Helmet",
    hint: "Fast bowler ki tez bouncer se apna sar aur chehra bachane ka sakht cover.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-58",
    word: "Gloves",
    hint: "Bat pakarte waqt ungliyon par ball lagne se bachane ke liye pehne jane wale dastane.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-59",
    word: "Seeti",
    hint: "Referee ya umpire ke munh mein dabi choti cheez jis se teez awaz nikal kar khel roka jata hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-60",
    word: "Scoreboard",
    hint: "Maidan mein laga bara board jis par runs, wickets aur overs likhe hote hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-61",
    word: "Stumps",
    hint: "Pitch ke dono taraf gari hui teen vertical lakriyan jin par bails rakhi jati hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-62",
    word: "Bails",
    hint: "Stumps ke oopar tiki hui do choti lakriyan jo ball lagte hi neechay gir jati hain.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-63",
    word: "Pitch",
    hint: "Maidan ke darmiyan 22 yard ki wo jagah jahan bowler ball karwata hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-64",
    word: "Boundary",
    hint: "Maidan ke chaaron taraf lagi hui rassi ya safed patti jo khel ki hadd tay karti hai.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-65",
    word: "Pavilion",
    hint: "Match ke dauran baqi khiladiyon ke baithne aur tayyar hone ka khususi kamra.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-66",
    word: "Runner",
    hint: "Zakhmi batsman ki jagah tez bhagne ke liye crease par khara hone wala dosra saathi.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-67",
    word: "Night Tournament",
    hint: "Ramazan ki raaton mein lights ke neechay hone wale cricket ke mukable.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-68",
    word: "Floodlights",
    hint: "Raat ke waqt maidan ko din jaisa roshan karne wali bari bari poles par lagi lights.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-69",
    word: "Sledging",
    hint: "Batsman ka dhyan bhatkane ke liye bowler aur fielders ka bol bol kar pareshan karna.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-70",
    word: "Walkover",
    hint: "Opponent team ke waqt par na pahunchne par bina khele hi jeet mil jana.",
    category: "sports",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-sports-ur-71",
    word: "Duck",
    hint: "Batsman ka pehli hi ball par bina koi run banaye zero par out ho kar jana.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-72",
    word: "Full Toss",
    hint: "Bowler ki fenki hui ball jo zameen par tappa khaye baghair seedha batsman ke bat par ati hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-73",
    word: "Yorker",
    hint: "Bowler ki bohut tez ball jo bilkul batsman ke paon aur bat ke darmiyan ja kar lagti hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-74",
    word: "Reverse Sweep",
    hint: "Right handed batsman ka achanak ulta ghoom kar left hander ki tarah peeche shot marna.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-75",
    word: "Appeal",
    hint: "Ball leg pad par lagte hi saare fielders ka ek sath zor se chilla kar umpire se out mangna.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-76",
    word: "Mankading",
    hint: "Bowler ka ball karwane se pehle hi non-striker ko crease se bahar nikalne par out kar dena.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-77",
    word: "Powerplay",
    hint: "Shuruaati overs jab sirf do fielders boundary par khare ho sakte hain aur chhakay marna aasan hota hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-78",
    word: "Follow On",
    hint: "Pehli innings mein bohut kam runs banane par doosri team ka unhe dobara batting ke liye bhejna.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-79",
    word: "Super Over",
    hint: "Match tie hone par faisla karne ke liye dono teams ko ek ek over khelne ka moqa milna.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-80",
    word: "Target",
    hint: "Pehli team ke banaye runs se ek run zyada jo doosri team ko jeetne ke liye chahiye hota hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-81",
    word: "Duckworth Lewis",
    hint: "Barish aane par match ke overs aur runs kam karne ka pechida hisab kitab.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-82",
    word: "Follow Through",
    hint: "Ball fenkne ke baad bowler ki body ka aage ki taraf bhagte hue balance banana.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-83",
    word: "Pinch Hitter",
    hint: "Tez runs banane ke liye aakhri overs ke maahir batsman ko oopar bhej dena.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-84",
    word: "Night Watchman",
    hint: "Test match mein din khatam hone se thora pehle main batsman ko bachane ke liye bowler ko bhej dena.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-85",
    word: "Clean Sweep",
    hint: "Series ke saare matches bina koi ek bhi hare lagatar jeet lena.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-86",
    word: "Offside",
    hint: "Football mein pass milne se pehle hi opponent ke aakhri defender ke peechay khare hona.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-87",
    word: "Hand of God",
    hint: "Football history ka wo mashhoor goal jo sar ke bajaye chori se hath se kiya gaya tha.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-88",
    word: "Time Out",
    hint: "Wicket girne ke baad naye batsman ka makhsoos waqt mein pitch par na pahunchne par out hona.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-89",
    word: "Stumping",
    hint: "Batsman ke shot marne ke chakkar mein crease se bahar nikalte hi keeper ka bails gira dena.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-90",
    word: "Hit Wicket",
    hint: "Shot marte waqt batsman ka apna hi bat ya paon ghalti se stumps par lag jana.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-91",
    word: "Leg Before Wicket",
    hint: "Ball bat par lagne ke bajaye seedha pad par lage jo stumps ki line mein ho.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-92",
    word: "Third Umpire",
    hint: "TV screen par slow motion video replay dekh kar mushkil faislay dene wala judge.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-93",
    word: "Water Boy",
    hint: "Drink breaks mein maidan ke andar khiladiyon ke liye paani aur towels lane wala khiladi.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-94",
    word: "Golden Duck",
    hint: "Match mein apni zindagi ki pehli hi ball par bina run banaye out ho jana.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-95",
    word: "Diamond Duck",
    hint: "Bina koi ball khele hi run out ho kar zero par pavilion wapis chalay jana.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-96",
    word: "Unsold",
    hint: "League ki auction mein kisi bhi team ka kisi khiladi par boli na lagana.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-97",
    word: "Bench Strength",
    hint: "Main team ke ilawa bahar baithay reserve khiladiyon ki taqat aur karkardagi.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-98",
    word: "Chinaman",
    hint: "Left arm wrist spinner ki fenki hui aisi ball jo achanak andar ki taraf turn hoti hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-99",
    word: "Doosra",
    hint: "Off spinner ki fenki hui ball jo chalakian se bahar ki taraf nikal jati hai.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-sports-ur-100",
    word: "Reverse Swing",
    hint: "Purani aur ek taraf se khurduri ball ka hawa mein achanak andar ki taraf murna.",
    category: "sports",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
