// Regenerates public/sw.js from public/sw-template.js with a fresh
// CACHE_VERSION, so every `next dev` / `next build` run gets a service
// worker that will clean up the previous version's caches on activate.
//
// public/sw.js is a build artifact (gitignored) -- edit sw-template.js
// instead. This intentionally has zero dependencies so it never risks
// conflicting with Next.js's bundler (webpack or Turbopack).

const fs = require("fs");
const path = require("path");

const rootDir = path.join(__dirname, "..");
const templatePath = path.join(rootDir, "public", "sw-template.js");
const outputPath = path.join(rootDir, "public", "sw.js");
const appRoutesTsPath = path.join(rootDir, "lib", "app-routes.ts");
const appDir = path.join(rootDir, "app");
const publicDir = path.join(rootDir, "public");

const pkg = require(path.join(rootDir, "package.json"));

const template = fs.readFileSync(templatePath, "utf8");

// --- ROUTE SYNC CHECK -------------------------------------------------
// public/sw-template.js and lib/app-routes.ts each hand-maintain their
// own copy of the app's route list (the service worker script can't
// import the TS file -- see the comment in each). Pulled out of sync
// once already (this is literally the bug this task was filed to fix),
// so: fail the build loudly if they ever drift again, instead of
// quietly shipping a service worker that doesn't precache a route the
// app actually has, or that precaches one it doesn't.
function extractStringArray(source, constName) {
  const match = source.match(
    new RegExp(`const ${constName} = \\[([\\s\\S]*?)\\];`),
  );
  if (!match) {
    throw new Error(`[generate-sw] could not find "${constName}" array`);
  }
  return [...match[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
}

const swAppRoutes = extractStringArray(template, "APP_ROUTES");
const tsAppRoutes = extractStringArray(
  fs.readFileSync(appRoutesTsPath, "utf8"),
  "APP_ROUTES",
);

const onlyInSw = swAppRoutes.filter((r) => !tsAppRoutes.includes(r));
const onlyInTs = tsAppRoutes.filter((r) => !swAppRoutes.includes(r));
if (onlyInSw.length || onlyInTs.length) {
  throw new Error(
    "[generate-sw] APP_ROUTES has drifted between public/sw-template.js " +
      "and lib/app-routes.ts -- these must list the exact same routes.\n" +
      (onlyInSw.length
        ? `  Only in public/sw-template.js: ${onlyInSw.join(", ")}\n`
        : "") +
      (onlyInTs.length
        ? `  Only in lib/app-routes.ts: ${onlyInTs.join(", ")}\n`
        : ""),
  );
}

// Every route should resolve to a real page. This is a warning, not a
// build failure -- a route implemented via a route group or other
// non-obvious App Router convention would be a false positive here.
for (const route of swAppRoutes) {
  const segment = route === "/" ? "" : route.slice(1);
  const pagePath = path.join(appDir, segment, "page.tsx");
  if (!fs.existsSync(pagePath)) {
    console.warn(
      `[generate-sw] WARNING: APP_ROUTES has "${route}" but ` +
        `${path.relative(rootDir, pagePath)} does not exist -- this route ` +
        "will be precached even though it 404s.",
    );
  }
}

// Every other precached URL (icons, offline.html, etc.) should be a
// real file in public/. Unlike the route check, this fails the build:
// it's a plain file-existence check with no framework convention that
// could produce a false positive, and a missing entry here is exactly
// what silently broke offline support before (see the precacheAll()
// comment in sw-template.js) -- cache.addAll()/cache.add() reject on a
// 404, which is easy to miss if it's only ever noticed at runtime.
const precacheMatch = template.match(/const PRECACHE_URLS = \[([\s\S]*?)\];/);
if (!precacheMatch) {
  throw new Error('[generate-sw] could not find "PRECACHE_URLS" array');
}
const precacheEntries = precacheMatch[1]
  .split(",")
  .map((line) => line.trim())
  .filter(Boolean);

const missingStaticFiles = [];
for (const entry of precacheEntries) {
  if (entry === "...APP_ROUTES") continue; // checked above
  const url = entry.replace(/^"|"$/g, "");
  if (url === "/manifest.webmanifest") continue; // generated by app/manifest.ts, not a public/ file
  if (!fs.existsSync(path.join(publicDir, url))) {
    missingStaticFiles.push(url);
  }
}
if (missingStaticFiles.length) {
  throw new Error(
    "[generate-sw] PRECACHE_URLS references file(s) that don't exist " +
      `under public/: ${missingStaticFiles.join(", ")}\n` +
      "  Either add the missing file(s) or remove them from PRECACHE_URLS " +
      "in public/sw-template.js.",
  );
}
// --- end ROUTE SYNC CHECK ----------------------------------------------

// Version = package.json version + a build timestamp, so both manual
// version bumps and every plain rebuild produce a distinct cache
// namespace (old caches get swept on the next activate).
const cacheVersion = `${pkg.version}-${Date.now()}`;

const output = template.replace("__CACHE_VERSION__", cacheVersion);

fs.writeFileSync(outputPath, output, "utf8");

console.log(
  `[generate-sw] public/sw.js written with CACHE_VERSION=${cacheVersion}`,
);
