import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "random-objects" category -- English.
 *
 * All 100 words are common, everyday objects an average person would
 * instantly recognize, regardless of difficulty. Difficulty here changes ONLY
 * how directly the hint points at the word -- never how obscure the word itself is:
 *   - easy (40):   the hint states the object's most obvious function directly.
 *   - medium (30): the hint points at a related detail/context instead
 *                  of the defining function, so it takes a moment of thought.
 *   - hard (30):   the hint is oblique -- an unusual angle, minor detail,
 *                  or consequence -- without ever naming the obvious function.
 */
export const RANDOM_OBJECTS_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-random-objects-en-1",
    word: "Spoon",
    hint: "A small curved utensil with a handle used for eating liquid foods like soup.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-2",
    word: "Toothbrush",
    hint: "A small plastic tool with bristles used to clean your teeth.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-3",
    word: "Key",
    hint: "A small jagged piece of metal used to unlock a door.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-4",
    word: "Umbrella",
    hint: "A folding canopy on a stick that you open to stay dry in the rain.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-5",
    word: "Pillow",
    hint: "A soft rectangular cushion you rest your head on when you go to sleep.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-6",
    word: "Chair",
    hint: "A piece of furniture with four legs and a backrest meant for sitting.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-7",
    word: "Clock",
    hint: "A device with hands or digital numbers that hangs on the wall to tell time.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-8",
    word: "Scissors",
    hint: "A hand tool with two sharp metal blades used for cutting paper.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-9",
    word: "Towel",
    hint: "A piece of absorbent fabric used to dry your body after a shower.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-10",
    word: "Mirror",
    hint: "A reflective glass surface you look into to see your own face.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-11",
    word: "Comb",
    hint: "A flat piece of plastic with narrow teeth used to untangle hair.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-12",
    word: "Pencil",
    hint: "A wooden writing instrument with a graphite core that can be erased.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-13",
    word: "Wallet",
    hint: "A small folding case kept in a pocket to hold cash and credit cards.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-14",
    word: "Backpack",
    hint: "A bag with two straps worn over the shoulders to carry heavy books.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-15",
    word: "Glasses",
    hint: "A pair of lenses sitting on your nose that help correct blurry vision.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-16",
    word: "Camera",
    hint: "A device that captures still photographs or records moving video.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-17",
    word: "Guitar",
    hint: "A stringed musical instrument with a long neck that is strummed or plucked.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-18",
    word: "Hammer",
    hint: "A heavy tool with a metal head used for pounding nails into wood.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-19",
    word: "Soap",
    hint: "A slippery, scented block that creates lather and bubbles for washing dirt off.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-20",
    word: "Blanket",
    hint: "A large piece of warm fabric draped over the bed to keep you cozy.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-21",
    word: "Laptop",
    hint: "A portable personal computer with a folding screen and attached keyboard.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-22",
    word: "Fork",
    hint: "A metal dining utensil with several tines used to spear solid foods.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-23",
    word: "Knife",
    hint: "A utensil with a sharp blade and a handle used for slicing food.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-24",
    word: "Plate",
    hint: "A flat, round dish that you serve and eat your meals from.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-25",
    word: "Mug",
    hint: "A heavy ceramic cup with a handle used for drinking hot coffee or tea.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-26",
    word: "Broom",
    hint: "A long-handled tool with stiff bristles used for sweeping dust off the floor.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-27",
    word: "Bucket",
    hint: "A cylindrical open container with a handle used for carrying water.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-28",
    word: "Toilet",
    hint: "A plumbing fixture with a bowl and seat used for human waste disposal.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-29",
    word: "Television",
    hint: "A large rectangular screen in the living room used for watching shows and movies.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-30",
    word: "Telephone",
    hint: "A handheld communication device used to call and talk to people far away.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-31",
    word: "Book",
    hint: "A bound collection of paper pages containing printed text or stories.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-32",
    word: "Candle",
    hint: "A cylinder of wax with a central wick that is lit to provide light.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-33",
    word: "Flashlight",
    hint: "A portable, battery-powered tube that projects a bright beam of light in the dark.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-34",
    word: "Helmet",
    hint: "A hard protective shell worn on the head while riding a bicycle or motorcycle.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-35",
    word: "Watch",
    hint: "A small timepiece secured directly to your wrist with a strap.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-36",
    word: "Ring",
    hint: "A small circular band of precious metal worn on the finger as jewelry.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-37",
    word: "Necklace",
    hint: "A piece of jewelry consisting of a chain worn around the throat.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-38",
    word: "Shoes",
    hint: "Sturdy protective coverings worn on the feet when walking outside.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-39",
    word: "Socks",
    hint: "Soft fabric garments worn on the feet inside your footwear to prevent blisters.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-40",
    word: "Hat",
    hint: "A shaped covering worn on the head to block the sun or keep warm.",
    category: "random-objects",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-random-objects-en-41",
    word: "Charger",
    hint: "You plug this cord into the wall when your mobile device reaches one percent battery.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-42",
    word: "Headphones",
    hint: "You place these over your ears to listen to music without disturbing the person next to you.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-43",
    word: "Keyboard",
    hint: "A flat board covered in individual letters and numbers that you tap while looking at a monitor.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-44",
    word: "Mouse",
    hint: "A small plastic device you drag across a desk to move an arrow on your computer screen.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-45",
    word: "Printer",
    hint: "A noisy machine that takes blank paper and covers it in wet black ink from a computer document.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-46",
    word: "Stapler",
    hint: "You press down hard on this heavy desk gadget to forcefully bind a stack of essays together.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-47",
    word: "Paperclip",
    hint: "A small bent piece of wire used to temporarily hold a few sheets of paper together.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-48",
    word: "Envelope",
    hint: "A folded paper sleeve that you lick to seal before dropping it in a mailbox.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-49",
    word: "Stamp",
    hint: "A tiny square sticker you must buy and place on the corner of a letter to mail it.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-50",
    word: "Tape",
    hint: "A clear, sticky strip pulled from a plastic dispenser to wrap birthday presents.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-51",
    word: "Glue",
    hint: "A thick, sticky white liquid squeezed from a bottle during elementary school art projects.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-52",
    word: "Eraser",
    hint: "A small pink rubber block used to furiously rub away mistakes made with graphite.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-53",
    word: "Ruler",
    hint: "A flat wooden or plastic edge marked with inches and centimeters to draw straight lines.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-54",
    word: "Calculator",
    hint: "Students use this small digital keypad during math tests to avoid doing long division in their heads.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-55",
    word: "Thermometer",
    hint: "You place this under your tongue or armpit when you feel like you have a high fever.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-56",
    word: "Bandage",
    hint: "A small adhesive strip you unwrap and stick over a paper cut to stop the bleeding.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-57",
    word: "Tweezers",
    hint: "Two tiny metal prongs pinched together to pluck stray eyebrow hairs or remove a splinter.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-58",
    word: "Razor",
    hint: "A sharp, disposable bathroom tool dragged across the skin to remove unwanted hair.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-59",
    word: "Perfume",
    hint: "A very expensive liquid sprayed on the neck or wrists to smell nice before a date.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-60",
    word: "Deodorant",
    hint: "A solid stick swiped under the arms every morning to prevent unpleasant body odor.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-61",
    word: "Lipstick",
    hint: "A colored cosmetic tube rolled up and applied directly to the mouth.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-62",
    word: "Sunscreen",
    hint: "A thick white lotion rubbed all over the body at the beach to prevent a painful burn.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-63",
    word: "Shampoo",
    hint: "A soapy liquid squeezed out in the shower to massage into the scalp and clean your hair.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-64",
    word: "Toothpaste",
    hint: "A minty paste squeezed onto bristles before brushing your mouth every morning.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-65",
    word: "Floss",
    hint: "A thin waxy string you pull tightly between your molars to remove stuck food.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-66",
    word: "Mouthwash",
    hint: "A harsh, minty liquid you swish in your cheeks and spit out for fresh breath.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-67",
    word: "Sponge",
    hint: "A porous, squishy block that absorbs soapy water, used to scrub dirty dishes in the sink.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-68",
    word: "Matchbox",
    hint: "A tiny carton holding wooden sticks that you strike against the side to create a small flame.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-69",
    word: "Map",
    hint: "A large folded piece of paper showing roads, borders, and oceans used for navigation before GPS.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-70",
    word: "Calendar",
    hint: "A chart hanging on the wall with numbered boxes where you write down upcoming appointments.",
    category: "random-objects",
    difficulty: "medium",
    language: "english",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-random-objects-en-71",
    word: "Iron",
    hint: "It spits out steam and gets dangerously hot to aggressively flatten the wrinkles in your dress shirt.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-72",
    word: "Vacuum",
    hint: "Pets are terrified of this extremely loud machine that you push across the carpet to suck up dirt.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-73",
    word: "Microwave",
    hint: "A box that loudly hums and rotates your leftover food on a glass plate until the center is lava-hot.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-74",
    word: "Blender",
    hint: "A glass pitcher with spinning blades at the bottom that violently purees fruit into smoothies.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-75",
    word: "Toaster",
    hint: "You push a lever down on this appliance and wait for hot, crispy slices of bread to pop out.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-76",
    word: "Refrigerator",
    hint: "A massive, heavy kitchen appliance humming quietly to ensure your milk doesn't spoil.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-77",
    word: "Oven",
    hint: "You set this to 350 degrees and slide a tray of raw cookie dough inside to bake.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-78",
    word: "Dishwasher",
    hint: "You load dirty plates into the racks of this appliance and drop a soap pod inside to avoid hand-washing.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-79",
    word: "Washing Machine",
    hint: "A large metal drum that spins your dirty laundry around in soapy water.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-80",
    word: "Fan",
    hint: "A device with rapidly spinning plastic blades that blows cooling air across the room in summer.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-81",
    word: "Heater",
    hint: "A portable device you plug in during freezing winters that glows orange and radiates warmth.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-82",
    word: "Remote Control",
    hint: "The plastic clicker always getting lost in the couch cushions when you want to change the channel.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-83",
    word: "Lamp",
    hint: "A household furnishing with a shade that you click on to read a book in a dark room.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-84",
    word: "Lightbulb",
    hint: "A fragile glass globe screwed into a socket that suddenly illuminates when you flick a switch.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-85",
    word: "Extension Cord",
    hint: "A long, thick wire you unroll when the wall outlet is too far away to plug in your tools.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-86",
    word: "Plunger",
    hint: "A rubber suction cup on a wooden stick that saves you from a very embarrassing bathroom overflow.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-87",
    word: "Trash Can",
    hint: "A plastic bin lined with a plastic bag where you throw away your food wrappers and garbage.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-88",
    word: "Dustpan",
    hint: "A flat plastic scoop that you awkwardly sweep debris into to pick it up off the floor.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-89",
    word: "Mop",
    hint: "A bundle of wet, soapy yarn on a stick used to wipe sticky spills off the kitchen tiles.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-90",
    word: "Hose",
    hint: "A long green rubber tube uncoiled in the yard to spray water on the flower beds.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-91",
    word: "Rake",
    hint: "A long-handled tool with metal teeth used in autumn to gather dead leaves into a massive pile.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-92",
    word: "Shovel",
    hint: "A heavy tool with a broad metal blade meant for digging holes in the dirt or clearing snow.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-93",
    word: "Wheelbarrow",
    hint: "A small cart with a single front tire and two handles used for transporting heavy bags of soil.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-94",
    word: "Ladder",
    hint: "A portable set of aluminum steps you unfold to climb up and clean out your roof gutters.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-95",
    word: "Screwdriver",
    hint: "A hand tool used to twist small threaded metal pins tightly into a piece of wood.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-96",
    word: "Wrench",
    hint: "A heavy metal tool you use to firmly grip and tighten a stubborn hexagonal nut.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-97",
    word: "Pliers",
    hint: "A small metal hand tool with strong jaws used to firmly pinch, bend, or snip heavy wire.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-98",
    word: "Tape Measure",
    hint: "A flexible yellow ruler that retracts loudly into a metal casing after you check the length of a room.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-99",
    word: "Funnel",
    hint: "A cone-shaped plastic tool used to pour messy liquids cleanly into a bottle with a tiny neck.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-random-objects-en-100",
    word: "Colander",
    hint: "A metal bowl covered in tiny holes used to drain the boiling water off your cooked pasta.",
    category: "random-objects",
    difficulty: "hard",
    language: "english",
  },
];
