import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "sports" category -- English.
 *
 * All 100 words are common, everyday sports and universal athletic terms
 * an average international player would instantly recognize. Difficulty
 * here changes ONLY how directly the hint points at the word:
 *   - easy (40):   the hint states the sport's/term's core defining trait directly.
 *   - medium (30): the hint points at a related detail, context, or equipment.
 *   - hard (30):   the hint is oblique -- an unusual angle or indirect consequence.
 */
export const SPORTS_ENGLISH_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-sports-en-1",
    word: "Soccer",
    hint: "A global sport played by kicking a round ball into a netted goal without using hands.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-2",
    word: "Basketball",
    hint: "A game where players bounce a ball and shoot it through an elevated hoop.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-3",
    word: "Cricket",
    hint: "A bat-and-ball game played on a grass field centered around two sets of wooden wickets.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-4",
    word: "Tennis",
    hint: "Two players use strung rackets to hit a small yellow ball over a central net.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-5",
    word: "Golf",
    hint: "Players use specialized metal clubs to hit a small white ball into distant holes.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-6",
    word: "Swimming",
    hint: "Athletes propel themselves through water lanes using various arm and leg strokes.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-7",
    word: "Boxing",
    hint: "Two padded-glove fighters square off inside a padded ring trying to score a knockout.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-8",
    word: "Baseball",
    hint: "A batter swings at a pitched ball and tries to run around four bases to score.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-9",
    word: "Volleyball",
    hint: "Two teams use their hands to hit a light ball back and forth over a high net.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-10",
    word: "Running",
    hint: "The fundamental track activity of moving quickly on foot across a set distance.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-11",
    word: "Cycling",
    hint: "Athletes race each other at high speeds while pedaling two-wheeled bicycles.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-12",
    word: "Ice Hockey",
    hint: "Players on ice skates use curved sticks to slide a rubber puck into the goal.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-13",
    word: "Table Tennis",
    hint: "Players bounce a lightweight plastic ball back and forth across a miniature table using paddles.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-14",
    word: "Bowling",
    hint: "Rolling a heavy ball down a wooden lane to knock down ten standing wooden pins.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-15",
    word: "Badminton",
    hint: "Players hit a feathered shuttlecock over a high net using lightweight rackets.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-16",
    word: "Rugby",
    hint: "A physical contact sport where athletes run forward while passing an oval ball backward.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-17",
    word: "Skiing",
    hint: "Gliding down snow-covered mountains on long narrow boards attached to your boots.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-18",
    word: "Surfing",
    hint: "Riding standing up on a wooden board across the crest of an ocean wave.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-19",
    word: "Wrestling",
    hint: "A combat sport where two opponents attempt to force each other's shoulders to the mat.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-20",
    word: "Archery",
    hint: "Using a flexible bow to shoot sharp feathered arrows at a painted target.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-21",
    word: "Karate",
    hint: "A traditional martial art involving striking, kicking, and open-handed blocking techniques.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-22",
    word: "Gymnastics",
    hint: "Athletes perform acrobatic flips, somersaults, and balance routines on specialized apparatuses.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-23",
    word: "Marathon",
    hint: "A grueling long-distance road race covering a precise distance of twenty-six point two miles.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-24",
    word: "Skateboarding",
    hint: "Riding and performing trick jumps on a short wooden board mounted on four small wheels.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-25",
    word: "American Football",
    hint: "A gridiron game where players wear helmets and carry an oval ball into the endzone.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-26",
    word: "Formula 1",
    hint: "High-speed open-wheel race cars competing on circuit tracks around the world.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-27",
    word: "Figure Skating",
    hint: "Performing artistic jumps, spins, and dances on ice wearing specialized bladed boots.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-28",
    word: "Weightlifting",
    hint: "Athletes attempt to lift immensely heavy iron barbells above their heads.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-29",
    word: "Billiards",
    hint: "Using a long wooden cue stick to strike hard balls across a cloth-covered table.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-30",
    word: "Darts",
    hint: "Throwing small pointed missiles at a numbered circular board hung on a wall.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-31",
    word: "Horse Racing",
    hint: "Jockeys ride thoroughbred animals at full speed around a dirt or grass track.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-32",
    word: "Fencing",
    hint: "A swordplay sport where two competitors wear mesh masks and thrust thin protective blades.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-33",
    word: "Rowing",
    hint: "Athletes sit in narrow boats and use wooden oars to pull themselves through water.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-34",
    word: "High Jump",
    hint: "Athletes sprint down a runway and leap backward over a raised horizontal bar.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-35",
    word: "Long Jump",
    hint: "Track athletes sprint at top speed and leap as far into a sand pit as possible.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-36",
    word: "Chess",
    hint: "A strategic board game where two players move sixteen pieces to capture the opponent's king.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-37",
    word: "Rock Climbing",
    hint: "Ascending steep natural rock faces or artificial indoor walls using specialized grips.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-38",
    word: "Dodgeball",
    hint: "Players throw rubber balls at members of the opposing team to eliminate them.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-39",
    word: "Water Polo",
    hint: "Treading deep pool water while passing a rubber ball to throw into a floating goal.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },
  {
    id: "fallback-sports-en-40",
    word: "Snooker",
    hint: "Potting colored balls in a specific sequence using a long cue stick on a large green table.",
    category: "sports",
    difficulty: "easy",
    language: "english",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-sports-en-41",
    word: "Referee",
    hint: "The official on the field dressed in stripes who blows a whistle to enforce rules.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-42",
    word: "Trophy",
    hint: "A shiny metallic cup presented to the winning team at the end of a championship.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-43",
    word: "Yellow Card",
    hint: "Held high by an official as an explicit caution after a reckless tackle.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-44",
    word: "Penalty Kick",
    hint: "A direct shot at the goal with only the goalkeeper standing on the line to stop it.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-45",
    word: "Home Run",
    hint: "A powerful hit that clears the outfield fence entirely, allowing a slow trot around the bases.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-46",
    word: "Red Card",
    hint: "Flashing this forces an offending player to leave the match immediately without a replacement.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-47",
    word: "Offside",
    hint: "An infraction called when an attacker receives a pass behind the last defender.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-48",
    word: "Touchdown",
    hint: "Carrying or catching the ball across the opponent's goal line for six points.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-49",
    word: "Knockout",
    hint: "A decisive fight finish where an opponent cannot rise off the canvas before ten seconds.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-50",
    word: "Championship",
    hint: "The ultimate final tournament match determining who takes home the season title.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-51",
    word: "Gold Medal",
    hint: "The coveted top-tier award placed around the first-place athlete's neck on the podium.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-52",
    word: "Free Throw",
    hint: "An uncontested shot taken from fifteen feet away after an opponent fouls you.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-53",
    word: "Goalkeeper",
    hint: "The only player permitted to use their arms to prevent shots from crossing the line.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-54",
    word: "Mascot",
    hint: "An oversized costumed character dancing on the sidelines to energize the arena crowd.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-55",
    word: "Stadium",
    hint: "A massive structural arena lined with thousands of spectator seats surrounding a playing surface.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-56",
    word: "Halftime",
    hint: "The mid-game intermission where exhausted players rest in locker rooms and adjust tactics.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-57",
    word: "Slam Dunk",
    hint: "Jumping high above the court rim to forcefully power the ball straight through the net.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-58",
    word: "Grand Slam",
    hint: "Winning all four major professional tournaments within a single calendar year.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-59",
    word: "Olympic Games",
    hint: "A historic multi-sport event hosted every four years uniting elite global athletes.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-60",
    word: "Sudden Death",
    hint: "An intense overtime rule where the very first team to score immediately wins the entire game.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-61",
    word: "Deuce",
    hint: "A score tied at forty-forty requiring a player to gain two consecutive points to win the game.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-62",
    word: "Hole in One",
    hint: "An extraordinarily rare occurrence where a tee shot drops directly into the cup.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-63",
    word: "Checkmate",
    hint: "The winning board state where an opposing monarch is trapped under direct attack.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-64",
    word: "Bullseye",
    hint: "The tiny central red dot on a target granting maximum possible points.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-65",
    word: "Pitcher",
    hint: "The player standing on a central mound throwing balls toward home plate.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-66",
    word: "Quarterback",
    hint: "The offensive leader who receives the snap and decides whether to hand off or pass.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-67",
    word: "Captain",
    hint: "The elected team leader who wears an armband and communicates directly with referees.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-68",
    word: "Tiebreaker",
    hint: "A short additional phase played when two opponents finish regulation time with equal points.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-69",
    word: "Outfield",
    hint: "The vast grassy boundary area positioned far behind the inner diamond bases.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },
  {
    id: "fallback-sports-en-70",
    word: "Warm Up",
    hint: "Gentle exercises and stretches done right before a match to prevent muscle injuries.",
    category: "sports",
    difficulty: "medium",
    language: "english",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-sports-en-71",
    word: "Substitution",
    hint: "A tactical pause where a fresh player jog onto the pitch to swap places with a tired teammate.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-72",
    word: "Coin Toss",
    hint: "A simple metallic flip high in the air before kick-off that dictates who gets first possession.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-73",
    word: "Clean Sheet",
    hint: "A defensive point of pride achieved when a goalie prevents the opposing team from scoring entirely.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-74",
    word: "Photo Finish",
    hint: "Examining high-speed camera frames to identify whose torso crossed the finish ribbon milliseconds earlier.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-75",
    word: "World Record",
    hint: "The highest athletic benchmark ever achieved in human history for a specific event.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-76",
    word: "Underdog",
    hint: "The competitor expected by oddsmakers to lose who surprisingly captures the crowd's affection.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-77",
    word: "Fastbreak",
    hint: "Sprinting down the court after a turnover before opponents can retreat to set up defense.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-78",
    word: "Hat Trick",
    hint: "A individual accomplishment celebrated when one player scores three times in a single match.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-79",
    word: "Overtime",
    hint: "Extra minutes added to the clock because regulation ended without a clear winner.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-80",
    word: "Whistle",
    hint: "A loud silver sound maker around an official's neck that instantly freezes all active play.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-81",
    word: "Scoreboard",
    hint: "A massive electronic display hovering high above the venue showing real-time numbers and remaining time.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-82",
    word: "Podium",
    hint: "A three-tiered wooden platform top competitors step onto to receive their medals.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-83",
    word: "Corner Kick",
    hint: "Restarting play from the field's flag intersection after a defender knocked the ball past their own boundary line.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-84",
    word: "Equalizer",
    hint: "A crucial late-game goal that brings a trailing team back level with their opponent.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-85",
    word: "False Start",
    hint: "Moving out of the starting blocks before the starter pistol fires, resulting in a strict warning.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-86",
    word: "Par",
    hint: "The pre-calculated target number of strokes an expert golfer is expected to need for a hole.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-87",
    word: "Out of Bounds",
    hint: "Stepping onto or beyond the painted boundary lines, causing an immediate loss of possession.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-88",
    word: "Disqualification",
    hint: "Getting permanently ejected from a competition for breaking rules or unsportsmanlike behavior.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-89",
    word: "Fan Zone",
    hint: "A dedicated plaza outside the venue where supporters gather to celebrate with big screen broadcasts.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-90",
    word: "League Table",
    hint: "A ranked ladder showing all teams sorted by wins, losses, and total accumulated points.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-91",
    word: "Rebound",
    hint: "Snatching the ball out of the air after a missed shot bounces off the backboard.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-92",
    word: "Power Play",
    hint: "A temporary numerical advantage gained while an opposing player sits in the penalty box.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-93",
    word: "Victory Lap",
    hint: "Running around the track while waving a national flag to celebrate a championship win.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-94",
    word: "Wall of Defenders",
    hint: "A row of players standing shoulder-to-shoulder ten yards away to block a dangerous free kick.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-95",
    word: "Shot Clock",
    hint: "A countdown timer enforcing that an offensive possession must attempt a shot within seconds.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-96",
    word: "Steal",
    hint: "Cleanly plucking the ball away from an opponent while they are dribbling or passing.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-97",
    word: "Draft Pick",
    hint: "Selecting top young amateur athletes to join professional sports franchises annually.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-98",
    word: "Halfpipe",
    hint: "A U-shaped snow ramp used by snowboarders to launch skyward and perform air tricks.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-99",
    word: "Water Break",
    hint: "A brief pause sanctioned during sweltering conditions so players can hydrate on the sidelines.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
  {
    id: "fallback-sports-en-100",
    word: "Fair Play",
    hint: "The spirit of mutual respect and integrity prioritizing sportsmanship over winning at all costs.",
    category: "sports",
    difficulty: "hard",
    language: "english",
  },
];
