// lib/fallback-words/animals/urdu/index.ts

import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "animals" category -- Roman Urdu.
 *
 * 100 words drawn from everyday Pakistani vocabulary -- domestic pets,
 * farm animals, local wildlife, and common insects -- every one of them
 * instantly recognizable to an average Roman Urdu-speaking player.
 * Difficulty changes ONLY how directly the hint points at the word.
 * Hints are written in natural, conversational Roman Urdu using ONLY
 * Latin letters.
 */
export const ANIMALS_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (40)
  {
    id: "fallback-animals-ur-1",
    word: "Kutta",
    hint: "Ghar ki rakhwali karne wala wafadar paaltu janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-2",
    word: "Billi",
    hint: "Doodh peene wali aur chuhe pakarne wali aam gharelu paaltu.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-3",
    word: "Sher",
    hint: "Jangal ka badshah kehlane wala taqatwar janwar jis ke chehre par baal hote hain.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-4",
    word: "Haathi",
    hint: "Bohat bari soondh aur bare kano wala bhari jandar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-5",
    word: "Bandar",
    hint: "Darakhton par chalangein lagane wala shararti janwar jis ki lambi dum hoti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-6",
    word: "Bhalu",
    hint: "Gana aur shehad shouq se khane wala bara aur bhari janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-7",
    word: "Ghora",
    hint: "Sawari aur tanga chalane ke liye istemal hone wala teez janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-8",
    word: "Gaye",
    hint: "Gaon mein doodh aur gosht ke liye pali jane wali aam janwar jis ki pooja bhi hoti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-9",
    word: "Bhains",
    hint: "Kaley rang ka bara janwar jis ka doodh bohat ghara hota hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-10",
    word: "Bakri",
    hint: "Chota paaltu janwar jis ka doodh bachon aur beemaron ke liye mufeed hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-11",
    word: "Bher",
    hint: "Is masoom janwar ke jism ke balon se oon (wool) banti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-12",
    word: "Murgi",
    hint: "Har roz nashtay mein khaye jane wale anday yahi deti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-13",
    word: "Murgha",
    hint: "Subah savere baang de kar gaon walon ko jagane wala parinda.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-14",
    word: "Kabootar",
    hint: "Aman ki alamat samjha jane wala aam shehri parinda jo katar katar karta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-15",
    word: "Kauwa",
    hint: "Kaale rang ka chalak parinda jo kaan kaan karta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-16",
    word: "Cheel",
    hint: "Asmaan mein bohat unchai par urne wala shikari parinda jo gosht utha le jata hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-17",
    word: "Tota",
    hint: "Hare rang ka khubsurat parinda jo insani awaz ki naqal karta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-18",
    word: "Ullu",
    hint: "Raat ke waqt dekhne wala aur ghoomti hui gardan wala parinda.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-19",
    word: "Machli",
    hint: "Pani mein rehne wali makhlooq jis ke beghair guzara nahi aur jo kanto mein hoti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-20",
    word: "Magarmach",
    hint: "Pani aur khushki dono par rehne wala khatarnak shikari jis ke jabray mazboot hote hain.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-21",
    word: "Saanp",
    hint: "Zameen par rengne wala zehreela janwar jis ki tangen nahi hotin.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-22",
    word: "Kachwa",
    hint: "Bohat ahista chalne wala aur apni peeth par sakht khol uthane wala janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-23",
    word: "Mendak",
    hint: "Barish ke mosam mein phudakne aur tar tar karne wala pani ka janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-24",
    word: "Chuha",
    hint: "Gharon mein kapre aur cheezen kutarne wala chota sa teez janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-25",
    word: "Makhi",
    hint: "Khane par baithne wala aam urta hua keera jo beemari phelata hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-26",
    word: "Machar",
    hint: "Raat ko kaat kar khoon choosne wala urta keera jis se dengue hota hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-27",
    word: "Chunti",
    hint: "Bohat mehanti chota sa keera jo hamesha qataar mein chalta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-28",
    word: "Makri",
    hint: "Deewaron aur kono mein apna jala banne wala ath tangon wala keera.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-29",
    word: "Chipkali",
    hint: "Ghar ki deewaron par tezi se chalne aur keeray khane wali makhlooq.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-30",
    word: "Khargosh",
    hint: "Lambe kano wala chota safed janwar jise gajar bohat pasand hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-31",
    word: "Hiran",
    hint: "Khubsurat seenghon wala aur bohat teez dorne wala masoom janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-32",
    word: "Lomri",
    hint: "Kahaniyon mein bohat chalak mashhoor hone wala jangli janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-33",
    word: "Bheriya",
    hint: "Raat ko asmaan ki taraf mu kar ke awazein nikalne wala jangli janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-34",
    word: "Gadha",
    hint: "Bojh uthane ke liye istemal hone wala bohat mehanti aur mazloom janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-35",
    word: "Oont",
    hint: "Sehra ka jahaaz kehlane wala lambi gardan aur kuhan wala janwar.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-36",
    word: "Mor",
    hint: "Apne khubsurat rang birange par phaila kar barish mein nachne wala parinda.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-37",
    word: "Chidya",
    hint: "Gharon ke sehan mein chehchahane wala chota sa masoom parinda.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-38",
    word: "Batakh",
    hint: "Pani mein tairne wala safed parinda jis ki chounch chapti hoti hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-39",
    word: "Titli",
    hint: "Baghiche mein phoolon par baithne wala khubsurat rangon wala urta keera.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-40",
    word: "Khachar",
    hint: "Paharoun par saman le jane wala mazboot janwar jo ghore ki tarah dikhta hai.",
    category: "animals",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (30)
  {
    id: "fallback-animals-ur-41",
    word: "Teetar",
    hint: "Gaon aur kheton mein shikar kiya jane wala chota, gol sa parinda.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-42",
    word: "Batair",
    hint: "Ek chota aur mota parinda jis ka gosht dabbon mein bhar kar bhi becha jata hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-43",
    word: "Koel",
    hint: "Apni meethi aur sureehli awaz se pehchana jane wala bilkul kaala parinda.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-44",
    word: "Bulbul",
    hint: "Baaghon mein gane wale is chote parinde ka zikr aksar hamari urdu shairi mein hota hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-45",
    word: "Cheetah",
    hint: "Jangal mein sab se teez dornay ke liye mashhoor raftar wala janwar.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-46",
    word: "Zarrafa",
    hint: "Sab se lambi gardan wala janwar jo hamesha unchay darakhton ke patte khata hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-47",
    word: "Genda",
    hint: "Is sakht khaal wale bhari janwar ke naak ke theek upar ek bara seengh hota hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-48",
    word: "Daryaee Ghora",
    hint: "Pani ke andar rehne wala aur wazan mein bohat bhari janwar jis ka mu bohat bara khulta hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-49",
    word: "Zeebra",
    hint: "Qudrati tor par safed aur kaali dhariyon wala jangal ka janwar.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-50",
    word: "Kangroo",
    hint: "Apne pait ki makhsoos thaili mein apna bacha rakhne wala janwar.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-51",
    word: "Panda",
    hint: "Bhaans (bamboo) shouq se khane wala cheen ka safed aur kaala bhalu.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-52",
    word: "Gorila",
    hint: "Insan jaisi shakal wala sab se taqatwar aur chati peetne wala bara bandar.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-53",
    word: "Chakor",
    hint: "Paharoun par milne wala parinda jo riwayaton mein chand ka ashiq samjha jata hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-54",
    word: "Shaheen",
    hint: "Allama Iqbal ki shairi mein himmat, jidd-o-jehad aur nojawanon ki alamat wala shikari.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-55",
    word: "Uqaab",
    hint: "Bohat unchi uran urne wala bara shikari parinda jis ki nazar teez hoti hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-56",
    word: "Tiddi",
    hint: "Jhund ki shakal mein aa kar poori fasal ko nuqsan pohanchane wala urta hua hara keera.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-57",
    word: "Bichoo",
    hint: "Apni dum ke akhri hissay se zehar ka khatarnak dink marne wala hashrat.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-58",
    word: "Kenchwa",
    hint: "Barish ke baad zameen ke andar naram mitti mein rengne wala lamba keera.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-59",
    word: "Keera",
    hint: "Kisi bhi chote reengne ya urne wale hashrat ke liye bola jane wala aam lafz.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-60",
    word: "Jhingur",
    hint: "Raat ke sannate mein khet aur ghaas se lagatar teez awaz nikalne wala hashrat.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-61",
    word: "Jugnu",
    hint: "Andheri raat ke waqt pichay se chamakne wala chota sa khubsurat urta keera.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-62",
    word: "Khatmal",
    hint: "Purani charpai aur bistar mein chup kar insani khoon choosne wala keera.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-63",
    word: "Deemak",
    hint: "Ghar ki lakri aur darwazon ko andar se kha kar khokhla karne wala keera.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-64",
    word: "Bhir",
    hint: "Peelay rang ka urta keera jis ke katne par bohat teez dard aur sujan hoti hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-65",
    word: "Shahad Ki Makhi",
    hint: "Phoolon ka ras choos kar insanon ke liye meetha sheera banane wali.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-66",
    word: "Neola",
    hint: "Zehreele saanp ka sab se bara aur jani dushman janwar.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-67",
    word: "Sehi",
    hint: "Khud ko bachane ke liye apne jism ke teez kante khare karne wala janwar.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-68",
    word: "Gidhar",
    hint: "Jangal mein raat ko awazein nikalne wala woh janwar jise mohawron mein buzdil kaha jata hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-69",
    word: "Tenduwa",
    hint: "Darakhton par charhne ka mahir, chittidar khaal wala khatarnak shikari.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-70",
    word: "Bara Singha",
    hint: "Is hiran ke sar par bohut shakhon wala taj hota hai.",
    category: "animals",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (30)
  {
    id: "fallback-animals-ur-71",
    word: "Neel Gaye",
    hint: "Hindustan aur Pakistan ke junglat mein pai jane wali bari jangli makhlooq jo hiran jaisi lagti hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-72",
    word: "Markhor",
    hint: "Paharoun par charhnay wala hamara qoumi janwar jis ke seengh pechdaar hotay hain.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-73",
    word: "Pahari Bakra",
    hint: "Oonchi aur phisalti chattano par asani se chalne ke liye mashhoor jangli makhlooq.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-74",
    word: "Chinkara",
    hint: "Cholistan aur thar ke sehraon mein taizi se dorne wala chota aur naazuk hiran.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-75",
    word: "Urial",
    hint: "Pahari ilaqaon mein milne wali jangli bher jis ke seengh agay ki taraf gol hotay hain.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-76",
    word: "Fakhta",
    hint: "Ghol ghol awaz nikalne wala halkay bhure rang ka nihayat masoom parinda.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-77",
    word: "Baya",
    hint: "Apni choanch se tinko ko jod kar apna khubsurat aur laktka hua ghosla bun-ne wala parinda.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-78",
    word: "Hudhud",
    hint: "Is mashhoor parinde ke sar par paron ka ek taj hota hai aur is ki chounch lambi hoti hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-79",
    word: "Maina",
    hint: "Totay ke ilawa awazein nikalne mein mahir ye ek aam parinda hai jise log paalte hain.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-80",
    word: "Hans",
    hint: "Pani mein tairne wala khoobsoorat safed parinda jise kahaniyon mein pyar ki alamat samjha jata hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-81",
    word: "Feel Murgh",
    hint: "Bara aur bhari parinda jo aam tor par america aur yahan shadiyon ke khano mein pakaya jata hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-82",
    word: "Shutur Murgh",
    hint: "Sab se bara taqatwar uran na bhar sakne wala jandar jo sirf taizi se dor sakta hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-83",
    word: "Gidh",
    hint: "Murda janwaron ka gosht kha kar mahol ko saaf rakhne wala aur ganja lagne wala parinda.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-84",
    word: "Chamgadar",
    hint: "Wahid mammal janwar jo asman mein urne ki salahiyat rakhta hai aur ulta latakta hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-85",
    word: "Jhinga",
    hint: "Samundar se nikalne wala chota sea food jis ka chhilka naram aur rang gulabi hota hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-86",
    word: "Kekra",
    hint: "Samundar ke kinaray hamesha tircha chalne wala aur sakht chimton wala janwar.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-87",
    word: "Girgit",
    hint: "Mahol ke hisab se apna rang bilkul tabdeel karne ki salahiyat rakhne wala jandar.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-88",
    word: "Goh",
    hint: "Bari shakal wali aur wehshat naak chipkali jis ki girift deewaron par bohat mazboot mani jati hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-89",
    word: "Seep",
    hint: "Samundar se milne wala wo sakht khol jis ke andar se asli moti nikalta hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-90",
    word: "Jonk",
    hint: "Yeh khoon choosnay wala lamba keera puranay waqton mein ganda khoon nikalne ke liye istemal hota tha.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-91",
    word: "Kankhajura",
    hint: "Is lambay keeray ke baray mein mashhoor hai ke is ki so tangen hoti hain.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-92",
    word: "Soondi",
    hint: "Pato ko khane wala yehi lamba keera baad mein barra ho kar uran bharne lagta hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-93",
    word: "Joun",
    hint: "Bacchon ke balon mein aksar par jane wala chota khoon choosne wala keera.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-94",
    word: "Pissu",
    hint: "Kutton aur billiyon ki khaal mein chupa rehne wala chota aur tang karne wala keera.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-95",
    word: "Ghariyal",
    hint: "Is khatarnak pani ke janwar ki lambi aur patli thothni hoti hai jo danton se bhari hoti hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-96",
    word: "Dolphin",
    hint: "Samundar ki sab se zeheen aur insano se asani se dosti karne wali makhlooq.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-97",
    word: "Whale",
    hint: "Samundar ki tahon mein rehne wala duniya ka sab se bhari aur bara janwar.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-98",
    word: "Shark",
    hint: "Pani mein rehne wali is khoonkhwar makhlooq ko uski peeth ke fin se pehchana jata hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-99",
    word: "Khanzeer",
    hint: "Ek napak samjha jane wala janwar jise mazhabi tor par khana sakhti se mana hai.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-animals-ur-100",
    word: "Tattu",
    hint: "Paharoun par saman uthane ke liye aam istemal hone wala ghore jaisa dikhne wala chota janwar.",
    category: "animals",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
