import type { FallbackWordEntry } from "../../types";

/**
 * TIER 3 static fallback entries for the "technology" category -- Roman Urdu.
 *
 * 100 words drawn from Pakistani daily tech vocabulary and mobile culture
 * (like PTA Approved, Box Pack, Load, MBs, Power Bank, Flashlight) that an
 * average Roman Urdu-speaking player would instantly recognize.
 * As with the English list, difficulty only changes how directly the hint
 * points at the word, never how obscure the word itself is.
 * Hints are written in natural Roman Urdu using only Latin letters.
 */
export const TECHNOLOGY_URDU_FALLBACK_WORDS: FallbackWordEntry[] = [
  // EASY (1-40) - Direct, obvious defining trait
  {
    id: "fallback-technology-ur-1",
    word: "Mobile",
    hint: "Baat karne aur internet chalanay ke liye hath mein pakra jane wala chota aala.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-2",
    word: "Sim",
    hint: "Phone ke andar dalne wali choti si chip jis se number chalta hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-3",
    word: "Charger",
    hint: "Phone ki battery khatam hone par usay bijli se bharne wala plug.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-4",
    word: "Handsfree",
    hint: "Kaan mein laga kar ganay sunne ya call par baat karne wali taar.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-5",
    word: "Battery",
    hint: "Mobile ke andar maujood cheez jo usay power faraham karti hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-6",
    word: "Screen",
    hint: "Phone ka wo sheeshe wala hissa jis par tasweer aur video nazar aati hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-7",
    word: "Password",
    hint: "Apna phone ya account kholne ke liye lagaya jane wala khufiya code.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-8",
    word: "Internet",
    hint: "Puri duniya ki maloomat aur doston se jorne wala digital nizam.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-9",
    word: "Data",
    hint: "Mobile par internet chalane ke liye sim par on kiya jane wala connection.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-10",
    word: "Signal",
    hint: "Screen ke oopar wale koney mein linein jo batati hain ke network kaisa hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-11",
    word: "Balance",
    hint: "Call karne ke liye sim mein load karwaye gaye paise.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-12",
    word: "Load",
    hint: "Dukan wale se apna number bata kar sim mein paise dalwana.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-13",
    word: "Package",
    hint: "Ek mahine ke liye makhsoos calls aur internet lene ka offer lagwana.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-14",
    word: "Online",
    hint: "Jab koi shakhs internet par maujood ho aur usay message kiya ja sake.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-15",
    word: "Offline",
    hint: "Jab kisi ka internet band ho aur wo reply na kar sake.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-16",
    word: "Selfie",
    hint: "Apne hi mobile ke front camera se apni tasweer kheenchna.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-17",
    word: "Video Call",
    hint: "Phone par baat karte hue dusre shakhs ko live dekhna.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-18",
    word: "Group",
    hint: "Ek hi jagah par bohut sare doston ka jama ho kar message karna.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-19",
    word: "Admin",
    hint: "Jo shakhs online jamaat banata hai aur usay control karta hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-20",
    word: "Block",
    hint: "Kisi tang karne wale shakhs ke calls aur messages ko hamesha ke liye band karna.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-21",
    word: "Delete",
    hint: "Kisi tasweer ya message ko apne phone se hamesha ke liye mita dena.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-22",
    word: "Install",
    hint: "Play store se koi naya software apne phone mein dalna.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-23",
    word: "Update",
    hint: "Purane software mein naye features lane ke liye usay naya karna.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-24",
    word: "Download",
    hint: "Internet se koi gana ya video apne memory card mein save karna.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-25",
    word: "Camera",
    hint: "Tasweer kheenchnay aur video bananay ke liye phone ke peechay laga sheesha.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-26",
    word: "Mic",
    hint: "Jis choti si jagah mein hum bolte hain taake hamari awaz dusri taraf jaye.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-27",
    word: "Speaker",
    hint: "Phone ka wo hissa jahan se loud awaz aur ganay sunayi dete hain.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-28",
    word: "Keyboard",
    hint: "Computer mein type karne ke liye istemal hone wala buttonon wala board.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-29",
    word: "Mouse",
    hint: "Computer screen par teer ke nishan ko idhar udhar ghumanay wali cheez.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-30",
    word: "USB",
    hint: "Data ek computer se dusre mein le jane wali choti si flash drive.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-31",
    word: "Laptop",
    hint: "Godh mein rakh kar chalaya jane wala battery wala fold hone wala computer.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-32",
    word: "Computer",
    hint: "Table par rakha jane wala CPU aur monitor wala mukammal system.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-33",
    word: "Smartwatch",
    hint: "Kalai par pehni jane wali ghari jo mobile ke messages bhi dikhati hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-34",
    word: "Drone",
    hint: "Remote se hawa mein urne wala aur video bananay wala aala.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-35",
    word: "App",
    hint: "Mobile mein maujood mukhtalif kamo ke liye chote software.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-36",
    word: "Link",
    hint: "Neeli rang ki likhai jis par click karne se koi nayi website khul jati hai.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-37",
    word: "Message",
    hint: "Kisi ko likh kar bheji gayi koi chhoti si text baat.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-38",
    word: "Cable",
    hint: "Mobile ko computer se jorne wali aur data transfer karne wali taar.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-39",
    word: "Robot",
    hint: "Insaan ki tarah kaam karne wali aik automatic aur computer wali machine.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-40",
    word: "Router",
    hint: "Ghar mein internet ka network aur wireless signals dene wala dabha.",
    category: "technology",
    difficulty: "easy",
    language: "roman-urdu",
  },

  // MEDIUM (41-70) - Related detail/context
  {
    id: "fallback-technology-ur-41",
    word: "DP",
    hint: "Log apne profile par apni behtareen tasweer lagate hain taake sab pehchan saken.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-42",
    word: "Status",
    hint: "Chaubees ghante baad khud ba khud mit jane wali tasweer ya video update.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-43",
    word: "Story",
    hint: "Apni rozmara ki masroofiyat ko chote clips mein doston ko dikhana.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-44",
    word: "Voice Note",
    hint: "Likhne ka waqt na ho to button daba kar apni awaz record kar ke bhejna.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-45",
    word: "Screenshot",
    hint: "Mobile ki screen par jo kuch chal raha ho uski tasweer mehfooz kar lena.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-46",
    word: "Seen",
    hint: "Message par lagne wala wo neela nishan jo batata hai ke aglay ne parh liya hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-47",
    word: "Forward",
    hint: "Kisi ka bheja hua mazahiya message aage 5 aur doston ko bhej dena.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-48",
    word: "Hang",
    hint: "Jab mobile bohut slow ho jaye aur button dabane par bhi kaam na kare.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-49",
    word: "Restart",
    hint: "Phone atkaney lag jaye to usay band kar ke dobara on karna.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-50",
    word: "Setting",
    hint: "Mobile ki brightness, awaz aur network theek karne ke liye is menu mein jate hain.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-51",
    word: "Ringtone",
    hint: "Call aane par mobile mein jo gana ya khaas music bajta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-52",
    word: "Wallpaper",
    hint: "Mobile screen lock kholne se pehle pichay nazar aane wali tasweer.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-53",
    word: "Alarm",
    hint: "Subah jaldi uthne ke liye raat ko mobile mein time aur ghanti set karna.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-54",
    word: "Flashlight",
    hint: "Andhera hone par rasta dekhne ke liye phone ke peechay jalne wali roshni.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-55",
    word: "Post",
    hint: "Apni koi baat ya tasweer internet par sab doston ko dikhane ke liye dalna.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-56",
    word: "Comment",
    hint: "Kisi ki lagai hui tasweer ke neechay apni raye ya likhai add karna.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-57",
    word: "Like",
    hint: "Kisi ki post pasand aane par angoothe ka nishan ya dil dabana.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-58",
    word: "Share",
    hint: "Kisi ki achi video ko apni profile par doosron ke sath bantna.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-59",
    word: "Viral",
    hint: "Koi aisi video jo raaton raat pure mulk mein phail jaye aur sab dekh len.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-60",
    word: "Follower",
    hint: "Wo log jo internet par aapki videos shauq se dekhte hain aur account se jure hote hain.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-61",
    word: "Views",
    hint: "Ye number batata hai ke kitne hazar logon ne ye video dekh li hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-62",
    word: "Channel",
    hint: "Video website par kisi ka apna banaya hua page jahan wo content dalta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-63",
    word: "Subscribe",
    hint: "Kisi ke video banane wale account ko hamesha ke liye apni list mein shamil karna.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-64",
    word: "Notification",
    hint: "Jab koi naya message aye to phone ki screen par aane wala beep aur popup.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-65",
    word: "Inbox",
    hint: "Wo jagah jahan apke tamaam naye aur purane private messages jama hote hain.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-66",
    word: "Hacker",
    hint: "Wo chor jo internet ke zariye aapki khufiya maloomat ya password chura leta hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-67",
    word: "Virus",
    hint: "Aik aisi ghalat file jise kholne se computer ya mobile ka sara data kharab ho jata hai.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-68",
    word: "Fake ID",
    hint: "Apna asli naam chupa kar kisi doosre ke naam se banaya gaya dhoke wala account.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-69",
    word: "OTP",
    hint: "Bank transaction confirm karne ke liye mobile par message mein aane wala 4 digits ka code.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-70",
    word: "Fingerprint",
    hint: "Mobile ka lock kholne ke liye apna angootha makhsoos sensor par lagana.",
    category: "technology",
    difficulty: "medium",
    language: "roman-urdu",
  },

  // HARD (71-100) - Oblique, unusual angle, without stating defining trait
  {
    id: "fallback-technology-ur-71",
    word: "PTA Approved",
    hint: "Hakumat ko tax de kar mobile ko mulk mein hamesha chalne ke qabil banana.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-72",
    word: "Box Pack",
    hint: "Wo aala jo dukan par bilkul naya ho aur uski seal abhi tak na khuli ho.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-73",
    word: "Second Hand",
    hint: "Naya model lene ki auqat na ho to kisi aur ka istemal shuda device lena.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-74",
    word: "Warranty",
    hint: "Naya phone kharab hone par company ki taraf se muft theek karwane ki raseed.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-75",
    word: "Lag",
    hint: "Heavy game khelte waqt tasweer ruk ruk kar aur atakk atakk kar chalna.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-76",
    word: "Heating",
    hint: "Bohut der tak video recording karne se device ka peechay se garm ho jana.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-77",
    word: "Airplane Mode",
    hint: "Safar ke dauran tamam signals band karne wala jahaaz ke nishan wala button.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-78",
    word: "Silent",
    hint: "Meeting mein baithe hue device ki ghanti aur awaazon ko bilkul band kar dena.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-79",
    word: "Hotspot",
    hint: "Apna internet package sath baithe doston ke sath wifi bana kar share karna.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-80",
    word: "Location",
    hint: "Delivery wale ko apna theek ghar dhoondne ke liye bheja jane wala GPS point.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-81",
    word: "Map",
    hint: "Anjan shehar mein rasta bhatakne se bachne ke liye nizam e rasta ka istemal karna.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-82",
    word: "Copy",
    hint: "Ek jagah se likhai ya file utha kar dusri jagah le jane ke liye pehla amal.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-83",
    word: "Paste",
    hint: "Uthai hui likhai ya tasweer ko nayi jagah par waisa hi theek chhap dena.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-84",
    word: "Type",
    hint: "Angothon ko tezi se chala kar bada sa paragraph tayyar karna.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-85",
    word: "Save",
    hint: "Zaroori maloomat ko memory mein mehfooz kar lena taake baad mein kaam asake.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-86",
    word: "Upload",
    hint: "Apni heavy video file ko aam logo ke dekhne ke liye server par charhana.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-87",
    word: "Server",
    hint: "Puri duniya ke mukhtalif systemon ko ek sath control karne wala bada nizam.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-88",
    word: "Code",
    hint: "Software bananay wale engineer jo screen par ajeeb si likhai aur lines likhte hain.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-89",
    word: "Fiber",
    hint: "Zameen ke neechay bichi hui shishe ki cable jis se internet ki tez speed aati hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-90",
    word: "Speed",
    hint: "Internet theek se na chale to log check karte hain ke kitne mbps data araha hai.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-91",
    word: "Ping",
    hint: "Online gaming mein trigger dabane aur goli chalne ke darmiyan aane wala waqfa.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-92",
    word: "Memory Card",
    hint: "Storage jaldi full hone par andar lagai jane wali izafi choti si chip.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-93",
    word: "Screen Glass",
    hint: "Naya phone lene ke baad usay tootne se bachane ke liye lagwaya jane wala protector.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-94",
    word: "Power Bank",
    hint: "Lamba safar ho to charge bachanay ke liye istemal hone wali izafi portable battery.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-95",
    word: "Keypad",
    hint: "Purane zamane ki devices jin mein touchscreen ke bajaye zor se dabane wale buttons thay.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-96",
    word: "Touch Screen",
    hint: "Ungliyon ke halke isharay par chalne wala baghair buttonon ka jaded nizam.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-97",
    word: "Search",
    hint: "Kisi bhi sawal ya maslay ka hal talaash karne ke liye engine par likhna.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-98",
    word: "Mute",
    hint: "Kisi buri awaz wali video ya annoying doston ke messages ki awaaz ko daba dena.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-99",
    word: "Pairing",
    hint: "Do mukhtalif smart devices ko aapas mein taar ke baghair hamesha ke liye connect kar dena.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
  {
    id: "fallback-technology-ur-100",
    word: "Spam",
    hint: "Anjan numbers aur comapniyon se aane wale bohut sare farzi aur faltu messages ka azaab.",
    category: "technology",
    difficulty: "hard",
    language: "roman-urdu",
  },
];
